### ISSUE TITLE
Entfernungsanzeige in Objektansicht ist falsch

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#10]
... entweder wird 5tsdunfnochwas Kilometer angezeigt oder nur -- (owbohl das Bild eine Koordinate hat, weil in der Bildansicht und in den Listenanscihten etc. stimmt es.)

**Comment by Mojo1917** [comment]
Fehler ist behoben. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
danke, schau ich dann an.
