### ISSUE TITLE
Ansicht-Optimierung: die "vor xy Tagen" Anzeige beim Objekt neben dem Datum (Erstellung- und Letzet Besuchsdatum) ist von der vertikalen Position immer irgendwie anders.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#101]
manchmal ist es so hoch, manchmal so. Auch zueinander (Erstellt/besucht) "hängt" es an einer andere Position. 

Kannst Du diese fix definieren? Z.B. untenbündig zur Datumslinie davor etc.?

**Comment by Mojo1917** [comment]
Okay der Fehler des Autolayouts ist behoben. Werden jetzt alle fix an der unteren Baseline gehalten.
Änderung kommt mit dem nächsten Update.
