### ISSUE TITLE
In der Kartenansicht, wenn ich den Filter umgeschaltet habe habe ich die App abstürzen lassen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#103]
... es blicken dann die Farben der Objkeet wie wild udn auch mein Standort (also eher Flackern)

**Comment by Mojo1917** [comment]
Das ist der Fehler, den ich in der Mail erwähnt hatte ;) War gestern keine Zeit mehr den zu beheben.

**Comment by Mojo1917** [comment]
Fehler ist behoben. Änderung kommt mit dem nächsten Update.
