### ISSUE TITLE
Osrtsuche in Karte funktioniert nicht mehr...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#104]
... die Suche leifert immer keine Ergebnisse.

Und: es wird unter das Suche-Fenster zusätzlcih die andere Suchzeie mit angezeigt.

**Comment by Mojo1917** [comment]
Untere Suchzeile wird nicht mehr bewegt.

**Comment by Mojo1917** [comment]
Die Suche funktioniert so wie bisher. Man darf nicht vergessen, dass das hier kein Google Maps dahinter ist. Entsprechend ist der Ergebnisssuche nicht so gut. Das suchen nach Städten funktioniert jedoch.

Bitte überprüfe das nochmal :)
