### ISSUE TITLE
nochmals Karte: die Anzeige in Farbmodus ist fehlerhaft, während sie im Bildermodus passt.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#105]
z.B. habe ich 3 Bilder, 2 mit Faroiten: wenn ich im Farbmodus auf Favorit filtere, fliegt die anzeieg zu zwei Bäumen hin, davon hat aber nur einer einen Stern, der andere nicht.

(Bei Bildern verhält sich die Filterung richtig)

**Comment by Mojo1917** [comment]
Sollte sich automatisch hiermit behoben haben #92
