### ISSUE TITLE
Kannst Du den Namen "LocBase" überall in "Locbase" abändern?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#107]

**Comment by McFly753** [comment]
Wenn nicht dynamsich (also der Titel in der Datenbank), lass es erstmal, aber das Ticket offen.

**Comment by Mojo1917** [comment]
Ist nicht dynamisch möglich, da der Name manuell überall gesetzt ist. Ich verschiebe es auf später.

**Comment by Mojo1917** [comment]
Okay ist geändert. Ich hoffe ich habe keins übersehen ;)

**Comment by Mojo1917** [comment]
Super danke hatte ich übersehen ;)
