### ISSUE TITLE
Kommas richtig setzen in den Abfragen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#108]
> Kamerazugriff: "... auf deine Kamera zugreifen, um ..."
> Fotozugriff: "... auf deine Fotos zugreifen, um ein..."
> Standortzugriff: "... die Möglichkeit, dich zu ..." 

> Tutorial: "Tippe hier, um ..." (überall)

> Einstellungen, Objketeinstellujngen & Tags > "Tippe, um ..."

Evtl. habe ich es noch irgendwo vergessen.

**Comment by Mojo1917** [comment]
Ups sorry. Die Dialog Texte gebe ich in der Programmierung immer zu schnell ein, weil ich mit dem Kopf bei der Code-Logik bin :D

**Comment by Mojo1917** [comment]
Ist geändert. Wenn ich noch Fehler finde passe ich sie an. Änderung kommt mit dem nächsten Update.
