### ISSUE TITLE
Tutorial temp. ausschalten für den Test, weil wir es noch nicht für die ganze App haben...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#109]
... das ? in den Einstellungn kannst Du aber lassen.

**Comment by Mojo1917** [comment]
Es ist derzeit nur in den Einstellungen. Ich deaktiviere die standardmäßige Aktivierung. Muss jetzt manuell über den Button in den Einstellungen aktiviert werden.

**Comment by Mojo1917** [comment]
Änderung kommt mit dem nächsten Update.

**Comment by Mojo1917** [comment]
App fragt jetzt beim Ersten Öffnen der Settings nicht, ob das Tutorial gestartet werden soll.
