### ISSUE TITLE
Koordinaten-Änderung eines Bildes sollte intuitiver sein

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#11]
... ich weiss nicht, ob ich das Bild zuerst lange drücken soll und dann verschieben oder die Karte verschieben soll und manchmal schaffe ich es, das Objekt zuu verschieben... aber ist nicht sauber gelöst.

> was wäre, wenn einfach hier alle Bilder des Objektes angezeigt werden und das Objket, über das ich einsteige (also das ich verändern will) wackelt? Solange, bis ich es wohinbewege und dann nochmls drauf klicke etc. 

> dann könnte ich hier auch alle andern Bilder bewegen, indem ich einfach ein anderes danach länger drücke, bis es wackelt?

**Comment by Mojo1917** [comment]
Okay ich werde schauen, in wie weit ich hier das Verhalten der Karte abändern kann ;)

**Comment by McFly753** [comment]
Ok. Brauhst Du noch Infos oder dann am Tel?

**Comment by Mojo1917** [comment]
Nein ich denke ich verstehe was du meinst. Ich werde versuchen das vordefinierte Verhalten der Karte so abzuändern.

**Comment by Mojo1917** [comment]
Koordinaten-Änderung ist jetzt komplett überarbeitet. Sie funktioniert jetzt wiefolgt:

Um ein Bild zum verschieben zu aktivieren muss dieses einmal angeklickt werden. Danach kann es ohne zeitliche Verzögerung verschoben werden. Nach dem Verschieben wird es wieder 'gelockt'. Ohne erneutes anklicken kann es nicht mehr verschoben werden.

Wird ein anderes Bild ausgewählt obwohl noch ein anderes 'gewählt' ist wird das neue aktiviert und das alte 'gelockt'.

Um ein ausgewähltes Bild zu 'locken' ohne es zu verschieben muss es einfach angeklickt werden.

Sollte man direkt von einem Bild kommen ist dieses zum verschieben ausgewählt und kann ohne Verzögerung verschoben werden.

**Comment by Mojo1917** [comment]
Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Ja, ist schön geworden. 

Nur: wenn ein Bild wackelt, kann ich aus dieser Ansicht rausfallen, weil ich asuversehen die Karte nach rechts wegwschen kann und dann diese Ansicht verlasen wird. (ich kann das gerade nicht merh nachvollziehen, wie ich das geschafft habe... ,) )

Aber: wenn ich dann diese Einstellung verlasse, sollte ich zu dem letzen Bild, das ich verändert habe, zurück kommen, nicht komplett zurück zum Objekt.

**Comment by Mojo1917** [comment]
Zu dem verlassen der Ansicht: Das ist die ganz normale Geste unter iOS die es ermöglicht durch wischen nach recht ausgehend vom linken Rand zurück zu gehen.

Die Änderung habe ich übernommen. Habe hier auch direkt die Navigation ein wenig vereinfacht.

**Comment by McFly753** [comment]
ok, danke!
