### ISSUE TITLE
Wenn ich in den Einstellungen auf Datenbank gehe, die vom Namen noch nicht verändert wurde, setz bitte gleich den Cursor in das Feld

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#110]

**Comment by Mojo1917** [comment]
Ob der Name nicht verändert wurde lässt dich nicht prüfen.

**Comment by Mojo1917** [comment]
Sobald der Name 'Datenbank' enthält (ist ja der default Name) wird der Cursor is Feld gesetzt.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.
