### ISSUE TITLE
Löschen der Datenbank sollte nach Abfrage nochmals redundant abgefragt werden, z.B. indem man nach seinem Ja nochmals gefragt wird, dass man hiermit xy Objekt mit zz Bildern löscht. Und dann sollte man "Ja" eingeben.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#113]
Können wir auch später machen, wenn nicht schnell genug umsetzbar.

**Comment by Mojo1917** [comment]
Ablauf soll also wie folgt aussehen?
1. Wischen -> Löschen
2. Abfrage: Wirklich löschen? -> Ja
3. Abfrage: xy wird gelöscht! -> Ja eintippen

**Comment by McFly753** [comment]
Ja > 
Wenn die Datenbank xx mit yy Objketen und zz Bildern wirklich gelöscht werden soll, dies bitte mit "JA" bestätigen.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Die App verlangt jetzt die Exakte Eingabe von 'JA'. Oder sollen wir auch 'ja', 'Ja', und 'jA' zulassen? Das macht es vielleicht etwas leichter.

**Comment by McFly753** [comment]
Danke, passt. // Aber, was mich hier stört: kommt der User darauf, dass er nach rechts wischen muss, um die Datenbank zu löschen? Was ist, wenn wir das Auswahlfeld nach links vor den Datenbanknamen setzen und dahinter ein Löschen-Icon?

**Comment by Mojo1917** [comment]
Klar können wir auch machen.

**Comment by Mojo1917** [comment]
Okay ist angepasst. Jedoch habe ich mich hier jetzt an den Standart von Apple gehalten. Wenn das soweit für dich passt. Ich denke das macht es einheitlicher.
Wir haben jetzt in der oberen Leiste einen Löschen-Button. Wird dieser gedrückt wechselt die Liste in den EditingMode. Jetzt können Datenbanken gelöscht werden bis oben in der Leiste auf 'Fertig' gedrückt wird.
