### ISSUE TITLE
Bilder ohne Koordinaten abfragen/behandeln (hab den Titel des Tickets geändert, siehe weiter unten)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#114]
Bugs:
Ich hatte ein Bild in einem Objket mit Positionsdaten. 
Dann habe ich eines (anscheinend) ohne hinzugefügt und dann werde ich gefragt, ob ich welche hinzufügen will,
> a) obwohl das erste Bild welche hat, 

> b) das zweite Bild (also das ich gerade hinzufüge) welche hat. 

> Und wir dann auch Beide Bilder sehr nah beieinander angezeigt werden, weil beide ja auch Koordinaten haben. ABER: keines von beiden wackelt, was für mich irritieend ist, da ich dann nicht weiss, welches ich änder muss.

> Und, klciek ich dann eines an, das dann auch wackelt, dann kann ich es nicht verschieben, weil ich immer die Karte als ganzes verschiebe.

> Und, wenn ich einem Bild (das dann wirklich bei 0 x 0 liegt, also keine Positiondaten hat), neue Koordinaten zzweisne soll, wäre es gut, wenn ich maximal gezoomt starte, weil ich befinde mich ja irgendwo im Atlantik.

Form:
- Das erste Bild (erste klein)
- ..., das du dem (nicht dass)
- ... hinzugefügt hast, enthält keine... (Komma)

**Comment by McFly753** [comment]
Und: kannst Du in dem Abfragefetsner eine weietre Option hinzunehemn und war "meinen Standort verwenden"

**Comment by Mojo1917** [comment]
Alles umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke, passt.
Aber, lass es uns doch immer abfragen (nicht nur beim ersten Bild)
und neben "Nein", "Meinen Standort verwenden" und "Positionsdaten manuell hinzufügen" würde ich auch noch "Positionsdaten aus dem Hauptbild übernehmen" anbieten.

**Comment by McFly753** [comment]
Und: das bitte noch von oben umsetzen: "Und, wenn ich einem Bild (das dann wirklich bei 0 x 0 liegt, also keine Positiondaten hat), neue Koordinaten zzweisne soll, wäre es gut, wenn ich maximal gezoomt starte, weil ich befinde mich ja irgendwo im Atlantik."

**Comment by Mojo1917** [comment]
Okay, das Objekt ist jetzt perfekt zentriert.

**Comment by Mojo1917** [comment]
Das mit dem ausweiten auf alle Bilder mässen wir nach hintern verschieben. Ich schaffe es zeitlich nicht das einzuführen, da es weitaus komplizierter ist als die reine Abfrage fürs erste.

Wie sieht es denn aus, wenn mehrere Bilder ohne Location auf einmal importiert werden? Soll die Abfrage dann für jedes Bild neu erscheinen oder ein Dialog für alle? 
Wie ist es, wenn der Nutzer sich entscheidet bei mehreren Bildern die Position auf der Karte zu ändern? Soll er dann automatisch durch alle Bilder geführt werden?

**Comment by Mojo1917** [comment]
Position aus dem Hauptbild nehmen wird erst relevant, wenn wir es für alle Bilder ausgeweitet haben :)

**Comment by McFly753** [comment]
Und: als weitere Option: Ort auch über andere Bilder als Koordinate zuweisen können (wie bei hinzugefügten Bildern ohne Geokoordinaten)

**Comment by Mojo1917** [comment]
Okay nochmal zusammenfassend:
Bei dem Import von einem oder mehreren Bildern ohne Koordinaten bieten wir folgende Optionen an
1. ‚Meinen Standort verwenden‘: Wird diese Option gewählt fügt die App zu allen neu Importierten Bildern den Standort des Nutzers hinzu.
2. ‚Positionsdaten manuell hinzufügen‘: Dies öffnet die Karte und bietet die Möglichkeit das erste neu importierte Bild zu verschieben. Ist das passiert werden alle neu importierten Bilder auf diese Position gelegt. (Ich denke es macht wenig Sinn dem Nutzer jedes Bild einzeln verschieben zu lassen. Sie gehören ja zum gleichen Objekt und sind damit an der gleich Position)
3. ‚Position aus existierendem Bild importieren‘: Alle Bilder beginnen zu wackeln. Wenn der Nutzer jetzt eins auswählt werden alle neu importierten Bilder auf diese Koordinaten gelegt.

Ich denke das ist dann der fertige Ablauf, oder habe ich was vergessen? ;)

**Comment by Mojo1917** [comment]
Okay. Guter Punkt. Dennoch würde ich hier keinen Extra Dialog anbietem, da wir in dem oben erwähnten Dialog dem Nutzer eh die Möglichkeit bieten den Standort aus einem bereits existierenden Bild zu importieren. Der Nutzer kann hier ja die Option 'Position aus existierendem Bild importieren' wählen. Dann wackeln alle Bilder die eine Position besitzen (auch die neu importierten).

Aber ich kann auch gerne einen zusätzliche  Dialog anbieten der Folgendes bietet: "X der Y importierten Bilder haben keine Positiondaten. Möchtest du die Positionsdaten aus den anderen importierten Bildern importieren?"
Optionen:
- "JA" -> Zeigt dem Nutzer eine Liste der Bilder die er importiert hat an und lässt ihn eine wählen (Hier können wir jedoch die Bilder nicht anzeigen, da dies in einem Dialog nicht geht.)
- "Nein, weitere Optionen" -> Zeigt dem Nutzer den oben beschriebenden Dialog.

**Comment by McFly753** [comment]
wie heute am Tel besprochen.

**Comment by McFly753** [comment]
> Danke, schon sehr gut, nur:

- wenn ich zwei Bilder ohne Koordinaten hochlade, sagt er mir, dass ich das eine wackelnde verschieben soll, er legt nur das andere nicht wackelnde über das wackelnde Bild, so dass ich da nicht hinkomme... ;)

- ich importiere zwei Bilder, eines mit positionsdaten und das andere ohne: das System sagt mir aber dann, dass beide Bilder keine Positionsdaten haben.

- in dem Menü, wenn er auch nach Positionsdaten aus existierendem Bild frägt, ädnere den Text dieser Zeile bitte ab auf: "Position aus anderem Bild übernehmen" // Und die Zeile danach bitte abändern auf: "Position manuell hinzufügen" (also hier Position statt Positionsdaten)  -aber oben deinen Text dieses Fensters so mit Positionsdaten etc. lassen.

-  Lass uns das "Hilfe"-Fenster beim Import später über die Hilfe abbilden, die wir ihm hier einfach beim ersten benutzen anschalten. Das machen wir aber dann in dem Hilfe Ticket. Ändere nur jetzt schon mal den Text ab: 

Positionsdaten manuell hinzufügen
Verschiebe das wackelnde Bild, um dessen Position neu zu bestimmen. Nachem du das Bild platziert hast, kannst Du diesen Vorgang erneut ausführen, indem du das Bild zuerst anklickst, damit es wieder wackelt.

Positionsdaten manuell hinzufügen
Verschiebe das eine wackelnde Bild, um die Position von allen 2 Bildern neu zu bestimmen. Nachem du das Bild platziert hast, kannst Du diesen Vorgang erneut ausführen, indem du das Bild zuerst anklickst, damit es wieder wackelt.

**Comment by Mojo1917** [comment]
Zu 2: Sollte nicht mehr auftreten.

**Comment by Mojo1917** [comment]
Zu 3: Ist angepasst.

**Comment by Mojo1917** [comment]
Zu 4: Auch geändert ;)

**Comment by McFly753** [comment]
Danke!
