### ISSUE TITLE
Titelbild der App ist zerstört, wenn das Iphone oben diese Extra Zeile (Hotspot etc.) anzeigt.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#117]

**Comment by McFly753** [comment]
![img_5941](https://user-images.githubusercontent.com/493612/38392045-61810182-3926-11e8-8808-e3aa68fa0279.png)

Geht noch nicht, aber ist egal, wenns nicht fixbar ist (ich war etwas zu spät beim Bild aufnehmen, Du siehts es schon in der Überbelndungspahse ;) )

**Comment by Mojo1917** [comment]
Okay also der Fehler besteht leider immer noch auch unter iOS 11.4. Wir hoffen einfach mal, dass Apple disen mit iOS 12 behebt :)

**Comment by McFly753** [comment]
Dopplet.
