### ISSUE TITLE
Farben: nimm bitte einen homogenen Farbverlauf in dem Spektrum unseres Blauwertes her. > s. Farbwerte

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#119]
<img width="143" alt="bildschirmfoto 2018-01-29 um 22 37 19" src="https://user-images.githubusercontent.com/493612/35535771-fca8f3f6-0544-11e8-8322-86bff75f3e2e.png">

RGB:
47 145 251
44 134 229
39 121 210
32 103 181
28 89 157
24 76 134

**Comment by Mojo1917** [comment]
Okay nehme die Farben von oben. Es kann nur passieren, dass bei geringer Displayhelligkeit der Unterschied nicht mehr klar sichtbar ist.

**Comment by Mojo1917** [comment]
Neue Farbwerte sind eingebunden.
