### ISSUE TITLE
Der "Koordinaten"-Bobbel dezenter machen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#12]
... er ist irgendwie zu globig. 

> kannst Du ihn auch blau machen 

> und eben kleiner/dezenter machen?

**Comment by Mojo1917** [comment]
Um welchen geht es? den in der Objekt-Einzel-Ansicht?

**Comment by McFly753** [comment]
Ja, wo rechts die kleine Karte angezeigt wird. 
![img_4303](https://user-images.githubusercontent.com/493612/34906017-9c2ffaca-f864-11e7-9da3-665a3b226687.PNG)

**Comment by Mojo1917** [comment]
Okay ist jetzt blau und ich verwende hier jetzt den 'alten' Pin von Apple. Ändert sich dann mit dem nächsten Update.

**Comment by McFly753** [comment]
danke, schau ich dann an.
