### ISSUE TITLE
Bilder-Plugin sollte sich meine letzte Position beim Import merken

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#120]

**Comment by McFly753** [comment]
Lass uns dies zusammen mit dem Sync-Ticket besprechen.

**Comment by Mojo1917** [comment]
Das hatte ich in einer freien Minute schnell in die App eingefügt.
Die Änderung ist in der aktuellsten Version schon enthalten. Die App speichert jetzt für jedes 'Album' den letzten Punkt an dem man zuletzt importiert hat und springt zu diesem sobald das 'Album' ausgewählt wird.
Ich hatte mir nur gedacht, dass man dann vielleicht einen Button braucht um wieder nach ganz oben zu springen. (Oder das Verhalten in den Einstellungen der App kontrollieren?)

Aber das Einfachste ist dies telefonisch zu besprechen.

**Comment by McFly753** [comment]
Ja, ist gut so und so ein Button wäre gut. ODER wir heben diesen Anker einfach nach einer geiwssen Zeit wieder auf? Am nächsten Tag? Oder einfahcere Idee?

**Comment by Mojo1917** [comment]
Ich denke am intuitivsten wäre entweder ein button (Rund unten recht in der Bildschirmecke) der einem erlaubt nach oben zu springen
Oder wir setzen die Position immer nach einem Neustart der App zurück.

**Comment by McFly753** [comment]
Meinst Du mit neustart, dass sie wirklich abgeschossen sein muss? Das debke ich macht keinen Sinn

> dann eher mit diesem Button.

**Comment by Mojo1917** [comment]
Nein ich meinte hier, wenn die App in den Hintergrund geht.

Aber wahrscheinlich ist der Button am sinnvollsten. Dann kann der Nutzer dies kontrollieren.

**Comment by Mojo1917** [comment]
Okay Floating Button unten rechts ist eingebunden.

**Comment by McFly753** [comment]
Ist schön, Danke. NUR: positioniere ihn bitte unten links. Er ist zu präsent und kann schnell verwechselt werden mit "Hochladen".

**Comment by Mojo1917** [comment]
Okay verstehe. Ich persönlich finde die Funktion des Buttons recht logisch. Da ich ja aus meiner Mediathek importiere macht ein 'Upload' Button recht wenig Sinn. Aber ich habe vielleicht auch die falsche Sichtweise.

Habe jetzt mal Text, Icon und Text und nur Icon ausprobiert und Icon und Text sieht nicht aus. Wir müssen und entweder für Text oder Icon entscheiden.

Ich habe einen Screenshot angehängt wie der Button unten links mit Text aussieht. Dann kannst du besser entscheiden.

**Comment by Mojo1917** [comment]
![foto 13 06 18 11 34 57](https://user-images.githubusercontent.com/20678932/41343079-f7543a0a-6efd-11e8-96bf-69ab0b83793a.png)

**Comment by McFly753** [comment]
Ok, dann lass es, wie Du es ursprünglich hattest und wir testen es an meinem Team.
