### ISSUE TITLE
Suche-Feld blau hinterlegen, wenn als Filter aktiv

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#121]
... ich stolperer des öferen drüber, dass ich noch einen Text im Suchefilter habe, und das nicht erkenne, wenn die Suchleiste ausgeklappt ist

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Ist gut so, kannst Du nur dann, wenn der Eintrag hier blau ist, vor den Eintrag noch "Suche:" hinschreiben. Das ist intuitivier, was hier los ist... ;)

**Comment by Mojo1917** [comment]
Klar. Jedoch habe wir dann immer einen zusätzlichen Text in diesem Feld.

**Comment by Mojo1917** [comment]
Ist eingefügt. Sobald die Suchzeile text enthält setzt die App hier ein "Suche: " vor.
