### ISSUE TITLE
Done Button fehlte

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#122]
(Von Max:)
Bug (ist nur einmal aufgetaucht ): Bei Photo Import -> Camera Roll hat der "Done" Button gefehlt, aber der Ort an dem ich den Knopf vermutet hatte hat trotzdem funktioniert

**Comment by Mojo1917** [comment]
Okay ich habe die neuste Version des Plugins installiert. Button ist bei mir jetzt ausnahmslos immer sichtbar gewesen.
