### ISSUE TITLE
Sortierung sollte bei der Liste "Sortierung" heissen und nur bei der Karte "Farbsortierung"

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#124]
![img_5943](https://user-images.githubusercontent.com/493612/38393944-d5807a3a-392c-11e8-8f2f-3756c073c7ea.jpeg)

**Comment by McFly753** [comment]
Wenn Du es nicht ändern willst, müssten wir es dynamsich immer Sortierung lauten lassen

**Comment by Mojo1917** [comment]
Behoben
