### ISSUE TITLE
Beim Objektname Ändern das Feld mit dem alten Namen ausfüllen und alles markieren

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#125]
Könntest Du den derzeitigen Objektname in das Feld vorausfüllen, aber hier komplett markieren? Also dass wenn man anfängt, zu schreiben, dass es gleich gelöscht wird. Man aber auch Teile des alten Namens übernehmen kann?

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit nächsten Upload.

**Comment by McFly753** [comment]
danke, nur kannst Du hier immer den aktuellen Namen dort zeigen und markieren? (s. Screenshot)

**Comment by Mojo1917** [comment]
Sorry war ein Fehler im Nachladen des Objekts nach der Änderung. Korrektur kommt mit dem nächsten Update.
