### ISSUE TITLE
Grafisches Detail: könntest Du den blauen Pfeil bei dem ausgeklappten Filter/Sortier-Bereich etwas tiefer setzen (orientiere Dich optisch an den Text "Filter" links)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#127]
Damit kannst Du auch den ganzen Bereich etwass kleiner bekommen.

**Comment by Mojo1917** [comment]
Klar können wir machen, aber dann wir die aktive Fläche des Buttons sehr kein. Er wird dann schwerer zu treffen sein.
Sollen wir es dennoch umsetzten?

**Comment by McFly753** [comment]
Muss ich mir anschauen. (meine Tstversion ist abgelaufen)

**Comment by McFly753** [comment]
Lieber Niklas, lass es uns mal versuchen. Denn wir können ja auch noch wischen.

UND, in diesem Schritt: kannst Du die "wischbare" aktive Fläche auch nach unten zu den zwei Butosn (Karte und Liste) erweitern, so dass man diese auch schon zum hochwischen verwenden kann?

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.
