### ISSUE TITLE
Sortierreihenfolge ändert sich in der Listenansicht bei Entfernungssortierung nicht...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#129]
... ich habe das Foto von meiner Kollegin Magda bekommen, was mich an den beiden Fotos irritiert, ist, dass keine Entfernungen angeziegt werden, aber Orte?

![img_9641](https://user-images.githubusercontent.com/493612/38643355-2755ae66-3ddd-11e8-990c-37d1996b8fda.PNG)
![img_9640](https://user-images.githubusercontent.com/493612/38643360-2ce8566c-3ddd-11e8-9b39-0326555d29b9.PNG)

**Comment by Mojo1917** [comment]
Die App zeigt die Entfernung unter zwei Umständen nicht an:
1. Die App hat keinen Zugriff auf den Standort -> Muss dann in den Einstellungen aktiviert werden
2. Die App hat zwar eine Freigabe für den Standort iOS konnte diesen jedoch noch nicht erfassen. Sobald der Standort vom System erfasst wurde aktualisiert sich die Ansicht in der App. Dann funktioniert auch die Sortierung.

**Comment by Mojo1917** [comment]
Habe folgendes nochmals aus Performance-Gründen angepasst:
Sollte die Standortanfrage beim Ersten Mal scheitern versucht die im 30 Sekunden Intervall diesen erneut zu erhalten.

**Comment by McFly753** [comment]
Aber wird nichgt der Standort der letzten Erfassung vom Iphone immer gespeichert und dann verwendet?

**Comment by Mojo1917** [comment]
Naja das weiß ich nicht. Vielleicht für Systemdienst. 
Für Apps ist es jedoch wie folgt: Sobald die App beginnt den Standort zu verfolgen wird die erste neu erfasste Position nach Beginn der Erfassung an die App weitergegeben. Mit dieser kann dann gearbeitet werden. Alle Positionen die vor Beginn der aktuellen Standort Verfolgung vom System erfasst wurden werden nicht weitergegeben.

**Comment by McFly753** [comment]
Ich schliesse das Ticket mal. Wenn so ein Fehelr nochmals auftritt, vesuche ich ihn besser eingrenzen zu können.
