### ISSUE TITLE
Letzte Besuche sollten durch die Bilder beschrieben werden

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#13]
1. das Hauptbild sollte nbeben dem Erstellungsdatum auch den ersten "letzten Besuch" schreiben.

2. Haben weitere BIlder andere Datume als das Hauptbild, schreiben sie wiederum ein/mehrere "letzte Besuche"

**Comment by McFly753** [comment]
Aber, hier müssen wir aufpassen, dass das Hauptbild diesen Ersten besuch nur schreiebn darf, wenn es das aller erste Hauptbild ist. Nicht dass beim Verändern der Reihenfolge dauernd der letzte Besuch umgeschreiben wird. // Hier müssen wir auch darauf aufpassen, dass auch das Erstellunhgsdatum nicht umgeschreieben wird. // Nur der Ort wird umgeschrieben.

**Comment by Mojo1917** [comment]
Okay, wie soll die App sich in folgendem Fall verhalten:
1. Bild wird hinzugefügt und damit Besuch geschrieben.
2. Das Erstellungsdatum des Bilds wird geändert.

Soll dieser Fall einfach ignoriert werden?

**Comment by McFly753** [comment]
Ja. Prinzipiell: jede Änderung irgendeines Bildes (Haupt oder Nebenbild) ändert nie rückwirkend ein Datum (weder Erstellung noch Besuch). Aber: jedes Bild ändert immer die Orte (Huaotbild auch im Objekt selbst. Diese Ortsdaten werden somit immer von dem Hauptbild übernommen.

**Comment by Mojo1917** [comment]
Ist umgesetzt wie oben beschrieben bzw. gestern am Telefon besprochen.
Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Alles klar, Danke!

**Comment by McFly753** [comment]
Passt: nur: dreh die Sortierreihnefolge der "letzten Besuche" in dem "letzten Besuche Fenster" um, oben sollte natürlcih der letzte Besuch zuerst stehen, also oben jüngeres Datum, unten älteres.

**Comment by McFly753** [comment]
Und: stell mal den einen Besuch auf ein paar Jahre zurück ein:

> schau, dass dennoch das ganze absolute Datum sichtbar ist und auch das "Tagen" ausgeschrieben ist. Der Platz reicht ja.

> Und, KLeinigkeit: kannst Du Tausenderpunkte setzen. ;)

**Comment by McFly753** [comment]
![img_4410](https://user-images.githubusercontent.com/493612/35177848-9a15e19a-fd83-11e7-8a6d-3f1bc7b29b07.PNG)

**Comment by Mojo1917** [comment]
Ist behoben. Trennzeichen ist auch eingefügt. Änderung kommt mit dem nächsten Update.
