### ISSUE TITLE
Ich hätte gerne eine andere Zoomstufe, wenn man auf der Karte nach einem Land sucht. Gibt man Deutschland ein, dann sollte die Zoomstufe auf dem Umriß von ganz Deutschland abgestimmt sein.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#134]
(von meinem Kollegen Robert)

**Comment by Mojo1917** [comment]
Okay können wir so machen. Da wir jedoch nicht wissen ob der User nach einem Land oder einem Ort sucht müssen wir für alle Suchstufen festlegen wie weit die App herauszoomt.
Sollen wir diese auf 'Landes-Zoom' legen?

**Comment by Mojo1917** [comment]
Oder wir bieten dem Nutzer doch die Möglichkeit in der Suche anzugeben ob er einen Ort / Land sucht. Dann können wir dies hier noch ein wenig verfeinern.

**Comment by McFly753** [comment]
Können wir es nicht so versuchen, wie am Tel besprochne. Du suchst Du beides, also Ort und Land und erkennst, was er zurücklifert und stellst dementsprechend die Zoom-Stufe ein?

**Comment by Mojo1917** [comment]
Klar wir versuchen es ;)

**Comment by Mojo1917** [comment]
Ich habe jetzt doch eine Möglichkeit gefunden die genaue Fläche eines Landes oder Stadt zu erfassen. Die App zoomt jetzt perfekt auf alle gesuchten Orte. 
Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Super, Danke!
