### ISSUE TITLE
"Alle Filter aufheben" anbieten, wenn man auf 0 Ergebnisse Filtert

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#135]
> im Hauptscreen

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
bitte einen Punkt nach "aufzuheben" ;)

**Comment by Mojo1917** [comment]
Okay klar! hatte deinen Kommentar oben falsch verstanden.

**Comment by McFly753** [comment]
Danke. NUR: bitt zeige diese zweite Zeile mit dem Filter NICHT an, wenn die Datenbank noch keine Obejkte hat, das verwirrt nur.

**Comment by Mojo1917** [comment]
Kommt mit dem nächsten Update.
