### ISSUE TITLE
Zugriff auf Datenbank-Wechsel vereinfachen 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#136]
Es gibt in unserem Team User, die die App frü verschiedene Datenbanken nutzen würden, auf die sie tägllich zugreifen. Somit sollten wir den Datenbankwechsel ihnen vereinfachen.

Was wäre, wenn wir oben den Titel der Datenbank verwednen. Das Klick darauf ist ja schon verwendet (Statistik), aber man könnte rechts/links wischen, um die Datenbanken zu ändern?

**Comment by Mojo1917** [comment]
Ist implementiert. Änderung ist jedoch noch nicht im letzten Update eingeschlossen.
