### ISSUE TITLE
Bilder, die mit der App fotografiert werden, sollten automatisch auch in die "normale" Foto-App des iPhones übernommen werden. Wäre gut für die Datensicherung.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#137]
ist wichtig.

**Comment by Mojo1917** [comment]
Ist eingefügt. Hierfür benötigt die App Zugriff auf die Fotos. Wenn Dieser Zugriff nicht gewährt ist gibt die App zusätzlich einen Hinweis aus.

**Comment by McFly753** [comment]
Zwei Dinge:

1. Bitte im Dialog noch die Kommas setzen, und zwar: 
- ... gesichert werden kann, ...
- ... zu aktivieren, ...
- ... nicht möchtest, ...

2. In dem Dialogfeld in den Einstellugen kann ich nichts in dieser Richtung einstellen?
![img_7596](https://user-images.githubusercontent.com/493612/41191984-329004e0-6c2a-11e8-89d7-103ee9715e21.PNG)

**Comment by Mojo1917** [comment]
Option wird jetzt immer angezeigt.

**Comment by McFly753** [comment]
Hab jetzt zwar keine Option bekommen, aber die Bilder werden auch in der Fotoapp abgelegt...
Damit schliesse ich das Ticket.
