### ISSUE TITLE
Könnten wir noch eine Bemerkung bei jedem Bild erlauben?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#139]
Dass wir unten über dem Datum ein Textfeld zulassen?

Text: ...

und eben das Veränderungs-Popup dann bei Klick auf diese Feld öffen. 

Die Frage ist nur, was zeiegn wir an, solange kein Text drin ist? Weil ein leeres Feld direkt ujnter dem Foto sieht nicht gut aus. Oder wir zeigen es leer nicht an, doch wo kann man dann seinen ersten Text eingeben? (Über klick oben auf den Titel)? - Hast Du hier eine Idee?

**Comment by Mojo1917** [comment]
Ja auf jeden Fall!

Ich würde dies für eine einfach Nutzerführung immer über die gleiche Aktion machen und wie folgt implementieren:
Wenn kein Text festgelegt ist würde ich in grauer Schrift 'Tippe hier um einen Kommentar hinzuzufügen' anzeigen. Wenn dann ein Kommentar hinzugefügt ist, ist dem Nutzer direkt klar, dass er diesen über einen Klick auf diesen ändern kann. (Sonst müssten wir spätestens dann dem Nutzer einen entsprechenden Hinweis geben.)

**Comment by McFly753** [comment]
Wie heute am Tel. besprochen.

**Comment by Mojo1917** [comment]
Einen Punkt haben wir hier vergessen. was machen wir, wenn der Text länger wird als in eine Zeile passt? 
Sollen wir dann mehrere Zeilen einblenden? Dann müssen wir jedoch die mögliche Fläche des Bildes verkleinern. 
Oder sollen wir dann den Anfang des Textes anzeigen und wenn der Nutzer darauf klickt den ganzen Text in einem Popup. Hier bieten wir dann auch den Button zum bearbeiten an.

**Comment by Mojo1917** [comment]
Objekt kann jetzt durch klick auf die Titelbar in der Großansicht der Bilder geändert werden.

**Comment by Mojo1917** [comment]
Dialog zum ändern des Kommentars wird angezeigt. Wir müssen uns nur überlegen was das schlauste ist um mit langen Kommentaren umzugehen.

**Comment by Mojo1917** [comment]
Ist umgesetzt.

**Comment by Mojo1917** [comment]
Ist übernnommenn
