### ISSUE TITLE
Hilfe erweitern

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#141]

**Comment by McFly753** [comment]
@Mojo1917 Wenn wir die Hilfe so aufsetzen, wie besperochen, dass wir eine por "Screen" haben, dann haben wir:

- Einstellungen (1)

- Einstellungen/Datenbank (oder schreiben wir es klein drüber, wie beim Sichern?)
- Einstellungen/Objketeigenschaften (oder schreiben wir es klein drüber, wie beim Sichern?)
- Einstellungen/Tags (oder schreiben wir es klein drüber, wie beim Sichern?)
- Einstellungen/Entfernungsbenachrichtigung (oder schreiben wir es klein drüber, wie beim Sichern?)
- Einstellungen/Jahresbenachrichtigung (oder schreiben wir es klein drüber, wie beim Sichern?)
- Einstellungen/Sichern (oder schreiben wir es klein drüber, wie hier?)
- Einstellungen/Wiederherstellen (oder schreiben wir es klein drüber, wie beim Sichern?)

- Listenansicht (2)
- Kartenansicht (3)
- Detailansicht (4)
- Bilderansicht (5)
- Ort ändern (6)
- Statistik (7)

- Letzte Besuche (oder schreiben wir es klein drüber?)
- Tags (oder schreiben wir es klein drüber?)

> In meinen Augen: 7 Hilfeseiten. Hierbei müssen wir ja das Icon positionieren können.
Das geht recht gut bei: 
- Einstellungen (1) (lass uns hier nur das Impressum rausnhemen und als letzten Menüpunkt unter das Wiederherstellen setzen.
- Listenansicht (2)
- Kartenansicht (3)
- Bilderansicht (5)
- Ort ändern (6)
- Statistik (7)

Nur nicht so gut bei Deatilansicht, da wir hier schon den Abfalleimer und das Sharen haben (den Favoritenstern haben wir ja schon ausgelagert).
Was hältst Du davon, wenn wir hier den Abfalleimer und ds Sharen unter ... (hochkant) verstecken udn links daneben die Hilfe setzen?

>> Willst Du diese Anpassungen mal machen und schonmal dann die Hilfe für die verschiedenen Objkete "durchschaktbar" machen, nur ohne Text?

**Comment by Mojo1917** [comment]
Ich denke auch, dass diese 7 Seite reichen sollten. Die Anderen sind wie du schon gesagt hast selbsterklärend.
Ich werde die Anpassungen mit dem nächsten Update einspielen.

**Comment by Mojo1917** [comment]
Ich denke für die Statistik sowie Ort ändern ist kein 'geführtes Tutorial', wie wir es für alle komplexeren Ansichten haben, notwendig. Ich denke hier macht es Sinn, wenn wir nach dem Klicken auf das Fragezeichen einen einzelnen knappen Dialog zeigen, der dem Nutzer die Möglichkeiten der aktuellen Ansicht zeigt. Ähnlich wie bei Ort ändern, wenn der Nutzer eine Gruppe von Bildern positioniert.

Wir können uns zudem überlegen einen solchen Dialog für alle anderen Ansichten zu zeigen die du oben schon erwähnt hast.

Was denkst du?

**Comment by Mojo1917** [comment]
Für alle anderen Ansichten habe ich das Tutorial ohne Texte implementiert. 
Leider können wir die Buttons in der oberen Leiste nicht im Tutorial markieren. Ich denke jedoch, dass diese selbsterklärend sind. 
Zudem habe ich manche Elemente gruppiert und zeige sie in einer Info-Blase, damit das Tutorial nicht zu lang wird.

Die Änderungen kommen mit dem nächsten Update.

**Comment by Mojo1917** [comment]
Zusätzlich kann jetzt auf jede Stelle des Bildschirms getippt werden um zum nächsten Tipp zu gelangen -> Ein Button lies sich nicht zuverlässig platzieren; trotzdem umgehen wir somit das Problem, dass der Nutzer erwartet mit dem UI-Element interagieren zu können.

**Comment by Mojo1917** [comment]
Eins hatte ich noch vergessen: Bezüglich der Listen/Karten-Ansicht und unserem Problem mit dem 'Rahmen'. Ich habe jetzt die gesamte Ansicht als Ganzes behandelt. Das heißt das Tutorial für diese wird immer als gesamtes abgespielt. Wenn dir das so nicht gefällt kann ich es gerne noch anpassen.

**Comment by McFly753** [comment]
Lieber Niklas, ich habe oben unsere Kommentare nochmals druchlesen und würde noch folegndes (zu dem heute besprochenen wie Rahmen separat, Anker, Fortschritt, Tour starten/fortführen...) ergänzen:

1.) die App stürzt ab, wenn ich die Hilfe beim "Ort ändern" aufmachen will
2.) nach dem Hilfekreis der Kartenansicht springt das Tutorial ohne zu fragen in die Detailansicht.
3.) Bei Tags (aus der Detailansicht): lass uns hier noch eine HIlfe anbieten, den selben Text wie in den Einstellungen.
4.) Kannst Du das noch implementieren: "Schliesst der zum ertsen mal die Hilfe durch "Abbrechen", bestätigen wir dies noch mit einer Hilfeseite/Popupseite und schreiben dort: Alles klar, Du kannst jederzeit die Tour durch Klick auf dieses Symbol wieder starten. -> OK (schliesst dann die Hilfe). (Aber das merken wir uns, so dass das nur einmal gezeigt wird.)

**Comment by Mojo1917** [comment]
Zu 1: Okay Fehler sollte mit dem nächsten Update behoben sein.
Zu 2: Frage ist jetzt eingebaut.
Zu 3: Klar, kommt mit dem nächsten Update.
Zu 4: Klar, kommt mit dem nächsten Update.
Zu 5: Klar, Buttons liegen jetzt auch auf großen Displays zentriert unter dem Text

**Comment by Mojo1917** [comment]
Zu 6: Diese Funktion hatte ich auch noch nicht gesehen. Ist jetzt aber deaktiviert.
Zu 7: Klar die Buttons sind jetzt neu benannt und einen entsprechenden Dialog zeigen wir auch an.

**Comment by Mojo1917** [comment]
Zu 8-11: Sind eingebunden.

**Comment by Mojo1917** [comment]
Okay ich habe hierzu noch 2 Fälle für die wir uns überlegen müssen wie wir hiermit umgehen:
Was passiert, wenn der Nutzer auf einer Seite das Tutorial startet die er schon abgeschlossen hat. Nach aktueller Logik springt die App zu der nächsten nicht erledigten Blase (außerhalb). Sollen wir in diesem Fall die aktuelle Seite zurücksetzen und den Nutzer wieder durch die Ganze führen? Im Anschluss machen wir dort weiter wo es nach unserer Hierarchie weiter geht.

Fall 2: Was sollen wir machen, wenn der Nutzer das gesamte Tutorial abgeschlossen hat? Sollen wir auch in diesem Fall die gesamte aktuelle Seite zurücksetzen?

**Comment by Mojo1917** [comment]
Okay ich setzt die beiden Punkte so um :)

**Comment by Mojo1917** [comment]
Ist komplett umgesetzt. Update wird hoffentlich morgen freigeschaltet ;)
