### ISSUE TITLE
2-Sprachigkeit (Englisch)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#142]

**Comment by McFly753** [comment]
Sobald wir mit der Deustchen Version druch sind, wäre es gut, wenn Du nen Export über alle texte fahren könnetst (etc. - Du meinstets, Apple hat das standarisiert), so dass ich alles zum Übersetzen geben kann...

**Comment by McFly753** [comment]
Wenn Du die letzten Tickets eingebaut hast, willst Du mir dann diesen Export schciken?

**Comment by McFly753** [comment]
Wenn Du den nächsten Upload mit allen Tickets gemacht hast, könnetst Du mir auch schonmal den Export zum Überstezen geben.

**Comment by Mojo1917** [comment]
Klar mache ich dann!

**Comment by Mojo1917** [comment]
Sende ich dir morgen früh zu!

**Comment by McFly753** [comment]
Schau ich mir noch an.

**Comment by Mojo1917** [comment]
Neue Sprachdatei folgt mit dem nächsten Update.

**Comment by McFly753** [comment]
OK!

**Comment by Mojo1917** [comment]
Hier werden sich mit dem aktuellen Update noch ein paar weitere Strings ergeben

**Comment by Mojo1917** [comment]
Alles klar!

**Comment by Mojo1917** [comment]
Ich sende dir den Export zu, wenn wir nach dem aktuellen Update keine Text-Änderungen mehr haben ;)

**Comment by McFly753** [comment]
ok ;)

**Comment by Mojo1917** [comment]
Update mit dem Englischen Sprachpaket lädt gerade zu Apple hoch ;)

**Comment by Mojo1917** [comment]
PS.: Wenn mich nicht alles täuscht, dann müssen wir die Beschriftung der Menüs im Englischen umstellen, oder?

**Comment by McFly753** [comment]
ok, ja.

**Comment by McFly753** [comment]
Ich schliesse dieses Ticket und ggf. gehen wir dann auf einzel-Fälle über
