### ISSUE TITLE
(Im Zuge des Import/Exports) - und ein letztes Feature: Verschicken eines Objektes ermöglichen.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#143]
Lieber Niklas, ich hatte meine internenen Aufzeichnungen abgeglcihen udn dies ist das letztes Feature, das ich Dir noch nicht mitgeteuilt hatte:

> Können wir es umsetzen, dass ein User ein ganzes Objekt an einen anderen User schickt, der dieses dann zu seiner Datenbank hinzufügt?

(Wir haben hier wie beim anderen Import ein Porblem, wenn die User-Datenbank-Strukturen unterschiedlcih sidn. Das könnten wir leicht umgehen, indem wir Tags und Eigenschaften einfach so importieren, als wären die Strukturen identisch, wir dies aber als Abfragemenü darstellen, wo wir die geschriebenen Felder (und die Feldüberschriften von User Empfänger) mit den Ursprünglcihen Feldbeschriftungen (von User Sender) gegenüberstellen und wir dem User zulassen, in diesem Schritt diese Daten abzuändern. -> Was denkst Du, geht das alles tehnisch und wie schcike ich? (per Email? Als ZIP?)) Danke!

**Comment by Mojo1917** [comment]
Ja das lässt sich auf jeden Fall einbauen.
Nur nochmal, dass ich das richtig verstanden habe:
1. Der Nutzer wählt die Datei, die er erhalten hat aus.
2. Locbase öffnet sich und fragt in welche Datenbank der Nutzer dieses Objekt einfügen möchte.
3. Die App zeigt dem Nutzer die original hinterlegten Tags und lässt ihn diese in die eigene Datenbank aufnehmen, wenn Tags mit gleichem Text nicht schon existieren?
4. Die App zeigt dem Nutzer die original ausgewählten Eigenschaften und lässt ihn Äquivalente aus der eigenen Datenbank wählen?

Zum Verschicken würde ich den gleichen Dialog verwenden, den wir auch beim Exportieren des Backups verwenden. Hier werden ja alle gängigen Methoden angezeigt. Zudem auch WhatsApp und Mail.
Dies natürlich auch als .locbase Datei.

(Punkt 3 und 4 werden sehr zeitintensiv, weil wir zusätzlich zum reinen Import (den wir für das eintragen vielen Objekt geplant haben) dem Nutzer noch die Möglichkeit des Abgleichens von Tags und Eigenschaften bieten müssen. -> Dieses Abgleichen hatten wir uns für den Import gespart, weil wir uns dazu entschieden hatten dem Nutzer das Verändern von Tags und Eigenschaften nicht zu erlauben / ermöglichen.

**Comment by Mojo1917** [comment]
Eine Frage noch: Für das Backup gibt es mit dem folgenden Update die Möglichkeit die Backup-Datei aus Locbase heraus auszuwählen. Wie sollen wir hier mit dem empfangenen Objekt umgehen?
Ich hatte zuerst überlegt einen ähnlichen Dialog einzubinden. Ich denke jedoch, dass man die meisten Objekt über Mail, WhatsApp, etc. erhalten wird. Da der Dialog jedoch nur für Cloud-Dienst funktioniert macht das nicht viel Sinn. Sollen wir daher nur die Möglichkeit bieten ein Objekt wie bisher auch ein Backup nur aus der entsprechenden App zu Locbase zu kopieren?

**Comment by McFly753** [comment]
Dann lass es uns einfacher machen: wir üebrtragen alles, was immer sicher geht und weisen den (davor den sendenen User) und den empfangen User dann darauf hin, dass keine individuellen Objketeinstellungen oder Tags übertragen werden/wurden. (Und dem Empfänger wird hier dann ausdrücklcih gesagt, dass er bei diesem Objekt noch diese Infos hinzufügen muss und dann sprinbgen wir in die Deatilansoicht des Objektes. / Sollte dann nicht so aufwändig sein, oder?

Beim Empfangen: nur von SMS/Whatsapp etc. aus ausgelöst, braucht der Empfänbger nicht "auslösen" zu können. (Wie beim Teilen einer Notiz bei Apple etc.).

**Comment by Mojo1917** [comment]
Ja das macht es auf jeden Fall leichter. Wir können die Funktion ja jederzeit erweitern ;)

Okay dass implementiere ich es so.

**Comment by McFly753** [comment]
Danke! Funktioniert (über Mail), aber: Ich kann die Datei senden, aber mit Imessage nicht öffnen, weil ich sie nicht anklicken kann etc.?

Und: Der Favoritenstern geht jetzt etwas unter. Lass uns den Linksbündig über "Erstellt vor x Tagen" setzen, und dafür diese beiden Sektionen weiter runter. Da sollte er gut aufgehoben sein.

**Comment by McFly753** [comment]
![img_8602](https://user-images.githubusercontent.com/493612/42398337-c5a896bc-8169-11e8-8f1c-70929cde97bc.PNG)

**Comment by McFly753** [comment]
![img_8606](https://user-images.githubusercontent.com/493612/42399194-2ae47354-816d-11e8-9bde-6f5837c35412.PNG)

**Comment by Mojo1917** [comment]
Zu WhatsApp: Funktioniert bei mir einwandfrei. Nutzt du die aktuellste WhatsApp Version? Früher hat WhatsApp dies nicht zugelassen.

**Comment by Mojo1917** [comment]
Fehler mit der gescrollten Liste ist behoben.

**Comment by Mojo1917** [comment]
Datei kann jetzt in iMessage angeklickt und geöffnet werden.

**Comment by McFly753** [comment]
Ok, du hast reicht, mein WhatsApp hat irgendeinen bug - ich checke es mit der nächsten Version

**Comment by Mojo1917** [comment]
Ist soweit umgesetzt.
Aber: Den Stern können wir nur schwer an diese Position legen. Auf dem iPhone 5 und allen anderen so kleinen iPhones ist dort leider nicht genug Platz. Wir könnten uns überlegen ihn nicht linksbündig sondern rechtsbündig (also oben rechts in der Ecke unter der Toolbar) oder in der Ecke oben links auf dem Titelbild zu platzieren.

**Comment by Mojo1917** [comment]
Button liegt jetzt im Bild in der Ecke unten rechts. Bin mir nur jetzt nicht mehr sicher, ob der Nutzer am Anfang nicht denkt er würde das Bild als Favorit markieren. Andererseits kann er ja nur das erste Bild markieren...
