### ISSUE TITLE
Könntest Du auf diesem Fenster unten mittracken, WANN welches Backup mit welcher DATEIGRÖSSE und der ANZAHL aller Objekte gemacht wurde und wie der NAME der exportierte Datei war? Evtl. auch mit Lösch-Button des Eintrages in diesem Listing?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#147]
![41d33002-925e-478b-ba28-297fb4efa701](https://user-images.githubusercontent.com/493612/41881656-d42d0d36-78e4-11e8-9504-9368038c3779.png)

**Comment by Mojo1917** [comment]
Ja klar kann ich einbauen. Ich lege hierfür eine Datenbank an in der wir alles tracken können. Ich schließe diese jedoch nicht ins Backup ein, oder sollen wir diese auch sichern?

**Comment by Mojo1917** [comment]
Okay! Habe es so eingebaut. Diese Daten werden von dem Backup nicht berührt.
Die Option Einträge zu löschen folgt morgen ;) Genauso wie ein neues Update über TestFlight.

**Comment by Mojo1917** [comment]
Ist jetzt komplett implementiert. Folgt mit dem nächsten Update.

**Comment by McFly753** [comment]
Super, Danke! Nimm bitte die Uhrzeit noch hinzu.

**Comment by Mojo1917** [comment]
umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke! Kleine Anpassung:
- führe die Überschrift mit "ERSTELLTE SICHERUNGEN" hier erst auf, wenn es mind. eine Sicherung zum Anzeigen gibt.

**Comment by McFly753** [comment]
Danke
