### ISSUE TITLE
Kleine Textänderungen:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#151]
- „Einspielung des Backups erfolgreich“
- „Bitte beende jetzt die App und starte sie dann neu.“

-> kannst Du einen Neustart nicht erzwingen?
![215a76dd-7808-410a-92b4-620ab72459e5](https://user-images.githubusercontent.com/493612/41881978-a4997dfa-78e6-11e8-9d35-15155488de70.png)

**Comment by McFly753** [comment]
-> kannst Du einen Neustart nicht erzwingen?

**Comment by Mojo1917** [comment]
Klar! Ich wollte nur zuerst einmal den Import an sich einspielen, bevor alles zu komplex wird und sich Fehler schwerer finden lassen.

Neustart der App ist jetzt nur noch notwendig, wenn die App daran scheitert die aktuellen Ansichten zu aktualisieren. In all meinen Tests hat dies jedoch immer funktioniert und ein Neustart war nicht mehr erforderlich.
