### ISSUE TITLE
Kleine optische Verbesserung

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#153]
wir könnten oben rechts doch schreiben:
- Erstellt vor 6 Tagen am:

Und auch:
- Letzer Besuch vor 23 Tagen am:

Und, schreib die Entfernung in der gleichen kleinen Dchriftsrt wie die Koordinate.
![f92378f0-7910-409a-8c85-c1a0d3b94c02](https://user-images.githubusercontent.com/493612/41882165-a0219536-78e7-11e8-9738-f28bbdade00d.png)

**Comment by Mojo1917** [comment]
Ist umgesetzt. Auf dem 5er iPhone erzeugt die App jetzt einen Zeilenumbruch, damit alles lesbar ist.
