### ISSUE TITLE
Nach Filterwechsel (in dem Fall durch Klick auf eine Stadt in der Statistik) sollt auch die Karte richtig hingescrollt werden 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#154]
![24ca5a8c-6fca-4306-8214-451ce125c5c4](https://user-images.githubusercontent.com/493612/41882440-25201748-78e9-11e8-85a0-9f81f20c5089.png)

**Comment by Mojo1917** [comment]
App zentriert jetzt immer richtig. Zusätzlich übernimmt die App den Kartenausschnitt, wenn der Filter ein/aus geklappt wird. Dadurch erfolgt hier eine neu Zentrierung.
