### ISSUE TITLE
Dieser Fehler ist mal wieder aufgetreten 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#155]
![10f3fd2a-1cf4-45be-bc59-2b1d36b8cb38](https://user-images.githubusercontent.com/493612/41882460-47274410-78e9-11e8-8fa7-a3f20489cdcb.png)

**Comment by Mojo1917** [comment]
Gefunden und behoben ;)

**Comment by McFly753** [comment]
ich schliesse es mal - wusste nicht, wie ich den Bug reporduzieren kann. Falls er doch nochmals auftreten sollte, gebe ich Dir bescheid.
