### ISSUE TITLE
Bild-Positionierung muss mit klick bestätigt werden.

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#157]

**Comment by Mojo1917** [comment]
Ist eigefügt. Die Position für ein Bild wird jetzt erst geschrieben, wenn das wackelnde Bild ein Mal angeklickt wird oder ein anderes Bild gewählt wird.

**Comment by McFly753** [comment]
Passt, Danke. Ändere bitte nur die Erklärung ab auf: "...Nachdem du das Bild fertig plaziert hast, beende die Neupositionierung durch einen erneuten Klick auf das wackelnde Bild."

**Comment by Mojo1917** [comment]
Übernommen.

**Comment by McFly753** [comment]
danke
