### ISSUE TITLE
Komische Anzeige beim Import eines Objekts ohne Position

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#158]
![img_8598](https://user-images.githubusercontent.com/493612/42398115-dbb19766-8168-11e8-8e62-e077a2340a15.PNG)

**Comment by Mojo1917** [comment]
War ein Fehler in der Übersetzung ;) Ist in der nächsten Version behoben!

**Comment by McFly753** [comment]
Danke
