### ISSUE TITLE
Bitte hier nicht "Abbrechen" verwenden, sondern "Nein"

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#159]
![img_8597](https://user-images.githubusercontent.com/493612/42398159-ff677dd8-8168-11e8-900c-defa72aafce8.PNG)

**Comment by McFly753** [comment]
@Mojo1917 Was passiert eigentlich, wenn ich NEIN sage? Habe ich dann einen Besuch vor dem Erstellujnhgsdatum oder was machen wir mit dem Datum des Bildes?

**Comment by Mojo1917** [comment]
Ist angepasst. Wählt der Nutzer 'Nein' wird der Besuch nicht erstellt und das Datum nicht geändert.

**Comment by McFly753** [comment]
Ok, passt.

**Comment by McFly753** [comment]
Danke
