### ISSUE TITLE
Kannst Du sowas als Button oder Unterstrichen etc. anzeigen?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#160]
![img_8595](https://user-images.githubusercontent.com/493612/42398257-6f307926-8169-11e8-8aee-15e4bf588261.PNG)

**Comment by McFly753** [comment]
... und hier siehts Du das Leerzeichenproblem (anderes Ticket)

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Das Leerzeichen Problem behebe ich zusammen mit dem anderen ticket ;)

**Comment by McFly753** [comment]
danke!
