### ISSUE TITLE
Kleinigkeit: nach dem Löschen einer ganzen Datenbank: kannst Du dann erstmal zurück die die Haupteinstellungen springen?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#161]

**Comment by Mojo1917** [comment]
Ist eingebunden. Jedoch kann der Nutzer dann keine neue Datenbank auswählen sollte er mehrere haben ;)

**Comment by McFly753** [comment]
Doch, ich würde automatisch auf die danach springen

**Comment by Mojo1917** [comment]
Okay ist umgesetzt.
