### ISSUE TITLE
Optimierungen bei letzten Besuchen und Erstellt am

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#162]
1. Bitte hier bei beiden deutsche Monatesbezeichungen verwenden.

2. Wenn ich einen einzigen "letzten Besuch" drin haben, und diesen anklicke, um ihn zu verändern, aber nichts verändere und auf fertig klicke, meckert er, dass ich einen Besuch erstelle, der vor dem Erstellungsdatum liegt?

**Comment by Mojo1917** [comment]
Zu 1: Die genutzte Methode setzt automatisch den Montasnamen in der auf deinem iPhone ausgewählten Spreche ein. Wenn du dein iPhone auf Deutsch stellst wird das hier richtig funktionieren.

**Comment by Mojo1917** [comment]
Zu 2: Ist behoben. Der Vergleich der beiden Daten ist jetzt zuverlässiger.

**Comment by McFly753** [comment]
zu 1: siehe Screenshot, ich bin auf Deutsch, dennoch bekomme ich hier eine Englische Auswahl? // Alle anderen Apps, z.B. Kalender-App, zeigt mir ihre Auswahl in Deustch an.

zu 2: Danke

neu 3: wie besprochen: der erste Besuch sollte immer geschrieben werden, also er ist mind. gleich dem Erstellungsdatum und sollte nicht leer sein.

neu 4: wenn ich den Besuch aus einem Bild übernehme, sollte ich nach dem Klick auf ein wackelndes Bild wieder in diese Besuchs-Liste springen, dass ich den neuen Dateneintrag sehe.

**Comment by Mojo1917** [comment]
4 und 5 sind eingebunden

**Comment by Mojo1917** [comment]
Zu 1: ist behoben. Fehler entstand, weil du mehrere Sprahcen ausgewählt hattest ;)

**Comment by Mojo1917** [comment]
zu 3: Ist eingebunden. Der Besuch wird jetzt zusätzlich geschrieben, wenn das Erstellungsdatum manuell geändert wird. (Das war soweit ich es richtig sehe das einzige wo es noch gefehlt hat.)
