### ISSUE TITLE
In Detailansicht: bitte neben dem Ortsname auch den ganzen Bereiche um Koordinaten und Entfernung klickbar machen, um zum "Ort verändern" zu kommen, nicht nur den Ort.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#165]
UND: wenn ich hier daruf klicken möchte, ohne dass es einen Ort gibt, weil es noch kein Bild gibt, bitte das abfangen und erklären, dass das Objekt mind. ein Bild besitzen muss, um den Ort verändern zu können.

![Uploading IMG_9858.PNG…]()

**Comment by McFly753** [comment]
![img_9858](https://user-images.githubusercontent.com/493612/43007645-38d0a830-8c39-11e8-9e42-4968c21ad527.PNG)

**Comment by Mojo1917** [comment]
Dialog in eingebunden.

**Comment by Mojo1917** [comment]
Die Fläche zum klicken ist auch ausgedehnt.
