### ISSUE TITLE
Bug bzgl. Verschiebung der Detailansicht zu hoch (also dass man über das Notizen-Feld hoch scrollen kann 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#166]
(was dann auch Probleme bei der Ansciht der Suche gibt, weil die Bobbels im nicht sichtbaren Bereich liegen können.

**Comment by Mojo1917** [comment]
Wird ab nächster Version abgefangen. Vielen Dank für die genaue Beschreibung :)
