### ISSUE TITLE
Abfrage Geo-Position erst bei Benutzung

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#167]
... wie besprochen, erst wenn ich 
- auf meinen Standort klicke 
- oder ein Bild ohne Koordinaten hinzufüge und "meinen Standort" verwednen möchte
- oder auf Entfernung sortieren möchte

UND: beim zweiten mal dann auch abfragen, aber dann eben den User zu den Einstellungen schicken.

UND: beim der ersten Abfrage bitte nicht das NEIN fett machen, sondern eines der anderen zwei Optionen.

(Hier könnten wir uns überlegen, ob wir ein Ausrufeuzeichen links neben dem Objketnamen einfügen, der anzeigt, wenn die Geo-Positioon nihct feigebene ist (rotes Ausrufezeichen). Bei Klick hierauf wird mir wieder dieses (zweites - zu Einstellungen) Fenster angezeigt.

**Comment by Mojo1917** [comment]
Geo Abfrage ich jetzt ausgelagert :)

**Comment by Mojo1917** [comment]
Okay ist soweit implementiert, aber wir haben ein Problem: Fragen wir den Nutzer erst nach der Positionsfreigabe, wenn er ein Bild hinzugefügt hat das keine Position enthält, kann es starken Verzögerungen kommen. Im Falle, dass der Nutzer sogar in die Einstellungen geleitet wird, kann es sogar passieren, dass die App im Hintergrund vom System beendet wird und damit die Info verloren geht welche Bilder mit dem Standort markiert wurden.

Daher schlage ich folgendes vor: Wählt der Nutzer den Import aus der Foto-Mediathek fragen wir ihn bevor sich diese öffnet nach dem Standortzugriff. Verbietet er diesen bieten wir die Möglichkeit den eigenen Standort zu verwenden nicht an. 
Was denkst du?

**Comment by McFly753** [comment]
Ok, alles so ok!

**Comment by McFly753** [comment]
OK, alles gut. Nur bei dem Ausrufezeihcne ist noch ein Fehler und ich würde ihs Hauptmenü (Liste und Karte) auch tun, aber nur als ganz normales rotes "!" - dass es nicht ganz so raussticht und so viel Platz verwendet. S. auch den Screen shot, wo zwei angezeigt werden.
![img_0126](https://user-images.githubusercontent.com/493612/43546336-a69e1fd4-95d8-11e8-85c7-e15c0367de0f.PNG)

**Comment by Mojo1917** [comment]
Okay ist umgesetzt :)
