### ISSUE TITLE
Anzeige-Bug wenn eine Zeile mehr angezeigt wird (z.B. Hotspot)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#168]
![img_9857](https://user-images.githubusercontent.com/493612/43007701-65e4d9ae-8c39-11e8-8ae8-15ca520e2536.PNG)

**Comment by Mojo1917** [comment]
Welche Software ist auf deinem gerät installiert? Unter iOS 11.4 scheint es zu funktionieren.

**Comment by McFly753** [comment]
iOS11.4.1

**Comment by Mojo1917** [comment]
Okay, ich muss warten, bis mir iOS 11.4.1 als Emulator zur Verfügung steht. Dann schaue ich mir das an.

**Comment by Mojo1917** [comment]
Nein, ich kann ihn leider nicht finden... Wenn er auch bei Apple auftritt wird es ein Fehler im Betriebssystem sein; ähnlich zu dem im Launchscreen. Ich schließe es mal behalte es aber im Blick ;)
