### ISSUE TITLE
Filter-Darstellung schöner machen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#17]
1. ohne Unterstreichung
2. lass Doppelfiltern etwas mehr Randabstand, schrift kann kleiner werden
3. Leere Filter einfach leer lassen, keine "--" anzeigen.

**Comment by Mojo1917** [comment]
Leider kann ich auch hier das Unterstrichene auf meinem Gerät nicht sehen. Könnte ich hiervon einen Screenshot haben?

**Comment by McFly753** [comment]
![img_4300](https://user-images.githubusercontent.com/493612/34906031-d2e254a0-f864-11e7-80b5-630373766e80.PNG)

**Comment by Mojo1917** [comment]
Okay passt. Danke.

**Comment by Mojo1917** [comment]
Welche iOS Version läuft auf deinem Gerät? Nur damit ich das Unterstrichene auch in der iOS Version überprüfen kann?

**Comment by McFly753** [comment]
Beim Test war es noch 11.2.1. - gestern kam ein Update auf 11.2.2., das ich aber heute erst aufspiele.

**Comment by Mojo1917** [comment]
Punkte 2 und 3 sind übernommen.

**Comment by McFly753** [comment]
Past alles, bis auf der Randabstand (siehe Bild) -> Filter 1 passt, Filter 2 nicht?

UND: lass in der Liste bei der Entferungsanzeige (hier 0.0km) auch ein/zwei Pixel Randabstand am Anfang.

**Comment by McFly753** [comment]
![img_4407](https://user-images.githubusercontent.com/493612/35177550-b8f31bda-fd80-11e7-8710-deb9cd80f01a.PNG)

**Comment by Mojo1917** [comment]
Ich habe den Mindestabstand jetzt von 3px auf 5px erhöht.

Der Abstand ist jetzt auch eingefügt.
