### ISSUE TITLE
Tags nicht "leer" erlauben. Also wenn der Name gelöscht oder nicht eingegeben wird, den Tag löschen 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#170]
- aber erst nach Abfrage, weil nicht dass man den Namen ändern will, kurz den Tag Namenslos hat und das System es dann löscht (und somit aus x Objekten).

![img_9869](https://user-images.githubusercontent.com/493612/43009402-df552cf4-8c3d-11e8-8d71-dccf908900fc.PNG)

**Comment by Mojo1917** [comment]
Wird jetzt abgefangen. Sollte der Nutzer, nachdem einmal Text in einem Tag stand diesen entfernen wird die App, sobald das Feld leer ist den User fragen, ob er diesen Löschen möchte. Wählt er hier 'nein' bleibt der letzt Buchstabe erhalten, es sei denn er füllt es mit neuem Text.
Wir können diese Abfrage jedoch nicht stellen, wenn der User die Seite schließt, da wir hier keine Dialoge mehr öffnen können. (Somit bleiben Tags die angelegt wurden, aber nicht beschriftet wurden auch leer in der Datenbank)

**Comment by McFly753** [comment]
ok, schau ich mir dann an. Danke!

**Comment by McFly753** [comment]
danke, aber noch nicht ganz: wenn ich in den Einstellungen den Namen eines bestehenden Tags lösche, dann kommt die Abfrage. da sage ich nein, nicht löschen. Dann ist die Zeile leer (dass ich was reinscheiben kann) udn dann gehe ich oben links raus, dann schreibt das System einen Buchstaben da in den Tag rein. Das ist verwirrend.

> Wenn ich das Feld leer mache, noch keine Abfrage. Erst wenn ich das Feld leer mahce und dann ohne was neues reinzuschreiebn aus diesen Einstellungen gehe. Dann bauche ich diese abfrage und die müsste etwas anders sein, eher sowas, Möchtest Du den Tag löschen? > Ja lässt ihn dann aus der Seite raus, nein lässt ihn auf der Seite.

**Comment by Mojo1917** [comment]
> Wenn ich das Feld leer mache, noch keine Abfrage. Erst wenn ich das Feld leer mahce und dann ohne was neues reinzuschreiebn aus diesen Einstellungen gehe. Dann bauche ich diese abfrage und die müsste etwas anders sein, eher sowas, Möchtest Du den Tag löschen? > Ja lässt ihn dann aus der Seite raus (bzw. geht zum zweiten Abfragefenster, wenn der Tag genutzt ist), nein lässt ihn auf der Seite.

So wollte ich es implementieren, aber wir haben das Problem, dass sobald der Nutzer die 'Tags' schließt die Instance der Tag-Ansicht zerstört wird und wir keine Dialoge mehr anzeigen können. Wir können diese auch nicht zuverlässig in der Seite darüber anzeigen, da wir nicht wissen welche dies sein wird. Ich schaue, ob mir eine passende Lösung einfällt.

**Comment by McFly753** [comment]
Danke! Bitte nur den Text des Poups ändern:

Möchtest du sie löschen oder weiter bearbeiten? (kein Komma)

**Comment by Mojo1917** [comment]
Ups... Ist angepasst ;)

**Comment by McFly753** [comment]
Ok, Danke!

Lass uns die Tags hier noch etwas abändern - so wird es zu verwirrend. 
Die Abfrage so ist opk, aber lass uns versuchen, dass der User eher nicht mit einem leeren Tag "enden" muss.
a) er muss Tags manuell löschen können (siehe anderes Ticket, das ich gleich reinstelle)
b) wenn man irgendwo auf den Screen tipt, sollte ein leerer Tag, der auch sonst noch nirgends benutzt wurde, einfach gelöscht werden (und hiermit auch die Tastatur eingeklappt werden) // das selbe gilt für den keleinn Pfeil, wenn ich die Tastaur einklappe)
c) das (b) sollte auch so in der Hauptabfrage abgefragt werden. Also wenn das Löschen dieses leeren Tags nichts ausmahct (weil nirgends verwendet), ihn einfach ohne Abfrage löschen.
d)

**Comment by Mojo1917** [comment]
Ich musste das Schließen der Tastatur durch ein Tippen auf die Liste wieder entfernen. Leider hat sich dies mit den Recognizern für das Löschen durch Wischen und Klicken auf den Button gebissen. Daher habe ich das schließen wieder auf den Pfeil und ein wischen in der Liste beschränkt.
Ansonsten müssten wir bei dem Löschen-Button in der Hauptzeile bleiben.
Tut mir leid :/

**Comment by McFly753** [comment]
Ok, verstehe. Aber was löszt ein tippen auf (eigentlcih "unter") die Liste aus? Weil das wäre ja technisch das Entfernen des Cursors aus diesem Feld, somit könntest Du ja sehen, dass er das Feld verlässt und hier eben schon die "Leere-Tags"-Abfrage machen, nicht?

**Comment by Mojo1917** [comment]
Nicht ganz... Lass es und gleich am Telefon besprechen ;)

**Comment by Mojo1917** [comment]
Okay die Liste ist jetzt nur so lang wie nötig und die Fläche daunter kann geklickt werden ;)

Wie du sagst: wir schaffen alles :D

**Comment by McFly753** [comment]
Super, freut mich! :)

**Comment by McFly753** [comment]
Danke, passt!
