### ISSUE TITLE
Beim Verändern des Ortes des Objektes bitte diese Hilfe "forcen", ähnlich wir bei der anderen Positionierung, nur eben hier alles mit dem Hauptbild.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#172]
UND: das Hauptbild auch wackeln lassen.

**Comment by Mojo1917** [comment]
Okay ist eingebunden.

**Comment by Mojo1917** [comment]
Bei mir funktioniert alles. 

Du bekommst die Blase nicht nochmal angezeigt, weil du es bereits aus der Bildansicht heraus gezeigt bekommen hast. Der Punkt ist ja dann erledigt. Oder sollen wir Ihn zwei mal zeigen?

Aus der Detailansicht heraus ist ja auch kein Bild zum verschieben markiert. Dies passiert nur, wenn der Nutzer aus der Bilder-Groß-Ansicht kommt, oder wenn er ein Bild ohne Standort importiert. Sollen wir dies ändern? (Sollte der Nutzer dann in der Detailansicht auf den Ort klicken wird z.B. das erste Bild zum Verschieben markiert.)

**Comment by Mojo1917** [comment]
Ja ich  hatte auch einen Crash-Report bekommen. Ich fange den Fehler jetzt zusätzlich ab.

Okay die anderen Punkte sind umgesetzt oder verbessert ;) Ich bin mir aber auch nicht sicher was hier sinnvoller ist. Sollten wir jedoch alle verschieben sollten wir den Nutzer hierüber jedes Mal aufklären. Ich denke das ist schnell vergessen und dann ärgert man sich nur...
