### ISSUE TITLE
Beispielobjekt anlegen & Eigenschaften vorbenennen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#174]
Objekt habe ich Dir per Locbase geschickt.

Eigenschaften:

Eigenschaft 1a   Eigenschaft 1b
Eigenschaft 2a   Eigenschaft 2b
Eigenschaft 3
Eigenschaft 4

**Comment by Mojo1917** [comment]
Ist eingefügt.

**Comment by Mojo1917** [comment]
klar
