### ISSUE TITLE
Impressum leicht anpassen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#175]
1. Locbase unter das Logo schreiben
2. Impressum dann nicht mehr wiederholen, sondern hier "Kontakt" schreiben
3. Datenschutz/Coockies etc. > denkst Du, hier passt alles?

![img_9874](https://user-images.githubusercontent.com/493612/43009784-e6dd7408-8c3e-11e8-8734-40e3e9d7f698.PNG)

**Comment by Mojo1917** [comment]
1. und 2. sind umgesetzt.

Ich denke Datenschutz und Cookies sollten kein Problem sein. Da wir keine Webseite betreiben die Cookies in Verbindung mit der App setzt sollte dies kein Problem sein. Zusätzlich sammelt die App keine (nutzerbezogenen) Daten die mit uns geteilt werden. Alles bleibt ja lokal auf dem Gerät oder in der privaten iCloud.
Wir haben auch kein Analytics oder Crash Collection implementiert die Daten an uns sendet.
Aber dennoch kann ich mir irren...

**Comment by McFly753** [comment]
ok, Danke

**Comment by McFly753** [comment]
Danke, mach nur die zwei Überschriften ("Kontakt" und "Open source...") linksbündig
