### ISSUE TITLE
Elevator-Pitch & Tour-Starten Frage

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#176]
1. dirket beim ersten Starten der App zeigen wir nach dem Aufbau der Karte und dem Zoom der Karte von Miesbach in die Welt das Pitch-Popup an. Nimm hierzu erstmal folegnden Text (den müssen wir nochmal dann optimieren):

Locbase ist eine geobasierte und leicht zu bedienende Datenbank, welche sich aufgrund ihrer großen Individualisierungsmöglichkeiten und intelligenter Funktionen für eine Vielzahl von Anwendungen eignet, in denen Bilder und Objekte bezüglich ihrer Geo-Position und der Erstellungszeit kategorisiert werden sollen. 

Ob als professionelle Location-Datenbank für den Film und Event-Bereich, eine persönlichen Schlösser&Burgen Sammlung, die Katalogisierung von besonderen Bäumen oder der Ablage seinen Lieblings-Restaurants, Locabase kann vielseitig eingesetzt werden.

Tour starten? (Nein, später. / Ja (fett))

2. beim zweitenmal wird dies nicht merh angeboten, aber man kann die Tour manuell in aus den Einstellunegn heraus starten. Hierbei startet die den Kreis dann in der Kartenansicht (und hier beim Rahmen).

**Comment by Mojo1917** [comment]
Wir können 'JA' nur als Auswahl auf die linke Seite setzen, da normalerweise die fette Schrift für 'Cancel' genutzt wird und das automatisch nach links gezogen wird :D

**Comment by McFly753** [comment]
Ich hatte ein paar Fehler drin:

- "Ob z.B. als professionelle ..." > + "z.B."
- "oder als eine persönliche..." > + "als" und "..liche"
- ", zur Kategorisierung von besonderen Objekten wie z.B. Bäumen oder Gebäuden..." > Textänderung
- "oder einfach als Verwaltung seiner Lieblings-Restaurants..."  > Textänderung und "seiner"

**Comment by Mojo1917** [comment]
okay sind jetzt verbessert.
