### ISSUE TITLE
Bug wegen Suchleiste, ist wieder aufgetreten.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#177]
![img_9876](https://user-images.githubusercontent.com/493612/43015809-eab575f0-8c50-11e8-8122-adc099b83ca2.PNG)

**Comment by McFly753** [comment]
UND: Loeschen > Löschen

**Comment by McFly753** [comment]
(das UND: Loeschen > Löschen)) ist über der Tatstaur, um die Suche zu löschen.

**Comment by Mojo1917** [comment]
Okay super danke ist alles wieder behoben. Der Fehler mit der Suchleiste ist auch hier durch das Tutorial aufgetreten.
