### ISSUE TITLE
Suche erweitern

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#18]
Kann die Suche neben die Titel auch die Tags und evtl. auch die Orte druchsuchen?
(Also Und-Suche verscheidener Eingabebegriffe)

**Comment by McFly753** [comment]
Und: es wäre in der Kartenansicht irgendwie gut, wenn man einfach zu einem gewissen Ort springen kann (also z.B. "München") - aber wir könnten wir ds sinnvoll einbauen?

**Comment by McFly753** [comment]
evtl. macht auch eine textsuche auf der Karte keinen Sinn und hier springen wir nur zu den Orten (also machen ne Google-Maps suche, wenn das das Plugin kann)?

**Comment by Mojo1917** [comment]
Ich werde die Suche um Tags und Orte erweitern.

Ich werde die Suche in der Karte durch die Ortssuche ersetzen soweit Apple Karten hierfür eine entsprechende Möglichkeit bietet. Wie soll die App sich verhalten, wenn die Suche mehrere Orte als Ergebnis liefert?

**Comment by McFly753** [comment]
Das kommt auf den AUfwand an. Hat das Plugin ne einfache Lösung (zwischenfenster etc.), dann nehme das, wenn nicht, evtl. den ersten Eintrag nehmen?

**Comment by Mojo1917** [comment]
Nein so etwas wird Apple Karten nicht anbieten. Ich schau, ob ich hierfür ein einfaches Popup einbauen kann.

**Comment by McFly753** [comment]
Ok, alles klar, Danke!

**Comment by Mojo1917** [comment]
Suche berücksichtigt jetzt Orte (Stadt und Land), Tags und Name.
Änderung kommt mit dem nächsten Update.

**Comment by Mojo1917** [comment]
Ortssuche wurde wie hier beschrieben eingebaut #36

**Comment by McFly753** [comment]
Alles klar, Danke!

**Comment by McFly753** [comment]
Passt so sehr gut, nur: in München nimmt das PlugIn als Orsttext dei Stadtteile und nicht "München". Kann man hier was anders einstellen, weil somit finde ich die Objkete in München nicht?

**Comment by Mojo1917** [comment]
Okay sollte jetzt besser laufen. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke!
