### ISSUE TITLE
Reihenfolge der Hilfe und Ziegen auf bestimmte Objekte der Hilfe

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#180]
Lieber Niklas, ich habe jetzt nochmals die Reihenfolge der Hilfsobjekte auf den einzelen Seiten gechekt und die passen für mich.

HIer noch ein paar Verbesseruungs-Kleinzigkeiten:

1. Kannst Du bei der Hilfe zu den Bennenungen der individuellen Felder nicht nur "Objket" auswählen, sondern alle 4 Zeilen? (oder eben zumindest merh als nur eine)?

2. Kannst Du bei Sichern/Wiederherstellen hier auch beide Zeilen anziegen (also auch das Wiederherstellen)?

3.) Gib auch dem Beispielobjket eine Hilfe: "Hier kannst du ein Beispielobjekt deiner Datenbank hinzufügen, um anhand dessen die Funktionsweise von Locabase leichter verstehen zu können."

und:
4.) Der kleien Text (nicht Hilfe) bei den Einstellungen: ich würde hier (wie von Dir schonmal angemerkt) redundant bei diesen zwei Feldern noch klein was unter die jeweilgen Punkte schreiben:

- Tippe, um die Datenbanken zu bearbeiten

- Benenne individuell die diversen Felder

Danke!

**Comment by Mojo1917** [comment]
die anderen Punkte sind auch umgesetzt ;) Bei der Benennung werden jetzt zwei einbezogen. Bei mehr wäre die Blase so groß, dass der Text untergeht.

**Comment by Mojo1917** [comment]
der eine Text ist wieder entfernt.
