### ISSUE TITLE
Sammlung zur Hilfe, meistens mein Fehler:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#181]
- Bezeichnung der Datenbank: es wird die linke Ecke gezeigt, nicht oben der Datenbankname. (Aber, das passiert nur nach Neuinstallation und wenn ich sofort mit der Tour starte, nicht beim zweiten einsparten der Tour (wenn ich einmal durch war mit dieser Seite)

- Bezeichnung der Datenbank: Das ist die Bezeichnung der aktuellen Datenbank…

- Hinzufügen: Füge hiermit neue Objekte…

- Liste/Karte: Hiermit kannst du deine Objekte als Liste oder auf einer Karte anzeigen …. (weil wir später auch mal „auf“ sagen)

- Favoriten: Hiermit kannst du…

- Sortierung: Hier kannst du die Sortierung… 

- Daten/Bilder:  (Daten/Bilder weglassen.) und: Setze fest, ob deine Objekte… (Weill wir Du immer klein schreiben…)

- Favoritenstern in der Detailansicht: „Favorisiere hiermit …

- Datumsbereich: Hier kannst du das Datum…

- Datumsbereich: der in dem Hilfekreis angezeigte Datumsbereich ist irgendwie graphisch verschoben? Kannst Du das fixen?

- Statistik: Mach doch den Kreis größer, dann sieht es nicht so komisch aus…

- Statistik: Auf dieser Seite findest du … 

- Entferungsbenachrichtigung: Hier kannst du festlegen, … Entfernung du …

- Jahrestagsbenachrichtigung: Hier kannst du einstellen, …

- Sichern/Wiederherstellen: Hier kannst du …

- Hilfe zu Beispielobjekt: zeige hier auch noch einen Fortschrittsbalken an.

**Comment by McFly753** [comment]
Oh, er hat das BOLD nicht mitgezogen, siehe den Screenshot hier bitte:
<img width="895" alt="bildschirmfoto 2018-08-14 um 14 05 40" src="https://user-images.githubusercontent.com/493612/44090662-3e86433e-9fcb-11e8-86ed-113ed3b9ce16.png">

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Nur in wie weit verschiebt sich der Datumsbereich?

**Comment by Mojo1917** [comment]
Hättest du hierzu einen Screenshot?

**Comment by McFly753** [comment]
![img_0269](https://user-images.githubusercontent.com/493612/44112358-29d6a2aa-a005-11e8-9109-f3a4d4498cae.jpeg)

**Comment by Mojo1917** [comment]
Okay alles behoben!
