### ISSUE TITLE
Die App hängt sich auf, nachdem ich die Positionsdaten eines Bildes neu geschrieben habe (immer).

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#183]

**Comment by McFly753** [comment]
![img_0271](https://user-images.githubusercontent.com/493612/44092251-2aecd482-9fd0-11e8-9915-88e5b89eaaec.jpeg)

**Comment by Mojo1917** [comment]
Ich bekomme den Fehler leider nicht reproduziert. Über welche Buttons öffnest du das Ort-Ändern? :)

**Comment by McFly753** [comment]
egal wie ich es mache. Über Hauptbild oder einzelne Bilder. 
Bei Dir alles OK?

**Comment by McFly753** [comment]
>> geht jetzt, hatte glaube ich aber mit meiner schlechten Internetverbindung im Zug zu tun...

**Comment by McFly753** [comment]
PS: aber kannst Du hier allgemeoin in der App nichgt abfragen, wenn die App Internet braucht und es nicht hat, weil deswegen bin ich hier dann nicht merh weitergekommen?

**Comment by Mojo1917** [comment]
Okay vielen Dank für den Hinweis. Ich fange das ab!

**Comment by Mojo1917** [comment]
Wir zeigen dem Nutzer dann einen Hinweis, das dies nur bei 'guter' Verbindung möglich ist.

**Comment by Mojo1917** [comment]
Ist umgesetzt.
