### ISSUE TITLE
Problem mit der Standortfreigabe

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#184]
Ich kann die App so einstellen, dass  mein Standort nur beim Benutzen der App abgerufen wird und danach kann ich aber dei Entfernungsbenachrichtigung einstellen, ohne dass mich die App warnt. Weil wenn die App aus ist, werde ich ja dann nicht benachrichtigt werden, oder?

**Comment by Mojo1917** [comment]
Nein das ist so nicht ganz richtig. Sobald die Standortüberwachung gestartet ist, wenn die App im Vordergrund ist lässt iOS auch die Überwachung weiter zu, wenn die App im Hintergrund noch offen ist. iOS zeigt dies dann über die in-Call-Status-Bar an (siehe Screenshot). Hier sollte die Benachrichtigung wie gehabt funktionieren. Wenn man diese Anzeige nicht möchte kann sie verborgen werden, indem man der App 'Immer' Zugriff erlaubt.
![img_0510](https://user-images.githubusercontent.com/20678932/44094518-af9bbda0-9fd6-11e8-9395-cd2244e18917.png)

**Comment by McFly753** [comment]
ok, alles klar! Verstehe!
