### ISSUE TITLE
App-Absturz bei Datum Ändern (Bild) auf Ipad

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#187]
... auf Iphone stürzt es nicht ab...

> Ich möchte das Datum (irgndeines) Bildes ändern, die App stürzt hierbei immer ab.

**Comment by Mojo1917** [comment]
Okay die Abstürze sind behoben. Bei iPads muss zusätzlich angegeben werden worauf sich das Menü bezieht. Jetzt tauchen sie immer da auf wo der Button ist der das Menü geöffnet hat. Kannst du dir gerne anschauen, ob es dir gefällt. Wenn nicht müssen wir auf dem iPad alle Dialoge, die von unten nach oben aufklappen, ein einfaches Pop-up einbinden.

**Comment by Mojo1917** [comment]
Der Fehler in der Ausrichtung ist auch behoben :D
