### ISSUE TITLE
Ein Feature noch beim Verschicken/Teilen von Objekten

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#188]
Können wir nicht doch auch die eigenschaften und Tag mit übertragen, dem anderen aber sagen, dass diese nicht stimmen müssen oder dass diese angelegt werden müssen?

Also bei Tags: hier würdest Du schauen, ob es die Tags gibt (notfalls auf einer anderen Position, aber genauso heissend) und dann zuteilen. Gibt es die Tags nicht, werden sie erstellt (nach Abfrage).
("3 von 5 Tags des Empfangenen Objketes konnten auch in deiner Datenbank richtig zugeteilt werden. Folgende Tags konnten nicht geschrieben werden:  ...  
Sollen diese Tags auch bei dir angelegt und diesem empfangenen Objket zugeteilt werden? (Ja, Nein)

Bei Eingenschaften wird es komplizierter, weil es ja ein Paar und/oder kein Paar etc. sein kann. In diesem Fall würde ich die Eigenschaften aber auch "absuchen" und die, die extakt zuteilbar sind, zuteilen, hier aber die, die nicht gefunden werden, nicht erstellen, es dem User aber mitteilen. ("Nur 4 von 6 Eigenschaften des empfangenen Objekts konnten auch in deiner Datenbank richtig zugeteilt werden. Folgende konnten nicht geschrieben werden: " ... "

Und dann den Teilen-Dialog anpassen auf: "Bitte beachte, dass das Objket zwar mit allen seinen Daten und Bildern geteilt wird, es aber sein kann, dass der Empfänger in seiner Datenbank andere Tags oder Eigenschaften definiert hat und somit das Objket evtl. nicht mit allen Informationen bei ihm importiert werden kann."

>>> Grund: in einem Team hat man normalerweise die selbe Datenstruktur und dann sollten wir das Objket auch vollständig teilen können. (Und fangen nur die Porblemfälle ab.)

**Comment by McFly753** [comment]
PS: Allgemein: Du achtest bei solchen PoUps schon darauf, dass du die Bezeichnungen wie "Objket", "Tag" etc. aus der Datenbank liest, oder?

**Comment by Mojo1917** [comment]
Ist umgesetzt ;)

**Comment by McFly753** [comment]
Danke, Kleinigkeiten dann in neues Ticket.
