### ISSUE TITLE
Neue Menüzeile & Schliessen von Seiten vereinheitlichen 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#189]
Überall oben links das 3-Punkte-Menü-Icon setzen und dort folgende unterpunkte mit aufnehemn:
- die, die sowieso dort drin wären (
- Hilfe/Tour
- Statistik
- Einstellungen

Rechts sitzt dann entweder das "+" oder der kleine Pfeil nach unten zum Schliessen.

Hierbei dann auch bei den Fotos und den Untereinstellungen das "Zurück" über dieses Pfeilchen auslösen (Ich hoffe, wir bekommen kein didaktisches Problem, das damit zwei Pfeilchens hintereinander verschachtelt liegen können?)

Und bei der Foto-Detailansicht bitte auch das Wischen nach unten erlauben, das schliesst die Fotoansicht.

**Comment by Mojo1917** [comment]
Okay ich denke, dass wir das rote Ausrufezeichen aber zusätzlich direkt in der Hauptzeile anzeigen, richtig?

**Comment by Mojo1917** [comment]
Ich habe gerade leider ein Problem mit dem 'schließen' und 'add' icon gefunden... In den Einstellungen > Datenbank müssten sich nach unserer Logik beide auf der rechten Seite befinden...
Ich binde beide mal hier ein. Vielleicht finden wir ja noch eine schönere Lösung (Vielleicht unter den Punkten. Widerspricht zwar der Logik, aber diese Funktion wie ja auch bei den meisten Nutzern nicht sehr oft genutzt.)

**Comment by Mojo1917** [comment]
Alles weitere ist implementiert ;)

**Comment by McFly753** [comment]
Danke. Lass das mit dem Pfeilchen erstmal so. Nur:

Bitte überall in den Menüs IMMER diese drei Menüpunkte (in diesr Reiehnfolge) anzeigen:
Hilfe/Tour
Statistik
Einstellungen

also auch in der Dtailansicht, Einstellujnbgen, Unterseiten der Einstellungen, Listenasichten, Bilderansoichten etc.

Es sollen diese Punkte immer von überall angesprungen werden können.

**Comment by McFly753** [comment]
PS: Rufezeichen bleibt draussen.

**Comment by Mojo1917** [comment]
Oh okay das hatte ich falsch verstanden ;) Wird so umgesetzt!

**Comment by Mojo1917** [comment]
Wir können hier nur folgendes Problem bekommen: Nutzer ist in der Listenansicht -> Einstellungen -> Statistik -> Einstellungen.
Ich denke um dies abzufangen macht es vielleicht Sinn in der Statistik keine Navigation in die Einstellungen zuzulassen ;)

**Comment by McFly753** [comment]
verstehe ich nicht. Wenn ich in der Statistik bin springe ich einfach auf Einstellungen. Brauchen wir so einen "Pfad"? // oder stehe ich auf dem Schlauch?

**Comment by Mojo1917** [comment]
Naja wir können unter iOS nicht in verschiedene Fenster springen. Wir können nur über das aktive Fenster ein neues öffnen oder das aktuelle schließen. Somit könnte der Nutzer dann die verschiedenen Fenster übereinander legen. Kann man sich wie einen Stapel vorstellen auf den wir neue Fenster legen. Und nicht wie eine Ebene auf der wir ein anzuzeigendes Fenster auswählen.
Es ist aber nicht zuverlässig möglich zu prüfen ob ein bestimmtes Fenster im 'Stapel' liegt.

**Comment by Mojo1917** [comment]
Wir könnten und somit überlegen aus der Einstellung keine Navigation in die Statistik zuzulassen und andersrum ;)

**Comment by McFly753** [comment]
OK, dann lass aus den Einstellungen keine Statistik zu. Danke!

**Comment by Mojo1917** [comment]
Okay ;)
