### ISSUE TITLE
Kartenverhalten nach Filter-Änderung oder Suche

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#19]
> Die Karte sollte nach Filteränderung immer alle Objekte anzeiegn, das heisst rauszoomen. 

> Die Karte sollte, wenn es keine Objeket zum anzeiegn gibt, dies mit einem Text anzeiegn (Keine Bäume zu Anzeige)

**Comment by Mojo1917** [comment]
Karte zoomt jetzt raus. Am oberen Rand wird jetzt der Hinweis 'Keine Objekte zur Anzeige'.

**Comment by McFly753** [comment]
Muss ich die aktuelle Versiojn löschen und die neue Installieren?

**Comment by Mojo1917** [comment]
Nein Sorry war missverständlich. Kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Ok, alles klar.

**Comment by McFly753** [comment]
Siehe #29 (zu weiter Zoom und bitte keine Zoomveränderung, wenn nur umsortiert wird)
