### ISSUE TITLE
Neuer Filter/Sortierbereich

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#190]
1. Sortierbereich nur in diesem gesammelten Button und hier mal zentriert zwischen den Karte/Listen-Buttons probieren. 

2. Die eingeklappte Bar beinhaltet: "Eigenschaften" (=kein Filter) bzw. "3 Eigenschaften" (= 3 Eigenschaftsfilter) (Feld etwas größer) dann den Stern (Feld kleiner) und dann die Suche mit nem Löschenkreuz wenn ausgewählt. (Wir zählen beim ersten Feld also hier nicht merh den Favoriten udn die Suche mit zu den Filtern)

3. Das Einstellungsfilterfeld klappt diesen Bereich aus, wie gehabt, nur eben ohne den Sortierungsbereich, ohne die Suche, ohne den Favoriten und also nur die 4 oder 8 Einstellungen mit dem Schliessen-Pfeilchen. Lass auch das "Filter" oben links weg. Das Zu/Aufwischen würde ich noch beibehalten. // Von der Logik würde ich aber dieses ausgeklappte Feld immer dann "zwangsschliessen", wenn ich die Ansicht (Karte/Liste) wechsele und auch wenn ich in ein Objket springe oder sonst wie diese Ansicht verlasse. Ich will es nur zum wirklichen "Live-Filtern" offen lassen.

**Comment by McFly753** [comment]
PS: und abundzu bleibt immer noch das Suche-Feld oben hängen...

**Comment by Mojo1917** [comment]
Notiz an mich: Schließen auch über den öffnenden Button ermöglichen.

**Comment by Mojo1917** [comment]
Suchfeld dürfte jetzt nicht mehr hängen bleiben. Ist komplett neu und verbessert implementiert ;)

**Comment by Mojo1917** [comment]
Ist jetzt komplett umgesetzt. Das anpassen der Sortierung durch wischen füge ich ein, wenn wir den Sortierbutton dort lassen wo er jetzt ist :)

**Comment by McFly753** [comment]
Danke, Tickest hieraus in separaten Tickets.
