### ISSUE TITLE
In der Listenansicht sitzt das Attribut-Feld (hier z.B. Barock) ein bis zwei Pixel optisch zu hoch.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#193]

**Comment by Mojo1917** [comment]
![simulator screen shot - iphone 8 - 2018-08-15 at 15 37 10](https://user-images.githubusercontent.com/20678932/44151087-bc9ccd34-a0a1-11e8-835f-463f42a244c3.png)

**Comment by Mojo1917** [comment]
Okay aufgrund der unterschiedliche Textgröße kam es zu der Verschiebung. Alle Buchstaben stehen jetzt auf der gleichen 'Baseline'

**Comment by McFly753** [comment]
Ok, Danke! Sieh Dir sowas aber immer optisch an, nie technisch... ;)

**Comment by Mojo1917** [comment]
Klaro! Ich war mir nicht sicher, was besser aussieht :D
