### ISSUE TITLE
Tags & Attribut ausblendbar machen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#196]
am besten in den Einstellungen, evtl. mischen wir das in den Bereich rein, wo man die Bezeichnungen verädnern kann?

(Dann aber auch die Hilfe an dieser Stelle anpassen: "Hier kannst du, wenn du willst, die Tags und das Attribut ausschalten und auch alle Felder individuell benennen.")

**Comment by Mojo1917** [comment]
Ist umgesetzt.

**Comment by McFly753** [comment]
Danke (nein, Du bist noch komplett frei!)
