### ISSUE TITLE
Das Logbase Logo in unserem verwendeten Blauton ändern. (Startbildschirm und Impressum und APP-Icon)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#198]

**Comment by Mojo1917** [comment]
Okay sieht jetzt wie folgt aus
![icon-180](https://user-images.githubusercontent.com/20678932/44146175-c1ae6714-a08e-11e8-8472-cd4e60fe3c5d.png)

**Comment by McFly753** [comment]
das lila stört mich etwas, ich würde es komplett balu machen. Lass es aber so, dass soll dasn Thisi machen (unser Art Director)

**Comment by Mojo1917** [comment]
Okay alles klar ;) Noch habe ich es nicht eingebunden. Das macht dann nur unnötige Arbeit ;) Ich bin dann das endgültige ein! Hoffe das passt.
