### ISSUE TITLE
Hilfe für Eigenschaften hinzufügen (in dem Unterfenster) und Hilfe zu den Tags anpassen.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#199]
Eingenschaften-Unterfenster (nicht oben):
"Hier kannst du bis zu 8 Eigenschaften bzw. Eigenschafts-Paare erstellen, auf die du dann in den Anzeigen deine Objekte filtern kannst. Du kannst hier auch jederzeit die Reihenfolge verändern, ohne die korrekte Zuordnung zu den Objekten zu verlieren."

Tags-Unterfenster (nicht oben): (bitte erweitern auf:)
"Hier kannst du beliebig viele Tags erstellen, die du dann den diversen Objekten zuteilen kanst. Du kannst hier auch jederzeit die Reihenfolge verändern, ohne die korrekte Zuordnung zu den Objekten zu verlieren."

**Comment by Mojo1917** [comment]
Okay ist in den beiden Einstellungsunterseiten eingebunden. Hoffe das war die richtige Stelle.
