### ISSUE TITLE
Kartenbug - Objekte verschwinden

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#2]
Wie schon geschrieben, stimmt was mit der Kartenansicht nicht.

> schalte ich iregendeinen neuen Filter ein/um oder von Bilder zu Datenansicht, verschwinden die Objekte uaf der Karte - sie kommen erst wieder, wenn ich etwas in der Karte zoome

> beim Start wird das erste Objekt immer als zwei Objekte angelegt und nur Gruppiert angezeigt

**Comment by Mojo1917** [comment]
Fehler sind behoben. Ich bin auf eine andere Bibliothek umgestiegen.
Änderungen kommen mit dem nächsten Update.

**Comment by McFly753** [comment]
Ok, warte auf das Update.
