### ISSUE TITLE
Manchmal stürzt die App noch ab, wenn ich die Hilfe starte...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#200]
... ich kann es gerade aber noch nicht reproduzieren...

**Comment by Mojo1917** [comment]
Den Fehler habe ich auch gerade gefunden. Ich weiß wie er entsteht ;) Tritt er bei dir auch nur in den Einstellungen auf, oder auch woanders?

**Comment by McFly753** [comment]
das weiss ich nicht genau, sicher ist, dass er in den Einstellungen war (und ich mich auch nur hieran erinnern kann...) ;)

**Comment by Mojo1917** [comment]
Ist behoben!
