### ISSUE TITLE
Rechten oberen Bereich in der Objekt-Detailansicht schöner machen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#201]
und zwar für Iphone 5 und höher separat.

Höher als Iphone5: (lass und das folegnde mal ausprobieren, dann sehen wir weiter):

1. Fahne des Landes (linksbündig), rechts daneben den Favoritenstern. (also doch wieder aus dem Bild raus, Sorry.)
2. Darunter die Stadt und den Ort 
3. Darunter in der selben Schriftgröße (aber evtl. in Klammer) das Attribut
Dann lass uns das mal probieren, mal sehen wie es aussieht: 
4. Erstellt / letzter Besuch am:
5. DD.MM.YY     DD.MM.YY (geht Blocksatz, also links und 
6. (nur wenn wir die dynamischen Tage zum letzen Besuch wo unter bekommen)
7. Koordinaten & Entfernung
8. Karte

Iphone 5 davon dann abgeleitet und angepasst.

**Comment by McFly753** [comment]
Jein. Versuch bitte hier die Anordnung selbst zu verändern, weil ich ihn erst ab 2 Wochen wieder arbeitstechnisch greifen kann. Danke!

**Comment by Mojo1917** [comment]
Okay alles klar ;)

**Comment by McFly753** [comment]
das ist noch offen.

**Comment by Mojo1917** [comment]
Folgt mit dem nächsten Update ;)

**Comment by Mojo1917** [comment]
Zur Anzeige der Flaggen müssen wir den Country Code speichern. Ich habe daher die Datenbank hierfür erweitert ;)

**Comment by Mojo1917** [comment]
Ich habe jetzt eine Bibliothek mit 255 Flaggen eingebunden. Ich denke das sollten so gut wie alle sein :)

**Comment by Mojo1917** [comment]
Wir haben hier ein Problem mit 5. (Mehr gleich am Telefon)

**Comment by Mojo1917** [comment]
Ist umgesetzt. 5er folgt, wenn wir hiermit fertig sind ;)

**Comment by McFly753** [comment]
Danke, ist schon mal besser so, aber:

- Fahne und Stern müsen optisch ein paar Pixel weiter runter.
-Mach die Fahne ca. 80% kleiner
- Mach den Favoritenstern, wenn nicht ausgewählt nicht ausgefüllt. (Weil sonst sieht er nicht ausgewählt fast ausgewählt aus)
- nochmals wegen den Datums (erstellt und letzter Besuch) DD.MM.YY DD.MM.YY > geht hier Blocksatz, also links und rechtsbündig? // Und dann keinen "/" dazwischen.
- und schreib dann darüber besser: "Erstellt bzw. letzter Besuch am:"
- wenn ich in Australien bin und ein Objekt in Deustchaldn anzeige, wird die Entfernunbg abgeschnitten (s. Bild)

![img_1037](https://user-images.githubusercontent.com/493612/45180546-4c2cd580-b24e-11e8-8c8f-be03540cd40d.PNG)

**Comment by Mojo1917** [comment]
Okay für das Attribut werde ich dann nach Klicken ein Feld anzeigen in das der Nutzer dann alles eintippen kann. Sollen wir das der Einfachheit halber machen wie bei der Eingabe in die Suchleiste?
Wir würden dann die entsprechende Leiste oberhalb der Tastatur anzeigen und die Eingabe übertragen. Dann muss der Nutzer nicht dort oben in die kleine Zeile tippen.

**Comment by Mojo1917** [comment]
Okay das Ticket ist im kommenden Update noch nicht ganz umgesetzt. Folgt eins später ;)

**Comment by McFly753** [comment]
HIer machen wir dann Poup, oder?

Und: Bitte, wenn das Feld noch leer ist, hier "(Attribut)" in grau anzeigen.

**Comment by Mojo1917** [comment]
Klaro ist beides schon so eingebunden ;) Hatte es nur vor dem Upload des letzten Updates noch nicht ganz fertig. Folgt dann Montag.

**Comment by McFly753** [comment]
Danke, passt alles. Nur: schreib das Attribut (und auch den asugefüllten Text im Attribut) in Klammern

**Comment by Mojo1917** [comment]
Ich lege die Anpassung des Layout für iPhone 5 / SE mal als eigenes Tickets an, damit wir dies nicht übersehen.

**Comment by McFly753** [comment]
Danke!
