### ISSUE TITLE
Vibration, wenn Nutzer Elemente verschieben kann

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#202]
- Bilder (Sortierung und Ort)
- Tags
- Objekteigenschaften

**Comment by Mojo1917** [comment]
Okay ab iPhone 7 aufwärts sollte die App jetzt angenehm kurz vibrieren (Kann ich leider nicht testen. Meins ist älter :D)

Bei älteren Geräten gibt es diese Möglichkeit nicht. Hier können wir nur knapp 1s vibrieren lassen. Oder sollen wir hier einen kurzen 'Tick'-Ton ähnlich dem bei Tastaturanschlägen abspielen?

**Comment by McFly753** [comment]
Ja, mach bei den älteren einen Klick-Ton. Bei mir geht es mit der Vibration.

**Comment by Mojo1917** [comment]
Oki ist umgesetzt ;)

**Comment by McFly753** [comment]
Danke, passt!
