### ISSUE TITLE
Anpassung/Vereinheitlichung von Löschen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#204]
Bitte in allen Linsetnansichgten die Löschen-Option aus dem Mneü nehmen und dirket in die zu löschende Zeile rein. 

Entweder wie in der Listenansicht der Objkte: mit verschieben udn dann löschen.
Oder einfach als Löschbutton, den man klicken kann. (wäre hier in den Einstellunegn einafcher zu versteehn)

> Tags
> Eigenschaften (macht diese nur leer)
> Datenbanken

**Comment by Mojo1917** [comment]
Wäre es nicht sinnvoll die Eigenschaften nach dem Löschen auch in allen Objekten zurückzusetzen? Oder sollen wir nur die Benennung löschen?

**Comment by McFly753** [comment]
Ja, klar, aus den Objekten müssen sie natürlcih dann auch rausgelöscht werden.

**Comment by Mojo1917** [comment]
Okay ist eingefügt.

**Comment by McFly753** [comment]
Danke, passt!
