### ISSUE TITLE
Zu Hilfe/Tour ...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#205]
- Noch nicht implementiert: "Du klappst ja den Filterbereich auf, wenn Du die Tour startest. Kannst Du Dir das merken und bei Beendigung der Tour diesen wieder schliessen?"

- Noch nicht implementiert: "Statistik: Mach doch den Kreis größer, dann sieht es nicht so komisch aus…"

- kannst Du auch die Tour durch ein wishcne nach unten abbrechen? (dann kommen ggf. diese Popups)?

- Können wir die Prozentanzeige doch auch in jedem Hilfefenster anzieegn?

- Kannst Du in die Hilfe für das Notizfeld dazustzeen: "Eine URL kannst du öffnen, indem du länger auf den Link tipst." (oder sgat man ... klickst. ?)

- Du hattest Recht: lass uns immer (also jedes mal), solange der User kein Objket in der Datenbank hat, nach Abbruch oder BEendigung der Hilfe fragen, ob wir ein Beispielobjekt anlegen sollen.

Wenn ich auf der Seite, auf der ich die Hilfe starte, sie nach Abschluss erneut starte, startet sie nur mit dem letzten Fenster ein (ich war auf Statistik, also die Hilfe hätte mit der Statistik die Tour beendet).

**Comment by Mojo1917** [comment]
Ich denke man kann tippen und klicken sagen... Ich bin mir da auch nie sicher :D

**Comment by Mojo1917** [comment]
Den letzten Punkt von dir verstehe ich nicht ganz. Wenn du die Tour beendet hast und die dann auf einer Seite neu startest zeigt sie bei dir nur den letzten Punkt dieser Seite an?
Ich kann das bei mir leider nicht reproduzieren :/ Auf der Statistik Seite haben wir nur einen Punkt. 
Oder habe ich die falsch verstanden?

**Comment by Mojo1917** [comment]
Ggf. sollten wir die letzten Punkte zum Tutorial die nach dem nächsten Update noch ausstehen am Telefon besprechen? Ich denke das ist leichter!

**Comment by Mojo1917** [comment]
Der Rest ist umgesetzt.

**Comment by McFly753** [comment]
Ja, ich würde die Logik der Tour noch etwas anpassen:

1. lass uns immer, wenn ich ein neues Fenster zum ersten mal betrete, die Hilfe einstarten.
(also so wie bei dem Bild neu positionieren)
2. Dann verändern wir leicht die Benennungen des Buttons: statt "Abbrechen" > "Hilfe abbrechen"
3. Wenn Du am letzten Screen der jeweiligen Seite angekommen bist, verändern wir die Logik und Beschriftung der Buttons auf: Zurück / Hilfe beenden und darunter: Nächste Seite.
-> Was denkst Du, hat das irgendwelche zusätzlichen Auswirkunen auf unsere Reiehnfolge etc?

**Comment by McFly753** [comment]
PS: gerne auch am Telefon. Heute würde es gut gehen...

**Comment by Mojo1917** [comment]
Ich denke das sollte gehen ;)

**Comment by McFly753** [comment]
Super, und: dann nimm die "besonderen" Hilfeseiten (also die, die wir nicht in die Tour implementieren) mit dazu, dass zumidnest von diesen die Tour weitergemacht werden kann. 
Hierzu müssten wir nur folgendes anpassen/verädnern:

a) die Bezeichnungen der Buttons auf den Screens vor dem letzten Screen: wie oben beschrieben.
b) auf dem letzten Screen dieser Seite dann: Statt "Zurück / Fertig // Abbrechen" folgende Buttons:
Zurück / Hilfe beenden und darunter: Nächste Seite.

**Comment by Mojo1917** [comment]
Ich habe jetzt doch noch eine letzt Rückfrage hierzu: Ist es nicht ungewöhnlich, wenn wir in der Tour auf der letzten Blase die Buttons tauschen? Ich kenne nur nich als Nutzer und weiß, dass wenn ich 5x den gleichen Button gedrückt habe nicht mehr lese was hier drauf steht. Dies würde dann bei unseren Nutzern dazu führen, dass sie immer ausversehen bei der letzten Blase die Hilfe schließen. Was denkst du?

**Comment by Mojo1917** [comment]
Okay ist umgesetzt.

**Comment by McFly753** [comment]
Danke, passt alles, nur das fehlt noch:

"Wenn ich auf der Seite, auf der ich die Hilfe starte, sie nach Abschluss erneut starte, startet sie nur mit dem letzten Fenster ein (ich war auf Statistik, also die Hilfe hätte mit der Statistik die Tour beendet)."

(ich klicke auf "Hilfe beenden" auf dem lezzten Hilfescreen einer Seite -> damit würde ich diese Hilfe als gelesen sehen, also dann beim nächsten mal diese Seite zurückgesetzt sehen.

**Comment by Mojo1917** [comment]
Okay ich versteht :D Kommt mit dem nächsten Update!

**Comment by Mojo1917** [comment]
Sollte jetzt nicht mehr auftreten.

**Comment by McFly753** [comment]
Danke!
