### ISSUE TITLE
Reihenfolge Hilfe/Tour:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#206]
Reihenfolge in der Hilfe
- Noch nicht implementiert:
die verschachtelte Rahmenserklärung wird manchmal unnötig wiederholt: ich bin z.B. auf der Liste und lasse mir den Rahmen erklären (komplett durch) und gehe dann aus der Hilfe raus und springe dann in die Karte und starte die Hilfe, dann startet die Erklärung wieder beim Rahmen, obwohl der ja eigentlich abgeschlossen ist. Hier müsste die Hilfe zuerst die Kartenansicht fertig erklären und dann eigentlich zur nächsten Seite springen und erst beim nächsten Starten (auf der Karte) den Rahmen neu einstarten. Falls ich aber zur Liste springe und diese noch nicht durch ist, sollte ich auch hier zuerst die Liste abarbeiten und nicht den Rahmen zeigen - die passiert auch hier erst beim nächsten mal. (Ich hoffe, das war jetzt verständlich… :) )

- und, auch zur Reihenfolge: eigentlich sollten wir nicht nur im Kreis gehen, sondern immer zuerst die (noch nicht abgearbeiteten) Hilfeseiten anspringen, die davor lagen.
Also z.B.: ich starte auf der Listenansicht, aber habe die Kartenansicht noch nicht (oder noch nicht vollständig) abgeschlossen: dann sollte zuerst die Kartenansicht abgefertigt werden, bevor ich z.B. in die Einstellungen komme. Also die Regel: immer zuerst schauen, ob "wichtigere" Seiten evtl. noch nicht oder noch nicht ganz erklärt wurden.

**Comment by Mojo1917** [comment]
Sind beiden in der aktuell veröffentlichten Version umgesetzt.

Zu 1: Möglicherweise wird bei dir der letzte Rahmen Punkt angezeigt, wenn du auf 'Abbrechen' drückst? Er gilt dann noch nicht als abgearbeitet. Wenn du dann in der Liste startest wird dieser wieder angezeigt. Oder liege ich falsch?

Zu 2: Sollte der Fall sein. Die App beendet zuerst die Seite auf der die Hilfe gestartet wurde (oder startet sie neu, wenn sie komplett ist) und geht dann nach unserer Gewichtung die einzelnen noch fehlenden Punkte durch; Aktuelle Gewichtung ist: Frame, Map, Liste, Objekteinzel, Statistik, Einstellung.
Verhält sie sich bei dir anders?

**Comment by McFly753** [comment]
zu 1.) 2.) -> war eigentlich (vom Fehler her) so wie beschrieben. Da Du aber einiges geändert hast: ich teste die nächste Version nochmals, dann kann ich die Hilfesachne nochmals zusammenfassen.

**Comment by Mojo1917** [comment]
Okay ;)

**Comment by McFly753** [comment]
Ich schliesse dieses Ticket und lege ein neues an für die Hilfe...
