### ISSUE TITLE
zum Beispielobjekt...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#207]
- Sobald der User Bestätigt, dass ein Beispielobjekt eingefügt werden soll (oder wenn er dies in den Einstellungen manuell macht): bitte dann auf die Karte auf dieses Objekt springen.

Aber bitte in der ein weiter weg Zoomansicht, nicht in der ganz nahmen (verändere dies bitte auch auf dem Startscreen, wenn man ein Objekt hat)

**Comment by Mojo1917** [comment]
Okay ist umgesetzt.

**Comment by McFly753** [comment]
Danke!
