### ISSUE TITLE
zum Import eines Objektes ...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#208]
- Bitte das erste Popup vom Text her anpassen:
Titel: Objekt importieren
Text: 0 von 2 Tags des empfangenen ((klein schreiben)) Objektes ((Buchstabendreher)) konnten auch in deiner Datenbank richtig zugeteilt werden. Folgende Tags konnten nicht geschrieben werden: xyz, zzz
Sollen diese Tags auch in Deiner Datenbank ((leicht verändert)) angelegt und diesem empfangenen Objket ((((Buchstabendreher)) zugeteilt werden?

- Es ist auch ein Popup vorhanden, wenn die Eigenschaften abweichen (rein als Info, dass und welche abweichen und nicht importiert werden, oder?)

- Popuop nach Import anpassen, am besten zwei vershceidene: einmal, wenn alles so übernommen werden konnte, das andere mal mit dem text wie bisher (also "Bitte beachte, dass das Objekt ggf. ((einfügen)) ohne seine ...

- Import stürzt immer ab, wenn ich ein Objekt importiere, das ich gerade erst exportiert und dann gelöscht hatte, aber in den Einstellungen etwas die Tags/Eigenschaften verändert hatte: (gleiche Tags, aber andere Reihenfolge. Das Selbe bei Einstellungen. Und jeweils habe ich einen Tag/Einstellung gelöscht.)

**Comment by Mojo1917** [comment]
Klar! So sieht der Dialog aus: 
![img_0517](https://user-images.githubusercontent.com/20678932/44911639-df827a00-ad27-11e8-8221-3f7c90bb646c.png)

**Comment by Mojo1917** [comment]
Ist umgesetzt. Leider kann ich den Fehler nicht reproduzieren und auch keinen Absturzbericht einsehen. Hattest du die App vor dem Update deinstalliert? Wir hatten ja die Datenbank überarbeitet und dadurch kann es hier zu diesem Fehler gekommen sein.

**Comment by McFly753** [comment]
Ok, ich habe die App deistalliert und folgendes gemacht:
1. Beispielobjekt hinzugefügt.
2. drei Tags ("1" und "2" und "3" udn Tag "4" hinzugefügt) (und 1-3 dem Objket zugewiesen)
3. Eigenschaft 2 verändert auf Eigenschaft 2a udn 2b (also Pärchen) (und Objket hier auf 2a gestellt)
4. Objekt geteilt
5. Objket gelöscht
6. Enstellungen bearbeitet: 
a) Tag 1 und 2 vom Namen so gelassen, aber in ihrer Reihenfolge vertauscht
b) Tag 3 gelöscht
c) Tag 5 an Position 1 hinzugefügt 
also dann: 5 > 2 > 1 > 4
d) Reihenfolge Eigenschaft 1 und 2a/b vertauscht.
e Eigenschaft 1 (jetzt an positioon 2) vom Namen verändert auf "Eigenschaft neu"
7. Objekt importiert.

>> Und: ges stürtzt nicht ab und es geht alles! :))

**Comment by McFly753** [comment]
bei Import stürzt leider die App wieder ab. Ich versuche nochmals, den Fehelr reproduzieren zu können.

**Comment by Mojo1917** [comment]
Ich denke ich kenne den Grund: Wir haben mit dem letzten Update wieder die Datenbank überarbeitet. Somit kann es zu Fehlern bei dem Import von Objekten kommen, die vor diesem Update exportiert wurden ;)

**Comment by McFly753** [comment]
Nein, das kann der Grund nicht sein, habe neu installiert und alles von dieser Datenbank aus getestet...

Aber: ich kann es jetzt wider nicht nachvollziehen. Hier ist aber noch ein Bug drin, sollten wir beobachten. Ich schliesse aber das Ticket.
