### ISSUE TITLE
Bei Wechsel der Datenbanken: lass uns seine Filter/Sortierung merken und beim Zurückspringen in die andere Datenbank beibehalten.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#211]

**Comment by Mojo1917** [comment]
Okay können wir machen. Aktuell setzen wir die Filter zwischen App-Starts zurück. Soll das beibehalten werden oder sollen wir sie fortan zwischen App-Starts zurücksetzen?

**Comment by Mojo1917** [comment]
Ist umgesetzt.

**Comment by McFly753** [comment]
Danke, passt!
