### ISSUE TITLE
Können wir die Fotoansicht auch drehbar machen? (Horizontal View)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#212]

**Comment by Mojo1917** [comment]
Okay die Ansicht der Fotos in groß kann jetzt gedreht werden ;)

**Comment by McFly753** [comment]
Danke! Nur: bitte die Bilder auf max. Größe und entweder all den Text nicht anbieten oder diese darüberlayern.

**Comment by Mojo1917** [comment]
Okay, wenn wir ihn darüberlayern startet das Bild teilweise von der Info box bedeckt.
Ich blende diese Box einfach auf iPhones im Querbild aus. Ich denke das ist am besten. Wenn man eine der Infos bearbeiten will wird man das wohl eh nicht im Querbild machen, oder? Finde es dann immer recht schwer zu tippen, etc.
Ich hoffe das passt so.

Auf dem iPad stört die Box eh nicht, oder?

**Comment by McFly753** [comment]
Ja, passt. / Ja.

**Comment by McFly753** [comment]
Danke!
