### ISSUE TITLE
Kleine Anzeigefehler

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#213]
Alles auf Iphone X getestet:

- Wenn Tags/Eigenschaften ausgeblendet sind, gibt es einen Leeraum unter den Notizen. Ich würde die Notizen einfach verlängern, oder?

- Scrollfehler: wenn ich auf das Notizfeld klicke, dann oben auf den Objektnamen: dann bin ich zu tief vom Scroll her.

- Die vier Map etc. Icons liegen zu tief

- Die Statistik startet zu hoch

**Comment by McFly753** [comment]
![img_0663](https://user-images.githubusercontent.com/493612/44648780-b8b90080-aa14-11e8-9924-00ea51835674.PNG)

![img_0664](https://user-images.githubusercontent.com/493612/44648785-bbb3f100-aa14-11e8-98b7-15d562b242a9.PNG)

![img_0665](https://user-images.githubusercontent.com/493612/44648804-c9697680-aa14-11e8-9afb-981fd6ce540d.PNG)

**Comment by McFly753** [comment]
![img_0670](https://user-images.githubusercontent.com/493612/44649212-d470d680-aa15-11e8-931a-e6a446f088fd.PNG)

![img_0671](https://user-images.githubusercontent.com/493612/44649273-fb2f0d00-aa15-11e8-887c-7a9c806f2dda.PNG)

**Comment by McFly753** [comment]
Nicht ganz, diese beiden Dinge sind noch vorhanden:

- Wenn Tags/Eigenschaften ausgeblendet sind, gibt es einen Leeraum unter den Notizen. Ich würde die Notizen einfach verlängern, oder?

- Scrollfehler: wenn ich auf das Notizfeld klicke, dann oben auf den Objektnamen: dann bin ich zu tief vom Scroll her.

**Comment by Mojo1917** [comment]
Okay ich habe beides nachgebessert. Im Emulator und auf meinem Testgerät bekomme ich die Fehler nicht mehr erzeugt!

**Comment by McFly753** [comment]
Danke.
