### ISSUE TITLE
Zu neuem Filter/Sortierungsbereich

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#214]
- auf die "(keine) Eigenschaften" muss ich zweimal klicken, um sie auszuklappen 

- lass bitte doch den Pfeil rechts oben weg, das reicht auch mit runterwischen oder nochmals auf Eigenschaften klicken.

- Die Sortierung (hier ist sie auf dem Iphone X auch zerschossen) funktioniert in der Mitte irgendwie doch nicht ganz. Lass sie uns mal rechst versuchen und linsk daneben (evtl. als Schalter getrennt) die Karten und Lisetnansicht setzen. 

- Kannst Du dann das hochwischen auf den Sortierungsbutton schon mal ausprobieren?

**Comment by McFly753** [comment]
![img_0669](https://user-images.githubusercontent.com/493612/44649291-097d2900-aa16-11e8-8c0d-a78edb479d54.PNG)

**Comment by Mojo1917** [comment]
Punkt 1 u. 2 sind umgesetzt.

**Comment by Mojo1917** [comment]
Aufgrund der Veränderungen an der Nutzerführung in List und Karte (automatisches einklappen etc.) verzögert sich aktuell alles ein wenig ;) Da ist ein Fehler drin der sich nicht richtig beheben lässt :D

**Comment by Mojo1917** [comment]
In welcher App hattest du das mit dem Menü auf dem Button? Leider funktioniert keine Umsetzung bei uns in der App. Würde mir das gerne in der App einmal anschauen ;)

**Comment by Mojo1917** [comment]
OKay der Button ist jetzt an den linken Rand gezogen. Leider kann ich zwischen den beiden Buttons keinen Trennser setzen, da sie ja nach Displaygröße woanders sind.

**Comment by McFly753** [comment]
Lieber Niklas, 

bzgl. Punkt 3: ich habe eine schönere Idee: teiel unten den Bereich, wo bis jetzt die zwei Buttons (Liste Karte) drin liegen in zwei in etwas gleich große Bereiche. Rechts sitzt wie oben beschrieben der Sortierbutton (lass in farblos) und links daneben setzen wir nur einen Button, und zwar den "Ansichtenumschalter". Da würde ich reinschreiebn, in der Textzeile: Karte / Liste  und darüber beide Symbole setzen, und das ausgewählte blau machen. Das vereinfacht alles auch, weil ich mit einem Klcik auf einen Button alles machen kann. Oder?

bzgl. Punkt 4: ich habe diese Funktion (die ich mir vorstelle) nirgends gesehen, fände sie aber recht schön. Es gibt aber eine leicht ähnliche Funktion, und zwar: lade Dir bitte ToDay To-Do (von Chi Trung Tran) runter (wird ein paar Euro kosten, aber die baruche ich auch für unser ToDo Programm). Wenn Du dort ein neues ToDo erstellst, kannst Du rechts vertikal über die 3 Striche wischen. Hier bekommst Du kein Menü angeziegt, aber diese Auswahl ist leicht ähnlich.

**Comment by Mojo1917** [comment]
Okay ist alles endlich umgesetzt ;) Das wischen über den Button funktioniert jetzt ohne Verzögerung. Ich hab es jetzt auch optisch genauso eigebunden wie bei dem Datenbankwechsel!

Ich lasse dennoch den Klick auf den Sortierbutton eingebunden, oder?

**Comment by McFly753** [comment]
Lieber Niklas, Danke! ;)
Nur, das verstehe ich nicht. Weil geht er dann mit Klicken UND mit wischen? - Wenn ja, dann lass mal und ich schaue es mir an!

**Comment by Mojo1917** [comment]
Lieber Matthias, ja genau. Es gibt verschiedene 'UIGestureRecognizer' einer davon kann klicks erkennen und ein anderer Wischgesten. Wir können hier für jede Art der Nutzerinteraktion einen definieren und so auf verschiedene Nutzergesten auf dem gleichen Element reagieren ;)

Das ist etwas anders als bei der Liste, weil es da fest definierte Gesten gibt und diese sich mit unseren eigenen nicht 'vertragen'

**Comment by McFly753** [comment]
ok, alles klar!

**Comment by McFly753** [comment]
Danke, passt. (Kleinigkeit in neuem Ticket.)
