### ISSUE TITLE
Kleine optische Verbesserung in den Einstellungen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#215]
- Bitte in den Einstellungen die einzelnen Felder optisch so trennen, dass der graue Hintergrund als Trenner wieder sichtbar wird. Dann ist es übersichtlicher. 

- Und: kannst Du die zwei "Ausschalter" rechtsbündig machen und den ETxt links daneben setzen?

![img_0662](https://user-images.githubusercontent.com/493612/44649514-bf487780-aa16-11e8-8aaf-10628759be12.PNG)

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Ich habe den Trenner jetzt doppelt so dick gemacht. Viel mehr geht nicht ohne das es störend aussieht ;)

**Comment by McFly753** [comment]
Hier würde ich optimieren, hier hatte ich mich falsch ausgedrückt, sorry::
> bitte diesen Trenner, den Du vergrößert hast, wieder zurücknehmen, den meinte ich nicht.
(ich meinte den zwischen den verschiedenen Benennungen)
> hier dann: was ist, wenn Du 
1.) diese "Striche" in diesem Bereich weglässt 
2.) die Bennenugen (bei zweiern wie einsern) in eine Zeile machst, also bei zweiern: Objekt Singular  Objekt Plural und bei einsern: Attribut (aber in der kleinen Schriftgröße wie bei den zweiern)?
3.) dann ggf. zwischen den verscheidnene Benennugen den grauen Hintergrujnd druchschauen lässet (oder evtl. brauchen wir das auch gar nicht)

**Comment by Mojo1917** [comment]
Okay ich denke den grauen Hintergrund brauchen wir nicht durchschauen lassen. Ich finde es sieht komisch aus, wenn dies bei den Zweiern der Fall ist und bei den beiden Darunter nicht der Fall.

Zu dem Bug: Sobald die beiden Felder (Attribut und Tag) als ausgeblendet markiert sind habe ich dies Felder deaktiviert, damit der Nutzer hier nichts mehr eingeben kann. Soll ich es wieder rausnehmen? Ich dachte dies sei nur logisch :D

**Comment by Mojo1917** [comment]
Der Bereich sieht jetzt wie folgt aus. Hoffe das ist jetzt richtig!

![img_0531](https://user-images.githubusercontent.com/20678932/45318114-3d8b3a80-b53c-11e8-9884-e0a5190cea2d.png)

**Comment by McFly753** [comment]
Ja, passt so! // Wegen "deaktivierung": kannst Du machen, nur dann graue diese deaktivierten Felder auch einfach noch optisch aus.

**Comment by Mojo1917** [comment]
Okay ist setzte sie ein wenig dunkler!

**Comment by McFly753** [comment]
Passt so, nur bei Deaktivierung: hier bitte auch den Text in den Feldern ausgrauen, nicht nur die Felder. (also auch die Schriftfarbe) - natürlich ein anderes Grau als der Hintergrund... :)

**Comment by Mojo1917** [comment]
Okay kommt mit dem nächsten Update!

**Comment by McFly753** [comment]
Danke!
