### ISSUE TITLE
Bei Entfernungsfilterung verliere ich die Sortierungs-Gruppen-Bescrhiftrujg in der Liste

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#218]
![img_0896](https://user-images.githubusercontent.com/493612/44955199-3af86780-aee2-11e8-848c-7dfacc8245c3.PNG)

**Comment by Mojo1917** [comment]
Trat aufm wenn die App noch kein GPS-Signal gefunden hatte. Ab jetzt wir ein entsprechender Hinweis angezeigt.

**Comment by McFly753** [comment]
Danke!
