### ISSUE TITLE
Kamera geht nicht auf...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#219]
1. App komplett neu installiert.
2. 3x nein/abbrechen gesagt
3. + 
4. Auf Foto-Hionzufügen klicken > von Kamera
5. 3x mit ja bestätigt
>> dann bleibt die App da stehen, öffnet aber nicht die Kamera

(Beim zweiten Versuch geht sie dann auf.)

**Comment by Mojo1917** [comment]
Fehler ist behoben!

**Comment by McFly753** [comment]
Danke!
