### ISSUE TITLE
Farbsortierung in Karte ist noch nicht testbar...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#22]
Weil die Objekte immer verschwinden.

**Comment by Mojo1917** [comment]
Ist verbessert. Karte funktioniert jetzt wie geplant.

**Comment by McFly753** [comment]
Danke. Schon online oder im nächsten Upload?

**Comment by Mojo1917** [comment]
Nein alles über das nächste Update ;) Am Wochenende prüft Apple leider keine Apps. Ich werde das Update morgen im Laufe des Tages hochladen.

**Comment by McFly753** [comment]
Ok, alles klar.

**Comment by McFly753** [comment]
Noch nicht sinnvoll testbar, siehe #29
