### ISSUE TITLE
Seite (Notizen) geht nicht bis ganz unten...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#220]
![img_0899](https://user-images.githubusercontent.com/493612/44955238-b9550980-aee2-11e8-8691-23f811bb6417.PNG)

**Comment by Mojo1917** [comment]
Ist schon behoben... Also in der nächsten Version ;)

**Comment by McFly753** [comment]
Schreib mal was in das Attributsfeld und klapp die Tastaur wieder zu - dann geht das Feld wieder nichgt bis nach unten...

**Comment by Mojo1917** [comment]
Jetzt wirklich behoben!

**Comment by McFly753** [comment]
Danke!
