### ISSUE TITLE
Leichte Hilfetext-Änderung

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#223]
Hier kannst Du nach Objekt-Namen, Tags, Attribut, Land oder Ort via Freitext suchen bzw. filtern.

![img_0903](https://user-images.githubusercontent.com/493612/44955308-bb6b9800-aee3-11e8-9b61-f4bfe7884756.PNG)

**Comment by McFly753** [comment]
Passt: ABER: "Objekt"(Singular)-Namen, "Tags"(Plural), "Attribut"(Singular) wird nicht dynamisch aus der Datenbank gelesen.

> wie ist es prinzipiell hier bei der Hilfe?

**Comment by Mojo1917** [comment]
Du hast Recht ist mir 'durchgerutsch'. Kommt mit dem nächsten Update.

**Comment by Mojo1917** [comment]
Auch hier #249

**Comment by McFly753** [comment]
ok
