### ISSUE TITLE
Ich würde den Startscreen nicht quer(horizontal startbar machen 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#227]
![img_0910](https://user-images.githubusercontent.com/493612/44955408-51ec8900-aee5-11e8-97c5-4e37a96e9330.PNG)

**Comment by Mojo1917** [comment]
Tritt dies bei dir immer auf? Bekommen es im Emulator nicht erzeugt.
Ich versuche es dennoch mal sicherheitshalber abzufangen.
