### ISSUE TITLE
Bild benennen und Kleinigkeiten 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#228]
1.)
a) Lass uns hier hier auch noch einheitlich werden und auch individuelle Bildnamen einführen.
Die Namen sind auch hier vorab vergeben mit: "Bild 1", "Bild 2" etc. - können aber umbenannt werden.

b) Dann würden wir die Anzeige hierbei der Bildansicht abändern auf:
Bildname (Schriftgröße wie ehm. Objektname)
Objektname, Bild 1 von 5 (Schriftgröße wie bisher in dieser Zeile)

c) Klick öffnet dann das Bildname-Veränderungs Popup - hier kann man dann auf dieser Seite nicht mehr den Objektnamen verändern.

2.) Und: lass uns hier die Menübezeichung bzgl. Löschen konsequent machen:
also: "Bildname löschen". Und von der Reihenfolge auch an erster Position.

3.) Und kannst Du den Kommentar (beim IphoneX) etwas nach oben schieben, der klebt etwas zu weit unten an dem Menüstrich und den runden Kanten...

4.) Und: können wir den Bild-Kommentar (ähnlich wie die Tags oder das Attribut) in den Einstellugen ausblendbar machen? Wo könnten wir es in den Einstellungen am besten unterbringen? 

5.) Und dann müssten wir die Hilfeseiten abändern auf: 
a) Namensänderung auf Bild-Namen abändern.

b) Untere Hilfeseite in zwei Hilfeseiten aufteieln (oder dynamisch aus zwei auswählen, jenachdem ob der Kommenar ein oder ausgeschaltet ist). 
Also entweder:
- Hier kannst du die Metadaten (Datum und Ort) des Bildes verändern.
- Hier kannst du einen Kommentar zu dem Bild dazuschreiben.
Oder:
a) Hier kannst du die Metadaten (Datum und Ort) des Bildes verändern und einen Kommentar zu dem Bild dazuschreiben.
b) Hier kannst du die Metadaten (Datum und Ort) des Bildes verändern.

![img_0915](https://user-images.githubusercontent.com/493612/44955418-79dbec80-aee5-11e8-9692-b0a52b6a5bce.PNG)

![img_0917](https://user-images.githubusercontent.com/493612/44955968-d394e480-aeee-11e8-8b4a-87c0546c1d42.PNG)

**Comment by Mojo1917** [comment]
Jetzt da wir schon 3 ausblendbare Elemente haben könnten wir uns vielleicht überlegen in den Einstellungen einen eigene Sektion einzubauen. Diese könnten wir direkt unter die Sektion Benennung legen. Was denkst du?

**Comment by McFly753** [comment]
Ja, ist wahrscheinlich übersichtlicher. Oder auch davor?

**Comment by Mojo1917** [comment]
Okay dann lager ich das aus!

**Comment by Mojo1917** [comment]
Im Tutorial würde ich für das Kommentarfeld keine eigene Blase zeigen. Es ist schon selbsterklärend. Daher denke ich können wir es in die andere aufnehmen, wenn vorhanden ;)

**Comment by McFly753** [comment]
OK!

**Comment by McFly753** [comment]
Passt alles, nur:

"3.) Und kannst Du den Kommentar (beim IphoneX) etwas nach oben schieben, der klebt etwas zu weit unten an dem Menüstrich und den runden Kanten...
>> Du hast es etwas zu weit nach oben geschoben... ;) schiebs mal wieder ca. 1/2 - 2/3 Zeilenhöhe alles nach unten.

**Comment by Mojo1917** [comment]
zu 3. der Abstand verhält sich aktuell an dem von Apple empfohlenen Abstand zu dem unteren Button. der liegt bei dem iPhone X leider recht weit oben. Apple empfiehlt, dass wir in den Bereich darunter keine Elemente legen sollten. Bei allen anderen iPhone Modellen ist dieser Abstand gleich 0. Zudem lässt es sich schwer abfangen, ob wir auf dem X sind oder nicht (Vorallem auf mögliche neue iPhone Modelle hin betrachtet). Wenn wir den Abstand zu der sog. 'Safe Layout Area' verringern können wir dies nur auf allen Geräten. Dann klebt der Kommentar jedoch auf 'herkömmlichen' iPhones am unteren Rand.
Wir können die Box nur wieder wie vorher, wirklich an den Bildschirmrand heften. Dies war jedoch ein Layoutfehler von meiner Seite. Daher würde ich dies nicht empfehlen.
Was denkst du?

**Comment by Mojo1917** [comment]
Alles andere ist umgesetzt ;)

**Comment by McFly753** [comment]
Danke!
