### ISSUE TITLE
Erstellungsdatum Veränderung -> Bug.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#229]
Dieser Bug schein doch noch da zu sein:

Geh auf das Beispielobjekt und versuche das Erstellungsdatum (manuell) zu ändern. 
Ändere es aber nicht, aber klicke auf fertig.

Dann kommt der Bug, dass er meckert, dass ich einen Besuch vor dem Erstellungsdatum erstellen will. Und ob ich das will etc. (und dann wird mir ein zweiter Besuch am selben Tag angelegt)

![img_0922](https://user-images.githubusercontent.com/493612/44956368-8a945e80-aef5-11e8-92f8-67f328208c1a.PNG)

![img_0923](https://user-images.githubusercontent.com/493612/44956369-8bc58b80-aef5-11e8-8a51-3daf08b9c9e3.PNG)

![img_0924](https://user-images.githubusercontent.com/493612/44956372-9718b700-aef5-11e8-80bb-da55bc6287da.PNG)

**Comment by McFly753** [comment]
Bug ist noch da

**Comment by Mojo1917** [comment]
Okay, der Bug sollte bei neu erstellten Beispielobjekten nicht auftreten.

**Comment by Mojo1917** [comment]
Okay ich habe die Fehler bei der Erstellung des Beispielobjektes jetzt behoben. Bei allen, nach dem neuen Update, neu erstellten Objekten tritt der Fehler nicht mehr auf.

**Comment by McFly753** [comment]
Danke!
