### ISSUE TITLE
Hilfe-Bobbel hier etwas vergrößern...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#230]
... nicht nur über das Plus, sondern auch den ersten Eintrag mitnehmen/anschneiden

![img_0921](https://user-images.githubusercontent.com/493612/44956390-f1197c80-aef5-11e8-8c11-299f703402b8.PNG)

**Comment by Mojo1917** [comment]
Leider können diese beiden Elemente nicht in eine Blase aufgenommen werden. Sie lassen sich aufgrund ihrer verschiedenen ParentViewElemente nicht richtig abbilden. Ich habe jetzt zwei Hilfeblasen angelegt ;) 
Ich hoffe das passt.
