### ISSUE TITLE
Kannst Du in der Kartenansicht auf ein Bildchen/Punkt auch einen Langklick erlauben, der dann direkt in die Detailview dieses Objektes springt?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#232]
und mit Vibrations/Klick-Bestätigung...

**Comment by Mojo1917** [comment]
Klar habe ich einprogrammiert ;)

**Comment by McFly753** [comment]
Kannst Du die "Latenzzeit" auf die Hälfte reduzieren? Oder ist sie schon minimal?

**Comment by Mojo1917** [comment]
Nein ich habe die halbiert ;)

**Comment by Mojo1917** [comment]
Habe gerade festgestellt, dass es bei einer so kurzen Zeit nicht mehr möglich ist, dass ich nur 'einfach' Klicke. Dies wird dann schon als Langklick erkannt...

**Comment by Mojo1917** [comment]
Dies liegt leider an einer Verzögerung in der Gestenerkennung.

**Comment by McFly753** [comment]
Ok, dann lassn wir es do, Danke!
