### ISSUE TITLE
Vibration/Klick öfters einsetzen?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#233]
Ich habe gesehen, dass Apple die Vibartion auch bei allen Schaltern (siehe unsere Einstellugen) einsetzt. 

Lass es uns auch da machen und setze es auch mal hier ein:
Umschkaten der Karte/Liste

Dann sehen wir weiter, ob wir es noch an meheren Punkten so machne.

**Comment by McFly753** [comment]
Und: setz es bitte auch bei den Datum-Drehreglern ein.

**Comment by Mojo1917** [comment]
Okay bei den Datumsreglern haben wir jetzt neben dem 'tick' Geräusch das Feedback. Dieses lässt sich jedoch nur ausführen, wenn eine 'Rolle' still steht und die Eingabe gültig ist. Vielleicht ist dies so eh intuitiver?

**Comment by Mojo1917** [comment]
Bei allen anderen ist es auch eingebunden.

**Comment by McFly753** [comment]
Ok, schaue ich mir dann an.

**Comment by McFly753** [comment]
Danke, passt.
