### ISSUE TITLE
Database-Umschaltung cleverer machen 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#234]
Lass uns oben, beim Data-Base-Umschalten eine ähnliche Logik wie bei dem (neuen) Filterbutton anweden:

Gehen wir davon aus, dass es 5 Datenbanken gibt und ich mich in der 2. befinde. Dann kann ich horizontal nach rechts und links wischen. In gewissen Abständen switche ich (nur den Titel) zu den anderen Datenbanekn, was auch mit einer Vibration/Klick bestätigt wird. Links kann ich noch einmal gehen, rechts aber drei mal. Aber auch wieder zurück etc. - aber erst beim LOslassen wird (nochmals Vibration/Klick) die Datenbank angesprungen.

Diese Bedienung ist mir serh wichtig für die Zukunft, weil die Bedieung unserer ToDo-App sehr auf diesem Prinzip beruhen wird.

**Comment by Mojo1917** [comment]
Okay das hier hat sich leichter implementieren lassen als der Button unten ;)

**Comment by Mojo1917** [comment]
Wir können die nötige Strecke, die pro 'Umschaltung' notwenig ist, noch anpassen!

**Comment by McFly753** [comment]
Danke.
Aber kannst Du keinen Krei machen, sondern bei der linken und rechten Dankenbank bei der AUswahl "stehen" bleiben?

**Comment by Mojo1917** [comment]
Achso ja klar! Das bekommen wir hin ;)

**Comment by McFly753** [comment]
Danke, und die Reihenfolge logischer, also umdrehen. Linker Anschlag ist erste Datenbank, rechter anschlag ist letzte Datenbank.

**Comment by Mojo1917** [comment]
Okay habe sie umgedreht ;) 

Hatte mich von der Rotation an einer 'Rolle' orientiert. Also, wenn ich nach links ziehe rolle ich zur Rechten Seite und andersrum.

**Comment by McFly753** [comment]
Genau, ja!

**Comment by Mojo1917** [comment]
Okay alles klar! Ist umgesetzt.

**Comment by McFly753** [comment]
Danke!
