### ISSUE TITLE
Teilen/Import: ein paar Erweiterungen: 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#235]
1.) Mehrere Listen-Objekte Teilbar machen:
Also ich sollte im Menü (über der Listenansicht) auf Teieln gehen können, dann komm ich in einen Ansichtsmodus der Liste, wo ich ein oder mehrer Objeket auswählen kann und ich diese dann alle zusammen Teilen kann. / Auch der Import sollte dann nacheinander ausgeführt werden. (Lass uns teelfonieren.)

2.) Ganze Datenbank teilbar machen: Könen wir eine ganze Datenbank teilen? Wo löse ich das aus?

3.) Kann ich eine solche Datenbank, die als ganzes verschickt wird, auch nur in eine bestehnde "Mergen"? (also nicht nur als neue Datenbank mit allen EInstellunbegn hinzufügen, sondern in eine bestehende einfügen. Das wäre eigeentcluh nichgts anderes, wie das Importieren von den einzelenen Objketen, eben nichgt nur ein Objket oder ein paar sondern alle.

4.) Allgemein (egal ob ein Objkezt oder mehrer Objkete): Kann ich Dupletten abfangen/abfragen? Also wird ein Objekt importiert, wird erst geschaiut, ob der selbe Dateiname existiert UND ob die Koordinaten des Hauptbildes gleich sind. Wenn beides der Fall ist, kommt die Abfrage: Das zu importierende Objket XYZ ist serh ähnlich zu deinem bestehenden Objket ZYX. Willst du es dennoch importieren?"

**Comment by McFly753** [comment]
Und: hier müssen wir dann auch noch die Hilfe erweitern, wenn soweit.

**Comment by Mojo1917** [comment]
Punkt 1 ist implementiert. Die Import-Ablauf ist an dem von einem Objekt orientiert, damit wir hier einen immer gleichen Ablauf haben.

**Comment by Mojo1917** [comment]
4. ist auch umgesetzt und 2 / 3 fast fertig ;)

**Comment by Mojo1917** [comment]
Alles umgesetzt. Kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Import geht leider nicht. egla ob ein Objket oder mehrere im Container sind. Das Import-Laden-Icon ("Lese Datei") hört nicht auf, sich zu drehen... // und das leider nun auch nicht mehr bei einem Einzel-Objket-Import.

**Comment by McFly753** [comment]
![img_1511](https://user-images.githubusercontent.com/493612/45840136-71bde280-bd16-11e8-938a-4cbce9e5d4c2.PNG)

**Comment by Mojo1917** [comment]
Oh das sollte natürlich nicht der Fall sein. Hast du die Dateien verändert? Bei mir scheint auf den Ersten Anhieb alles zu funktionieren. Ich schaue mir das morgen nochmal genauer an ;)

**Comment by McFly753** [comment]
Nein, ich habe nur exportiert und gleich wieder importiert. (via der "Dateien"-Ordner auf dem Iphone)

**Comment by Mojo1917** [comment]
Der Fehler ist jetzt behoben. Es hatte sich in iOS leider etwas in Bezug der Freigabe von Dokumenten über Files geändert.

**Comment by McFly753** [comment]
Danke, aber:

- bitte den Teilen Prozess der ganzen Datenbank bitte von der Didaktik her wie das Löschen einer ganezn Datenbank machen. Also links einen Radiobutton einbelden. Nichgt den rechts verwenden, das irritiert.

- Datenbank teilen geht nicht, ich exportiere eine Datenbank mit 13 Einträgen, bekomme aber vile weniger importiert - auch wenn ich eine neue Datenbank erstellen will. (ich habe dir meinen Export per Mail geschickt)

- Wenn eine neue Datenbank angelegt wird, bitte manche Abfragen abfangen (z.B. das neu-erstellen von Tags)

- bie Import in eine neue Datenbank, wird scheinbar keine neue angelegt. Ich hatte 4 Datenbanken udn nach Nueanlegen durch Import habe ich auch wieder nur 4?

- Einzelne Objkete teilen haben ähnliche Probleme wie ganze Datenbank importieren.

**Comment by Mojo1917** [comment]
Okay vielen Dank für die Datei. Viele der Fehler scheinen durch die Emoji zu entstehen. Ich denke aber, das lässt sich beheben!

**Comment by Mojo1917** [comment]
zu 3: Ist behoben. Entstand durch den fehlerhaften Import von Tags in Verbindung mit emoji.

zu 4: konnte das hier leider nicht reproduzieren. Auch nicht mit der Datei von dir. Bei dem Import in eine Neue wird diese bei mir auch immer angelegt. Vielleicht hing dieser Fehler mit einem anderen zusammen.

**Comment by Mojo1917** [comment]
ZU 2: Hattest du Objekte mit dem gleichen Namen? Also waren die fehlenden Objekte z.B. alle unser BeispielObjekt? Ich denke dies wird der Fehler in meiner Logik gewesen sein. Ich werde ihn mal abfangen. Dann sollte er eigentlich nicht mehr auftreten.

**Comment by Mojo1917** [comment]
5 und 6 sind umgesetzt.

Beim Teilen wird jetzt ein entsprechendes Icon links angezeigt. Ich denke ein zweiter RadioButton würde nur verwirren.

**Comment by Mojo1917** [comment]
Die Probleme bei Einzelnen Objekten treten bei mir auch nicht mehr auf.

**Comment by McFly753** [comment]
Ok, ich teste es dann, wenn online.

**Comment by McFly753** [comment]
Lieber Niklas, Danke!

Das noch:

1. beim Teilen von merheren Objketen: wenn ich keine Veränderung in der Liste sehe, woher weiss ich dann, dass ich die Einträge anklicken soll? Was wäre, wenn man alles ausgraut und das Ausgewählte aber in normal Farben ist (o.ä.)?

2. Beim Teilen von meherern Objketen: hier sollte, solange kein Objket ausgewählt ist, oben nict "teilen" sondern "abbrechen" stehen. Sobald ein Eintrag ausgewählt ist, steht da "teilen".

3. nach dem Import sollte in die jeweilige Dataenbank gesprungen werden, wenn man sich noch nicht dort befindet (kann sein, dass das der Fall ist, wollte nur sicher gehen)

4. beim Anlegen einer ganzen Datenbank sollte eine Abfrage kommen, wie diese Datenbank genannt werden soll. Ich würde ihr nicht automatisch den "alten" Namen geben.

**Comment by Mojo1917** [comment]
Wie per iMessage besprochen erweitere ich die App noch um die Funktion alle Datenbanken auf einmal teilen zu können.

**Comment by Mojo1917** [comment]
Okay ist eingefügt. Update sollte morgen verfügbar sein ;)

**Comment by McFly753** [comment]
Danke! (Eine Sache hierzu noch, aber in neuem Ticket)
