### ISSUE TITLE
Menüs tauschen und einheitliche Schliessen/Zurück-Logik

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#236]
Wie am Telefon besprochen, lass uns folegndes probieren:

Auf alle Fälle:
1.) Zurück und "+" überall nach links, Menü überall nach rechts.
Überlegung:
2.) (Denk Dir das aber bitte auch nochmals durch, ob/was logisch:)
- Zurück als Zurück-Pfeil anbieten oder doch nach unten oder als "nach Oben Pfeil" anbieten?
- Abhängig hiervon: nach oben oder nach rechts von der Animation her schliessen?
- Unabhängig davon fände ich es sinnvoll (zumindest am Iphone x) Fnester nach oben wegzuwischen. Vorteil hierbei wäre, dass ich auch Listen (Statistik, Einstellungen) nach oben schiessen könnte. (Nach rechts/links schliessen macht wegen den Bildern keinen Sinn) // natürlcih könnten wir sie auch nach unten schliessen, das hängt davon ab, was didaktisch besser ist. //  also davon soll es nicht abhängen... 
- wenn ich einheitlich sein möchte, müsste ich alles nach oben oder nach unten schliessen. Dann müsste aber auch alles von der Animation her passen. Das müssten wir ausprobieren.
-->>> Also: was ist intuitiver/schlauer? Nach unten, nach links, nach oben?

3.) zur Listen-Schliessung:  Statistik/Einstellung/Datenbanken/Eigenschaten/Tags/Sichern/Wiederherstellen/Impressum: könnte man auch durch vertikales Wischen ausfürhren, aber erst auf Anschlag und evt. mit einer "erscheindenden" Voranzeige "Schliessen". Das würde prinzipiell nach unten oder nach oben gehen.

-------> Vorschlag: wir tauschen erstmal nur die Icons und lassen alles auf unten, bis wir hier uns sicher sind. Wenn wir unten bleiben, würde ich Punkt 3 dann doch auch nach unten machen.

**Comment by Mojo1917** [comment]
Okay ich habe Punkt 1 umgesetzt, zusätzliche habe ich das 'Ausrufezeichen' links gelassen. Da man zu dem schließen Icon zwangsläufig gehen muss mit dem Finger 'verpasst' man es so nicht ;)

Jetzt meine Gedanken zu den anderen Punkten.
Wenn wir uns anschauen, wie Apple (bis jetzt) den Nutzer in Apps navigieren lässt lassen sich hier zwei Arten erkennen:
1. Das einblenden von Unterseiten mit starkem Bezug zu der vorherigen (Bsp. Einstellungen > Untereinstellungen). Dieses neue Fenster wird von Apple von rechts nach links ins Bild geschoben und kann über den 'Back'-Button wieder  zurückgeschoben werden.
2. Das Einblenden von neuen Fenstern, die wenig Bezug zu der vorherigen haben (Chatliste > Einstellungen) Hier wird die neue Seite von unten nach oben geschoben und über einen Button in der oberen Leiste kann diese wieder geschlossen werden. Diese Animation ist dann auch wieder rückläufig.

Zu den Wischgesten (links rechts) in Apps.
Ich denke für diese setzt Apple auf drei Arten ein:
1. Schließen von Fenstern, die sich wie in 1. beschrieben geöffnet haben, durch ein Wischen vom linken Bildschirmrand nach rechts.
2. In einer Liste können Elemente nach rechts geschoben werden und direkte Aktionen mit ihnen durchführen zu können ohne diese öffnen zu können (Viele andere Betriebssysteme kennen hierfür das lange drücken bzw. den rechtsklick)
3. Das wechseln zwischen Elementen die aus einer Liste heraus geöffnet wurden. (Bsp. Fotos)

Zu den Wischgesten (oben unten):
Hier nutzt Apple die Geste um Fenster durch ein Wischen nach unten zu schließen, wenn der Nutzer sich ganz oben befindet. (App Store )
Zusätzlich gibt es jedoch die Möglichkeit Listen zu 'überziehen' um diese zum Beispiel zu aktualisieren.
Eine Ausnahme ist hier nur das Beenden von Apps über das wischen nach oben. (Du meintest jedoch, dass dies auf dem X nicht mehr gehen würde)

So... soviel zu meinen Beobachtungen als nicht alltäglicher Apple-Nutzer ;) Ich hoffe diese sind soweit alle richtig. Ich habe noch nie das iPhone X genutzt (außer kurz in Store) kann daher hierzu nicht viel sagen.
Betrachtet man die oben beschriebenen Gesten sind diese auch in den meisten Apps recht einheitlich umgesetzt. Auch die Human Interface Guidelines von Apple raten eine einheitliche Navigation zu implementieren. Da iOS Geräte als sehr einfach und 'logisch' in der Bedienung gelten würde ich mich zusätzlich an die bekannten Gesten halten.

Davon abgeleitet denke ich sind folgende Gesten und Navigationen sinnvoll:
Aus der Liste / Karte geht es per Animation rechts links in der Objektansicht. In allen Seiten die davon abzweigen (ausgenommen Statistik und Einstellungen) würde ich per gleicher Animation einblenden.
Die Einstellungen würde ich von unten nach oben einblenden (Sie haben nur bedingt mit der vorherigen Seite zu tun) und dann in den Einstellungen wieder von rechts nach links.
Die Statistik würde ich immer von unten nach oben einblenden.

Somit würde ich dann auch in der Objektansicht sowie der Bildansicht ein wischen von links nach rechts zum schließen einbinden (Bei den großen Bildern sollte dies möglich sein, muss ich jedoch nochmal prüfen)
Ein Schließen durch wischen nach unten würde ich nur implementieren, wenn das Fenster sich von unten her geöffnet hat.

Zusätzlich gefällt mir die Ideen, dass wir durch ein überziehen (Bsp. Liste) die Statistik mit kurzer vorheriger Anzeige einblenden. Die hier eingeblendeten Elemente sollten jedoch einen leichten Bezug zu dem Inhalten der Liste bieten.

Apple hat zwar in seinem neuen X das Schließen von Apps durch diese Gesten von unten nach oben eingebunden. Jedoch habe ich bisher nicht mitbekommen, dass Apple dies auch für die Navigation in Apps plant. Daraufhin deutet auch, dass die Nutzer an die bisherigen Navigationsgesten gewohnt sind und es schwer werden könnte einen Nutzer 'umzugewöhnen'.

So, das war jetzt mehr als erwartet. Was denkst du hiervon?

**Comment by McFly753** [comment]
Lieber Niklas, Danke für die lange Ausführung! (Ich muss mich für meine vielen Tippfehler entschuldigen...) ;) 

Ich würde eher erstmal auf nach unten schieben zum schließen bleiben, denn wir haben fast alles so. Uns ein nach rechts schieben geht z.B. bei den Bildern schon nicht mehr... / lass uns es dann im nächsten Schritt am Tel besprechen. 
Willst Du aber folg des schonmal zum testen einbauen: dass ein Überziehen die Statistik auslöst und ein Überziehen z.B. In den Einstelluhgen diese schließt? (Nur hier als Test)

Danke! Liebe Grüße, Matthias

**Comment by Mojo1917** [comment]
Okay ist beides umgesetzt!

**Comment by Mojo1917** [comment]
Sehe gerade, dass ich das Tauschen der Menüs in der Statistik übersehen habe. Kommt mit der nächsten Version!

**Comment by McFly753** [comment]
Ja, Statistik noch und setzte dann diese auch noch um:

3.) zur Listen-Schliessung: Statistik/Einstellung/Datenbanken/Eigenschaten/Tags/Sichern/Wiederherstellen/Impressum: könnte man auch durch vertikales Wischen ausfürhren, aber erst auf Anschlag und evt. mit einer "erscheindenden" Voranzeige "Schliessen". Das würde prinzipiell nach unten oder nach oben gehen.

> Frage ist, ob wir hier "Seite schliessen" anzieegn oder einfach nur "zurück"?

**Comment by Mojo1917** [comment]
Okay setzte ich um. Naja also wir können hier denke ich beides schreiben.

Und die Aktion soll ausgelöst werden, wenn nach unten oder oben überzogen wird, richtig?

**Comment by Mojo1917** [comment]
Vielleicht ist 'Schließen' sinnvoller, weil man das 'zurück' ja nicht direkt wir rückgängig machen kann wie bei einer Navigation im Browser?

**Comment by McFly753** [comment]
ok, dann Seite schliessen.

Nur nach unten überziehen. 
(Wenn Du willst, kannst Du, wenn man die Einstellunbgen nach oben überzieht, unten das Locbaselogo mit der Copyright-Zeile einblenden... Ohne dass was passiert.)

**Comment by Mojo1917** [comment]
Okay das Logo will sich gerade nicht anzeigen lassen. Mache ich später!

**Comment by McFly753** [comment]
Danke, Logo setz ich in eigenes icket
