### ISSUE TITLE
Beim Runterziehen der Listenansicht der Objekte die Statistik aufrufen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#237]
- Also dass der Zuschauer eine Schrift mit "Statistik öffnen" sieht und dann, wenn er weit genug zieht, diese auch öffnet.

**Comment by Mojo1917** [comment]
Okay ist eingebunden. Ich habe die standardmäßig angezeigte ProgressBar gelassen. Ich finde sie zeigt ganz schön wann die Aktion ausgelöst wird. Kann sie aber auch gerne entfernen!

**Comment by McFly753** [comment]
Ok, Danke! Lassen wir mal so!
