### ISSUE TITLE
Kann es sein, dass wir männlich/weiblich nicht wirklich bauchen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#24]
wir könnten bei Abfragen einfach sagen, bist Du sicher, dass Du das Objekt wirklcih löschen willst etc.

oder?

Wenn nicht, müssten wir nämlcih noch ein "es" einführen... ;) ("Das Schloss")

**Comment by Mojo1917** [comment]
Derzeit verwende ich das Geschlecht nur für Nachrichten wie "Soll **der Baum** xy gelöscht werde?"

Gerne kann ich das rausnehmen und hier immer nur 'das Objekt' schreiben. Oder ich führe ein 'Es' ein. Was dir lieber ist.

**Comment by McFly753** [comment]
Lass es uns rausnehmen und schreibe es mit "Objekt"

**Comment by Mojo1917** [comment]
Okay dann werfe ich das raus. Ich werde den Eintrag in der Datenbank dennoch lassen, falls es später wieder Anwendung finden sollte ;)

**Comment by McFly753** [comment]
Alles klar! ;)

**Comment by Mojo1917** [comment]
Ich umgesetzt. Änderung kommt mit dem nächsten Update.
