### ISSUE TITLE
leichte Textänderung in der Standortabfrage 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#240]
Schreib bitte auch einheitlich hier "Möchte" statt "Darf"
"Locbase" möchte auf deinen Standort zugreifen

**Comment by Mojo1917** [comment]
Ich denke du beziehst dich hier auf den 'ersten' Dialog indem der Nutzer direkt die Auswahl treffen kann. Dies ist der Standart iOS-Dialog. Diese können wir nicht editieren. 
Apple macht dies, damit wir nicht einen ganz anderen 'harmlosen' Text einsetzen und so eine Standorterlaubnis von dem Nutzer unbewusst einfordern.

**Comment by McFly753** [comment]
ok!
