### ISSUE TITLE
Lass uns auch das Löschen einheitlich machen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#244]
und zwar bei Datenbank, Tags, Einstellungen und Sicherungs-Datei
-> und zwar nimm bitte die Logik der Sicherungsdatei her (mit dem extra Abfalleimer Icon oben rechts dann). Das ist schöner, denn so oft löscht man auch nicht.

(Und biete ihn nur an, wenn es auch was zu löschen gibt.)

**Comment by Mojo1917** [comment]
Okay!

**Comment by McFly753** [comment]
Danke!
