### ISSUE TITLE
Leichte Textänderungen in den Einstellungen & Bug in den Titeln

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#245]
1. Können wir hinter den Datenbaktitel die Anzahl aller Datenbanken in Klammer schreiben?
Also z.B. so: AKTUELLE DATENBANK (von insgesamt 3)

2. Bitte nenne den Bereich, wo man Dinge ausschalten kann "Vereinfachungen". (der hat bisher keinen  NAmen und daher sind alle NAmen nach oben um eine Position verrutscht)

3. Setz diesen Bereich von der Reihenfolge bitte nach die Objekteigenschaften & Tags

4.  Nimm von der Reiehnfolge her die Objekteigenschaften & Tags bitte direkt nach die Datenbanken.

**Comment by McFly753** [comment]
![img_1085](https://user-images.githubusercontent.com/493612/45231963-7343df80-b300-11e8-8772-dfd49fd3d162.PNG)

**Comment by Mojo1917** [comment]
Oh okay ;) Ist umgesetzt.

**Comment by McFly753** [comment]
Danke!
