### ISSUE TITLE
Sortierbutton optimieren

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#246]
- Könnetst Du den Sortierbutton bitte viel breiter machen, dass er nicht abgekürzt werden mus.
- und nicht blau machen (schau, was optisch passt, notfalls Outline etc.?)
- und könnetst Du drunter in der kleinen grauen Schrift (wie bei Karte / Liste): "Sortierung" schreiben?
- und bitte diesen Text bei Karte / Liste auch grau schreiben.
- und: bitet auch hier keinen "Kreis" darstellen, sondern oben unten "anschlagen"
- und setze (beim Iphoen x) bitte diesen Trenner-Strich hoch, der hängt noch unten (Bild kommt noch)
- und beim IPAD bitte beide Bereiche (links udn rechts) zentrieren (Bild kommt noch)
- und achte (Iphone 8) darauf, dass der Text ujnter diesen Butons ein paar Pixxel höher sitzt (ist hier zu knapp am Rand) (Bild kommt noch)

-> UND: da der Finger immer blöderweise den Button selbst überdeckt: können wir GRößeren Text einfachmittig über der App in grau und fett anzeigen (overlay)? Nur die Zeit lang, wie der Button bediehnt wird udn dan, wenn er losgelassen wird über 1sec. die Auswahl wegfaden lassen?

**Comment by McFly753** [comment]
![img_0019](https://user-images.githubusercontent.com/493612/45225843-0f191f80-b2f0-11e8-9d06-a22c54d59d0d.PNG)

![img_1039](https://user-images.githubusercontent.com/493612/45225867-1c360e80-b2f0-11e8-8ddf-38c883258459.PNG)

![img_0017 1](https://user-images.githubusercontent.com/493612/45227968-628d6c80-b2f4-11e8-9358-8d0e4d5b235e.PNG)

**Comment by Mojo1917** [comment]
Okay Ticket ist umgesetzt. Hier die Screenshots des neuen Layouts.
![simulator screen shot - ipad pro 9 7-inch - 2018-09-11 at 20 38 22](https://user-images.githubusercontent.com/20678932/45380421-f0be6700-b602-11e8-8e2f-851dd6e955db.png)
![simulator screen shot - iphone 8 - 2018-09-11 at 20 40 00](https://user-images.githubusercontent.com/20678932/45380422-f156fd80-b602-11e8-91a9-4283f7fd8be0.png)
![simulator screen shot - iphone x - 2018-09-11 at 20 38 56](https://user-images.githubusercontent.com/20678932/45380423-f156fd80-b602-11e8-8be9-0d174a39a010.png)

**Comment by McFly753** [comment]
Versuche es in einem grauen Kasten anzuzeigen, helle Schrift. Abgerundete Ecken. (Ich kenne das vom Mac, aber weiss nicht mehr, woher genau...)

**Comment by Mojo1917** [comment]
Ups mein Fehler. Hatte gedacht die bezieht sich aufs Design ;)

**Comment by Mojo1917** [comment]
Okay die Funktion uns Auflistung der Sortieroptionen in der Reihenfolge angepasst!

**Comment by McFly753** [comment]
Danke!
