### ISSUE TITLE
Suchfeld 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#247]
Bei "Suche:" würde ich nicht "Suche: " anzeigen, wenn das Suchfeld ausgefüllt ist, sondern dann nur den Filter selbst. Das versteht man denke ich.

**Comment by Mojo1917** [comment]
Okay dann nehme ich es wieder raus ;)

**Comment by Mojo1917** [comment]
Okay ist mit dem nächsten Update wieder entfernt!

**Comment by McFly753** [comment]
Danke! :)
