### ISSUE TITLE
Wirklich überall dynamisch sein...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#249]
... z.B. das Popup "Objketname // Bitte gebe den neuen Objketnamen ein." ist noch statisch.

-> Willst Du hier mal das ganze System durchschsuchen lassen, dass wir hier alles dynamisch haben?
(Hilft uns ja auch bei der Englischen Version)

**Comment by Mojo1917** [comment]
OKay ich schaue nochmal drüber! Lässt sich ja bei mir in den Strings leicht finden.

Nur eine Frage habe ich hier: Wie soll ich mit den Fällen umgehen in denen wir z.B. Artikel verwenden müssen. Wir können diese nicht an das Objekt anpassen. Soll ich diese Fälle statisch lassen?
_"5 von 10 Tags **des** empfangenen **Objektes** konnten auch in deiner Datenbank richtig zugeteilt werden."_

**Comment by McFly753** [comment]
In diesen Fällen bitte dann die Objkete lassen

**Comment by Mojo1917** [comment]
Okay alles klar!

**Comment by Mojo1917** [comment]
Ich habe in ein paar Fällen die individuellen Bezeichnungen nicht übernommen:
- Objekt:
-- Beim Import vor der Datenbankauswahl (Die App kann nicht sicher eine Bezeichnung wählen)
-- Immer wenn von 'Beispielobjekt' gesprochen wird (Wir haben ja immer das gleich Objekt und nicht z.B. einen 'Beispielbaum')
-- In dem Tutorial (Aufgrund der Artikel können wir es nicht immer anpassen. Daher habe ich es um einheitlich zu bleiben hier bei unseren Standartbeschreibungen gelassen.)

- Tags / Attribut / Notizen:
-- Auch diese habe ich in dem Tutorial gleichgelassen. Ich denke das ist einheitlicher. Zudem bezieht sich das Tutorial ja auf alle Datenbanken

Wenn ich die oben genannten Fälle auch anpassen soll kann ich dies gerne machen ;)

**Comment by McFly753** [comment]
Danke!
