### ISSUE TITLE
Stern sinnvoll implementieren...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#25]
... ich muss auf Sterne Filtern können -> lass uns doch einfach die Suche-leiste etwas reduzuieren und wir setzen dahinter den Stern als Filter?

> und dann die Sterne auch auf der Karte anzeiegn (wenn die Objekte als Bildern angezeigt werden)

**Comment by Mojo1917** [comment]
Sollen die Sterne in der Karte eine Funktion haben oder nur angezeigt werden?

**Comment by McFly753** [comment]
Die Sterne sollen nur angezeigt werden. // Wenn das zu aufwendig ist, können wir es erstmal auch weglassen, weil man kann diese Funktion durch Filterung auf einen Stern auch anpassen.

**Comment by Mojo1917** [comment]
Nein ich denke das sollte sich umsetzen lassen.

**Comment by Mojo1917** [comment]
Stern wird jetzt in der Karte angezeigt, wenn die Bilderansicht gewählt ist. Stern Filter wird später mit der Überarbeitung des Designs umgesetzt.

**Comment by McFly753** [comment]
Ok, ich schaue es mir dann nochmals an.
