### ISSUE TITLE
Können wir auch über 12000km Entfernung noch ein paar Unterentfernungen einfügen? Bzw. allgemein mehr Blöcke bilden?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#251]
Was haben wir bis jetzt?

![img_1048](https://user-images.githubusercontent.com/493612/45228347-89986e00-b2f5-11e8-9886-1217103380fd.PNG)

**Comment by Mojo1917** [comment]
Klar! Ich habe noch 15000 und 18000 aufgenommen. Ich denke höhere Werte machen wenig Sinn, da wir ja nicht viel mehr als ca. 20000 haben können, oder liege ich falsch?

Ich kann gerne noch weitere aufnehmen!

**Comment by McFly753** [comment]
Was haben wir denn allgemein jetzt für Abstufungen?

**Comment by Mojo1917** [comment]
Wir hätten dann 10, 30, 50, 100, 500, 1000, 2000, 4000, 8000, 12000, 15000, 18000

**Comment by McFly753** [comment]
OK!

**Comment by McFly753** [comment]
Danke!
