### ISSUE TITLE
Allgemein zur Hilfe, ein paar Anpassungen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#256]
(Das nächste mal lassen wir die Hilfe weg, die kostet uns ja fast mehr Arbeit als die App selbst... :) )

1. Lass uns die Hilfe im Menü: "Hilfe & Tour" nennen. (Nur auf "Hilfe" klicke ich eigentlich nie drauf.)

2. Lass uns die Hilfe doch NIERGENDS zwangsstarten, auch nicht bei der Bildpositionierung.

3. Lass uns den Einführungsscreen trennen:
a) Nenn den Einführungsscreen "Locbase Überblick" und lass den Text so aber setz darunter nur ein OK.

(Und: nimm in den Einstellungen einen Punkt direkt über dem "Tour starten" hinzu und nenne ihn "Überblcik" -> hiermit kann man dieses Popup dann manuell öffnen.)

b) Setz ein weiteres Popup hinter das erste, mit dem Titel: "Einführung"
Und dem Text: Lass dir in einer Tour durch die App die Funktionen von Locbase erklären. Du kannst diese jederzeit unterbrechen.
... dann mit den zwei Buttons vom alten Popup.

4. Nenn das "Tutorial beendet" Popup dann auch "Tour beendet" und im Text dann "rechts oben im Menü" :)

5. In der Tour selbst: Du hast recht, die Buttonveränderunhg ist irritierend.
-> also wir lassen das Weiter immer rechts.
-> aber: wir nennen es nur Weiter (so wie wir links nur Zurück haben)
-> darunter schreiben wir immer: Tour unterbrechen
-> auf der letzten Hilfeseite einer Seite schrreiben wir in den rechten Button wieder: nächste Seite

6. Wenn die Tour über mehrere Seiten geht und abgeschlossen wird (also richtig) - dann würde ich zur Kartenansicht zurückkehren. Ansonsten (wenn irgendwo dazwiscen abgebrocen wird) da bleiben, wo man ist.

7. Ich habe das letzte Objekt gelöscht und dann, wenn er mich nach Abbruch der Hilfe trägt, ob ich ein beispielobjekt anlegen will, stürzte die App ab. (nicht immer)

8. Hilfe beenden in Positionsveränderung geht nicht. (ich werde immer woanders hin navigiert)

9. (Dieser Punkt könnte hinfällig sein, wenn wir die Hilfe nicht merh überall automatsich starten): Wenn ich noch nicht in den Einstellungen war, dann Tags über die Datilseite erstelle, wird mir die Hilfe für die Einstellungen dazwischen geschoben und ich werde nach Hinzufügen von Tags nicht zurück zum Objekt geführt. 

10. Wenn ich ganz normal die komplett Hilfetour am Anfang durchmache, und ich am letzen Screen angekommen bin, zeig rechts dann "Tour beendet" an (weil oftmals kann man ja nicht wirklcih was machen).

11. Uns fehlt noch eine Hilfe auf der Einstellungsseite für Detailansicht der Datenbanken:
Hier kannst du beliebig viele Datenbanken anlegen, benennen und auswählen. Wenn du mehr als eine Datenbank erstellt hast, kannst du schnell zwischen diesen umschalten, indem Du in der Karten/Listenansicht oben auf dem Datenbanknamen rechst-links wischt. Alle Einstellungen wie Benennungen, Objekteigenschaften, Tags oder Vereinfachungen kannst du für jede Datenbank individuell festlegen. 

12. Kannst Du dann noch schauen, dass der "Tour unterbrechen" Link nicht zu nah am weissen Hilfe-Bobbel-Rand steht? Ich habe Dir die entsprechenden Screens hier reingestellt:

**Comment by McFly753** [comment]
![img_1060](https://user-images.githubusercontent.com/493612/45231343-4b537c80-b2fe-11e8-8f00-8433cdeefbf1.PNG)
![img_1061](https://user-images.githubusercontent.com/493612/45231348-4ee70380-b2fe-11e8-98ae-484f412e2087.PNG)
![img_1062](https://user-images.githubusercontent.com/493612/45231375-5d351f80-b2fe-11e8-8d17-fa05f3f83183.PNG)
![img_1063](https://user-images.githubusercontent.com/493612/45231386-61613d00-b2fe-11e8-8cbc-d915394d4045.PNG)
![img_1064](https://user-images.githubusercontent.com/493612/45231390-645c2d80-b2fe-11e8-8ce7-f1a213305121.PNG)
![img_1067](https://user-images.githubusercontent.com/493612/45231395-6920e180-b2fe-11e8-8c5b-c8d18bb77c03.PNG)
![img_1068](https://user-images.githubusercontent.com/493612/45231414-776efd80-b2fe-11e8-84fe-6d365f9fa4ba.PNG)

**Comment by Mojo1917** [comment]
7. okay habe ich gefunden und gefixt ;)
8. behoben
9. Ja fällt jetzt weg!

**Comment by Mojo1917** [comment]
6. und 10. - 12.

**Comment by Mojo1917** [comment]
Wenn ich aktuell eine Seite fertig abgearbeitet habe, jedoch nicht zur nächsten Seite möchte drücke ich 'Tour unterbrechen'. Dies speichert dann den letzten Punkt nicht als 'abgearbeitet'.
Was hälst du davon, wenn wir diese Logik anpassen und die aktuelle Bubble immer als abgearbeitet markieren, wenn der Nutzer 'Tour unterbrechen' wählt? Ich würde es hier nur einheitlich für alle einführen.
Sollte der diese dann nochmals sehen wollen kann er ja einfach wieder starten und 'Zurück' drücken.

**Comment by McFly753** [comment]
Ja, finde ich gut so.

**Comment by Mojo1917** [comment]
Okay binde ich so ein.

**Comment by Mojo1917** [comment]
10-12 sind umgesetzt.
Zu 12: Ich habe alles noch ein kleines Stück nach oben gezogen.

**Comment by McFly753** [comment]
Danke!
