### ISSUE TITLE
Feinoptimierung Hilfe/Tour

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#259]
1. Lass uns auf dem letzten Screen, wo jetzt "Tour beenden" steht, doch wieder "Tour beendet" schreiben und auch (wenn auf dieser Hilfeseite mehr als ein Eintrag existiert) dennoch auch einen Zurückbutton anbieten. 
2. Lass uns hier dann (da mit diesem letzten Screen ja eh die Tour beendet ist) unten als Ausnahme hier das "Tour unterbrechen" ersetzen mit "Tour neu starten".
3. Damit (und somit auch, wenn ich in den Einstellungen bei 100% stehe, und dort auf "Tour neu starten" gehe) würde ich dann aber auch alles wieder zurücksetzen und wieder bei 0% einstarten.
4. Reihenfolge: Felder von der Objekt-Detailansicht in Hilfe anpassen bzgl. ihrer Reihenfolge (Favorit und Attribut liegen noch in alter Reihenfolge drin)

**Comment by Mojo1917** [comment]
Alles umgesetzt. Auch die Anzeigefehler der Karte im Tutorial sind jetzt behoben.

**Comment by McFly753** [comment]
Danke.
Noch ein paar Optimierungen:

1.) Reihenfolge: Auf der Haupotansicht/Rahmen startest Du mit Datenbank, dann gehts Du zu + und dann nach unten zu Karte/Liste:

a) Nimm nach dem Datenbank-Namen und dem + auch hier noch das Menü hinzu: "Über das Menü kannst Du weitere Seiten und Funktionen aufrufen wie z.B. die Statistik öffnen oder Objkete teilen." 

b) den Bobbel der Karte/Liste-UMschaltungs-Erklrärung bitet wieder verkleinern.

c) Bei der Erklörung zu Eigenschaften: reduzier den Bobbel nur auf den Eigenschaften-Button im nicht ausgeklappten bereich

d) Und Sorry, hier lass uns wieder zurück gehen: bei Hilfestart wird das Eigenstchaften-Filter-Feld zugelassen.

e) und mach hier diese Reiehnfolge: Eigenschaften > Favoriten > Suche

f) der Einstellungs-Bobbel bei Ein/Ausbelnden zweigt nur 2 von den 3 Feldern an

g) Hilfe in Bilderansicht: Reihenfolge ändern: Bild-Titel > Menü (löschen) > Metadaten

h) Bei Hilfe in den Unterseiten der Einstellungen (Datenbank, Eigenschaften, Tags, Entfernungsbenachrichtigug, Jahresbenachrichtigung) aber auch bei der Hilfe in der Bilderansicht , wenn ich die Hilfe/Tour dort starte und dann auf "nächste Seite" klicke, wird die Tour beendet. Aber beim zweiten mal wird sie richtig weitergeführt. Nur jewiels (pro Unterseite) geht dies EINMAL nicht!? (alle anderen nicht im Kreis eingeschlossenen "Zusatzhilfeseiten" funktionieren auch beim ersten mal)

i) Wenn ich die Tour komplett zu Ende mache und dann nue starte, startet sie nicht bei 0%, sondern irgendwo bei 64%?

**Comment by Mojo1917** [comment]
Ist umgesetzt.
Die Fehler bekomme ich jetzt auch nicht mehr erzeugt!

**Comment by McFly753** [comment]
Danke, ich habe nur gerade gesehen, dass ich Du noch groß geschrieben hatte, wir es aber ja überall klein schreiben und dass ich "Objekte" falsch geschrieben hatte (aber wird ja eh dynamisch), also: "Über das Menü kannst du weitere Seiten und Funktionen aufrufen wie z.B. die Statistik öffnen oder Objekte teilen."

**Comment by McFly753** [comment]
Danke, nur das geht leider noch nicht:
i) Wenn ich die Tour komplett zu Ende mache und dann nue starte, startet sie nicht bei 0%, sondern irgendwo bei 64%?

**Comment by McFly753** [comment]
Das tritt bei mir iegntcluh immer auf - dachte es wäre nur bei einem Fenster, aber bei mir trat es von 3 Tests alle 3mal auf.

**Comment by Mojo1917** [comment]
Okay ich denke ich habe verstanden wo der Fehler ist. Aktuell ist es wie folgt implementiert:
1. Wenn die Tour zu Ende ist und der Nutzer auf einen der 'Tour neu starten' Buttons drückt (in den Einstellungen oder in der letzten Blase) wird die gesamte Tour zurückgesetzt.
2. Wenn der Nutzer die Tour abgeschlossen hat und über das Menü erneut 'Hilfe & Tour' auswählt wird nur die Tour in dem aktuellen Fenster zurückgesetzt. Ich habe dies so eingebunden, damit der Nutzer nicht alles erneut machen 'muss'.

Ist das der Fehler, den du beschreibst? Wenn ja, soll ich es so anpassen, dass der Button 'Hilfe & Tour' im Menü immer die gesamte Tour zurücksetzt, wenn diese abgeschlossen ist?

**Comment by McFly753** [comment]
Ja, würde in meinen Augen mehr Sinn machen. Danke!

**Comment by Mojo1917** [comment]
Okay, die Logik ist angepasst. Folgt mit einem späteren Update!

**Comment by McFly753** [comment]
Danke!
