### ISSUE TITLE
Gelegentlich: App-Absturz, wenn ich schnell durch Hilfe-Seiten mit Weiter klicke.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#260]
hab noch keine LOgik gefunden, ist mir aber bisher 3 mal passiert

**Comment by Mojo1917** [comment]
Okay ich warte hier auf die Crashreports ;) Die helfen bestimmt!

**Comment by McFly753** [comment]
Ich habe es gerade nur einmal beim Ipdad geschafft, da hatte ich die App neu instelliert und er hat es nichtmal zuer ersten Hilfeseite geschafft. Auf dem Iphoen (wo ich die App nur geupdatet hatte) und ich die Hiolfe schonmal ganz durch war, habe ich einen Absturz nicht geschafft.

**Comment by Mojo1917** [comment]
Okay. Der Fehler war leider in dem von dir getesteten Update auch noch nicht angefangen. In der aktuellsten Version von heute Abend dürfte er nicht mehr auftreten. Sorry war mit den beiden Updates leider etwas unübersichtlich.
Ich schaue zur Sicherheit morgen nochmal in den Crashreport, damit ich nicht doch etwas übersehen habe.

**Comment by McFly753** [comment]
Sollte gehen, Danke!
