### ISSUE TITLE
iMessage?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#261]
Was könngte man hier anbieten?

![img_1172](https://user-images.githubusercontent.com/493612/45587149-69d7fa00-b934-11e8-9a93-9422216d5cea.PNG)

**Comment by Mojo1917** [comment]
Hier könnten wie eine Erweiterung für die iMessage App  einbinden. Siehe der Screenshot. Damit sollen bestimmt Teile einer App besonders schnell mit anderen Nutzer geteilt werden können.
Wir könnten uns überlegen eine Erweiterung für das Teilen hier einzubinden. Ich bin mir jedoch nicht sicher ob sich der Aufwand dafür lohnt ;)
![img_0544](https://user-images.githubusercontent.com/20678932/45587193-cae6da00-b902-11e8-90f3-884ebb05496a.jpg)

**Comment by McFly753** [comment]
Nein, brauchen wir nicht, Danke!
