### ISSUE TITLE
Leichter Anzeigefehler

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#262]
manchmal rutscht mir die oberste Zeile noch zu hoch. 
(Weiss nicht nicht genau, wann.)

![img_1173](https://user-images.githubusercontent.com/493612/45587159-92f88a80-b934-11e8-8d9d-7729a845fcd2.PNG)

**Comment by Mojo1917** [comment]
Der Fehler sollte jetzt nicht mehr auftreten!

**Comment by McFly753** [comment]
Passiert immer, wenn ich in dr Liste bin und auf Staistik gehe und dort auf ein Land filtere.

**Comment by Mojo1917** [comment]
Okay habe es in der neuesten Version von heute 0.9.267 (44) getestet und bekomme den Fehler nicht erzeugt. Sollte hoffentlich bei dir auch der Fall sein ;)

**Comment by McFly753** [comment]
Danke!
