### ISSUE TITLE
In den ersten Minuten der App hatte ich den Fehler, dass ich alle Location-Basierten Dienste nutzen kann, mir aber immer diese Info angezeigt wurde.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#263]
![img_1177](https://user-images.githubusercontent.com/493612/45587175-d3f09f00-b934-11e8-87ad-2bb6e6d964fc.PNG)

**Comment by McFly753** [comment]
![img_1182](https://user-images.githubusercontent.com/493612/45587197-28941a00-b935-11e8-9ae7-5c4723b0f2ba.PNG)

**Comment by Mojo1917** [comment]
Wenn die Liste geöffnet wird jedoch noch keine Position verfügbar ist wird dieser Hinweis angezeigt. DieIe App hat zu diesem Zeitpunkt alle Berechtigungen und wartet nur auf das System. Diese Anzeige wird dann alle paar Sekunden aktualisiert, bis die App auf einen Standort zugreifen kann. Dann sollte diese Anzeige verschwinden. Ich senke aber zusätzlich nochmal die Wiederholzeit der Abfragen.

**Comment by McFly753** [comment]
Ok, ich probiere es nochmals, ich war auch im Gebäude. Lass die Frequenz erstmal so, weil sonst schrauben wir nur dem Batterie-Verbrauch hoch.

**Comment by McFly753** [comment]
hmmm... ich schliesse mal - hatte es gestern ein paar Stunden lang, jezt geht es aber.
