### ISSUE TITLE
Kleine Orte werden nicht mehr gefunden - geht das nicht anders?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#264]
![img_1178](https://user-images.githubusercontent.com/493612/45587180-e8349c00-b934-11e8-9119-7917692aea03.PNG)
![img_1179](https://user-images.githubusercontent.com/493612/45587181-e8349c00-b934-11e8-862a-8cc9a483ce85.PNG)

**Comment by Mojo1917** [comment]
Also die Suche sollte auf jeden Fall Ergebnisse liefern. Auf meinem Gerät lassen sich auch kleine Orte finden. Klappt es auch nicht, wenn du Deutschland dahinter eingibst?

**Comment by McFly753** [comment]
Hm, also es hat nichts mit groß/klein zu zun, sondern mit bekannt unbekannt.

Such z.B. mal nach "Ko Lanta" - wirst Du nicht finden. Aber "Ko Lanta, Thailand" findest Du.
Aber: "Ko Phi Phi" findest Du so, obwohl es kleiner als Ko Lanta ist, aber eben bekannter.

**Comment by Mojo1917** [comment]
Ja ist sehe was du meinst. Ich schaue mal, ob wir einen anderen Dienst von Apple ansteuern können.

**Comment by McFly753** [comment]
Ok, lassen wir so. danke!
