### ISSUE TITLE
Ansichtsänderung in Listenansicht

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#27]
Lass uns unter den Titel in der kompletten Zeile die Objekteigenschaften anzeigen und direkt hinter den Titel den ersten Teil des Textes. (Und gib dem Titekl mind. Platz (ausgeschrieben) solange wie der Orts-Kasten darunter ist
Das schaut besser aus und ist sinnvoller.

**Comment by Mojo1917** [comment]
Okay ist übernommen. Dem Screenshot kannst du durch die Farben markiert das Verhalten der beiden Felder zueinander sehen. Ist es so wie du es gewollt hast?

![foto 15 01 18 13 11 21](https://user-images.githubusercontent.com/20678932/34925574-efd05610-f9f5-11e7-9cf7-31d8d61c3d66.png)

**Comment by McFly753** [comment]
Passt so, willst Du mir im nächsten Update bitte nur mal das Anmerkungstextfeld und die Eingenschaftszeile vertauschen. Weil die Notiz ist zu unwichtig, als dass sie so präsent neben dem Titel steht.

**Comment by Mojo1917** [comment]
Okay Felder sind vertauscht. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke aber Sorry: Mittlerweile würde ich hier wieder zurückkehen, aber: folegndes machen:

(Lass uns noch ein einfaches Textfeld mit hinzunehemn, also ein Eigenschaftenfeld, das einfach ein kurzes Freitextfeld ist (ich will es nicht mit den Notizen mischen). 
> Es wäre also super, wenn Du das implementieren könntest in der Datenbank, dann optisch direkt als eine Zeile unter die Tags und über die Notizen setzen und dann auch in der Suche miteinbeziehen.

**Comment by Mojo1917** [comment]
Also sozusagen ein zweites Notizenfeld, das aber in der Suche verwendet wird?

**Comment by McFly753** [comment]
Genau, Sorry für den späten Nachtrag.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke: Nur das Feld hat bei mir optsich so ne komishce Outline...

- Und schreib hier in grau dies rein: "Eigenschaften"
- Und unten in das Notizfeld in grau: "Notizen"

**Comment by Mojo1917** [comment]
Okay Rahmen ist entfernt und die Placeholder bearbeitet.
Änderung kommt mit dem nächsten Update.
