### ISSUE TITLE
"Halber" Delete-Bereich tritt doch noch manchmal auf...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#270]
... aber ich kann ihn dann, wenn ich es soll, nicht reproduzieren... ;)

![img_1199](https://user-images.githubusercontent.com/493612/45587416-af49f680-b937-11e8-8677-0eb3106a2a76.PNG)

**Comment by McFly753** [comment]
Und: was unschön ist, wenn ich die Liste "überziehe", schaut manchmal das Delete hervor. Kannst Du diese Deletes sperren, sobald vertikal gezogen wird?

**Comment by McFly753** [comment]
![img_1509](https://user-images.githubusercontent.com/493612/45840288-d0835c00-bd16-11e8-8fcf-a56103d7fa1b.PNG)

**Comment by Mojo1917** [comment]
Okay ich denke das sollte sich abfangen lassen.

**Comment by McFly753** [comment]
Danke!
