### ISSUE TITLE
Suche-Bug, wenn ich dann die Statistik nutze.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#272]
Wenn ich z.B. in der Filter-Suche "München" stehen habe, dann aber ein Land, z.B. Australien in der Statistik anklicke, kommt die Suche irgendwie total durcheinander. Er schreibt mir dann irgendeine andere Stadt in das Suchfeld. 

In dem Fall von "Australien" dann Abu Dhabi (hatte ein Objekt mit dem Ort).

**Comment by Mojo1917** [comment]
Okay ist gefixt ;)

**Comment by McFly753** [comment]
Danke!
