### ISSUE TITLE
Overlay-Anzeige des Sortierbutton noch etwas fine-tunen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#273]
Bitte mache dieses Overlay in dem Style wie das Lautstärke Ändern vom Iphone, dann nur ca. „einen halben Zentimeter“ ;) Rand um den Text und setze ihn bitte zentriert auf ca. 1/5 von unten auf die Linke Seite (hier horizontal zentriert auf die 2/3 linke Fläche) 

Siehe wegen Position und Größe das Bild (nur angedeutet, natürlcih runde Ecken und in dieser Grau-Milchglas-Art, wenn einfach möglich.)

**Comment by Mojo1917** [comment]
Bin mir jetzt nicht ganz sicher, ob ich das mit der Positionierung richtig verstanden habe... Hast du es so gemeint? Könnte für Linkshänder doof werde, da man mit dem Daumen die Box verdeckt.
![img_0547](https://user-images.githubusercontent.com/20678932/45587914-a8f25500-b90c-11e8-9f84-ef60bdddb3cd.png)

**Comment by Mojo1917** [comment]
Die Box muss natürlich noch schmaler.

**Comment by McFly753** [comment]
Hm, die Linkshändersache hatte ich nicht bedacht... abe wir haben die ganze App auf rechtshänder angelegt...
Aber denkst Du, dass hier auch ein Linkshänder nicht mit der rechten Hand diesn Button bedienen würde? (Ich kann mal meine schwester fragen)

Lass ihn ujns doch mal so probieren.

Und hierzu noch eine Bitte: wie schnell ist der Prozessor? Können wir bei jeder Option, auch wenn ncoh nicht losgelassen, in Echtzeit umsortieren?

**Comment by Mojo1917** [comment]
Ja ich denke wir können in Echtzeit neu sortieren. Das sollte kein Problem darstellen.

Zu der Linkshändersache: Ich denke die App ist einwandfrei zu verwenden. Ich hatte mich hier nur auf die neue Position des Anzeigefensters bezogen. Diese liegt genau unter dem Finger, sobald man zum sortieren die links hand verwendet ;)

**Comment by McFly753** [comment]
Ok, ich habe mich auch darauf bezogen... :) - lass es uns da mal ausprobieren, dann sehen wir weiter.
Danke! LG, Matthias

**Comment by Mojo1917** [comment]
Okay alles klar :D Auf dem iPad habe ich den Dialog vorerst in der Mitte gelassen. Er liegt sonst so weit am Rand und fällt möglicherweise nicht auf. Kann ich aber auch gerne an das iPad anpassen.

**Comment by McFly753** [comment]
Danke, mach den Kasten bitet nur noch kleiner, siehe Bild:

![img_1506](https://user-images.githubusercontent.com/493612/45839790-a5e4d380-bd15-11e8-8578-0dfb3f70ea22.PNG)

**Comment by Mojo1917** [comment]
Okay ist angepasst. Wir können ihn jedoch in der Breite nicht viel kleiner machen, da dann 'Erstellungsdatum' nicht mehr drauf passt ;)

**Comment by McFly753** [comment]
UND: Du hattest doch recht: nachdem Du den Button angepasst hast, setze ihn doch wieder zentriert auf den Screen

**Comment by Mojo1917** [comment]
Okay

**Comment by McFly753** [comment]
Danke!
