### ISSUE TITLE
(Für meinen Schwager): 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#274]
1.) Max. Zoomstufe der Karte?
2.) Eigene Karte/Bild in Karte als Overlay möglich (manuell an der richtigen Position "verankert")? 
3.) Positionspunkt verkleinern und ohne dem großen "Pumpen" darstellbar?

**Comment by Mojo1917** [comment]
Lieber Matthias, 
leider habe ich keine Möglichkeit gefunden in dem MapKit von Apple dem maximalen Zoom zu erhöhen. Ich denke jedoch eine Möglichkeit für custom overlays und eine Modifizierung der Positionsanzeige gefunden zu haben. Dies müsste sich jedoch noch in der Praxis bewahrheiten ;)
Liebe Grüße,
Niklas

**Comment by McFly753** [comment]
Ok, Danke! 
Wichtig wäre aber als Grundlage der maximale Zoom. Gänge es einen anderen Ansatz hierfür?
Danke! LG, Matthias

**Comment by Mojo1917** [comment]
Schaue ich mir morgen an!

**Comment by McFly753** [comment]
Danke, schliesse ich hiermit.
