### ISSUE TITLE
(Wenn Du willst, kannst Du, wenn man die Einstellunbgen nach oben überzieht, unten das Locbaselogo mit der Copyright-Zeile einblenden... Ohne dass was passiert.)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#275]

**Comment by Mojo1917** [comment]
Habe es jetzt vergeblich versucht einzuprogrammieren. Aus irgendeinem Grund verrutscht dann jedes mal alles und die letzten Zeilen werden 'verschluckt'.
Könnte auch ein Fehler in meiner Entwicklungsumgebung sein. Diese wurde heute von Apple um iOS 12 erweitert und spinnt seit dem Update leider ein wenig. Sollte Apple hier einen Fix veröffentlichen werde ich es nochmal versuchen!

**Comment by McFly753** [comment]
Ok, ist auch nocht so wichtig - können wir auch erstmal sein lassen, ich schliesse das Ticket.
