### ISSUE TITLE
Objektansicht - Bereich rechts oben für iPhone 5 / 5s / SE optimieren.

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#276]

**Comment by Mojo1917** [comment]
Anbei die Screenshots von einem 5s mit der angepassten Ansicht. Wir haben hier leider sehr viel weniger Platz. Daher muss vieles hier enger sitzen ;)

**Comment by Mojo1917** [comment]
![img_0557](https://user-images.githubusercontent.com/20678932/45773694-3a363400-bc4b-11e8-8a09-306e72adf98d.png)
![img_0558](https://user-images.githubusercontent.com/20678932/45773695-3aceca80-bc4b-11e8-9486-fdd626efbf8f.png)

**Comment by McFly753** [comment]
Danke, aber:

1.) Bitte "deutsche" Datumsansicht, also mit Punkten, nicht /

2.) Ändere hier die Syntax und schreibe es so:
- lass alles in der kleinen Schriftart, auch die Daten selbst und schreibe dann:

Erstellt am 23.01.18
Letzter Besuch vor
23 Tagen am 22.91.17

psst das hin?

**Comment by Mojo1917** [comment]
Denke das sollte passen! Ich setzte es um und stelle dann nochmal die Fotos rein ;)

**Comment by Mojo1917** [comment]
Klaro das Format ist immer das auf dem Handy eingestellte ;)

**Comment by Mojo1917** [comment]
Leider hat es nicht hingepasst. Ich habe das Format angepasst. Wir haben jetzt zwei Umbrüche mehr. Hatte kurz überlegt einfach die Schriftart kleiner zu stellen, aber dann kann man nichts mehr lesen.
![img_0565](https://user-images.githubusercontent.com/20678932/45918415-edd73800-be86-11e8-80af-c837f86eff7d.png)
![img_0566](https://user-images.githubusercontent.com/20678932/45918416-edd73800-be86-11e8-884c-5b074709d519.png)

**Comment by McFly753** [comment]
Alles klar, passt. 

Schau in Deinem Screenshot oben nur die Enferungskarte über der Karet an, da passt die Schriftgröße nicht... ;)

**Comment by McFly753** [comment]
OK!

**Comment by McFly753** [comment]
muss ich mir erst auf meinem alten Hadny runterladen

**Comment by McFly753** [comment]
Danke!
