### ISSUE TITLE
Bitte den sensitiven Bereich oben bei dem Datenbank-Name (zum rechts-links swipen) erweitern...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#277]
... alos dass ich auch etwas links oder rechts davon mit dem Wischen starten kann.

![img_1507](https://user-images.githubusercontent.com/493612/45840243-afbb0680-bd16-11e8-8f38-bfd6cb1f2778.PNG)

**Comment by Mojo1917** [comment]
Okay der Bereich wird jetzt so weit vergrößert wie möglich!

**Comment by Mojo1917** [comment]
![simulator screen shot - iphone x - 2018-09-21 at 16 33 17](https://user-images.githubusercontent.com/20678932/45887466-10504f00-bdbc-11e8-9a9f-d1fb87787109.png)

**Comment by McFly753** [comment]
Machs nicht zu groß, weil denke auch an das rote "!", das links noch hinpassen muss (und bedienbar bleiben muss)

**Comment by Mojo1917** [comment]
Klaro das passt noch hin ;)

**Comment by McFly753** [comment]
Danke!
