### ISSUE TITLE
Zeig auch bei 0 Objekten diese Anzeige der Objekte (0 Objekte von 0) unter dem Datenbanknamen an.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#278]
![img_1508](https://user-images.githubusercontent.com/493612/45840351-06284500-bd17-11e8-8849-d5a983878716.PNG)

**Comment by Mojo1917** [comment]
Wird bereits angezeigt. Nur nicht, während des Datenbankwechsels. Sollen wir es auch dann dort anzeigen?

**Comment by McFly753** [comment]
Nein, da brauchen wir es nicht, alles klar!
