### ISSUE TITLE
Ortsbereich verrutscht bei Hilfe/Tour

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#279]
![img_1512](https://user-images.githubusercontent.com/493612/45840385-1fc98c80-bd17-11e8-94cf-ff8f04ed6b4f.PNG)

**Comment by Mojo1917** [comment]
Ist in der aktuellsten Version, die heute Abend freigeschaltet wurde, schon gefixt :)

**Comment by McFly753** [comment]
Danke!
