### ISSUE TITLE
Änderung Reihenfolge in Sortierung in Listenansicht

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#28]
lass uns diese Reihenfolge nehemn, sie ist sinnvoller, weil darunter diese Angaben von der horizontalen Höhe auch mehr dort stehen:

Erstellungsdatum > Entfernung > Häufigkeint > letzter Besuch

**Comment by Mojo1917** [comment]
Ist übernommen. Sollen wir diese Reihenfolge auch in der Karte nutzen? Dann ist es vielleicht einheitlicher.

**Comment by McFly753** [comment]
Ja

**Comment by Mojo1917** [comment]
Okay ist eingebaut.
Kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
danke, schau ich dann an.
