### ISSUE TITLE
Sollten wir den Sortierungsbutton bei der Kartenansicht mit Bildern verhindern oder lassen?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#280]
Was denkst Du? Wenn verhindern, dann nur ausgrauen und inaktiv machen oder reinschreiben "im Bildmodus nicht möglich" o.ä.?

**Comment by Mojo1917** [comment]
Ja ich denke das macht Sinn. In der Liste bzw. in der Daten-Ansicht wird er dann je entsprechend wieder freigegeben.
Ich denke das sinnvollste wäre ihn leicht transparent zu setzen? Dann ist er sichtbar und seine Funktion ist dennoch gleich erkennbar.

**Comment by McFly753** [comment]
Ok, nur was steht dann da drin? Oder bleibt das drin stehen, auf dem der Button stand?

**Comment by McFly753** [comment]
Danke!
