### ISSUE TITLE
aufgeklappte Eingenschaften-Filterung immer zumachen, wenn der User woanders hingeht...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#282]
... alos auch, wenn er sich ein Objekt anzeigt, den Sortierungsbutton verwendet, den Favoritenbutton verwnedet, die suche verwendet

also wenn er irgendwas macht, ausser die Filter in disem Aufklappbereich zu setzen oder ent-setzen oder wenn er scrollt.

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Leider wird es schwer die bei Interaktion it allen Unterelementen von Karte und Liste zu tun. Die von dir genannten sich jedoch alle umgesetzt.

**Comment by McFly753** [comment]
Danke!
