### ISSUE TITLE
Sollten wir nicht auch die kleinen Koordinaten noch klcikbar machen, um eine Ortsänderung zu starten? Oder ist es zu mickrig?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#283]

**Comment by Mojo1917** [comment]
Ich denke diese sind zu klein. Zumal man oftmals die Karte treffen wird und dann eine andere Aktion auslöst. Dennoch kann ich sie gerne belegen ;)

**Comment by McFly753** [comment]
Was ist, wenn wir sie belegen - wir müssen es ja keinem sagen... :)

**Comment by Mojo1917** [comment]
Hast Recht! Wird gemacht

**Comment by McFly753** [comment]
Sind aber nicht belegt?

**Comment by Mojo1917** [comment]
Sorry mein Fehler. Hatte dies zu Testen deaktiviert und wieder aktiviert. Ist jetzt auf jeden Fall klickbar, wenn auch schwer zu treffen.

**Comment by McFly753** [comment]
Danke!
