### ISSUE TITLE
Datenbank Umschalt Overlay 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#285]
Lass uns beim Datenbank umschalten auch zentriert ein Overlay anziegen, Kastengröße ähnlich des (geänderten) Sortier-Overlays und dann auch zerntriert auf den Screen.

(Weil so verdekce ich mit meinem Finger immer den Namen der Datenbank... ;) )

**Comment by McFly753** [comment]
Danke! (Aber hier und auch beim Sortierbutton): kannst Du das Overlay dann wirklcih vertikal zentieren?

**Comment by Mojo1917** [comment]
Klar.

**Comment by McFly753** [comment]
Danke!
