### ISSUE TITLE
Sortierbutton ... 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#286]
Lieber Niklas, 
ich habe gerade gesehen, dass wir ein Bedienungsproblem beim Sortierungsbutton haben. Und zwar: sagen wir, er steht auf Entfernung (also das oberste) - dann kann ich nicht ganz nach unten zum Erstellungsdatum kommen, weil ich dann über den Handyrand hinausscrllen müsste.

Vorschalg: Du "schaltest" (beim ersten nach oben wischen) den Button ca. gefühlt ersn "1 cm" weiter oben an, dann reicht mir auch der Weg bis nach unten.

Und: erweitere die sensitive Fläche über dem Button etwas, gerne etwas in ddi Suche rein, dann ist er leichter zu "treffen. :)

Danke! LG, Matthias

**Comment by Mojo1917** [comment]
Lieber Matthias,

ich bin mir nicht ganz sicher, ob ich das richtig verstanden habe: Also, wenn der Nutzer das erste Mal wischt ignorieren wir sozusagen den ersten cm? Bzw. So viel, dass es reicht um beim nach unten wischen alles zu erreichen, richtig?
Optional könnten wir und auch überlegen wieder zu erlauben, dass der Nutzer die Sortieroptionen wie in einem Kreis durchlaufen kann. Sprich nach Entfernung gehts wieder zum ersten.

Den Sensitiven Bereich kann ich gerne erweitern.

**Comment by McFly753** [comment]
Ja, zur Zeit ist es so, dass ich ca. "1cm" nach hoben wischen muss, bis der Button erscheint - wenn wir diesen Weg etwas länger machen, reicht er mir auch wieder fürs Runterstreichen, ohne dass ich über die Bildschirmkante hinaus müsste. Danke!

**Comment by Mojo1917** [comment]
Okay sollte der Button auf der letzten Sortierung stehen muss zur Aktivierung mindestens so weit nach oben Gestrichen werden, dass der Weg bis nach ganz unten für das Umschalten zwischen allen reicht.

**Comment by McFly753** [comment]
Genau!

**Comment by McFly753** [comment]
Wir müsseten ihn doch wieder so machen, wie er war - so versteht man ihn nicht. Dann evtl. doch mit Kreis und so wie von Dir angesprochen.

**Comment by Mojo1917** [comment]
Okay ist angepasst.

**Comment by McFly753** [comment]
Danke!
