### ISSUE TITLE
Beim 5er Iphone: 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#289]
- bitte nur Klicks, kein Vibrieren verwenden.
- und kannst Du selbst die Klicks hier weglassen bei dem Listen/Karte umschalten?

- Und: (kann aber auch an meiner Iphone-5-Einstellung liegen): alle Buttons mit Text (z.B. Datenbank oder Eigenschfaten) sind als Links unterstrichen?

**Comment by Mojo1917** [comment]
zu 1: Okay. Sollen wir denn z.B. bei dem Sortierungsbutton das Vibrieren zulassen, wenn der Nutzer wieder 'zurückspringt'?

zu 2: Klar das Feedback wird hier unterbunden.

zu 3: Das liegt an der Einstellung von Bedienungshilfen > Tastenformen

**Comment by McFly753** [comment]
zu 1. lass beim 5er das Vibireren komplet weg, weil das its einfach zu lang.
2&3: ok

**Comment by Mojo1917** [comment]
Okay das vibrieren ist komplett abgeschaltet.

**Comment by McFly753** [comment]
Danke!
