### ISSUE TITLE
Farbsortierung bei der Kartenansicht über Entfernung nicht möglich?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#29]
> Statt "keine" hier Entfernung

**Comment by Mojo1917** [comment]
Ist implementiert. Kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
danke, schau ich dann an.

**Comment by McFly753** [comment]
Prinzipiell zur Karte: ich kann die Sortierungen nicht wirklcih testen, weil die Karte immer komplett rausspringt. 
>
Kannst Du versuchen, dass Du (bei Neusetzung irgendeines Filters) in der Kartenansicht immer zwar soweit rasuzoomst, dass ich alle Bilder des Filters sehen kann, aber eben nur soweit, dass sie mir auch noch an den Rändern der Karte sind und nicht alle als ein Punkt in der Mitte. Also in der richtigen Balance?
Und, wenn der Filter nicht geändert wird (sondern nur eine Sortierung), dann die Zoom-Größe gar nicht verändert wird?

**Comment by Mojo1917** [comment]
Okay ist alles übernommen. Die Karte zoom jetzt auf alle sichtbaren Objekte, wenn sich diese verändern. Bei einer Änderung zwischen Daten<->Bilder und bei einer neuen Sortierung passiert nichts.

**Comment by Mojo1917** [comment]
Änderung kommt mit dem nächsten Update.
