### ISSUE TITLE
Manchmal verrutscht noch die Suche-Zeile

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#290]
![img_1714](https://user-images.githubusercontent.com/493612/46113230-cd441080-c1ed-11e8-8495-8ce5d23bf740.PNG)

**Comment by Mojo1917** [comment]
Okay ich habe mir hierzu den Code nochmals angeschaut. Wir bekommen von iOS eine genaue Position, an welcher das Keyboard beginnt und legen unser Textfeld genau so, dass es an diesem Punkt aufhört. Sollte das Keyboard höher rutschen liegt dies an einer fehlerhaften Info, die von iOS übermittelt wird.
Tritt dieses Problem nur einmal auf und nach einem erneuten öffnen des Suchfelds nicht mehr? Oder immer?

**Comment by McFly753** [comment]
Lieber Niklas, das tritt ab und zu (ganz selten) mal auf und ich konnte keine Logik darin erkennen oder es reproduzieren. // Lass uns das einfach mal schliessen, wenn es nochmals auftritt, komme ich auf Dich zurück. (wir müssen langsam zu unseren anderen Apps kommen... :=) )

**Comment by Mojo1917** [comment]
Okay ;)
