### ISSUE TITLE
Lass uns bitte noch die Datenbank-Einstellungs-Seite optimieren

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#292]
Dass sie didaktisch einfacher wird:

1. oben im Titel nur "Datenbank" scheriebn, wenn es nur eine Datenbank gibt, sonst "Datenbanken".

2. mach rechts keine Radiobuttons hin, sondern diese Reihenfolgen-Icons (wie bei Eigenschaften oder Tabs)
- hier sollte man die Reihenfolge verändern können
- wenn man auf dieses Reihenfolgentab klickt, dann wird die Datenbank ausgeählt. Dann wüde ich sie blau highlighten.

3. unter den Namen der Dstenbank würde ich in kleiner Schrift schreiben: 8 Objekte / 12 Bilder / 34MB

4. wenn man hier drauf klickt, wähle ich auch diese Datenbank als aktuelle aus.

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Aufgrund der Datenbankanpassung bezüglich der Umsortierung wird beim nächsten Update ein Deinstallieren verlangt.

**Comment by McFly753** [comment]
Danke, eine Feinheit:  mach die 1 Objekt / 2 Bilder / 1 MB Leiste rechtsbündig zum Datenbanknamen-Feld oben, dürfte schöner aussehen

**Comment by McFly753** [comment]
Danke! Und noch eine Kleinigkeit: wenn ich return drück, nimm den Coursor aus dem Feld... ;)

**Comment by Mojo1917** [comment]
Okay!

**Comment by McFly753** [comment]
Danke
