### ISSUE TITLE
Sollten wir die Bilderansicht nicht dann auch genauso durch Runterziehen schliessen lassen, wie alle anderen Seiten?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#293]

**Comment by Mojo1917** [comment]
Eigentlich schon. Habe versucht es zu implementieren. Leider entsteht hier der Fehler, dass wir die Ansicht, die sich beim nach unten ziehen zeigt, nur für die erste 'Seite' festlegen können. iOS verschiebt diese, auch wenn wir sie manuell verschieben, immer wieder hierhin zurück. Sollte der Nutzer somit auf einer anderen Seite nach unten ziehen sieht er nur einen schwarzen Bereich. Die Funktionalität bleibt jedoch erhalten.

Ich habe daher versucht diese Ansicht so gut es geht nachzubilden und in den Hintergrund der 'CollectionView' zu legen in der wir die Bilder präsentieren. Das Ergebnis sieht wie folgt aus. Leider lässt sich 'der sich füllende' Kreis nicht nachbilden. Ich hoffe das passt so.

Ansicht bei der normalen Implementierung
![img_0571](https://user-images.githubusercontent.com/20678932/46632234-3743aa80-cb4a-11e8-96f3-03ac3ad26c80.png)
Neue Ansicht beim ziehen
![img_0573](https://user-images.githubusercontent.com/20678932/46632235-37dc4100-cb4a-11e8-86a8-bf06a3c01ce0.png)
Neue Ansicht kurz vor dem schließen.
![img_0574](https://user-images.githubusercontent.com/20678932/46632236-37dc4100-cb4a-11e8-8349-11fe5220b67b.png)

**Comment by McFly753** [comment]
Danke, lassen wir so.
