### ISSUE TITLE
leichter Anzeigefehler bei Hilfe

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#295]
> der Kreis überschneidet sich jetzt leichgt mit der Prozentanzeige
![img_2414](https://user-images.githubusercontent.com/493612/46781430-9fed7b80-cd32-11e8-8295-3110977013fe.PNG)
![Uploading IMG_2413.PNG…]()
![Uploading IMG_2412.PNG…]()
![Uploading IMG_2411.PNG…]()

**Comment by Mojo1917** [comment]
Okay um das zu umgehen habe ich die Anzeige rechts neben den Balken gezogen und diesen leicht verkürzt.

**Comment by McFly753** [comment]
Danke
