### ISSUE TITLE
Was denkst Du: sollten wir auf der Karte nicht die Bezeichnungen für Map/Sat und Daten/Bilder umdrehen? Also dass das angezeigt wird, was man auch gerade sieht?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#296]
![img_2415](https://user-images.githubusercontent.com/493612/46781462-d5926480-cd32-11e8-9ddf-ef7f19f19d1a.PNG)

**Comment by Mojo1917** [comment]
Ich bin mir ehrlich gesagt nicht sicher was logischer ist. Einerseits zeigen wir dem Nutzer so, was für Funktionen noch verfügbar sind aber andererseits erzählen wir ihm dies auch in dem Tutorial.

Vielleicht Verallgemeinern wir auch einfach die Texte? Leider fällt mir hierzu nur kein Wort ein, dass entsprechend kurz wäre.

Ich ändere es mal für das nächste Update. Das lässt sich ja sehr einfach wieder ändern.

**Comment by Mojo1917** [comment]
PS: Nein ich denke dein Vorschlag macht mehr Sinn. So ist dem Nutzer leichter klar auf was sich der Butten bezieht. 'Bilder' lässt sich ggf. nicht direkt auf die Blauen Punkte in der Karte beziehen.

**Comment by McFly753** [comment]
Passt!
