### ISSUE TITLE
Wie können wir hier auf dem iPhone auch einen eigenen "Ordner" bekommen? ;)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#297]
![img_2417](https://user-images.githubusercontent.com/493612/46781576-50f41600-cd33-11e8-901e-de582df2737b.PNG)

**Comment by Mojo1917** [comment]
Ja das bekommen wir hin. Dafür müssen wir das App-Verzeichnis für File-Provider freigeben. Aktuell liegen hier jedoch die Datenbanken und die Bilder. Ich werde Sie an einen anderen Platz im iOS System legen und den Ordner dann freigeben.

**Comment by Mojo1917** [comment]
Hierdurch werden jedoch alle Datenbanken erneut gelöscht ;) Aber es sind ja noch keine 'Live-Daten' in der App, richtig? Dann muss ich diese nicht migrieren? Wenn du dann die Files-App öffnest kann auf all diese 'alten' Dateien zugegriffen werden. Die angezeigten Ordner können jedoch einfach gelöscht werden oder durch eine App-Neuinstallation entfernt werden. Danach werden Sie nicht wieder erzeugt und die Daten in Zukunft vor dem Nutzer verborgen.

**Comment by McFly753** [comment]
Ja, kein Problem!

**Comment by Mojo1917** [comment]
Okay binde ich so ein ;)

**Comment by Mojo1917** [comment]
Okay die Dateien werden jetzt wie von Apple angegeben in dem Unterverzeichnis '/Library' der App gespeichert. Hier wurden zwei Unterverzeichnisse angelegt '/images' und '/database' in denen die entsprechenden Dateien liegen. Diese sollten wie hier in Tabelle 1-1 (https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/FileSystemOverview/FileSystemOverview.html#//apple_ref/doc/uid/TP40010672-CH2-SW2) beschrieben wie bisher auch über das iCloud und iTunes Backup gesichert werden.
Damit kann der User auf diese Dateien nicht durch das freigeben des Unterverzeichnisses nicht mehr hierauf zugreifen. 

Damit wird jetzt das App-Verzeichnis jetzt auch zum Speichern von Dateien angezeigt. Sobald hier eine Datei gespeichert wurde kann das Verzeichnis auch über die Files-App angesteuert werden.

**Comment by McFly753** [comment]
cool, Danke! ;)
