### ISSUE TITLE
Schreiben wir noch "Okay" oder nur "Ok" oder "OK"? - wir sind hier mal einheitlich geworden, oder?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#298]
![img_2418](https://user-images.githubusercontent.com/493612/46781602-708b3e80-cd33-11e8-8f45-c76e782882a9.PNG)

**Comment by Mojo1917** [comment]
Mein Fehler... Scheint durchgerutscht zu sein. Alles ist jetzt durch 'OK' ersetzt.

**Comment by McFly753** [comment]
Danke!
