### ISSUE TITLE
Kartenbug - Objektgruppierung

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#3]
Wie schon geschrieben, die Gruppierung gruppiert viel zu früh.

> ich würde diese wirklich nur gruppeioren lassen, wenn es technisch wegen der Performance nötig wird, dabro noch gar nicht.

> notfalls lassen wir die Gruppierung einfach weg und ich komme auf Dich zu, wenn wir mal ein Problem wegen zu vielen Objeketn kommen und dann machen wir ein Update.

**Comment by Mojo1917** [comment]
Okay, ich bin gestern auf eine andere Bibliothek ausgewichen. In dieser funktioniert die Gruppierung einwandfrei. 
Ich werde diese jedoch einfach rausnehmen und sollte es irgendwann notwendig werden Objekte zu gruppieren können wir diese einfach wieder anschalten. Sei es, weil die Performance nachlässt oder weil die Karte zu unübersichtlich wird.

**Comment by McFly753** [comment]
Ok, passt!

**Comment by Mojo1917** [comment]
Ist deaktiviert. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
danke, schau ich dann an.
