### ISSUE TITLE
Statistik: Tags mit aufnehmen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#30]
Können wir in der Statistik die Tags noch mit aufnehemn?

**Comment by Mojo1917** [comment]
Tags sind aufgenommen. Sollen diese auch beim klicken als Filter übernommen werden?

**Comment by McFly753** [comment]
Wäre schön, wenn einfach möglich? (würden dann halt als Einzelworte in die Suche ausgefüllt werden)

**Comment by Mojo1917** [comment]
Okay. Ja genau so hätte ich das umgesetzt.

**Comment by Mojo1917** [comment]
Tags werden jetzt beim klicken in die Suchmaske eingefüllt.

Änderung kommt mit dem nächsten Update.
