### ISSUE TITLE
Beispieldatenbank einfügen in den Einstellungen anbieten

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#300]

**Comment by Mojo1917** [comment]
Okay es werden jetzt zwei Beispieldatenbanken angelgt mit einfacher sample Data ;) Danach öffnet sich die Datenbank Unterseite und nach Auswahl einer Datenbank wird diese Seite immer geschlossen.

**Comment by McFly753** [comment]
Passt, nur stelle die neuen Datenbanken von der Reihenfolge bitte hinter die bestehenden vom User

**Comment by McFly753** [comment]
![img_2502](https://user-images.githubusercontent.com/493612/46899388-24efa680-ce93-11e8-9708-7bbbd37bfa96.PNG)

**Comment by Mojo1917** [comment]
Okay kommt mit dem nächsten Update. Vielleicht wird es von Apple sogar vor Montag genehmigt.
