### ISSUE TITLE
Objekt teilen:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#302]
- Logbase-App stürzt ab direkt nach „Teilen“ eines Objektes per iMessage (die Nachricht wird aber noch verschickt). Ist bisher zweimal passiert (iPhone 7, OS 12.0)
- Bei Objekt teilen passiert erst gar nichts, wenn ich dann auf abbrechen gehe und dann wieder auf teilen öffnet er doch das Menue zum Teilen (BR) / Immer, oder nur das aller erste mal? / Das war nur beim allerersten Mal. Jetzt geht es. (Matthias: dieses Problem habe ich auch gast immer beim ersten mal.)
- Lässt gar nicht teilen, gibt mir noch die Meldung dass der Empfänger evtl. nicht mit allen Inhalten arbeiten kann, sobald das Feld „erstelle Datei“ erscheint stürzt die App ab. Habe es schon ein paar Mal versucht, funktioniert immer noch nicht, im Gegensatz zum dem Text von oben komme ich gar nicht bis Teilen, verschicke also nichts. (Phone 5 IOS 10.3.3)

**Comment by Mojo1917** [comment]
zu 1: habe die akzeptierten App Orientations angepasst. Jetzt sollte er nicht mehr auftreten. Wenn doch muss ich das nochmal anpassen ;)
zu 2: Wann genau passiert das? Beim Teilen eines einzelnen Objektes? Bekomme es leider nicht reproduziert.
zu 3: Fehler ist behoben.

**Comment by McFly753** [comment]
Du musst die App komplett neu installieren - dann stürzt sie beim ersten Teilen einmal ab; danach nicht mehr. (Hast du eigentlich ein IPhone oder machst Du alles simuliert?)

**Comment by Mojo1917** [comment]
Okay alles klar! Schaue ich mir an.

Ich habe zum entwickeln ein iPhone SE. Man kann mit dem Emulator zwar einiges testen, aber leider nicht alles.

**Comment by Mojo1917** [comment]
Auch Fehler 3 lässt sich jetzt nicht mehr reproduzieren.

**Comment by McFly753** [comment]
sollte passen!
