### ISSUE TITLE
Besuch hinzufügen, Iphone5:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#303]
- Wenn ich einen zweiten Besuch hinzufügen möchte, dann kann ich noch ein Datum aussuchen aber ich kann das Feld nicht mehr verlassen wenn ich auf „fertig“ klicke, damit kann ich nur im Datum scrollen, ich muss dann das Programm zwanghaft beenden und wieder neu starten. (Phone 5 IOS 10.3.3) 
![img_8101](https://user-images.githubusercontent.com/493612/47354344-57f42000-d673-11e8-95ac-c87deb0b8db1.PNG)

**Comment by Mojo1917** [comment]
Okay der Fehler ist für iOS 10 jetzt behoben.

**Comment by McFly753** [comment]
ok, kann ich nicht testen, aber schliesse das Ticket.
