### ISSUE TITLE
App-Sprache:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#304]
- App Sprache bei Locbase (z.B die Copy/Paste Menüs etc. ist Englisch, obwohl meine Gerätesprache Deutsch ist

**Comment by Mojo1917** [comment]
Das sollte sich automatisch beheben, sobald wir das Englische Sprachpaket einfügen.

**Comment by McFly753** [comment]
ok

**Comment by Mojo1917** [comment]
Mit dem nächsten Update sollten die Menüs auf Deutsch sein.

**Comment by McFly753** [comment]
Ok, danke, geht.
