### ISSUE TITLE
Problem in der Standortfreigabe:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#305]
- Team1: Für die Entfernungsbenachrichtigung schickt mich die App in meine Einstellungen zur Standortfreigabe, dort verstehe ich nicht wo ich das machen soll >> mir wurde danach iwann in der App angeboten „standortfreigen“ dort konnte ich dann zustimmen. Davor hat es einfach meine Einstellungen geöffnet aber nichts weiter... 
- Team2: Ich hatte diesen Fehler auch. Es kam das Menü, wo man einzelne Apps freischalten könnte, locbase würde mir da aber nicht angeboten.

**Comment by Mojo1917** [comment]
Okay Fehler ist jetzt behoben

**Comment by McFly753** [comment]
ok, Danke!
