### ISSUE TITLE
Es existiert nur ein Fotoordner beim Auswählen aus dem Album (MR BUG)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#306]
- Wenn zu existierenden Fotos später ein weiteres hinzugefügt wird, und man das erste Foto nicht aus der Camera Roll gewählt wurde (sondern aus einem anderen Album) springt es nicht an die gleiche Stelle (bzw. in das gleiche Album) sondern geht in die Camera Roll wieder ganz nach oben.

**Comment by Mojo1917** [comment]
Okay die App springt jetzt nicht mehr nur für jedes Album an die letzte Position aus der importiert wurde sondern beim öffnen des Dialogs auch in das Album aus dem zuletzt importiert wurde.

**Comment by McFly753** [comment]
Ok, passt bei einem Teil des Teams, aber bei mir wird mir NUR meine "Camera Roll" angezeigt... Wenn ich auf "Tap here to change" ((Sollten wir auch in Deutsch anzeigen, also mehrsprachig: "hier Ordner ändern" o.ä.)) klicke, wird mir NUR die Kamera-Roll angezeigt? (iPhone X)
![img_68c6edc52b70-1](https://user-images.githubusercontent.com/493612/48974228-6ce91800-f052-11e8-9c46-c86caebbbad4.jpeg)

**Comment by Mojo1917** [comment]
Okay, Übersetzung ist eingebunden.

Der Zugriff auf die Geräte Alben sollte auf allen Geräten gleich funktionieren. Im Emulator funktioniert es für alle Geräte (einschließlich X).
Könntest du der App einmal die Berechtigung für deine Fotos entziehen und dann wieder gewähren? Das sollte den Fehler beheben.

**Comment by McFly753** [comment]
Geht dennoch leider nicht... 
![img_4253d69e38b3-1](https://user-images.githubusercontent.com/493612/49499459-65094f00-f86e-11e8-81af-a7facc6ec156.jpeg)

(Ich probiere es mal auf meinem Ipad und meinem anderen iPhone X)

**Comment by Mojo1917** [comment]
Alles klar muss ich mir nochmal anschauen...

**Comment by Mojo1917** [comment]
Leider kann ich die Probleme nicht rekonstruieren. Auch dieser Fehler tritt nur auf deinem Gerät auf, richtig? Wenn dem so ist, folge bitte nach dem nächsten Update der hier genannten Anleitung, um mögliche Probleme bei der App-Installation auszuschließen. #343

**Comment by McFly753** [comment]
ok, mache ich, Danke!

**Comment by McFly753** [comment]
ich habe leider weiterhin (bei allen Geräten, die über meine Fotos verbunden sind) hier in Locbase keine Unterordner wie Favoriten etc.

**Comment by Mojo1917** [comment]
Okay, vielen Dank für die Info. Leider kann ich mir nicht erklären, warum die App auf deinem Gerät diese Alben nicht anzeigt.

Die App sollte folgende Alben laden: All Photos, Selfies, Panoramas, Favorites und alle vom Nutzer erstellte Alben.
Die Frage mag sich jetzt doof anhören, aber du hast Ordner, die in diese Kriterien fallen, oder? Wie gesagt der Fehler lässt sich nicht erklären.

Auf meinem iPad sieht es wie folgt aus: 
![img_0055](https://user-images.githubusercontent.com/20678932/50576115-00a8c380-0e0b-11e9-8264-91835575f482.png)

**Comment by McFly753** [comment]
Es ist bei mir aufgetreten, als ich meine Bilder in die Cloud gelegt hatte. Es tritt auf ALLEN meinen Geräten, die die Fotos über die Cloud organisieren auf. Ich lass mal andere aus dem Team testen, ob das bei ihnen auch so ist.

**Comment by Mojo1917** [comment]
Okay alles klar!

**Comment by McFly753** [comment]
Ich habe es auf meinen Geräten getestete und es ist auf ALLEN geraten so, egal ob 6er Iphone oder Der oder Ipad. Ich habe immer nur einen Ordner. // Das ist aber erst aufgetreten, als ich alle Bilder bei mir in die Cloud gelegt hatte. // Ich versuche mal bei meinen Team einen ähnlichen Fehler zu finden.

**Comment by McFly753** [comment]
Ich habe ein neues Iphone (Xs) - und auch hier habe ich nur einen Ordner... ich schaue mal, ob ich es bei den anderen diesen Fehler auch produzieren kann. Wenn nicht, liegt es an meiner ICloud-Fotomediathek...

**Comment by McFly753** [comment]
hmmm.... ich zeige es Dir mal...

**Comment by Mojo1917** [comment]
Glaube das war der Fehler, den du mir gestern noch zeigen wolltest. Ich schaue mir das nochmal an...

**Comment by McFly753** [comment]
Jein, das uns das andere - mehr am Tel.

**Comment by Mojo1917** [comment]
Ich habe die Bibliothek hierfür aktualisiert und neu eingebunden in der Hoffnung, dass es jetzt auch bei dir wieder geht!

**Comment by McFly753** [comment]
Danke, schaue ich dann.

**Comment by McFly753** [comment]
geht leider weiterhin nicht... ;(

**Comment by McFly753** [comment]
Ist leider nur bei meinen Geräten so, bei anderen auch mit allen Bilder in der ICloud werden alle Alben angezeigt... ;(

**Comment by Mojo1917** [comment]
Ich kann mir das leider echt nicht erklären. Weißt du ob andere Apps bei dir auf diese Ordner richtig zugreifen?

**Comment by McFly753** [comment]
Bei allen anderen geht es (Whats app etc.) - komisch...

**Comment by McFly753** [comment]
Du kannst hier nichts "erzwingen" oder, dass die App irgendwas anders machen muss. Weil ich habe nun ein neues IphoneX und neu installiert (natürlcih mit meiner Icloud-Datenbank) und hier gibt es auch nur einen Ordner. // Kann das problem evtl. an der Anzahl meiner lokal vorhanden Bilder (ca. 100.000) liegen?

**Comment by McFly753** [comment]
Tel

**Comment by Mojo1917** [comment]
Wie besprochen testen wir es nochmal mit einem anderen Plugin mit dem nächsten Update.

**Comment by Mojo1917** [comment]
In den Einstellungen ist jetzt in der Hauptzeile ein Button 'TEST'. Dieser öffnet einen anderen Imagepicker. Wäre super, wenn du nach dem nächsten Update einmal prüfen könntest, ob dieses auf deine Ordner zugreifen kann. Wenn das geht versuche zu verstehen, was dieser Picker besser macht als der andere.

**Comment by McFly753** [comment]
Ich bekomme jetzt zumindest alle meine FotoAlben angezeigt, leider nicht den (das so wichtigen) "Favoriten-Ordner".

**Comment by Mojo1917** [comment]
Okay das hört sich schonmal gut an. Dann werde ich hier ansetzen und schauen, was die beiden Dialoge anders machen!

**Comment by Mojo1917** [comment]
Okay ich habe den kompletten Prozess zum laden der Alben neu geschrieben. Mal schauen, ob es jetzt bei dir funktioniert!

**Comment by Mojo1917** [comment]
Sollten 'smarte' Alben fehlen dann gib gerne bescheid. Aktuell lade ich nur Favoriten, kürzlich hinzugefügt und screenshots
Alle von dir erstellten Alben sollte auch geladen werden.

**Comment by Mojo1917** [comment]
Okay eine Frage habe ich noch: Sind alle/die meisten Fotos in deiner Galerie Live-Photos?

**Comment by Mojo1917** [comment]
Mit dem neuen Update sollte der Dialog jetzt alle möglichen Ordner anzeigen. Ich habe für dieses Update alle Filteroptionen deaktiviert. Jetzt müsste die App auf jeden Fall deine Ordner anzeigen. Sollte das gehen können wir die Filter wieder Schrittweise einschalten.

**Comment by Mojo1917** [comment]
Neues Update ist gerade hochgeladen! In diesem werden jetzt nur noch 'deine erstellten Alben' / 'Favoriten' / 'Alle Photos' zur Auswahl geladen. Zusätzlich werden jetzt nur noch Photos/Live Photos zur Auswahl gestellt. Das sollte die Performance wieder auf die gewohnte Geschwindigkeit heben.
Ich hoffe wir bekommen hiermit jetzt nicht wieder unser altbekanntes Problem, dass die App auf deinem Handy nicht mehr alles findet.

**Comment by Mojo1917** [comment]
Ich lade gerade ein Update hoch, dass auf einen ganz andere Dialog zur Auswahl der Fotos setzt. 
Auf meinem Testgerät läuft dieser sehr zuverlässig... hoffentlich wird dieser auch bei dir zuverlässiger und schneller funktionieren. Würde mich über kurzes Feedback freuen!

**Comment by Mojo1917** [comment]
PS: Unsere Anpassungen an dem alten Dialog gibt es hier aktuell noch nicht, diese würde ich wieder einfügen, wenn hiermit alles besser funktioniert.

**Comment by Mojo1917** [comment]
Okay ein neues Update basierend auf dem Picker, der bei dir die Alben geladen hat lädt gerade hoch!

**Comment by Mojo1917** [comment]
PhotoPicker ist jetzt wieder der aus der Roten Version. Der Bug mit dem Anker sollte jetzt auch behoben sein.
