### ISSUE TITLE
Import von mehr als einem Bild gleichzeitig (gleich als erste Bilder):

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#307]
- Wenn in einem Importier-Schritt zwei Fotos von verschiedenen Tagen verwendet werden, wird die Abfrage gestellt, dass man einen Besuch vor dem Erstellungsdatum hinzufügt. Das ist verwirrend, da es die allererste Importfunktion ist (also es davor keine Bilder gab) - hier sollte diese Fehlermeldung nicht kommen, sondern die App das älteste Datum als Erstellungsdatum verwenden.

**Comment by Mojo1917** [comment]
Okay ist behoben.

**Comment by McFly753** [comment]
Danke!
