### ISSUE TITLE
Schreibfehler in Tour:     

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#308]
- Schreibfehler in Tour bei 57% (WIR anstatt WIRD) (Screenshot)
- Das XYZ -> lass uns hier dann bei das „Objekt“ bleiben -> ich weiss nicht mehr, wo das war, aber das kannst Du sicher per Suche finden.

**Comment by McFly753** [comment]
<img width="369" alt="bildschirmfoto 2018-10-23 um 03 30 48" src="https://user-images.githubusercontent.com/493612/47354766-6989f780-d674-11e8-832d-6590016ce856.png">

**Comment by Mojo1917** [comment]
Zu 2: Ich bin mir nicht sicher wonach ich suchen soll. In der Tour wird Objekt nie durch die nutzerspezifische Bezeichnung ersetzt. Ich denke du meinst den Hinweis beim Teilen es Objektes richtig? Ich nehme hier wieder 'Objekt' auf.

**Comment by McFly753** [comment]
Lieber Niklas, das kam von meinem Team, aber sie hatten kein Screenshot gemacht - kann auch sein. Danke!

**Comment by McFly753** [comment]
Danke!
