### ISSUE TITLE
Bug bei Bilder hinzufügen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#31]
... der aber als nützliche Funktion verwendet werden kann:

- wenn ich zu schnell beim Einfügen eines Bildes auf verschieden Bilder klicke, werden merere übernommen.

- können wir es nicht von Haus aus anbieten, dass mehr bilder übernommen werden?

**Comment by Mojo1917** [comment]
Apple bietet das auswählen mehrerer Bilder nicht an. Soll ich hierfür auf eine externe Bibliothek ausweichen?

**Comment by McFly753** [comment]
Schau mal, wie aufwändig. Wäre gut, wenn man im nachhinein Objekte mit vielen Bildern anlegt. 
> Tel.

**Comment by Mojo1917** [comment]
Die App unterstützt jetzt das Importieren von bis zu 10 Bildern auf ein Mal.

Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Super, ich bin gespannt!

**Comment by McFly753** [comment]
Danke, ist prinzipiell super gelöst und funktioniert einwandfrei.
Nur das Probelm ist, dass dieses Plugin leider nur auf entweder ALLE FOTOS oder meine Alben zugreift. Nicht aber auf die AppleEigenen intellegenten Alben (wie Selfies, Live Photos, Panoramen, Perosnen, Ort...) aber eben auch nicht FAVORITEN -> und das fehlt einem dann leider schon. // Kannst Du hier was machen?

**Comment by Mojo1917** [comment]
Nein das Plugin lässt hier leider nichts anderes zu. Wir können entweder zu dem alten wechseln, oder ich suche nach einem anderen Plugin das dies unterstützt.

**Comment by McFly753** [comment]
WillsT Du mal kurz schauen? Udn dann entscheiden wir.
(Notfalls mus ich halzt über "Alben" workarounden.

PS: lannst Du einen Hinweis einbauen, wenn der User versucht, über 10 Bilder auszuwählen? Oder wie es WhatsApp macht, dann zu "wackeln" o.ä.?

**Comment by Mojo1917** [comment]
Okay ich schaue mich mal um.

Ja ich kann einen Hinweis einbauen. Optional kann ich auch die maximal Anzahl hochsetzen ;)

**Comment by Mojo1917** [comment]
Habe jetzt ein anderes genutzt. Jetzt sollte alles erfüllt sein.

**Comment by Mojo1917** [comment]
Es können zudem unbegrenzt viele ausgewählt werden.

**Comment by McFly753** [comment]
Super, Danke! 

Nur: wir bräcuhten ne Abfrage, wenn ich versuche, Videos zu laden, weil das würde er zulassen...

Und, es müsset eigentlich heissen; importiere 3 Bilder, nicht 3 Objekte... ;)

**Comment by Mojo1917** [comment]
Leider kann das Plugin in der Auswahl keine Videos filtern. Sollte jedoch ein Video ausgewählt sein und der Import gestartet überspringt die App dieses einfach.

Nachrichtentext ist geändert.

**Comment by Mojo1917** [comment]
Änderungen kommen mit dem nächsten Update.
