### ISSUE TITLE
Anzeigenfehler:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#310]
- Notizfeld wird ab und zu noch immer angeschnitten (Screenshot)
Bzw. so komishc positioniert, dass ich nicht sehe, wo ich was schreibe.

**Comment by McFly753** [comment]
![img_2840](https://user-images.githubusercontent.com/493612/47355099-575c8900-d675-11e8-98b9-1b040494e5f6.PNG)

**Comment by McFly753** [comment]
![img_2896](https://user-images.githubusercontent.com/493612/47355186-8bd04500-d675-11e8-8c62-af7921de9933.PNG)

**Comment by Mojo1917** [comment]
Konnte den Fehler in der überarbeiteten Layout-Version nicht mehr erzeugen.

**Comment by McFly753** [comment]
Ok, ich schliesse das Ticket, melde mich, wenn es nochmals auftreten sollte.
