### ISSUE TITLE
Sortierbutton ändern:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#311]
Den Sortierbutton von der Bedienung her ändern auf Apples Tastatur-Länderumschaltung. Und zwar: Tippen bleibt gleich, nur mit Langklick oder Nach-oben-Schieben öffnen wir ein Drop-Up, in dem wir wie gehabt hoch-runterschieben können, aber eben immer alle Optionen sehen (schau dir mal diese Apple-Funktion an, ich kannte die so nicht, ist aber recht gut gelöst.)

**Comment by Mojo1917** [comment]
Okay die Funktion, dass beim Swipe eine Liste mit Optionen angezeigt wird habe ich jetzt nachempfunden (Leider können wir nicht das Pop-up von Apple nutzen). Sie sieht jedoch nicht so aus wie die von Apple sondern blendet alle Optionen auf dem Screen ein. Der Nutzer kann dann mit dem Finger über eine wischen und beim loslassen wird diese gewählt. Sobald sein Finger nicht mehr über einer Option 'schwebt' wird wieder die Sortierart gewählt, die zuvor ausgewählt war.

Das Ganze dann wie folgt aus:
![img_0613](https://user-images.githubusercontent.com/20678932/48306714-f5899380-e53d-11e8-8dbc-ac1247d94315.png)

Entspricht dies deinen Vorstellungen? Von Design her können wir es natürlich wie immer noch anpassen ;)

**Comment by Mojo1917** [comment]
Ansicht ist jetzt so erweitert, dass bei zu vielen Auswahlmöglichkeiten die Liste über den Screen hinaus erweitert wird. Swipt der Nutzer dann zum oberen oder unteren Ende wird smooth in diese Richtung gescrollt, bis der Nutzer den oberen oder unteren Bereich des Display mit seinem Finger wieder verlässt. Damit sind auch die Probleme mit zu vielen Tags, etc. behoben und wir können diese Auswahl global einsetzen.

**Comment by McFly753** [comment]
Lieber Niklas, vielen Dank. Ja, von der Logik her so wie ichs gemeint hatte, nur wenn Dus "kleiner" von der Höhe her bekommst, ebene so wei bei Apple (nur eben rechstbündig), wäre es schöner.
Danke! LG, Matthias

**Comment by Mojo1917** [comment]
Okay sollte sich machen lassen!

**Comment by Mojo1917** [comment]
Okay das Design ist jetzt mehr an den Dialog von Apple angelehnt. Ich werde ihn jetzt für die Filteransicht einbinden ;)
![img_0615](https://user-images.githubusercontent.com/20678932/48376337-e84ddf80-e6ca-11e8-9544-672d82623672.png)

**Comment by McFly753** [comment]
Super, Danke!
