### ISSUE TITLE
4 weitere Felder (Kategorie, Adresse, Tel, URL) / ausblendbar / neue Filteransicht

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#312]
Lass uns noch ein paar Felder einfügen und das Attribut woanders hin schieben (alle ausblendbar, siehe ganz unten).
- Adresse (also Straße und Hausnummer und PLZ) (kann die automatisch geschrieben aber dennoch vom User verändert werden? Also immer, wenn er ein neues Bild an Position 1 schiebt, würde dieses Feld überschrieben werden (evtl. machen wir ne Abfrage) - würde ich oben unter den Ort setzen, kleine Schriftart und in der US/DE-Syntax (je nach Sprachversion): 83714, 7 Tulpenweg oder 90210, 9663 Santa ­Monica Blvd. ­247) > wird nach hinten abgekürzt, also nur einzeilig.
- und dann unter die Objekteigenschaften und über die Tags nebeneinander in eine Zeile zuerst das neue Kategoriefeld (mit Farbbobbel und Kategoriename, mehr siehe unten) und dann das Attribut (dies mit echter Feldbezeichnung) 
- Telefonnummer (sollte knickbar sein) - die würde ich unten zur URL unter die Tags nehmen.
- Und doch ein separates URL-Feld (klickbar) - das würde ich unten zur Telefonnummer nehmen. 
- Evtl. könnten wir Telefonnummer und URL in eine Zeile nehmen (also zwei Felder nebeneinander?) (wird etwas trickreich beim einzelnen Ausblenden)

Folgendes würde ich noch abändern:

- lass uns das Erstellungsdatum/Besuchsdatum genauso klein schreiben, wie die Beschriftung. damit können wir folgendermaßen schreiben: 
- Erstellt am 18.10.18 
- 4 Besuche, letzter am 22.10.18
- Notfalls gehen wir auf die kleine Schriftgröße der Koordinaten)

Zu diesen neuem Kategoriefeld:
Lass uns ein Kategoriefeld mit Farbe einführen (ähnlich den farbigen Apple-Tags, aber eben nur als Kategorie (also nur 1 Wert gleichzeitig auswählbar). 
- Man kann beliebig vielen Kategorien anlegen und ihnen einen Namen geben (ähnlich den Tags)
- Man kann jeder Kategorie eine Farbe geben (geht das mit so einem Frabkreis und einer Pipette? Oder einfach einer Farbauswahl?)
- Man kann die Kategorien umsortieren wie Tags
- Man kann die Kategorien löschen wie Tags
- Man kann die Kategorien hinzufügen wie Tags
- Man kann EINE Kategorie auswählen, würde das wie unseren Sortierbutton bedienbar machen (s. aber auch das Ticket zu dem neuen Sortierbutton)
- Tabs etc. wie bei den Tags behandeln, auch die Abspeicherlogik etc.
- Wir zeigen diesen Babbel in der Listenansicht über der Fahne an (nicht, wenn keine Kategorie ausgewählt ist, was auch möglich sein muss - also es gibt „Keine Kategorie“ als Auswahl, dies hat die graue Farbe)
- In der Karte unter Daten werden hier die Farben angezeigt. Wenn es keine Farben gibt, werden sie alle in grau angezeigt (aber bitte Pins, dass man den Einsteckpunkt sieht) 
- Im Filter zeigen wir die Kategorie links neben dem Favoritenstaren an, siehe aber zur neuen Filteransicht weiter unten.

Und das würde ich redundant noch machen:
- ich würde dann das grau des Favoritensternes redundant in dieser Kategoriefarbe einfärben

-> Damit würde es im Objekt oben rechts (vollbestückt) nun so aussehen:
- Fahne / Favoritenstern (evtl. farbig)
- Ort, Land
- Adresse
- Erstellt am 18.10.18 
- 4 Besuche, letzter am 22.10.18
- Koordinaten 

-> Unten würde es so aussehen:
- Eigenschaften
- Kategorie / Attribut 
- Tags
- TEL / URL
- Notizen 

Bitte auch alle diese Felder ausblendbar machen. (Neue Filteransicht siehe ganz unten).
- (Tags)
- (Attribut)
- (Bildkommentar)
- Fahne
- Favoritenstern
- Objekteigenschaften 
- Adresse
- Telefonnummer
- URL
- hab ich was vergessen? (Notizen würde ich nicht ausblendbar machen, auch Ort/Land nicht und auch das Erstellungsdatum und die Besuche nicht)

Neue Filteransicht und Suche (Freifilter) neu
Wir haben ein Problem, wenn ich z.B. auf bestimmte Tags sortieren will und man sein Objekt wie einen Tag genannt hat. Oder wenn ich nach einem Ort suchen will und ich dies auch in einem Attribut verwendet habe. Wie wäre es, wenn wir die Suchanfrage konkretisieren:
Und wir haben neue Felder.
Vollausgestattet würde ich die folgenden für diese Filterzeile vorschlagen:
- Eigenschaften (kürzer, evtl. Icon und Anzahl)
- Kategorie (nur Farbbobbel und dann Dropup und dort dann auch Bezeichnung dahinter)
- Favoritenstern (weiterhin in der Mitte)
- Tags (evtl. auf die ersten beiden Buchstaben abgekürzt) (als Dropup und dort dann ausgeschrieben)
- Suche und über der Tastatur eine Auswahl anbieten, wo von Haus aus „alles“ ausgewählt ist, und zwar: Name, Attribut, Ort/Land, (und evtl. doch dann auch Notizen) oder alles.

**Comment by Mojo1917** [comment]
Okay soweit ist alles klar.
Nur für das Ausblenden all dieser einzelnen Elemente muss ich das Layout komplett neu aufsetzen, damit es sich besser an eine solch starke Veränderung anpassen lässt. Aktuell sind die Werte hierfür noch zu stark von Apples AutoLayout vorgegeben (Diese verträgt leider keine starken Laufzeit-Veränderungen an dem Layout)
Ich werde das Layout dann wieder zuerst für Displays größerGleich iPhone 6 erstellen und dann im nächsten Schritt die notwendigen Anpassungen für iPhone 5 und kleiner machen.

Die Änderungen an der Filterzeile sind soweit auch klar.
In eigenen Worten: Wenn der Nutzer auf die Suchzeile klickt werden die verschiedenen Attribute, die durchsucht werden, angezeigt und können abgewählt werden und werden dann in der Freitextsuche nicht mehr berücksichtigt? Habe ich das richtig verstanden?


Zu dem neuen Popup mit Swipe-Auswahl: Ich habe es bisher noch nicht geschafft dieses Verhalten von der Apple Tastatur zu kopieren oder online etwas ähnliches zu finden. Könnte daher noch etwas dauern... Ich bin da aber dran!

**Comment by McFly753** [comment]
Ja, passt so, Danke!

**Comment by Mojo1917** [comment]
Notiz an mich: Nach der Datenbankerweiterung den Teilen und Backup Prozess anpassen.

**Comment by Mojo1917** [comment]
- Datenbanken für Kategorie sind eingefügt

**Comment by Mojo1917** [comment]
Für das Objekt füge ich für Adresse mehrere Spalten ein: Straße, HausNr, PLZ, Ort.
Dadurch können wir die Adresse dann immer so darstellen wie in der Sprache benötigt. Oder reicht es dir, wenn wir diese einmal in dem aktuellen Nutzer-Format erstellen und dann als festen String weitergeben? Sollte ich dann mein Objekt jedoch teilen wird sich die Adresse dann nicht mehr umsortieren.

**Comment by McFly753** [comment]
Ok. Alles klar. ;)

**Comment by Mojo1917** [comment]
Ich denke bei der Auswahl von Tags und Kategorien beim Filtern wird sich ein Problem ergeben, wenn wir es äquivalent zur Auswahl beim Sortierbutton implementieren. Denn wie gehen wir damit um, wenn der Nutzer mehr Tags/ Kategorien hat als auf die Höhe des Bildschirms passen? Wir könnten uns jedoch überlegen, ein Popup einzubinden, dass eine Liste enthält in der der Nutzer scrollen kann. Hier kann er dann eine beliebige Auswahl treffen. Dann wird es jedoch mit der Auswahl durch wischen schwer.

**Comment by Mojo1917** [comment]
Wie per Mail besprochen werde ich schauen, was sinnvoller erscheint.

**Comment by Mojo1917** [comment]
Hier die Screenshots der neuen Filterleiste mit der Auswahl für Kategorien und Tags
![simulator screen shot - iphone x - 2018-11-13 at 20 52 26](https://user-images.githubusercontent.com/20678932/48439276-3247cb80-e786-11e8-98d7-cfe41bd79e36.png)
![simulator screen shot - iphone x - 2018-11-13 at 20 52 36](https://user-images.githubusercontent.com/20678932/48439277-3247cb80-e786-11e8-8885-83e709bda710.png)

**Comment by Mojo1917** [comment]
Das ist klar!

**Comment by Mojo1917** [comment]
Ich sehe gerade, dass die Pop-up Dialog auf dem iPad noch zu weit laufen und dass sie erst aufgehen wenn man wischt und nicht schon beim draufdrücken. Fixe ich in dem nächsten Update ;)

**Comment by McFly753** [comment]
Lieber Niklas, Danke für die Umsetzung, hier ein paar Punkte Feedback:

1. Adresszeile: Jetzt wird der Ort hier nochmals angezeigt, es sollte aber nur die Straße + Nr und die PLZ kommen, den Ort haben wir ja darüber bereits.

2. Die kleinere Schriftart hierfür bitte verwenden, wie geschrieben.

3. Die Erstellt am / Besucht am Syntax bitte so wie geschrieben (mach sie gerne in der kleineren Größe):
Erstellt am 18.10.18
4 Besuche, letzter am 22.10.18
Notfalls gehen wir auf die kleine Schriftgröße der Koordinaten)

4. Kategorie:

a) Farbauswahl: nimm bitte den finalen Farbkasten und das Choose und Cancel davor nach unten, also so, dass die große Auswahlfläche und dann der Schieberegler zuerst kommen und darunter das von oben.

b) Farbauswahl: können wir die Button unten wie bei der Hilfe gestalten und sie Deutsch nennen: Abbrechen und Übernehmen

c) Farbauswahl: diesen Screen sollte man auch durch runterziehen schliessen können.

d) Wenn die Kategorien ausgeschaltet sind, würde ich die Pins weiterhin in unserem Blau machen. Ansonsten in Grau (wenn keine Kategorie gewählt ist)

e) Ich würde hier nicht "Keine Kategorie" anzeigen sondern in diesem leichterem Grau "Kategorie" hinterlegen, wenn keine ausgewählt ist.

f) Fehlermeldung beim Löschen von verknüpften Kategorien leicht anpassen: "Diese Kategorie ist derzeit... dennoch löschen? Die Objekte gehen hierbei nicht verloren, nur die Kategorie de Objekte."

g) Wenn eine Kategorie angelegt wird, aber ihr kein Name gegeben wird und das Fenster verlassen wird, einfach diese Kategorie wieder löschen (so wie bei den Tags).

h) ich würde "keine Kategorie" nicht in der Filterung anbieten, das macht nicht wirklich Sinn und macht es etwas unübersichtlich.

i) Kategorie muss natürlich auch ausblendbar sein. Sorry, hatte ich Vergessen, mit aufzuführen.

5. Filterung:

a) Auch die Kategorie-Sortierung sollte bei Verwendung einen evtl. geöffneten Objekteigenschaftenfilter wieder zuklappen.

b) Auch die Tag-Sortierung sollte bei Verwendung einen evtl. geöffneten Objekteigenschaftenfilter wieder zuklappen.

c) Kannst Du in dem Kategorien- und Tag-Dropup bitte das "Alle" nach unten setzen?

6. Einstellungen :

a) Bitte die Objekte, die man ausblenden kann, in diese Reihenfolge und bitte mit Trennstrich unterteilen:

- Objekteigenschaften
- Kategorie
- Tags
---
- Favorit
- Fahne
- Attribut
---
Adresse
Telefonnummer
URL
---
Bildkommentar

7. Animationsproblem auf Karte bei Bilder-Ansicht: 
- hier werden teilweise rote Stecknagelköpfe zwischendurch angezeigt
- und die Bilder ruckeln/flackern beim zoomen stark

8. Das von Dir nicht vergessen: Ich sehe gerade, dass die Pop-up Dialog auf dem iPad noch zu weit laufen und dass sie erst aufgehen wenn man wischt und nicht schon beim draufdrücken. Fixe ich in dem nächsten Update ;)

**Comment by Mojo1917** [comment]
Ein 'Herutenziehen' des FarbauswahlScreens lässt sich fast nicht implementieren. 
Auf den ColorPickern liegen GestureRecognizer, die ein wischen erkennen um die neue Farbe zu wählen.  Wir können somit nur außerhalb dieser 'Ein nach unten Wischen' implementieren. Man könnte dann nur bei den Buttons und am äußeren Displayrand wischen. Soll ich es dennoch implementieren?

**Comment by McFly753** [comment]
Deute doch oben einfach diesen Strich an und mach es ähnlich der Karte?

**Comment by Mojo1917** [comment]
Okay das geht natürlich ;)

**Comment by McFly753** [comment]
Danke! Das hier noch, zwei andere Punkte in extra Ticket:


Zu 4a) Danke! Doch vertausch unten bitte den Farbkasten mit den zwei Buttons. Also dass die Buttons rechts unten sitzen.

Zu 4c) Da beim iPhone X ganz oben auch schon eine „runterziehen“-Fläche liegt, benötig ich etwas merh Spiel zum runterziehen. Was ist, wenn Du die ganzen Farben einfach ein Stück tiefer beginnen lässt, so dass wir etwas mehr sensitive Fläche haben? 

Zu 4d) mach sie immer blau, also somit ist die „nicht eingeteilt“ Kategorie eben blau. (evtl. Kannst Du beim Kategorie anzeigen eine „Keine Kategorie“ anzeigen, die man aber nicht umsortieren oder löschen kann, aber die Farbe ändern kann?

Zu 4e) bitte nicht „Kategorie hinterlegen“ in diesem Feld schreiben, sondern „Kategorie“ :=)

Zu 4f) jetzt kommt gar keine Fehlermeldung mehr, obwohl eine Kategorie mind. mit einem Feld verknüpft ist?

**Comment by Mojo1917** [comment]
4a) Ist umgesetzt
4c) Ist umgesetzt
4e) Ist umgesetzt
4f) Ist behoben

**Comment by Mojo1917** [comment]
Das sollte machbar sein ;) Ich füge jeder Datenbank ein neues neues Attribut hinzu. Dieses enthält dann eben diese Farbe.

**Comment by McFly753** [comment]
Danke.

zu 4a) -> Bitte didaktisch den Übernehmen Button nach unten, Abbrechen oben.

zu 4c) Diese Fläche reicht mir nicht. Denn wenn ich den "simulierten" Strich greifen möchte, ziehe ich im Betriebssystem diese Option runter. Wir müssen den Strich also tiefer setzen und die Farben noch mind um 0,5 cm ( : ) ) tiefer beginnen lassen, dass ich genug platz habe, den Strich zu greifen und zu ziehen.

zu 4d) "Keine Kategorie" ist bei mir (nach Neuinstallation) leider noch grau.

zu 4f) kann ich nicht testen, da ich das Kategorie-Feld nicht klicken kann (s. anderes Ticket)

**Comment by Mojo1917** [comment]
zu 4a) angepasst

zu 4d) Jetzt im Standart blau. Farbe lässt sich jedoch über die Kategorien Seite anpassen.
zu 4f) Okay, habe alles dazu hier reingeschrieben

**Comment by McFly753** [comment]
Ok, 4f) passt.

dann 4c) noch.

**Comment by Mojo1917** [comment]
So jetzt ist auch 4c umgesetzt ;)

**Comment by McFly753** [comment]
Danke! ;)

**Comment by McFly753** [comment]
Lieber Nils, evtl. reden wir aneinander vorbei... :)

> Jetzt habe ich zwar unter dem oberen schwarzen Strich etwas mehr Platz, aber wenn ich in diesen Platz greife und nach unten ziehe (also den Strich damit etwas zu tief greife), wird er nicht mitgekommen, sondern der Farbpicker bewegt. Ich möchte aber hiermit das Fenster (und eben mit einer etwas größeren Angriffsfäche) schliessen können. (Notfalls tel.)

**Comment by Mojo1917** [comment]
Sensitive Fläche ist jetzt größer. (Im Screenshot braun gekennzeichnet) Ich hoffe das ist jetzt besser zu greifen ;)
![simulator screen shot - iphone x - 2019-01-05 at 17 48 16](https://user-images.githubusercontent.com/20678932/50726793-1cb1ab00-1112-11e9-963f-7e2e44c250d3.png)

**Comment by McFly753** [comment]
Danke, Niklas. Aber: beim iPhone X ist dieser Bereich (rot) für das OS-Menü vorgesehen, dass ich auch runterziehen kann - also es bleibt uns nur diese Fläche (grün) übrig. Evtl. können wir es noch etwas nach unten erweitern?

**Comment by McFly753** [comment]
![img_5411](https://user-images.githubusercontent.com/493612/50727823-6bcffe00-115b-11e9-8917-0fb6087c0eb8.PNG)

**Comment by McFly753** [comment]
Danke!
