### ISSUE TITLE
 Autokorrektur:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#314]
- Bitte auch in den kleinen Feldern diese Wortvorschläge und Autokorrektur anzeigen lassen (bei Objketnamen, Attribut und später dann auch bei Kategorie (bei der Eingabe in den Einstellungen)
- Wenn ich den Objektnamen verändere, wäre es gut, wenn ich im Textfeld automatisch mit einem großen Buchstaben zu schreiben beginnen könnte, dann müssen wir nicht erst den Pfeil für die Großschreiben anschalten.

**Comment by Mojo1917** [comment]
Okay Wortvorschläge und die Großschreibung ist jetzt in allen Popover Dialogen aktiviert

**Comment by Mojo1917** [comment]
In den Einstellungen ist es jetzt auch aktiv

**Comment by McFly753** [comment]
Danke!
