### ISSUE TITLE
Entfernungsbenachrichtigung:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#315]
- Wenn die Entfernungsbenachrichtigung eingeschaltet ist, bekam ich für ein Objekt laufende Nachrichten dass ich mich in der Nähe befinde, hier würde eine Nachricht am Tag reichen. (Geht das?)

**Comment by Mojo1917** [comment]
Ja, das lässt sich einbauen ;)

**Comment by Mojo1917** [comment]
Okay, wir pushen jetzt nur noch einmal alle 24 Stunden.

**Comment by McFly753** [comment]
ok, muss ich noch testen, aber schliesse das Ticket.
