### ISSUE TITLE
Mehr Objekte auf einmal löschen können:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#316]
- mehr Bäume in einem Schritt löschen können in der Listenansicht (so wie ich mehrer Objekte teilen kann).

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Zu löschende Zeilen werden rot gekennzeichnet (wie blau beim teilen)

**Comment by McFly753** [comment]
Super, Danke!
