### ISSUE TITLE
Fotopositionierung Anpassungen:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#318]
- Beim Foto-Positionieren sollte man auch die Kartenansichten umschalten können
- Und auch auf Daten umschalten können (und diese als Stecknadel anzeigen, damit man den „Einstichpunk“ besser sieht
- Man sollte hier auch suchen können (aber wenn das Objekt wackelt, es dorthin mitnehmen)
- Das selbe für den Klick auf Standort

**Comment by Mojo1917** [comment]
1 & 2 sind umgesetzt

**Comment by McFly753** [comment]
Super, Danke!

Nur bei "Man sollte hier auch suchen können (aber wenn das Objekt wackelt, es dorthin mitnehmen)" -> kannst Du nach einem Suche-Sprung die Nadel noch wackeln lassen, also die Koordinate noch nicht schreiben?

**Comment by Mojo1917** [comment]
Ist umgesetzt. Damit die Position auf der Karte verschoben werden kann muss die neue Position einmal gespeichert werden. Aber das Bild wackelt danach noch und dann weiter verschoben werden.

**Comment by McFly753** [comment]
Danke!
