### ISSUE TITLE
Wenn oben eine Zeile eingerückt wird (z.B. wegen aktiven Telefonat) das unten bei der Suche berücksichtigen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#319]
![b5b8984e-1666-4b76-8a0a-baea107366bc](https://user-images.githubusercontent.com/493612/47355027-2714ea80-d675-11e8-89c6-5e4297be294e.jpg)

**Comment by Mojo1917** [comment]
Okay ist behoben.

**Comment by McFly753** [comment]
Danke!
