### ISSUE TITLE
Dynamische Anpassung der Objekteigenschaften-Anzahl in der Anzeige

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#32]
Ich würde, wenn man nur 4 oder weniger Obejkteigenschaften in den Einstellujngen definiert hat, hier dann auch nur eine Zeile mit 4 Filtern anziegen und nicht 8 mit 4 leren. Kannst Du das Dynamsich so einstellen?

**Comment by Mojo1917** [comment]
Klar das sollte kein Problem sein. Ich werde einfach die untere Hälfte dann ausblenden.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke!
