### ISSUE TITLE
Karten „runterziehen“ können:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#320]
Alle Karten auch zum „Runterziehen“ wie bei dem digitalen Homebutton beim Iphone machen. (Kartenansicht geht zur Statistik, Positions-Änderungskarte schließt sich.)

**Comment by Mojo1917** [comment]
Ist zum Großteil umgesetzt. Muss jetzt nur noch für die 2. Karte kopiert werden ;)

**Comment by Mojo1917** [comment]
Okay ist jetzt komplett umgesetzt.

**Comment by McFly753** [comment]
Hm, das funktioniert so nicht wirklich sinnvoll. Mein Fehler war auch, dass ich nicht bemerkt habe, dass wir ja schon einen kleinen Bereich über der Karte haben. Was ist, wenn man dieses Wischen überall dort auf diesem Bereich starten kann und nicht genau diesen Strich treffen muss?
(also auch noch darüber mit der Bewegung Anfang kann)?

Und: der Strich ist zu dick. Mach ihn mal auf ca. 60% der jetzigen Größe - und auch kleiner. Siehe Screenshot.

**Comment by McFly753** [comment]
![img_2aff3b9821ad-1](https://user-images.githubusercontent.com/493612/48974340-ec2c1b00-f055-11e8-80fd-d74f9a1b21b1.jpeg)

**Comment by Mojo1917** [comment]
Okay der sensitive Bereich liegt jetzt auch noch leicht unter dem Strich und auf dem gesamten Titel. Man kann also ganz einfach von oben nach unten ziehen ;)

Die Größe ist auch angepasst.

**Comment by McFly753** [comment]
Super, das its gut so. 

Allgemein: ich finde diese "länge" des Ziehens und die "Schnelle" der Reaktion genau richtig. Können wir alle anderen sensitiven Runterziehschaltflächen an diese "Reaktionsgeschwindigkeit" anpassen?

Und, das Einblenden von "Seite shcliessen "reicht völlig, ich brauche keinen "Kreis".

Und: bitte passe diesen neuen Strich und die Funktion auch noch bei dem "Ort verändern" Screen an.

**Comment by McFly753** [comment]
Zeig mal, wie Düs jetzt hättest und dann schauen wir uns alles nochmals in der Ganzheit an. Danke!

**Comment by McFly753** [comment]
Passt so, Danke!
