### ISSUE TITLE
Alles Teilen auch direkt in die eigene App anbieten

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#321]
- Damit kann ich ein Objekt in eine andere Datenbank verschieben oder eine ganze Datenbank duplizieren. / können wir das „Infofenster“ hierfür missbrauchen? Also den Nutzer nach diesem Text noch fragen, ob er das Objekt innerhalb seiner App oder mit anderen teilen will und dann zwei Buttons anbieten?
- „Willst du die Daten innerhalb Deiner App teilen oder mit anderen Personen?“
- in meiner App / mit anderen

**Comment by Mojo1917** [comment]
Ja das sollten wir hinbekommen! Aber vielleicht ist es von der Nutzerführung her leichter, wenn wir unsere App versuchen in dem Teilen-Dialog anzuzeigen? Dann muss der Nutzer nicht vorher entscheiden, ob er intern oder extern teilen mag.

**Comment by Mojo1917** [comment]
In jedem Teilen-Dialog wird jetzt eine Option zum Teilen lokal in Locbase angeboten. Wählt man diese Option wird die Datei einfach lokal weitergereicht für den jeweiligen Import ;)
![img_0631](https://user-images.githubusercontent.com/20678932/48547968-12222480-e8cc-11e8-8443-2323dc0cf4ec.png)

**Comment by McFly753** [comment]
Ich habe es nicht hinbekommen. Weil da folgt dann nichts mehr, die App springt einfach zurück (und an der Datenbank hat sich nichts verändert. Es müsste ja in diesem Fall (weil ich Abe zwei Datenbanken) mich fragen, in welche ich das Objekt importieren will.

Und: ich finde didaktisch diesen Weg nicht ganz verständlich bzw. der User findet dieses Icon nicht selbstständig (bei mir ist es erst an 5. Stelle, also ausserhalb des sichtbaren Scrollbereiches. Da wir das Infofenster eh immer zeigen, könnten wir es dort doch zumindest noch erklären: "... importiert werden kann." dann Leerzeile und dann: Du kannst die Daten aber auch innerhalb Deiner App teilen (zum Duplizieren oder Verschieben), klicke dann im nächsten Schritt auf "In meinem Locbase teilen"

Und: bitte schalte dieses Hinweisfenster auch vor die Teilenaktion bei Teilen von mehreren Objekten.

**Comment by Mojo1917** [comment]
Du hast Recht. Der Dialog wurde auf einigen iOS-Geräten nicht angezeigt. Der Fehler ist jetzt behoben.

Den Text habe ich eingebunden. Ich kann die Reihenfolge, in der die Element in diesem Dialog sortiert werden, nicht vorgeben. Jedoch hat der Nutzer die Möglichkeit, diese anzupassen.

**Comment by McFly753** [comment]
Ok, danke!
