### ISSUE TITLE
Abbrechen beim Teilen anbieten

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#322]
- es kann sein, dass ich die Funktion ausversehen ausgeführt habe und ewig lang zum aufgearbeitet der Daten brauche - dann sollte ich auch abbrechen können.

**Comment by Mojo1917** [comment]
Button steht jetzt bei jedem Teilen zur Verfügung.

**Comment by McFly753** [comment]
Ok, danke!
