### ISSUE TITLE
Tour-Circle-Optimierung:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#323]
- Team: Zurück-Funktion bei Tour ist inaktiv bei 71%, bei 74 % und auch bei 77%. Wenn man die Tour von Beginn an durchgeht und nochmal weiter zurück will, dann geht das nicht. Ich komme von 80 % nicht mehr zurück auf 30% der Tour
- Matthias: können wir nicht uns doch die Reihenfolge der Tour merken und mit dem Zurückbutton auch Seitenübergreifend zurückspringen? (nur wenn nicht zuviel Aufwand. Oder dann eben in anderer Reihenfolge, aber weiterhin zurück?)

**Comment by Mojo1917** [comment]
Da der Nutzer die Möglichkeit hat in beliebiger Reihenfolge alle Seite abzuarbeiten ist ein Zurückgehen in genau der Nutzerreihenfolge sehr zeitaufwendig zu implementieren. Zudem könnte es verwirrend werden, wenn die App dann so 'zufällig' zurückspringt.
Wir können jedoch folgendes machen: drückt der Nutzer zurück springt die App immer an den Punkt, der nach der Reihenfolge vor dem Aktuellen wäre und bereits angeschaut wurde. (War das so verständlich?) Was hälst du hiervon?

**Comment by McFly753** [comment]
Ja, passt mir so!

**Comment by Mojo1917** [comment]
Okay ist angepasst. Das gesamte Tutorial kann jetzt wieder zurück gelaufen werden.

**Comment by McFly753** [comment]
Ok, danke!
