### ISSUE TITLE
Passwortsicherung der App beim Start (Abschaltbar)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#324]
- Team: Ich fände eine Passwort Sicherung gut für die App, und wenn es nur der Fingerabdruck ist. Matthias: ist das einfach implementierbar als Plugin? Wenn nicht, weglassen.

**Comment by Mojo1917** [comment]
Hier gibt es bestimmt Plugins! Ich schaue, was sich da machen lässt ;)

**Comment by Mojo1917** [comment]
Okay ist eingebunden. Mit Face und Touch ID

**Comment by Mojo1917** [comment]
Klaro ;) Es wird immer eine PIN festgelegt. Nur damit diese nicht immer eingegeben werden muss kann man zusätzlich ein entsperren über Touch und Face zulassen.

**Comment by McFly753** [comment]
Ok, danke! 
Nur: können wir es vereinfachen, dass er den System-Code zum Entsperren nimmt?
Weil wenn wir ein eigenes vergeben, was machen wir dann, wenn der User es vergisst?
(Dann müssten wir mind. eine Email abfragen, wohin wir seinen Code ihm dann schicken können.)

**Comment by Mojo1917** [comment]
Das ist leider nicht möglich. Wir können werde auf den Lockscreen zugreifen noch das Passwort bei uns verwenden. Nur das iOS-System kennt das Nutzerkennwort.
Für den Fall, dass der Nutzer sein Passwort vergessen hat könnten wir nur eine Möglichkeit entwickeln, die dem Nutzer die Möglichkeit bietet sich den Code per Mail zusenden zulassen. Wir könnten hierfür ein kleines Server-Skript schreiben, an welches die App das Kennwort und die Nutzer-Mail überreicht und dieses dann die entsprechende Mail sendet ;)
Dann bin ich mir jedoch nicht sicher, wie es bzgl. einer Datenschutzerklärung ist, da der Server dann ja mit Nutzerdaten arbeitet.
Sollen wir so etwas einbauen?

**Comment by McFly753** [comment]
Dann lass es uns anders machen: 
Kannst Du nach dem Erstellen/Ändern des Passwortes ein Messagefeld einblenden, dass der User sich das Passwort wirklich merken muss, weil es nicht wiederhergestellt werden kann. Und ob er fortfahren will...

**Comment by Mojo1917** [comment]
Dialog wird angezeigt.

**Comment by McFly753** [comment]
danke, setze bitte nur in deinem text zwei Kommas merh. 
Und zwar:

... den Code vergessen,
... Möglichkeit mehr,

**Comment by McFly753** [comment]
Passt. Nur: wird der Code nur dann abgefragt, wenn die App zuvor komplett geschlossen (also abgeschossen) wurde? Oder wird der Code erst nach einer gewissen Zeit abgefragt? 
(Wenn nur nach Komplettabschuss, macht diese Funktion so keinen Sinn.)
(Wenn Zeit, können wir diese einstellen?)

**Comment by McFly753** [comment]
das ist komisch... ich hab es jetzt mal ausprobiert: ich habe die App in en Hintergrund getan, ohne was anderes aufzumachen: selbst wenn ich sie das 3 Minuten lasse, wird das Passwort nicht angefordert.

(? iPhone X) -- im Testprozess wurde es einmal angefordert, nach dieser Eingabe und eben auch ein paar Minuten warten nicht mehr

**Comment by Mojo1917** [comment]
Okay du hast Recht. Die Events scheinen seit dem letzten Update nicht mehr zu funktionieren. Ist jetzt verbessert.

**Comment by Mojo1917** [comment]
Ich habe das Zeitlimit, dass überschritten werden muss bevor das Passwort erneut abgefragt wird auf 30 Sekunden gesetzt. Passt das, oder hättest du lieber ein anderes Interval?

**Comment by McFly753** [comment]
Ok, 30sec. passt, Danke!

**Comment by McFly753** [comment]
Danke!
