### ISSUE TITLE
Blankobild einführen (evtl. - denk Dir das auch bitte mal durch)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#326]
- Können wir ein Blankobild einfügen (z.B. Bild mit unserem Locbase-Logo)
- Wenn man auf Bild hinzufügen geht, wird einem dies als 3. Option angeboten („Blankobild einfügen“)
- Das kann man dann von der Position her verschieben (weil es ja keine Koordinaten enthält)
- Zusätzlich kann man hiermit starten (also einem neuen Objekt und ein Blankobild hinzugefügt mit den „gewählten“ Koordinaten9, wenn man in der Kartenansicht auf einen Punkt (ohne Objekt) lange klickt.

**Comment by Mojo1917** [comment]
Ich denke das lange drücken auf die Karte ist eine gute Idee! Ich füge hier dann auch unser haptisches Feedback ein :)

**Comment by Mojo1917** [comment]
- Dieses ist eingebunden wie an allen anderen Stellen auch. Sollte somit ausgegeben werden. Funktioniert es bei dir an den anderen Stellen noch?
- Okay ist angepasst.

**Comment by McFly753** [comment]
Danke!
