### ISSUE TITLE
Wir sollten danach noch die Hilfe anpassen auf die neuen Features/Felder 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#327]

**Comment by Mojo1917** [comment]
Lass uns das im letzten Schritt machen, wenn wirklich alles andere (abgesehen von der Übersetzung ) fertig ist ;)

**Comment by McFly753** [comment]
Ok, und auch die Reihenfolge auf den einzelnen Seiten überprüfen, da wir ja manche Felder verschoben haben

**Comment by McFly753** [comment]
Hier noch aus anderem Ticket: "Sollten wir (in der Detailansicht eines Objektes) evtl. nicht die Karte, Koordinaten und Ort/Land zusammennehmen mit folgender Funktion:
Kurzklick: Sprung zur Karte
Langklick: Bildposition ändern
(Ausser Links)" 
> Müssen wir in Hilfe auch dann noch erklären

**Comment by Mojo1917** [comment]
Klar, schreibe ich rein, wenn ich die anderen Tickets fertig habe!

**Comment by Mojo1917** [comment]
Nach dem nächsten Update werde ich das hier füllen :)

**Comment by McFly753** [comment]
ok... :)

**Comment by Mojo1917** [comment]
Hier schreibe ich alle Änderungen rein, die ich einfügen würde (Wird sich fortlaufend erweitern):

Rahmen (Karte/Liste):
- Anpassung der Leiste unten (Tags und Kategorie aufnehmen)
- Textanpassung zum Datenbankwechseln durch drücken auf den Titel
- Info zur Sortierung nur noch in der Liste zeigen, da in der Karte nicht mehr sortiert werden kann (Textanpauung)

Karte:
- Textanpassung zur Bilder/Daten Ansicht anpassen -> Daten zeigt Kategorie soweit verwendet

Liste:
- Aktuell keine Änderungen

Einzelansicht:
- Reihenfolge aller Fenster ändern auf Titel, Menü, (Karte, Adresse, Stadt, Flagge), Daten, Bilder, Eigenschaften, Kategorie. Die letzten verbleibenden würde ich einfach in eins aufnehmen, da ich denke diese sollten selbsterklärend sein.
- Textanpassung ein- ausblenden -> Wurde stark erweitert
- Texte einfügen für alle neu eingefügten Blasen
- Text für die Interaktion mit Ort, etc. anpassen

Statistik:
- Aktuell keine Änderungen

Einstellungen:
- Einfügen der Kategorie in die Hilfe
- Codesperre einfügen und erklären, dass die App automatisch Face/Touch ID nutzt soweit eingerichtet und sonst die Displaypin ohne diese zu kennen.
- Erklärung auf der Unterseite "Element ein- und ausblenden" einfügen 
- Erklärung auf der Unterseite 'Kategorie' hinzufügen

**Comment by Mojo1917** [comment]
Das sind die Textanpassungen, so wie ich sie in die App einbauen würde:

Rahmen Karte/Liste Datenbankname
"Das ist die Bezeichnung der aktuellen Datenbank. Diese kannst du in den Einstellungen verändern. Wenn du mehr als eine Datenbank angelegt hast, kannst du durch drücken und wischen zwischen diesen umschalten."

Text Filter für Karte/Liste
"In diesem Bereich kannst du deine Objekte auf Eigenschaften, Kategorien, Favoriten, Tags oder Freisuche filtern, soweit diese nicht ausgeblendet sind. Mit Wischen nach oben und unten kannst du diesen Bereich vergrößern und verkleinern."

Text Filter Kategorie:
"Hiermit kannst du nach bestimmten Kategorien filtern."

Text Filter Tags:
"Hiermit kannst du nach bestimmten Tags filtern."

Karte Info für Bilder/Daten Button:
"Setze fest, ob deine Objekte als Pins in ihrer Kategoriefarbe (soweit genutzt) oder Mini-Bilder angezeigt werden."

Text Einzelansicht Karte/Ort/Fahne:
"Tippe auf eines dieser Element, um dir den entsprechenden Bereich auf der Karte anzeigen zu lassen. Durch lange drücken kannst du die Position des Objektes verändern. Mit dem Karten-Symbol öffnest du den Routenplaner zu diesem Objekt."

Einzelansicht Kategorie-Blase:
"Hier kannst du dem Objekt eine Kategorie zuteilen."

Einstellungen Kategorie:
"Hier kannst du beliebig viele Kategorien erstellen, die du dann den diversen Objekten zuteilen kannst."

Einstellungen ein-/ausblenden:
"Hier kannst du, wenn du willst, die meisten Infos für Objekte ausblenden, solltest du diese nicht benötigen.“

Einstellungen CodeSperre:
„Hiermit kannst du die App mit deiner Displaysperre schützen. Die App greif dabei auf die gleich Möglichkeit zum entsperren zurück, die auch dein Display sichert, ohne dabei die Passwort auslesen zu können.“

**Comment by McFly753** [comment]
Leicht verändert auf (copy/past und dann ggf. angepasst (ich habe es etwas vereinfacht)).

Das sind die Textanpassungen, so wie ich sie in die App einbauen würde:

Rahmen Karte/Liste Datenbankname
"Das ist die Bezeichnung der aktuellen Datenbank. Diese kannst du in den Einstellungen verändern. Wenn du mehr als eine Datenbank angelegt hast, kannst du durch drücken und wischen zwischen diesen umschalten."

> sagen wir immer "drücken" oder "klicken"?

Text Filter für Karte/Liste:
"In diesem Bereich kannst du deine Objekte auf Eigenschaften, Kategorien, Favoriten, Tags oder Freisuche filtern."

Text Filter Kategorie:
"Hiermit kannst du nach bestimmten Kategorien filtern."

Text Filter Tags:
"Hiermit kannst du nach bestimmten Tags filtern."

Karte Info für Bilder/Daten Button:
"Lege fest, ob deine Objekte als Pins in ihrer Kategoriefarbe (soweit genutzt) oder als Mini-Bilder angezeigt werden."

Text Einzelansicht Karte/Ort/Fahne:
"Tippe auf eines dieser Elemente, um dir den entsprechenden Bereich auf der Karte anzeigen zu lassen. Durch lange drücken kannst du die Position des Objektes verändern. Mit dem Karten-Symbol öffnest du den Routenplaner zu diesem Objekt."

Einzelansicht Kategorie-Blase:
"Hier kannst du dem Objekt eine Kategorie zuteilen."

Einstellungen Kategorie:
"Hier kannst du beliebig viele Kategorien erstellen, die du dann den diversen Objekten zuteilen kannst."

Einstellungen ein-/ausblenden:
"Hier kannst du, wenn du willst, die meisten Infos für Objekte ausblenden, solltest du diese nicht benötigen. Evtl. bereits vorhandene Daten werden hierdurch aber nicht gelöscht.“

Einstellungen CodeSperre:
„Hiermit kannst du die App mit deiner Displaysperre schützen."

**Comment by Mojo1917** [comment]
Wir sagen klicken. Ich habe den Text entsprechend angepasst.

Der Rest ist auch umgesetzt. Vielen Dank fürs korrigieren der Texte!

**Comment by McFly753** [comment]
schau ich mir die Tage an.

**Comment by McFly753** [comment]
ich sammle hier:

- Hilfe auch für die Felder URL, Telefon und Adresse anbieten
-

**Comment by Mojo1917** [comment]
Ja richtig. Soll ich diese rausnehmen? Ich hatte diese zusammengefasst, da ich dachte wir brauchen nicht jedes Feld einzeln erklären.

**Comment by McFly753** [comment]
PAsst so. 

Eine Sache noch: willst Du die Karten (Apple oder Google) Sache in den Einstellunegn noich mit einer Hilfe versehen?

**Comment by Mojo1917** [comment]
Ist eingefügt.

**Comment by McFly753** [comment]
Danke!
