### ISSUE TITLE
Kannst Du mir in diesem GutHub-Projket mehr Rechte einräumen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#33]
... so dass ich auch Labels vergeben kann? ODer siehts Du, welche Tickets ich beantwotrtet habe?

(Ich sehe nicht, welche ich beantwotrtet habe... )

**Comment by Mojo1917** [comment]
Klar ich habe dich eingeladen. Nein leider kann ich das auch nicht sehen. Daher habe ich alles direkt mit Tags versehen um den Überblick nicht zu verlieren.
