### ISSUE TITLE
Attribut: bitte jetzt, da das Feld woanders sitzt... > 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#330]
-> dies ohne Klammer anzeigen.
-> und, wenn das Feld noch leer ist, dort in diesem Grau "Attribut" schreiben.

**Comment by McFly753** [comment]
Schau mal, das ausgebaute Attribut sitzt vertikal etwas zu hoch in seinem Feld.

(Check das auch gleich bei Telefon und URL, die sitzen auch zu hoch...)

ODER: Kategorie sitzt zu niedrig (das ist einfacher... :) )

**Comment by Mojo1917** [comment]
Okay haben jetzt alle oben und unten gleich viel Platz ;)

**Comment by McFly753** [comment]
Passt alles, Danke!

Nur, jetzt bitte auch noch auf den selben vertikalen Text-Start achten. 
Kategorie startet weiter drin als Tags und Telefon und Notizen

**Comment by McFly753** [comment]
Danke!
