### ISSUE TITLE
leichte Textänderung:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#331]
Statt „weitere Tags anlegen“ bitte scheiben: „weiter Tags anlegen und bearbeiten“

Statt „weitere Kategorien anlegen“ bitte scheiben: „weiter Kategorien anlegen und bearbeiten“

**Comment by Mojo1917** [comment]
Klaro!

**Comment by McFly753** [comment]
blöderweise ist der Spruch bei Kategorien nun zu lange und wird abgekürzt...

Dann lass bei beiden Sprüchen doch das "weitere" weg, ok?

**Comment by Mojo1917** [comment]
Sorry hatte nicht bedacht, dass das X ja schmaler ist als die anderen. Hab es angepasst.

**Comment by McFly753** [comment]
Danke!
