### ISSUE TITLE
Im Startzustand bitte folgende Felder ausgeblendet lassen: & Syntax bei dem Ausblenden anzeigen 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#334]
1. lass uns die Logik ändern und hier anzeigen, was wir anzeigen, also nicht das "an" schalten, was wir ausblenden. 

b) Somit nenne den Titel des Eintrages in den Einstellungen statt "Elemente ausblenden" "Elemente ein- und ausblenden"

c) und schreibe darunter: "Tippe hier, um die Darstellung von Objekten festzulegen.

2.) Und lass uns somit nur folgende Felder "EINBLENDEN":
- Kategorien
- Objketeigenschaften
- Favorit
- Fahne

**Comment by Mojo1917** [comment]
Ist umgesetzt. Wenn ich es richtig verstanden habe werden standardmäßig nut diese vier angezeigt, richtig?
Kategorien
Objketeigenschaften
Favorit
Fahne

**Comment by Mojo1917** [comment]
Das Update kommt dann wieder mit einem Datenbankupdate, da die Kategorien jetzt auch ausgeblendet werden können. Aber das sollte ja kein Problem sein ;)

**Comment by McFly753** [comment]
Sorry, blende doch die Kategorie auch noch aus. Danke!

**Comment by Mojo1917** [comment]
Okay!

**Comment by McFly753** [comment]
Passt so, Danke!
