### ISSUE TITLE
Wenn beim Bild Verschieben der Pin zu „nah“ an der eigenen Position liegt, kann ich ihn nicht mehr greifen.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#339]

**Comment by Mojo1917** [comment]
Bekomme diesen Fehler leider nicht reproduziert. Habe dennoch die Interaction mit der eigenen Position eingeschränkt. Somit sollte dieser Fehler nicht mehr auftreten.
Kannst du den Pin nicht mehr anklicken, damit er wackelt, oder nicht greifen, um ihn zu verschieben?

**Comment by McFly753** [comment]
Passt, Danke!
