### ISSUE TITLE
Gedanken zur Optik/Didaktik

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#34]
Ich habe mir ein paar Gedanken gemacht, wie die app zum einen schöner aussehen kann und zum anderen intuitiver bedienbar ist. Du hast dies bereits teilweise mal angebracht, ich würde nun auf folgende Lösung gehen. (Ich hoffe, das ist nicht zu viel Aufwand.)

1. Das Iphone ist zu hoch, die wichtigesten Dinge müssen in Daumenreichweite sein. Dher würde ich das "+" wieder nach ujnten rechts nehemn, so wie es Apple auch standartweise hat (Notizen etc.) - unten haben wir genug Platz in unserem 2er Menü.

2. Ich würde wie von Dir mal vorgeschlagen nicht alle Filter/Sortierungen immer anzeigen. Aber dennoch möchte ich das wichtigste anzeiegn. Und dies in Daumennähe. Daher würde ich vorschlagen, diesen Block ein/ausklappen zu können. Hierbei würde ich etwas wählen, das evtl. auf den ersten Blick komisch aussiegt, aber in meinen Augen ist es die beste Lösung:

a) der "minimalisierte" Block kommt nach unten, in einer Zeile über das Menü
b) der "ausgeklappte" Block komtt nach oben, wie bisher

3.) Der "minimalisierte" Block hat von links nach rechts folgende Funktionen: 
- Stern-Filter (an/aus) (den wir rechts neben das Suchefeld in der ausgeklappten Variante legen wollen.)
- "4 Filter" oder "Filtern/Suchen" -> also er zeigt die anzahl der gesetzten Filter an. Suchwörter zählen je als ein Filter. Wenn man auf diesen Bereich klickt, wird der Block "ausgeklappt".
- Sortierung, alle im selben Bereich, es werden zuerst die Richtung umgeschaltet unddann zur nächsten Sortierart gesprungen.

4.) der "ausgeklappte" Block sieht prinzipiell aus, wie unser jetziger Block, nur hier würde ich folgende Veränderungen machen:
- wir starten zerst mit der kleinen Überschrift "Filtern" 
- darunter kommt zuerst das Eingabefeld (lass uns nicht reinschreiben, evl. nur das Such-Icon, denn es ist tehcnisch eher ein Filter)
- neben das Suchfeld kommt der Favoriten-Filter
- unter diese erste Zeile kommen dann die 4 bzw. 8 Filter
- darunter wie gehabt die Sortierer.

> Nur: wie/wo klappe ich diesen Block wiede rzu, dass ich zum minimalisierten Block zurückkehren kann?

s. auch meine Skizze.
![img_4323](https://user-images.githubusercontent.com/493612/34906225-41d4b688-f869-11e7-87a6-bd0c9fcfc412.JPG)

**Comment by Mojo1917** [comment]
Okay ich denke der Punkt ist am einfachsten am Telefon zu besprechen, da er doch die beiden Hauptfenster komplett umstrukturiert.
Ich denke dieser Punkt soll dennoch Anwendung finden richtig? #32

**Comment by Mojo1917** [comment]
Notiz an mich: Das hier nicht vergessen #25

**Comment by McFly753** [comment]
Ja, genau mit 32.

Es tut mir Leid, dass ich hier nun noch verändere, aber das ist eben der SocialPrototyping Prozess, manches merkt man erst, wenn man es sieht. -> dann Tel hierüber.

**Comment by McFly753** [comment]
PS: zusätzlich zum "Einklappen" & "Ausklappen" über erneutes Klicken auf Karte oder Listen-Menü und beim "Asuklappen" auch noch über Klick auf die Filter würde ich neben dem besprochenen zusätzlichen "Einklappen" über eine Wischbewegung nach unten auch eine Wischbewegung nach oben fürs Ausklappen einbauen. Dann können wir uns alles im Vergleich anschauen.

**Comment by Mojo1917** [comment]
Klar wird natürlich gemacht ;) 

Ich denke das Update sollte morgen im Laufe des Tages fertig werden. Es enthält dann die Umsetzung aller Tickets.

**Comment by Mojo1917** [comment]
Ist wie besprochen umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke!

**Comment by McFly753** [comment]
Ist gut, nur noch etwas verwirrend. Lass uns folgendes probieren:

1.) Wir nehmen den ausgeklappten Part auch nach unten, nichts mehr oben.

2.) Wir vertauchen in dem ausgeklappten Part Zeile 1 (Suchleiste etc.) mit Zeile 2(3) (Filter). Das sieht ruhiger aus.

3.) Wir vertauschen auch im eingeklappten Modus die Reihenfolge, weil es mit dem Stern am Anfnag unruhig wirkt: Keine Filter, Stern, Sortierung

4.) Und dann würde ich unten im Menü das (+) in die Mitte nehmen, aber das können wir auch erst im nächsten Schritt machen.

**Comment by McFly753** [comment]
zu 4) - da wir nicht so oft an neuen Locations sind (und somit nicht dauernd neue Objekte erstellen), könnten wir auch folegndes mit dem "+" machen: wir nehmen es wieder nach oben, aber nach oben rechts. Und die Einstellunen nehemen wir nach oben links. Was meinst Du?

**Comment by Mojo1917** [comment]
Punkt 3 ist umgesetzt. Ich habe dem Buttons zudem runde Ecke gegeben (siehe Bild). Ich finde dadurch passen sie besser ins Design. Sollte dir das nicht gefallen nehme ich es gerne wieder raus ;)
![foto 21 01 18 14 39 04](https://user-images.githubusercontent.com/20678932/35190911-08708d58-feb9-11e7-9fbd-e9870de06bb9.png)

**Comment by Mojo1917** [comment]
Punkte 1 und 2 sind auch umgesetzt.

**Comment by McFly753** [comment]
Super, dann nur noch das + nach Oben.

- Und unten wzischen beiden Ansichten würde ich in der mitte einen leichten horizonateln Strich machen, dass man sieht, dass es zei Buttosn sind.

**Comment by Mojo1917** [comment]
Beides umgesetzt. Änderung kommt mit dem nächsten Update.
