### ISSUE TITLE
! Alle Filter müssen natürlich auch ausgeblendet werden...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#341]
... wenn die jeweiligen Felder ausgeblendet sind.

Also hier kann es sein, dass die Kategorien, der Stern und die Tags wegfallen.

Schau mal, was ie beste Logik für Dich ist, mit diesen verschiednen Permutationen umgehen zu können.

**Comment by Mojo1917** [comment]
Okay mache ich. Zusammen mit der möglichen Anpassung des Sortierbuttons. Dazu siehe hier #342 

Das Ganze könnte von Design her schwer werden, da der Stern ja kleiner ist ale alle anderen. Sollen wir nicht alle Elemente dann gleich breit machen? Dann würde es nicht unruhig aussehen, wenn wir rechts ein Element ausblenden links jedoch nicht ;)

**Comment by McFly753** [comment]
Oder wir überlegen uns Anzeigen ür die jeweiligen Permutationen, dass jede sinnvoll aussieht? // Oder was wäre Genua dein Vorschlag?

**Comment by Mojo1917** [comment]
Okay dann nehme ich das so ins nächste Update ;)

Zu dem Standart nehme ich die Elemente rein, die wir in dem anderen Ticket angesprochen haben. Sprich Favorit, Fahne, und die Eigenschaften, richtig?

**Comment by McFly753** [comment]
Ja / Ja, würde ich erstmal drin lassen. Evtl. eben auch die Tags oder Kategorien. Müssen schauen, wie es ruhig aber dennoch interessant aussieht... aber das können wir ja dan auch noch ändern.

**Comment by Mojo1917** [comment]
Okay ist umgesetzt.

**Comment by McFly753** [comment]
Danke!
