### ISSUE TITLE
Animations/Anzeige-Problem

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#343]
Seit wir auch den Umbau mit den Kategorien/Pins gemacht haben, laufen die Zoom/Scroll Animatioen auf der Karte nicht mehr smooth, was die Darstellung der Bildchens oder der Pins anbelangt. Sie flackern, verschwinden manchmal, tauchen dann wieder auf oder es erscheinen unter den Bildchens manchmal Pins.

Können wir das Optimieren, dass es ganz smooth läuft? Das trübt das Benutzungserlebnis etwas.
Danke!!

**Comment by Mojo1917** [comment]
Habe hier nochmals ein paar Anpassungen getroffen. Wenn ich mich jedoch richtig erinnere traten die Probleme nur auf deinem iPhone auf.
Leider kann es bei iOS vorkommen, dass ein Update 'nicht richtig' installiert wird.
Sollten die Probleme mit dem nächsten Update nicht behoben werden könntest du dann bitte wie folgt vorgehen:
1. Update installieren
2. Ein Backup der Daten erstellen. **WICHTIG: Das Backup muss nach dem installieren des Update erfolgen, damit alle möglichen Datenabnkanpassungen erfolgt sind**
3. App deinstallieren
4. App neu installieren und Daten wieder einspielen.

**Comment by McFly753** [comment]
Geht, Danke!
