### ISSUE TITLE
Teilen-Dialog anpassen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#344]
Wenn wir ein Objekt (bzw. Objekte oder Datenbanken) teilen, müssen wir noch den Teilendialog anpassen:

Bitte beachte... andere (Eigenschaften), (Kategorien) oder (Tags) definiert hat ...
(Also hier Kategorien auch mit aufführen (und die Reihenfolge in diesem Satz logsicher machen).

**Comment by Mojo1917** [comment]
Okay.

**Comment by McFly753** [comment]
Danke, jetzt sind Dir da nur lauter so Nummern reingerutscht... ;)

**Comment by McFly753** [comment]
![img_43375999f402-1](https://user-images.githubusercontent.com/493612/50546871-f4d1cb80-0c69-11e9-8943-b961bf9c69c1.jpeg)

**Comment by Mojo1917** [comment]
Sorry... Sind jetzt wieder weg.

**Comment by McFly753** [comment]
Danke!
