### ISSUE TITLE
Die Pins bekommen keine Farben, bleiben alle grau

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#345]

**Comment by Mojo1917** [comment]
Oh sorry hatte dich so verstanden, dass wenn auf keine Kategorie gefiltert wird alle grau sein sollen. Soll ich das grau surch die Farbe der Kategorie ersetzen? Also viele Farben, wenn alle Kategorien angezeigt werden?

**Comment by McFly753** [comment]
JA, genau. Dafür hätte ich die Farben (auf der Karte) gedacht.

**Comment by McFly753** [comment]
Und wie gesagt: ohne die Kategorien würde ich alle Pins in unserem blau machen - und auch nicht rot, siehe wenn Du auf die normale Karte umschaltest: 

![img_4394](https://user-images.githubusercontent.com/493612/49690688-64eea500-fb35-11e8-8fde-a5034408b2f5.PNG)

**Comment by Mojo1917** [comment]
Alles klar. Sind jetzt blau, wenn Kategorie ausgeblendet sonst in der entsprechenden Farbe.

**Comment by Mojo1917** [comment]
Okay sollte dann mit dem nächsten Update funktionieren ;)

**Comment by McFly753** [comment]
Danke!
