### ISSUE TITLE
Überlegung zur "Ortsveränderung":

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#349]
Sollten wir (in der Detailansicht eines Objektes) evtl. nicht die Karte, Koordinaten und Ort/Land zusammennehmen mit folgender Funktion:

- Kurzklick: Sprung zur Karte
- Langklick: Bildposition ändern

> Wäre das nicht einheitlicher/logischer? Nur woher weiss der User, dass der Langklicken kann?

Was denkst Du?

**Comment by Mojo1917** [comment]
Ich denke diese Veränderung des Verhaltens macht Sinn! Jedoch können wir ein solches Verhalten nicht für die beiden Link-Felder einbinden. Siehe dazu dieses Ticket #347 
Ich würde es dennoch so umsetzen, den Nutzer hierauf jedoch im Tutorial hinweisen.

**Comment by McFly753** [comment]
ok!

**Comment by McFly753** [comment]
Fast. Es sollte nur, wenn ich lang drücke, dann nach einer kurzen Zeit eine zweite Rückbestätigung (Vibration/Klick) kommen und dann direkt auf die Karte zum Verändern gesprochen werden. Jetzt springe ich erst, wenn ich den Finge wieder wegnehme... 

UND: um es ganz leicht redundant zu machen, falls es der Nutzer nichgt versteht: lass uns mit einem EinfachClick auf die kleinen Koordinaten auch zu der Ortsveränderung springen.

**Comment by Mojo1917** [comment]
Okay beides umgesetzt.

**Comment by McFly753** [comment]
Danke!
