### ISSUE TITLE
Statistik: auch die Länder verlinken und dem User zeigen, dass er linken kann.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#35]
1) Kannst du hier dann, wenn Du die Suche auch auf Länder erweiterst hast, diese hier auch klickbar machen, dass man Ergebnisse bekommt? (hier könnten wir uns überlegen, ob man zur Kartenansicht springt.)

2) Kannst Du, wenn ich klicke, das ganze Feld blau mahcen (und wenn mein Finger weg ist, spinge ich) - somit ist es für den User ersichtlicher, was passiert.

**Comment by Mojo1917** [comment]
zu 1: Ja das kann ich machen. Ich denke ein springen macht zur Karte auf jeden Fall Sinn.

zu 2: Ja das kann ich auch gerne umsetzen.

**Comment by McFly753** [comment]
Ok, dann las uns immer zur Liste springen - der User kann dann ja immer noch umschalten, der Filter brleibt ja erhalten.

**Comment by Mojo1917** [comment]
Okay Punkte 1 und 2 sind umgesetzt. 
Änderungen kommen mit dem nächsten Update.

**Comment by McFly753** [comment]
Alles klar, Danke!

**Comment by McFly753** [comment]
> Wenn Du mit einer Suchanfrage zurück zur Liste springst, würde ich den Filter ausklappen, dass man die Logik versteht.

> Nimm bitte die Anzahl der Favoriten (und auch das Filtern darauf) hier noch in der Statistik mit auf.

**Comment by Mojo1917** [comment]
Ist übernommen. Kommt mit dem nächsten Update.
