### ISSUE TITLE
Wenn man per Karte einen "leeren" Platzhaltereintrag erstellt, ihn aber nicht verändert und wieder schliesst, würde ich ihn löschen.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#351]

**Comment by Mojo1917** [comment]
Ist bei mir bereits der Fall ;) Bin mir nicht sicher, ob ich das vor dem letzen Update oder danach gemacht habe. Mit dem Nächsten geht es auf jeden Fall!

**Comment by McFly753** [comment]
Danke!
