### ISSUE TITLE
Wenn ich auf der Karte bin, irgendwo reinzoome und dann einen Eintrag anklicke, um zu seiner Detailansicht zu kommen und dann diesen wieder schliesse, würde ich den Zoomeinschnitt der Karte behalten und nicht wieder rauskommen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#352]
... das würde passieren, wenn ich einmal auf den Positionsicon klicke.

**Comment by Mojo1917** [comment]
Okay das Kartenverhalten ist angepasst. Die Karte aktualisiert ihre Ansicht jetzt nur noch beim Ersten Start, bei Suchen oder Filter und auf Knopfdruck ;)

**Comment by McFly753** [comment]
Danke!
