### ISSUE TITLE
Kategorie-Feld ist nicht klickbar in der Detailansicht 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#353]

**Comment by Mojo1917** [comment]
Wir hatte doch auch hier auf eine Auswahl ähnlich zu der in den Filtern gewechselt. Also über das Wischen. Sollen wir beiden Funktionen unterstützen? Also Wischen und Klicken?

**Comment by McFly753** [comment]
Lieber Niklas, da hast Du recht. Das Problem ist, dass ich aber durch klicken auch das Popup-Menüp anzeigen sollte, sonst versteht man es nicht. 

1.)
> Ich habe mir die Filter für Kategorie und Tags angeschaut und ich denke, hier ist es das selbe. Was wäre, wenn Du schon bei einem (leicht längeren) Klick (solange der Klick ist) das Popupmenü anzeigst, weil dann glaube ich ist es intuitiver? (Ähnlich eben des Tastaturmneüs von Apple selbst)

> Also fast bei diesen Funktionen überall so: Kategorieauswahl, Kategorie-Filter, Tag-Filter, Sortierungsbutton

2.)
// Und: Könntest Du das "Kategorie anlegen" in diesem Popup nur solange anbieten, wie es noch keine Kategorie gibt. (Danach soll der User es in den Einstellungen machen, denn sonst stört mich dauernd dieser Eintrag)

**Comment by Mojo1917** [comment]
Okay beide Punkte sind umgesetzt.

**Comment by McFly753** [comment]
Danke!
