### ISSUE TITLE
Sicherung/Export

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#354]
Da der Export manchmal länger dauert, schaltet sich der Iphone-Bildschirm in den Sperrbildschirm und bricht damit die Sicherung ab. Das sollte bei dieser Aktion irgendwie unterbunden werden?
(derzeit klick ich Immer alle paar Sekunden auf den Screen, dass er an bleibt.)

Und, wenn die Datei geschrieben wurde, sollte noch eine Bestätigung kommen.

Und, da ich alle meine Dateien verloren habe: es macht scheinbar doch keinen Sinn, sie in den Locbase Ordner abzuspeichern?

**Comment by Mojo1917** [comment]
Screen wird jetzt während des Exports/Sicherung nicht mehr dunkel.
Für den Import würde ich dies nicht aktivieren. Da die App hier möglicherweise Usereingaben benötigt würde sich das Handy nicht sperren/stromsparen, wenn der Nutzer nicht reagiert.

Wie meinst du eine Bestätigung? Wir zeigen aktuell den Dialog, um die Datei zu teilen. Sollen wir hier einen Dialog vorschalten?

Ja leider ist dieser Ordner nicht für Dateien vorgesehen, die über App Deinstallationen hinweg behalten werden sollen. Ich bin mir auch nicht sicher, wie iOS dieser Ordner bei anderen Events löscht.

**Comment by McFly753** [comment]
Danke!

Bestätigung: wir haben ja zuerst eine Abfrage, WOHIN ich speichern möchte. Wenn ich das auswähle (und die App speichert), sehe ich weder, dass sie speichert noch danach, dass sie erfolgreich gespeichert hat. Diese Bestätigung wäre noch sinnvoll.

Ok. Dann lass uns das wieder wegnehmen, also diesen Ordner, nicht dass jemand anderes auf die Idee kommt, seine Backups da abzulegen.

**Comment by Mojo1917** [comment]
"Supports Document Browser" ist jetzt wieder deaktiviert und der 'Locbase'-Ordner wird nicht mehr angezeigt.

Der Dialog ist eingefügt.

**Comment by McFly753** [comment]
Danke!
