### ISSUE TITLE
Titel geändert auf: die Notizen wandern bei Klick immer noch ganz nach oben. (s. weiter unten)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#357]
Wenn Du die App neu installiert hast, dann blende mal alle Felder in den Einstellungen ein.
Dann geh auf unser Beispielobjekt und klicke dann auf das Notiz-Feld. Dieses Scrollt dann viel zu weit hoch.

**Comment by Mojo1917** [comment]
Fehler ist behoben.

**Comment by McFly753** [comment]
OK, Danke! 

 Können wir nur hier bei "Notiz", "Attribut", "Telefon" und "URL" das Fenster nicht ganz bis oben schieben, sondern den Text so in etwas auch Mitte des über der Tastatur noch übrigen Bildschirms halten?

**Comment by Mojo1917** [comment]
Klar, klebt jetzt nicht mehr oben ;) Je nach Displaygröße jedoch nicht ganz genau in der Mitte des freien Platzes... Das ist leider das altbekannte Keyboard-Problem.

**Comment by McFly753** [comment]
Danke - nur die Notizen (wenn zuerst angeklickt) wandern noch sehr weit hoch - willst Du da nochmals schauen?

**Comment by Mojo1917** [comment]
Ist verbessert.

**Comment by McFly753** [comment]
Bie mir irgendwie noch nicht, die Notizen wandern bei Klick immer noch ganz nach oben.

**Comment by Mojo1917** [comment]
Okay wir jetzt aber wirklich weiter nach unten gezwungen. 
![simulator screen shot - iphone xs - 2019-03-07 at 12 49 36](https://user-images.githubusercontent.com/20678932/53954790-80872e80-40d7-11e9-947d-9086965fcd2d.png)

**Comment by McFly753** [comment]
ok
