### ISSUE TITLE
Erweitertes Objekte Teilen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#358]
Können wir nicht auch auf der Kartenansicht oben rechts im Menü das Objekt Teilen anbieten und diese eben auf der Karte auswählen?

**Comment by Mojo1917** [comment]
Objektauswahl auf der Karte ist jetzt möglich. Jedoch aktuell nur für Bilder. Muss noch erweitert werden für die Pin Auswahl/Das Wechseln zwischen den Ansichten

**Comment by Mojo1917** [comment]
Teilen auf der Karte ist jetzt vollständig umgesetzt.

**Comment by McFly753** [comment]
Super, Danke!

Eine kleine Anpassung: springe nach dem Start des Exports bitte nicht in der Karte herum oder verändere den Zoom, das irritiert ein wenig.

**Comment by Mojo1917** [comment]
Ist korrigiert.

**Comment by McFly753** [comment]
Danke

**Comment by McFly753** [comment]
Irgendwie kann ich die Bilder/Pins fast nicht greifen/auswählen, check das bitte noch mal.

**Comment by Mojo1917** [comment]
Okay ist überarbeitet und zuverlässiger ;)

**Comment by McFly753** [comment]
Ich kann keine Objekte auf der Karte mehr greiffen (bzw. ich sehe nicht, dass sie aktiviert wurden)?

**Comment by Mojo1917** [comment]
Oh sehe ich auch gerade. Sorry wird gefixt ;)

**Comment by Mojo1917** [comment]
Okay behoben und jetzt auch wie versprochen verbessert ;)

**Comment by McFly753** [comment]
Danke!
