### ISSUE TITLE
Objekte Importieren

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#359]
- können wir das Importieren nicht auch oben rechts in das Menü legen (bei Karten und Listenansicht) und dann eben dem User die Datei auswählen lassen (so wie beim Gesamtbackup)?

- können wir in den Einstellungen bei Datenbank nicht auch das im Menü arbeiten, dass er eine Datenbank Importieren kann?

**Comment by Mojo1917** [comment]
Ist umgesetzt. Da die Datei jedoch erst nach dem Einlesen Aufschluss darüber gibt, ob es sich um Objekt / Datenbank / etc. handelt würde ich an jeder Stelle alles zulassen. Sonst wählt der Nutzer eine Datei und erst später nach dem Öffnen wird dann von der App abgebrochen. Der Nutzer kann ja jederzeit abbrechen, wenn er feststellt, dass er die falsche Datei erwischt hat.
Was denkst du?

**Comment by McFly753** [comment]
Ja, ich würde diesen Menüpunkt in den Einstellungen unter Datenbank nur "Datenbank importieren" nennen. (auch wenn ich hier mehr importieren kann)

Und lass es uns in dem anderen Menü statt "Datei importieren" > "Objekt importieren" nennen, ist konsistenter.

**Comment by Mojo1917** [comment]
Ist angepasst.

**Comment by McFly753** [comment]
Danke!
