### ISSUE TITLE
Fehler im "Offline-Modus"

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#361]
<img width="292" alt="bildschirmfoto 2018-12-30 um 19 46 48" src="https://user-images.githubusercontent.com/493612/50546939-a7eef480-0c6b-11e9-8322-f05c0c064fc1.png">

**Comment by McFly753** [comment]
Wenn ich mal kein Internet habe, wird mir der Ort etc. ja nicht aufgelöst. Das Problem ist, dass es dann, wenn ich wieder Internet habe, auch nicht wird. Ich muss dann in diesen Ort reingehen und auf den positions-Veränderungs-Screen gehen und dann erst zieht er sich die Infos aus dem Netz. Können wir das nicht automatisieren. Dass Du Dir merkst, sozusagen als Script, was er noch abarbeiten muss?

Wenn das geht, würde ich hier den Text abändern:
"... Internetverbindung gerade nicht ausreichend. Die App wird zu einem späteren Zeitpunkt versuchen, die Ortsangaben aus dem Netz zu laden." (o.ä.

**Comment by McFly753** [comment]
Siehe auch Ticket #365

**Comment by Mojo1917** [comment]
Klar, das lässt sich umsetzen. Dann lass uns doch einen Text bei dem Ort ähnlich zu 'Adressermittlung fehlgeschlagen' anzeigen, wenn die Ermittlung fehlgeschlagen ist. Hierdurch kann die App dann erkennen, bei welchen Orten sie erneut ermitteln muss. 
Was hälst du davon?

**Comment by McFly753** [comment]
Ok, alles klar, Danke!

**Comment by Mojo1917** [comment]
Wenn die Ortsermittlung fehlschlägt wird die App jetzt zu einem späteren Zeitpunkt versuchen die Daten erneut abzurufen. Dies passiert stromsparend :)
Um ein direktes Neuladen zu erzwingen kann die App einmal abgeschossen und wieder geöffnet werden.

Zudem gibt es jetzt zwei 'neue Flaggen'. 
Eine mit einem Ausrufezeichen -> Fehler beim Laden
Die Andere mit einem Fragezeichen -> Wirklich 'Unbekannt'

**Comment by Mojo1917** [comment]
Das klicken habe ich jetzt nicht drin, da normalerweise auf der Fahne ja eine andere Funktion liegt ;) Kann ich aber gerne überschreiben, wenn der Ort noch nicht geladen ist.

Das Nachladen erfolgt spätestens fünf Minuten nachdem das Handy wieder mit dem Internet verbunden ist.

**Comment by McFly753** [comment]
Ok, Danke! (Lass uns das nachladen später (hier ausnahmsweise und eben nur über diese Fahne) urüberlegen.

**Comment by McFly753** [comment]
Danke!

Könntest Du die beiden Icons nur genauso hoch wie Fahne machen und, damit sie grafisch besser passen, den Bereich evtl. komplett blau füllen und das ? oder ! invertiert (weiss) darstellen und von der Schriftart etwas größer (weil der Kasten ja höher wird) und evtl. fett?

(Und siehe oben noch, dass ich klicken kann.)

**Comment by McFly753** [comment]
Es kommt mir so vor, als müsste ich "manuell" etwas machen, dass er mir die bisher nicht geladenen Adressen nochmals versucht zu ermitteln. Also ich hatte mal 10min gewartet, und es passiert nichts. Wenn ich in ein "Rufzeichen"-Objekt gehe, dann arbeitet er alle ab.

NUR: dann auch nicht alle, nur die mit Koordinate. Die ohne Koordinate läßt er auf ! und erst wenn ich manuell auf das ! klicke, prüft er und schaltet auf ? um.

**Comment by Mojo1917** [comment]
Also ich es im Code nochmal überprüft und er versucht bei nicht geladenen Adressen alle 5 Minuten die Daten neu zu laden. Natürlich nur, wenn die App offen ist.
Jedoch aktualisiert die App das UI nicht, wenn diese Daten geladen wurden. Sondern erst, wenn z.B. die Ansicht geschlossen wird oder eine neue geöffnet.
Ich hatte dies nicht reingenommen, da ich es unpraktisch fand, wenn die App die Daten aktualisiert und dann z.B. die Ansicht neu lädt während ich gerade Infos bearbeite. Wenn du möchtest kann ich dies jedoch gerne einbinden ;)

Der zweite Fehler ist jetzt behoben!

**Comment by McFly753** [comment]
Passt, Danke!
