### ISSUE TITLE
Wenn ich eine Suche aus der Statistik öffne, bitte nur über die notwendigen Felder suchen lassen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#363]
... also z.B. wenn ich auf einen Ort oder Land suche, dann nicht auch den "Namen" und das "Attribut" angeschaltet lassen bei der Suche.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Da wir jetzt auch Filter für Tags haben wird der Tag nicht mehr in der Suche eingefüllt, sondern der Tag-Filter wird auf den richtigen Wert gestellt.
