### ISSUE TITLE
Problem mit den Füllbildern...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#364]
1.
Ich klicke auf die Karte und erstelle ein neues Objekt mit einem "Füllbild".
Dann öffne ich meine Fotos und importiere ein Bild OHNE Koordinate.
Dann trägt er - und ich bestätige - dass ich die Koordinate aus einem anderen Bild übernehmen möchte und wähle das "Füllbild" - er übernimmt aber dann für dieses Bild keine Koordinaten.

2. 
Ich sollt keine zwei Füllbilder hintereinander einfügen können. Also, wenn es ein Bild gibt, Füllbild oder normal, würde ich diesen Menüeintrag nicht mehr anzeigen.

3. 
Ich kann, auch wenn ich das Objekt "verändert" habe, damit es "bleibt" (z.B. Namen verändert) nicht mit Langklick auf die Positionsveränderung kommen. Ich denke, das könnte mit dem Fehler aus 1.) zusammenhängen.

**Comment by Mojo1917** [comment]
1. Okay, habe ich getestet und in der neuen Version funktioniert es
2. Okay, die Option wird jetzt nur angezeigt, wenn es noch kein Bild gibt
3. Habe ich auch getestet und in der neuen Version funktioniert es

**Comment by McFly753** [comment]
Danke!
