### ISSUE TITLE
Können wir eine "Fragezeichen" Fahne in die Fahnenliste hinzunehmen, wenn die Koordinate auf "Unbekannt, Unbekannt, Unbekannt" sitzt?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#365]
Und: dann könnten wir diese Fahne hernehmen, dass man draufklicken kann, und dann wird neu gecheckt, ob es doch Daten aus dem Netz gibt. (Siehe Ticket #361)

Doch evtl. bräuchten wir dann zwei so Lückenfüllerfahnen: 
- die Daten konnten noch nicht abgerufen werden (weil keine Internetverbindung)
- der Pin liegt wirklich in "Unbekannt".

Was denkst Du?

**Comment by Mojo1917** [comment]
Setze ich dann zusammen mit dem anderen um ;)

**Comment by McFly753** [comment]
Danke! :)

**Comment by Mojo1917** [comment]
siehe #361
