### ISSUE TITLE
Können wir die blaue Outline um die Bilder einen Tick dezenter machen?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#366]
... evtl. auf die selbe Strichdicke wie das "+" links oben darüber?
![img_5032](https://user-images.githubusercontent.com/493612/50550433-93cae780-0cab-11e9-80a3-66f78a5273d9.jpg)

**Comment by Mojo1917** [comment]
Rahmen ist angepasst.
Auflösung kommt morgen dran ;)

**Comment by Mojo1917** [comment]
Auflösung ist jetzt scharf!

**Comment by McFly753** [comment]
Danke, passt!
