### ISSUE TITLE
Bitte Reihenfolge in Einstellungen ändern

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#369]
1. "Vereinfachungen" bitte vor "Objekteigenschaften, Tags & Kategorien"

2. Eine neue Gruppe "Tips & Hilfe" einfügen, über der Gruppe "Sonstiges" und hier (in dieser Reihenfolge) folgende Punkte aufnehmen:
- Überblick
- Beispielsobjekt einfügen
- Beispieldatenbanken einfügen
- Tour starten

3. Codesperre und Impressum ist dann noch unter "Sonstiges" ganz zum Schluss.

**Comment by Mojo1917** [comment]
Ist angepasst

**Comment by McFly753** [comment]
Danke!
