### ISSUE TITLE
Fehlende Ortsbenachrichtigung

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#37]
Wird als letztes umgesetzt sobald der Rest der App steht.

**Comment by McFly753** [comment]
OK! // Bzgl. Zeitbenachrichtigung: ich hatte es mit einem Rückdatierten Objekt probieret, aber es hat nicht erinnert... ;( -> Evtl. neues Ticket hierfür

**Comment by Mojo1917** [comment]
Okay... Die Benachrichtigung sollte immer um 11 Uhr am Jahrestag kommen. Die Gerätezeit darf aber nicht manuell nicht verstellt werden. Damit kommt iOS komischerweise nicht klar.

**Comment by McFly753** [comment]
Nein, ich habe die Objektzeit so gestellt, dass dann am nächsten Tag eine Benachrichtigung gekommen wäre. Ist sie aber nicht...

**Comment by Mojo1917** [comment]
Okay ich schaue mir das nochmal an ;)

**Comment by McFly753** [comment]
Ja, habe ich. // Dennoch sollte man, wenn der User deise Funktion freischaltet, nochmals überprüfen, ob Mitteilungen freigegeben sind. Oder?

**Comment by Mojo1917** [comment]
Ja ein solcher Dialog ist schon eingebaut. Wollte nur sichergehen. 
Ich schaus mir nochmal an.

**Comment by McFly753** [comment]
Ja, ganz am Anfnag. Aber sagen wir, ich sage da nein, dann sollte ich heir nochamls daran erinnert werden, wenn ich trotz "nein" eine Mitzeilung anschalte.

**Comment by Mojo1917** [comment]
Den Punkt verstehe ich nicht ganz.

**Comment by Mojo1917** [comment]
Also ich habe es heute nochmal getestet und die Benachrichtigung ist problemlos um 11:00 gekommen.
![foto 18 01 18 15 49 04](https://user-images.githubusercontent.com/20678932/35082768-5307275e-fc67-11e7-933a-d2930f157f62.png)

**Comment by McFly753** [comment]
Mein Gedanke ist der: Du frägts am Anfnag, wenn ich die App zum ersten mal benutze, ob ich benachrichtigugen bekommen möchte. Sagen wir, ich sage hier nein. Dann würde ich aber, wenn ich dann dennoch die Funktion der Benachrictign einstelle (die so ja keinen Sinn macht, weil ich habe die Benachrichtigug ja abgeleht). darum würe ich in diesem Fall die Frage nach der Benachrichtigug nochmals abfragen.

**Comment by Mojo1917** [comment]
Okay jetzt habe ich das verstanden. Das geht leider nicht. Sobald der Nutzer diese Erlaubnis einmal verweigert hat kann die App diese nicht mehr anfordern. iOS lässt dies nicht zu. Die einzige Möglichkeit ist den Nutzer zu bitten die Erlaubnis in den Einstellungen er erteilen. 
Leider ist iOS hier sehr streng.

**Comment by McFly753** [comment]
Ok, verstehe! / evtl. fragen wir diese Dige dann erst später an und nicht ganz am Anfang?

**Comment by Mojo1917** [comment]
Okay der Dialog erscheint jetzt sobald der Nutzer zum Ersten Mal in die Einstellung zu den Mitteilungen geht.

**Comment by Mojo1917** [comment]
Machen die Jahrestagsbenachrichtigungen in dem aktuellen Update immer noch Probleme?

**Comment by McFly753** [comment]
Ich habe die Benachrichtigungen noch nicht getestet. Mache ich noch.

**Comment by McFly753** [comment]
Muss ich noch testen
