### ISSUE TITLE
Bitte den Text in diesem Fenster ändern:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#371]
Die Datei wurde erfolgreich exportiert.

(das denke ich reicht und ist verständlicher, oder?)

![img_5407](https://user-images.githubusercontent.com/493612/50725116-96a65c00-1133-11e9-8929-b60291543e7b.PNG)

**Comment by Mojo1917** [comment]
Ist angepasst.

**Comment by McFly753** [comment]
Danke!
