### ISSUE TITLE
Ansichtsoptimierung in Detailansicht...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#372]
... wenn weniger Felder angezeigt werden.

- > Was wäre, wenn wir folgende Regel machen:

- zwischen Fahne und Ort ist eine Zeile Abstand, zwischen Ort und Datums auch eine Zeile und zwischen Datums und Koordinaten auch eine Zeile. // Überflüssigen Platz gleicht die Karte von unten her aus, also sie wird größer nach oben, wenn mehr Platz vorhanden ist, als diese Texte und diese 3x Leerzeile.
- wenn Fahne und Favorit weg ist, rutscht alles nach oben (hast Du)

**Comment by Mojo1917** [comment]
Ist umgesetzt!

**Comment by McFly753** [comment]
Danke!
