### ISSUE TITLE
Können wir dem Nutzer frei lassen, welche KartenApp er auf seinem Iphone benutzt?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#375]
Also GoogleMaps oder Karten.

> Können wir das in den Einstellungen unter Sonstiges anbieten, auszuwählen?

**Comment by Mojo1917** [comment]
Wann meinst du? Wenn er die Navigation zu einem Objekt startet?

**Comment by McFly753** [comment]
Nein, dass er es in den Einstellungen festlegen kann, mit welcher App er das dann aufmachen möchte?

**Comment by Mojo1917** [comment]
Ja das ist möglich. Ich füge eine entsprechende Option unter Sonstiges in den Einstellungen ein ;)

**Comment by McFly753** [comment]
Danke! :)
