### ISSUE TITLE
Problem beim "Lang-Anklicken" eines Objektes auf der Karte, da ich eigentlich immer ein leeres Objekt erstelle

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#376]
... kannst Du hier einen gewissen Abstand zu bestehenden Objekten einhalten, so dass ich diese "erwischen" kann?

**Comment by McFly753** [comment]
Ok, verstehe. Was ist, wenn wir es so machen, aber nur "invertiert". Weil das problem ist ja der "Freiklick" irgendwo auf der Karte, was ist, wenn wir nur diesen "einschränken", sobald ein Bild in der Nähe ist? // Aber wir können es auch einfach mal so wie von Dir beschrieben ausprobieren, wir sind eh im "Social Prototyping" Modus... ;)

**Comment by Mojo1917** [comment]
Ich verstehe was deine Idee ist, jedoch denke ich, dass es recht schwer den Freiklick einzuschränken. 
Aktuell erkennen wir einen Klick auf ein Objekt, indem wir iOS überwachen lassen, ob der Nutzer lange auf das Bild drückt (oder jetzt auf den unsichtbaren Rahmen, den ich eingefügt habe)
Ein Klick auf die Karte wird einfach dann ausgelöst, wenn der Nutzer nicht auf ein Bild drückt ;)

Wenn wir den Klick auf die Karte einschränken wollen müssten wir bei jedem Langedrücken auf die Karte erst anhand von Zoomstufe und Koordinate des Klicks berechnen, welches Objekt der Nutzer mit der höchsten Wahrscheinlichkeit gedrückt hat (Oder eben nicht). Ich denke das ist auf jeden Fall möglich, aber es könnte ein wenig dauern, bis wir hierfür eine gute Formel gefunden haben ;)

**Comment by McFly753** [comment]
Ok, verstehe. Dann mach es erstmal so, wie von dir vorgeschlagen und wir schauen es uns an!

**Comment by McFly753** [comment]
Ich schliesse das mal und teste es, wenn ich mehr Objekte habe.
