### ISSUE TITLE
Leichte Logikanpassung bei Ort/Koordinate/Karte auf der Detailansicht

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#377]
Lieber Niklas,

wir haben hier schon viel angepasst, aber wir müssen es noch logischer machen. (mit leichter Erweiterung, wenn einfach)
Vorschlag: 

1.) Kurzclicks:

- Fahne: Sprung auf Karte, aufzoomen auf Land (so grob wie Du es auch in der "Suche" in der Karte implementiert hast) - ggf. danach auf Pin zentrieren?
- Ort-Zeile: Sprung auf Karte, aufzoomen auf Ort (so grob wie Du es auch in der "Suche" in der Karte implementiert hast) - ggf. danach auf Pin zentrieren?

- Adress-Zeile: Sprung auf Karte, Zoom auf PIN
- Karte: Sprung auf Karte, Zoom auf PIN

- Koordinaten: (Ausnahme): Positionsveränderung

2.) Langclicks:
- Fahne/Ortzeile/Karte/Koordinaten: Positionsveränderung
- Adresszeile: Adress-Popup

Danke! Liebe Grüße, Matthias

**Comment by Mojo1917** [comment]
Okay also die Anpassungen können wir soweit einfügen, bis auf den 'Zoom auf Land' und 'Zoom auf Ort'. Hierfür müssten wird noch eine zusätzliche Datenbank erstellen, die für jedes in der Datenbank erfasste Land/Ort die entsprechenden Parameter speichert, da diese sonst Offline nicht verfügbar sind.
Was hälst du anstatt dessen davon, wenn wir nicht genau auf das Land und der Ort zoomen, uns aber in der der ZoomStufe z.B. an der Größe Deutschlands und Miesbach orientieren? Wir treffen dann nur nicht immer genau das ganze Land/Ort.

**Comment by McFly753** [comment]
Ok, ja, lass es uns so versuchen. (Zum Verständnis: beim "Suchen" in der Karte geht aber diese Zoomstufe, oder? Die hatten wir ja mal eingeführt?)

**Comment by Mojo1917** [comment]
Ja, hier geht die Zoomstufe. Bei der Suche laden wir Daten zu den gefunden Orten herunter. Diese beinhalten dann auch die genaue Fläche, die das Ergebnis auf der Karte belegt. Da die Funktion zum auf die Karte springen jedoch immer und unverzögert funktionieren sollte müssten wir diese Daten alle offline erfassen.

**Comment by Mojo1917** [comment]
1. kommt noch
2. ist so umgesetzt.

**Comment by McFly753** [comment]
Lieber Niklas, dann lass uns diese Info doch zu jedem Baum mit abspeichern - dann kannst Du sie bei bedarf auch gleich "nutzen"? (Also Du fragst sie beim Geo-Tagen mit ab, sollte doch gehen, oder?)

**Comment by Mojo1917** [comment]
Ja klar wir können die Info zusätzlich mitladen. Kommt dann mit dem nächsten Update ;)

**Comment by Mojo1917** [comment]
Okay ist angepasst. Die App lädt jetzt zusätzlich diese Daten für jedes Objekt. 
Ich habe hierfür die Datenbank angepasst. Die Datenmigration erfolgt jedoch wie die letzten Male automatisch beim ersten Öffnen der App nach dem Update.

**Comment by McFly753** [comment]
Lieber Niklas, danke. Ein paar Kleinigkeiten noch:

1.) Bitte nach Anspringen des Landes/Ortes danach dennoch auf den Baum zentrieren. (Das bedeutet zwar, dass dann z.B. Deutschland nicht mehr ganz zu sehen ist, ist aber sinnvoller, als wenn mein Baum irgendwo dann rumliegt.

2.) Bei dem Langklick auf die Adresse stimmt was nicht. zu 80% öffnet er das Adressveränderungsfenster kurz und macht es dann gleich wieder zu.

3.) Bei der Positionsveränderung das wackelnde Bild bitte auch zentrieren.

4.) Bei der Positionsveränderung eines "?"-Bildes wird dieses nicht "wackelnd" eingestartet und ich kann es auch nicht "wackeln" lassen.

5.) Kannst Du (temporär) irgendwas einbauen, dass alle alten Bilder durchscannt, dass alle diese Infos mutgeladen werden? Oder kann das der User mit jedem baum manuell selbst machen, indem er z.B. die Position des Hauptbildes leicht verändert?

**Comment by Mojo1917** [comment]
1. ist angepasst.
2. Ist behoben!
3. ist umgesetzt
4. bekomme ich leider nicht reproduziert. Wie gehst du hier vor?
5. Du hast recht das hatte ich vergessen. Die App lädt diese Daten für alle Objekte aus alten Versionen innerhalb der ersten paar Starts nach dem neuen Update nach. Je nach Anzahl der Objekte kann es ein Zeit dauern.

**Comment by McFly753** [comment]
ok, 4 tel

**Comment by Mojo1917** [comment]
zu 4: Sollte jetzt behoben sein. Wenn ein Bild/Objekt ein Fragezeichen hat kann bei diesem die Position ganz normal verändert werden ohne Einschränkungen.

**Comment by McFly753** [comment]
zu 4: das Bild wackelt zwar und ich kann es verschieben, doch beim erneuten Klick (also dem beenden des Wackelmoduses) bleibt das "Schreibe neue Positionsdaten" Fenster so stehen (also die App hängt sich hier auf)

**Comment by McFly753** [comment]
Stop! // ich habe diesen "Aufhänger" bekommen, weil ich hier gerade eine Notifikation einer anderen App reinbekommen habe. Das hatte ich schonmal bei was anderem... weisst Du, was das sein kann?
