### ISSUE TITLE
In den Einstellungen jeweils auch den Objekteigenschaften-Eintrag, den Tags-Eintrag und den Kategorien-Eintrag ausblenden, wenn eines oder mehrer von diesen ausgeblendet sind. 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#379]
(Damit musst Du aber auch blöderweise die Überschrift dieser Gruppe immer anpassen. Oder wir finden einen neuen Namen... z.B. einfach Eigenschaften?)

**Comment by Mojo1917** [comment]
Was hälst du davon, wenn wir die entsprechenden Zeilen leicht transparent schalten (ähnlich dem Sortierbutton in der Kartenansicht) und ein Klicken auf diese nicht mehr zulassen? Dann sieht der Nutzer, dass es diese Option theoretisch gibt und wir müssen die Überschriften nicht immer neu anpassen?

**Comment by McFly753** [comment]
Ja, Gute Idee!

**Comment by Mojo1917** [comment]
Okay, ist umgesetzt.

**Comment by McFly753** [comment]
danke, passt. 
Willst Du nur - wenn Objekte ausgeblendet sind, die sich auf die Benennungen auswirken - dort es nicht grau hinterlegen (damit machen wir optisch das Gegenteil), sondern einfach den Text dort (In den Feldern und in der Überschrift) auch einfach nur ausgraben (und nicht knickbar machen)?

**Comment by Mojo1917** [comment]
Ist angepasst

**Comment by McFly753** [comment]
Danke!
