### ISSUE TITLE
Absturz der App

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#38]
Also ich habe jetzt fast 2 Std getestet, ich konnte es etwas eindämmen, aber noch nicht 100% reproduzieren.

- Der Absturzt passiert bei schnellem UMschalten zwischen KartenListenansicht und auch Filter ein/ausklappen. Da ich einfach fast Minutenlange wie ein Blöder hinundhertippen muss, bis es mir abstürzt, kann ich bisher noch nicht genau sagen, was es auslöst. Es kann auch sein, dass ich auf dei Map/Daten umschakten gekommen bin doer auf den Favoriten - ich war mehr auf dieser linekn Seite (mit ständigem Umschalten der Ansichten und abundzu eben auch Filter ein/ausklappen.

- ich konnte den Absturz jetzt ca. 7 mal wiederholen.

- danach konnte ich nur einmal die App neu starten, aber beim zweiten ABsturz dann auch (wie bei den anderen) lässt sich die App dann nciht mehr nutzen, da sie nach kurzem Aufblitzen des Inhalts (ich sehe immer noch kurz die Karte) sie wieder abstürzt. 

- ich bekommen den Absturz aber ohne ein angelegtes Objekt nicht hin.

- Anfangs hatte ich 2-3 Objeket mit Bildern, da habe ich den Absturz schneller reproduzieren können.

- Ich habe dann die Nilder auf jeweils nur eines reduzierzt und habe den Absturz auch noch hinbekommen.

- Dann habe ich nur merh ein Objekt angelegt mit Bild, hier war es schon schwerer, den Absturzt hinzubekommen.

- Aber ich habe ihn auch mit nur einem Objket ohne BIld hinbekommen, nur das schaffe ich gerade nicht merh.

Also: App installieren, öffnen, beide Fenster mit "immer erlauben" und "erlauben" bestätigen, zwei Objekte mit je einer Aufnahme erstellen und dann wie blöd hinundherschalten und rumdrücken - normalerweise stürzt es dann ab UND KANN DANN NICHT MEHR GEÖFFNET WERDEN. 
Es scheint also, als würde durch das Umschalten der Ansichten, das Ein/ausklappen der Filter oder auch das Umschalten der SAT/Dat oder auch des Sterns (sonst komme ich nirgends hin) irgendwas geschrieben zu werden, was die App aufhängt und es dann beim Neustart auch WIEDER aufhängt (das aber eben noch nicht vor dem Rumschalten) - hast Du ne Idee?

Ich teste moregn weiter, ich bekomme gerade einen Absturz nicht mehr so einfach hin...

**Comment by Mojo1917** [comment]
Okay super vielen Dank für die genau Beschreibung. So einfach kann ich das nicht beurteilen. Ich schau mir das aber gleich im Code und auf meinem Gerät an. Dann sollte ich das finden ;) 
Zusätzlich sollte ich in den nächsten Stunden von Apple einen Absturzbericht von deinem Gerät erhalten. Spätestens dieser sollte zeigen, wo der Fehler genau entsteht.

**Comment by McFly753** [comment]
Zusatz: ich habe gerade 4 Objekte angelegt gehabt, und ich habe nur nach links und dann nach rechts in der Karten/Listenansicht geschlatet und dann ist mir die App abgestürzt... ich installiere gerade neu... ;) (Der Bug scheint mit mehr Objketen schneller herbeirufbar zu sein)

**Comment by McFly753** [comment]
Zusatz: jetzt habe ich gesehn, wann die App abgestürzt ist: ich habe zweimal auf Liste geklickt und dann einmal auf Karte und dann ist die App abgestürzt...

**Comment by McFly753** [comment]
![img_4412](https://user-images.githubusercontent.com/493612/35178360-5c603b52-fd88-11e7-9346-ad8c4a9c4db6.PNG)

**Comment by Mojo1917** [comment]
Also den Absturzberichten zur Folge hängt der Fehler mit dem Laden der Karte zusammen. Das Cluster-Plugin scheint zu versuchen die Daten anzuzeigen bevor es entweder fertig initialisiert ist oder die Daten noch nicht vollständig geladen sind. Ich werde diesen Fehler abfangen. Dann sollte die App nicht mehr abstürzen. Werde mir das aber noch genauer anschauen.

**Comment by McFly753** [comment]
Ok, gut!

**Comment by Mojo1917** [comment]
Okay ich habe die Absturzberichte von deinem Gerät gelesen und der Fehler entsteht, wenn die Karte versucht Daten zu zeigen, die garnicht geladen sind. Der Fehler hängt mit dem Plugin zusammen, dass sich um das zusammenfassen der Objekte kümmert wenn es zu viele auf einem Punkt sind.
Das Plugin ist derzeit nicht aktiv, bzw. die Anzahl der Mindestobjekte sehr hoch. Da es sich jedoch neben den Zusammenfassen auch um die Anzeige kümmert habe ich es nicht entfernt. 
Wie es dazu kommt, dass das Plugin auch nach einem Neustart versucht diese Daten zu zeigen kann ich nicht sagen (Ist ja ein externes Plugin). 

**Wenn das Plugin versucht Daten zu zeigen die nicht geladen sind wird der Fehler ab jetzt abgefangen und die App stürzt somit an diesen Stellen nicht mehr ab. Ich habe Ihn in allen Fällen behoben, die mir von deinem Gerät gesendet wurden, bzw. an allen Weiteren die möglich gewesen sind**

Hiermit sollte der Fehler komplett behoben sein. Ich werde es aber während der weiteren Entwicklung im Auge behalten.

**Comment by Mojo1917** [comment]
Zusatz: Ich habe einen weiteren Fehler gefunden.

Hat man ein Objekt ohne Bild abgespeichert und wechselt dann in der Karte auf die Bild Ansicht stürzt die App ab, weil sie versucht ein nicht vorhandenes Bild zu laden. Da die App bei einem Neustart in der Karte startet und automatisch auch in der Bild Ansicht stürzt sie immer wieder ab.
Der Fehler ist behoben und auf der Karte wird in diesem Fall ein Samplebild gezeigt.

**Comment by McFly753** [comment]
bisher ist aber der Fehelr nicht merh aufgetreten...
