### ISSUE TITLE
Optimierungsvorschläge von Deiner Seite?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#380]
Lieber Niklas, hättest Du noch Optimierungen/Anpassungen von Deiner Seite her?

**Comment by Mojo1917** [comment]
Alte Backup-Dateien werden jetzt nicht mehr zugelassen.

**Comment by Mojo1917** [comment]
Die Auswahl wird jetzt auch zwischen den Ansichten übernommen.
