### ISSUE TITLE
Tag-Filter & Kategorie-Filter-Button optimieren

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#381]
Lass uns die Bedienung so machen, dass wenn man einmal auf diesen Filter klickt (also ohne das erscheinende Popup zu verwenden), man den Filter wieder ausschaltet. Also auf alle

**Comment by Mojo1917** [comment]
Ist umgesetzt. Trifft der Nutzer keine Auswahl wird der Filter gelöscht!

**Comment by McFly753** [comment]
Danke!
