### ISSUE TITLE
Popup bei Sortierbutton, Tagfilter und KategorieFilter liegt etwas zu tief...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#382]
... so komme ich manchmal beim klicken auf den untersten Eintrag. 
Lass mit dem Kasten einfach etwas Abstand zum auslösenden Button

**Comment by Mojo1917** [comment]
Okay, der Fehler ist behoben ;)

**Comment by McFly753** [comment]
Danke!
