### ISSUE TITLE
Evtl. bereits mit anderem Ticket erledigt: Export-Popup...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#385]
Von Johanna: Mir wurde dieses Textfeld angezeigt, obwohl ich den Teilungsvorhang abgebrochen habe. War wiederholt so...

<img width="228" alt="bildschirmfoto 2019-01-13 um 02 37 14" src="https://user-images.githubusercontent.com/493612/51077070-291ea080-16dc-11e9-9784-83f496c57d52.png">

**Comment by Mojo1917** [comment]
Sobald eine andere App ausgewählt wurde wird die Datei an diese übergeben. Locbase betrachtet dies als 'geteilt'. Wie die andere App mit der Datei umgegangen ist kann Locbase nicht beurteilen. (Nicht jede App kommuniziert hier richtig, ob die Datei wirklich verwendet wurde oder nicht).
Können wir auch leider nicht besser abfragen. Sollen wir den Text des Popup ändern?

**Comment by McFly753** [comment]
Kannst Du feststellen, an welche App die Datei übergeben wurde? Wenn ja, dann schreib in das Popup:
"Die Datei wurde erfolgreich an "..." übergeben."

Oder?

**Comment by Mojo1917** [comment]
Leider nicht möglich. Siehe #390 

Wir können den Popup-Text jedoch zu 
'Datei weitergegeben'
'Die Datei wurde erfolgreich an die von dir gewählt Option weitergegeben.' 
abändern. Dann ist das vielleicht nicht mehr so irreführend.

**Comment by McFly753** [comment]
"Die Datei wurde erfolgreich an die von dir gewählt Option bzw. App weitergegeben."

ODER: wir lassen das Fenster weg, weil es macht nach der Weitergabe, wo ich dann abbrechen kann, wirklich keinen Sinn mehr.

**Comment by Mojo1917** [comment]
Wir können es auch weglassen. Meist geht ja eine andere App auf und ich weiß ja, ob ich es gespeichert habe oder nicht ;)
Also nehme ich es wieder raus?

**Comment by McFly753** [comment]
Ja, nimm es raus und dann testen wir es.

**Comment by Mojo1917** [comment]
Klaro ich werden den Fortschritt auch hier anzeigen. Sollen wir dies beim Import dann auch machen? Ist dann einheitlicher!

**Comment by McFly753** [comment]
Ja, das wäre gut! Danke!

**Comment by McFly753** [comment]
Ich konnte es mit meinen wenigen Daten nicht wirklich testen, schliesse das Ticket aber mal...
