### ISSUE TITLE
Beim Teilen ein Größenwarnung bzw. Anzeige oder Empfehlung für den Übertragungsweg anzeigen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#386]
... es war bei 50% meines Team so, dass sie einfach eine 200MB Datei per Email teilen wollten etc.

> Hättest DU eine Idee, wie wir hier die User besser an die Hand nehmen können, dass sie sich für den richtigen Weg entscheiden? ;)

**Comment by Mojo1917** [comment]
In den meisten Fällen sind ja schon 20-30MB per Mail ein Problem. Wir könnten noch einen weiteren Dialog vorschalten, der ab 30MB angezeigt wird und den Nutzer darüber informiert, das die Datei recht groß ist und ein Teilen über einen Cloud-Dienst empfohlen wird?

**Comment by McFly753** [comment]
Ja, wäre gut!

**Comment by Mojo1917** [comment]
Hinweis ist eingebaut.

**Comment by McFly753** [comment]
ok
