### ISSUE TITLE
Gibt es eine Möglichkeit, die Karte in der Kartenansicht "ganz" rauszukommen, also dass man "die ganze Welt" in einem Bild sieht?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#387]

**Comment by Mojo1917** [comment]
Leider nicht weiter möglich. Es gibt keine Möglichkeit dem Zoom weiter zu verkleinern (Auch die 'Karten' App von Apple lässt hier nicht mehr zu).
Es lässt sich auch keine Erklärung von Apple finden, warum dies so ist.

**Comment by McFly753** [comment]
Ok, alles klar, Danke!
