### ISSUE TITLE
Zum Teilen, nur Strukturmerkmale teilen.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#388]
Lieber Niklas, ich weiss nicht, ob es den Aufwand rechtfertigt oder ob es fast schon implementiert ist (bei Tags, Kategorien etc. haben wir es ja fast, bei Datenbank importieren ganz):

Von Robert: Nochmal zum Thema Vorlagen zu Datenbanken, das meine ich so: 
Ich kann mir vorstellen, dass einer von uns beispielsweise eine Gastronomie-Datenbank anlegt,
oder eine Einkaufsstandorte Datenbank – was auch immer. Um nun diese Datenbank, die einer erstellt hat,
allen anderen zur Verfügung zu stellen (ohne alle Objekte aber die definierten Felder), wäre es doch gut, wenn der Erstersteller nur ein Objekt aus der Datenbank an alle anderen versendet und alle anderen dieses Objekt zur Neuanlage (Definition aller Felder) einer eigenen Datenbank nutzen könnten. Dann müsste nicht jeder zuerst alle Felder selbst definieren, sondern kann das übernehmen, was der Erstersteller definiert hat. (Also dass dessen Datenbank-Strukturmerkmale übernommen werden,
wenn ich das Objekt für eine Neuanlegung der Datenbank nutzen möchte.)  

Matthias: was wäre, wenn wir hier das "Datenbank teilen" so abändern, dass wir eifach die ausgewählte Datenbank ohne Inhalte teilen?

**Comment by Mojo1917** [comment]
Klaro passe ich so an. 
Sollen wir an dieser Stelle nicht dann zwei Optionen zur Verfügung stellen: 'Datenbankstruktur teilen' und 'Datenbankstruktur und Daten teilen'?
Ich denke das diese Funktion auch hin und wieder benötigt werden wird und dann muss nicht erst die Struktur und dann alle Objekte geteilt werden.

**Comment by McFly753** [comment]
Ja, gute Idee. Danke!

**Comment by Mojo1917** [comment]
Ist umgesetzt. Jedoch habe ich beim Import von einer Datei, die mehrere Datenbankstrukturen enthält die Option 'Locbase zurücksetzten und neue Datenbanken importieren' deaktiviert. Ich fand die ist an dieser Stelle umpassend.

**Comment by McFly753** [comment]
Danke!
