### ISSUE TITLE
Datenbankumschaltung anpassen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#389]
Lieber Niklas, Sorry hierfür, aber hier hat mein Team Recht: wir sollten unser Datenbank-Umschaltung der Sortierbutton-Logik anpassen. Also ich klicke drauf, das Popup (in diesem Fall Dropdown) geht auf und ich kann eine Datenbank aus der Liste wählen. Oder?

**Comment by Mojo1917** [comment]
Hört sich sinnvoll an ;)

**Comment by Mojo1917** [comment]
Hier ergibt sich nur folgendes Problem: Für die Map haben wir dieses 'Pull-Down' für die Statistik. Da der Strich alleine schwer zu greifen war reagiert der Strich auch auf das Pull-Down des Titels. Wenn wir für diesen jedoch das Wechseln der Datenbanken implementieren müssen wir auf das Pull-Down für den Strich an dieser Stelle verzichten.
Ich denke beide Geste, die auf das Pull-Down reagieren so nah beieinander liegen zu lassen wird für den Nutzer zu schwer. Ich denke man würde zu oft das 'falsche' treffen.

Ich denke wir müssen auf eins von beiden verzichten. Was denkst du?

**Comment by McFly753** [comment]
Hmm, das ist blöd... Vorschlag: wir machen das Pulldown für das Menü ganz "sauber" und geben der Karte unterhalb des Striches noch ca. 1cm runterziehen-Platz, aber nicht darüber, dass wir mit dem Datenbank-Pulldown nicht kollidieren. Willst Du das mal probieren:

**Comment by Mojo1917** [comment]
Können wir versuchen!

**Comment by McFly753** [comment]
Danke!

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Ich habe auch die Auswahl in den Statistiken entsprechend angepasst. Mir ist jetzt keine weitere Stelle eingefallen an der wir das Wechseln der Datenbank durch das wischen zugelassen haben. Wenn dir noch eine einfällt passe ich es hier auch noch an ;)

**Comment by McFly753** [comment]
Danke, sollte passen!

**Comment by McFly753** [comment]
Danke! Bitte passe die Position und das Verhalten des Dropdowns etwas an:

1.) wenn ich mehr rechts klicke, bitte das Menü linksbündig erscheinen lassen, wenn ich mehr links klicke, dann rechtsbündig (also genau anders herum als jetzt) - und keine mittlere Position zulassen.

2.) Das Dropdown (umgedreht zum Sortier Dropup) bitte auch etwas tiefer starten lassen, so dass man nicht mit einem Klick-und-Loslassen die Datenbank 1 automatisch auswählt.

**Comment by Mojo1917** [comment]
Beides angepasst. Wenn ich dich bei 1. richtig verstanden habe bezog sich die Ausrichtung auf den Text, richtig?

**Comment by McFly753** [comment]
Danke, nur:

1.) rechts-linksbündig: ja, so hatte ich es gemeint, nur ich würde das Feld nichgt so breit machen, sondern nur so breit wie den längsten Datenbank-Namen.

2.) > 2.) Das Dropdown (umgedreht zum Sortier Dropup) bitte auch etwas tiefer starten lassen, so dass man nicht mit einem Klick-und-Loslassen die Datenbank 1 automatisch auswählt. 
> Es ist noch zu hoch. So schalte ich mit einen einfachen Klick immer noch immer auf Datenbank 1 um.

3.) Wenn es nur eine Datenbank gibt, bitte hier kein Dropdown anzeigen.

**Comment by McFly753** [comment]
Danke!
