### ISSUE TITLE
TAGS: bitte Cursor gleich ins Feld setzen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#39]
... oder eben dann ins nächste Feld, wenn ich ein weietres hinzufüge

Und: Kannst Du hier das Return auf der Tastatur als Beendung der Eingabe sehen und dann die Tastatur schliessen und den Cursor aus dem Feld nehmen?

**Comment by Mojo1917** [comment]
Ist alles umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Fast. Nur den Cursor natürlcih nicht reisetzen, wenn ich in den Einstellungen nur in die Tags gehe.

**Comment by Mojo1917** [comment]
Sorry hatte ich falsch verstanden. Ist behoben. Änderung kommt mit dem nächsten Update.
