### ISSUE TITLE
App-Backup... Anzeige des Backups um den "Ort" des Backups erweitern?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#390]
Können wir in der Anzeige, wo wir die gemachten Backups registrieren in einer zweiten Zeile anzeigen, "wohin" das Backup geteilt wurde? Also icloud, dropbox (evtl. mit Pfad?), Mail, ...

**Comment by Mojo1917** [comment]
Das ist leider nicht möglich. Wir bekommen hier nur eine Art Typ der ausgewählten Option. Diese können wie folgt aussehen: 'com.apple.UIKit.activity.RemoteOpenInApplication-ByCopy', 'com.getdropbox.Dropbox.ActionExtension'
Es handelt sich hierbei um eine Art ID der Auswahl, an die der Nutzer gewählt hat. Diese kann man jedoch weder einer App noch einem Pfad zuverlässig zuordnen.
Aktuell gibt es keine Möglichkeit, die mir bekannt ist oder sich in der Apple Dokumentation finden lässt, um dies umzusetzen.

**Comment by McFly753** [comment]
Verstehe, kannst Du dann evtl. in der zweiten Zeile im Logfile des APP-Backups in kleinster Schriftart diese Zusatzinfo in Klammer anzeigen?

**Comment by Mojo1917** [comment]
Klar das ist kein Problem!

**Comment by Mojo1917** [comment]
Ist umgesetzt.

**Comment by McFly753** [comment]
Danke.!
