### ISSUE TITLE
Gefährlicher Bug in Hilfe

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#392]
Führe in den Einstellungen die Tour aus - es stürzt dann die App ab (und das dann immer nach Neustart), ohne dass man was machen kann. Ohne Backup kommt man nicht mehr an seine Daten, weil man die App deinstallieren muss, um aus dieser Bug-Schleife zu kommen. (Ich hatte keine Daten in meiner App, darum ist kein Schaden entstanden.)

**Comment by Mojo1917** [comment]
Fehler ist behoben!

**Comment by McFly753** [comment]
Danke!
