### ISSUE TITLE
Können wir überall, wo die Tastatur offen ist, diese auch mit Runterwischen (der Zeile über der Tastatur, da wo rechts auch der blaue Pfeil drin ist) schliessen lassen (redundant zum Pfeil)?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#393]

**Comment by Mojo1917** [comment]
Leider nicht möglich. Jegliche GestureRecognizer auf diesem UI-Element werden nicht ausgeführt.
Jedoch können wir das schließen des Keyboard einfach per ziehen der Liste/ScrollView erlauben. Somit schließt sich die Tastatur, wenn der Nutzer einfach oberhalb der Tastatur wischt ;)

**Comment by McFly753** [comment]
Aber kann in der Kartenansicht die Tastatur überhaupt offen sein? // Dann lass uns das versuchen!

**Comment by Mojo1917** [comment]
Ja kann sie, aber nur, wenn der Nutzer etwas in die Suche eingibt ;) Ist das einzige Feld. 
Das schließen ist auf allen anderen Seite umgesetzt.

**Comment by McFly753** [comment]
ok.... :)
