### ISSUE TITLE
Bitte. wenn man (durch das Durchladen der Positionstaste) auf alle seine Bäume "rauszoomt" - das auch machen, wenn der Zooms weit ist, also dann auf seine Bäume "reinzoomen" 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#397]

**Comment by Mojo1917** [comment]
Lieber Matthias,

ich verstehe was du meinst. Aktuell ist die Logik wie folgt implementiert: Wenn der Nutzer die Karte bewegt hat wird beim drücken der 'Positionstaste' immer zuerst die Karten Ansicht auf den Nutzer zentriert, da ich dachte der Nutzer wird nach einem Verschieben der Karte am ehesten wieder auf sich positionieren. Da das positionieren auf alle Objekt immer ersten als dritte Aktion folgt zeigt die App nie den Zoom von weit auf alle Objekte (Schritt zwei zoomt immer stark auf den Nutzer).
Gerne kann ich diese Logik aber so anpassen, dass die App diese nächste Aktion nicht nach dem verschieben der Karte zurücksetzt.

Liebe Grüße,
Niklas

**Comment by McFly753** [comment]
Ok, wie am tel. besprochen: sollte eigentlich nicht auftreten... :) > ich teste es in der nächsten Version nochmals.

**Comment by Mojo1917** [comment]
Alles klar ;)
