### ISSUE TITLE
Wir haben noch ein Anzeige problem, dass die Bilder auf der Karte sich ein und ausblenden, wenn ich die Karte verschiebe

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#398]
zeige ich Dir morgen.

**Comment by Mojo1917** [comment]
Habe leider nicht dran gedacht, dass du mir den Fehler zeigen wolltest. Kannst du mir ggf. einfach eine kurze Bildschirm Aufnahme davon schicken? ;)

**Comment by McFly753** [comment]
am tel

**Comment by Mojo1917** [comment]
Okay habe den Fehler gefunden. Entstand, wenn in der Liste nach den Besuchen sortiert wurde. Da früher auch die Karte diese Sortierung dargestellt hat wurde hier die Karte nach einem verschieben immer wieder nachgeladen.

**Comment by McFly753** [comment]
Ok, Danke!
