### ISSUE TITLE
Punktbild beheben

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#399]

**Comment by Mojo1917** [comment]
Fehler wird jetzt umgangen, indem ein Objekt das kein Bild hat einfach auf der Karte/Liste mit Beispielbild angezeigt wird, ohne das dieses als Bild beim Objekt eingefügt wird.
Ich habe mich dagegen entschieden bei jedem Bild immer ein Beispielbild einzufügen, da der Nutzer sonst immer wenn er ein neues Objekt anlegt das Beispielbild entfernen muss.

**Comment by McFly753** [comment]
Danke!
