### ISSUE TITLE
längere Wartezeit bei "Use Photo" oder Foto auswählen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#4]
Das "verwenden" von Bildern dauert etwas lange. 
Wenn Du das nicht beschleunigen kannst, kannst Du eine Anzeige dazuschalten, dass man weiss, das das System gerasde was macht?

**Comment by Mojo1917** [comment]
Nein Beschleunigen kann man das leider nicht, da die App Daten in den Speicher schreiben muss.
Die App zeigt jetzt jedoch einen Dialog an. 

Änderungen kommen mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke. Könntest Du in diesem Fenster anzeigen "Importiere 3 Objekte" (also beides dynamsich natürlich)?

**Comment by Mojo1917** [comment]
Ist übernommen. Änderung kommt mit dem nächsten Update.
