### ISSUE TITLE
Manchmal (derzeit ca. beim jeden 10. öffnen) wird mir nur eine Abfrage am Anfang gestellt und nicht zwei...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#40]
... aber wir wollten die Mitteilungs-Frage eh hier rausnehmen und erst beim ersten Nutzen der Mitteilungen fragen.

**Comment by McFly753** [comment]
Sorry, eher beim jeden 5. komplett ersten Öffnen der App nach Neuinstallation.

**Comment by McFly753** [comment]
Jetzt habe ich diesen Fall öfters. Es kommt jetzt nur die Abfrage zu Mitteilungen senden, nicht zum Standort. (aber die App hat den Standort)

**Comment by McFly753** [comment]
(kann es sein, dass ich zu schnell die App neu installiert habe und damit diese Freigabe noch von der letzten Instanz der App gegolten hat?)

**Comment by Mojo1917** [comment]
Ja richtig das habe ich auch schon festgestellt. iOS entzieht der App bei der Neuinstallation nicht immer korrekt alle alten Freigaben. Das wird aber ein Fehler im Betriebssystem sein.
