### ISSUE TITLE
Synchronisation der Bilder/Datenbanken zwischen Geräten -> iCloud

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#400]

**Comment by Mojo1917** [comment]
Notiz an mich: Prüfen, wie iCloud mit Konflikten in der Synchronisation umgeht. 
Bsp: Daten werden auf zwei Geräten ohne Internet verändert -> Was gilt?

**Comment by Mojo1917** [comment]
Lieber Matthias, 

soweit ich das CloudKit von Apple bis jetzt verstanden habe können wir alle Fotos und Datenbanken über das CloudKit in der privaten Cloud eines jeden Nutzers ablegen und die Daten damit zwischen allen iCloud-Geräten des Nutzers synchronisieren. Dazu müsste ich jedoch die ganzen Datenbanken neu in der Cloud anlegen.
Soll ich das machen?

Liebe Grüße,
Niklas

**Comment by McFly753** [comment]
Ja, wäre gut! // Wie gehen wir mit dem Upgrade um, dass alles smooth läuft?

**Comment by Mojo1917** [comment]
Das ist kein Problem. Ich würde einen Adapter schreiben, der die Daten aus alten Versionen vorerst nur in das CloudKit kopiert. Somit können wir alles testen ohne das Risiko eines Datenverlusts zu haben. Wenn das alles gut geklappt hat können wir die lokalen Daten mit einem neuen Update löschen.

**Comment by Mojo1917** [comment]
Denke ist sollte das bis Sonntag Abend fertig haben, damit Apple Montag prüfen man ;)

**Comment by McFly753** [comment]
Super! Danke!

**Comment by Mojo1917** [comment]
TO-LOG:
- Einrichten der Datenbanken -> DONE
- Anknüpfen der Datenbanken an die App -> In Arbeit
- Adapter zur Datenübertragung schreiben -> Ausstehend
- Backup-Funktion überarbeiten -> Ausstehend
- Share-Funktion überarbeiten -> Ausstehend

**Comment by Mojo1917** [comment]
Soweit fertig umgesetzt. Es fehlen noch 2 Kleinigkeiten, aber die kann ich erst umsetzen, wenn wir die App umgezogen haben. macht sonst nur doppelt Arbeit.

**Comment by McFly753** [comment]
Ok, was soll ich noch testen/machen?

**Comment by McFly753** [comment]
Danke!! :)

**Comment by Mojo1917** [comment]
Es gibt nicht spezielles zu testen. Wenn alles bei dir mit der Synchronisation funktioniert dann ist das super! Bevor wir sie jedoch freigeben würde ich einfach noch ein paar Tage warten, um zu schauen ob mit der Zeit Probleme auftreten (Davon gehe ich jedoch nicht aus).

**Comment by McFly753** [comment]
Ich hatte gesetrn das Problem, das Plötzlich beim Ipad bei allen 14 Objekten die Bilder weg waren. (graue Kästen) - und egal was ich gemacht habe, welches Netz oder ob App neu gestartet oder 12 Stunden gewartet die Bilder nicht mehr kamen. Ich habe dann die App deinstalliert und neu installiert und dann hat er aber alle Objekte mit allen Bildern sauber aus der Cloud geladen...

**Comment by Mojo1917** [comment]
Vielen Dank für die Info. Warum der graue Kasten gezeigt wird kann ich gerade nicht sagen, da die App in diesem Fall auf Preview Icon zeigt sollte. Ich schaue mir das nochmal, warum die App hier die Bilder nicht richtig zeigen wollte.

**Comment by Mojo1917** [comment]
Sollte nach dem nächsten Update nicht mehr auftreten.

**Comment by Mojo1917** [comment]
Habe hier noch einen Fehler gefunden. Wir mit dem nächsten Update behoben.

**Comment by Mojo1917** [comment]
Datenbanken und Bilder werde mit dem nächsten Update an einem anderen Ort gespeichert. Dies sollte das Problem korrigieren. Jedoch erfordert dies vor dem Update eine Deinstallation.

**Comment by McFly753** [comment]
Danke!
