### ISSUE TITLE
Kannst Du in den Einstellungen irgendwo die Versionsnummer anzeigen lassen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#401]
... z.B.: ganz unten "unter" den Menüzeilen, die man hochschiebt, einfach Locbase v1.2 etc.?

**Comment by Mojo1917** [comment]
Klar, ich binde es als letzen Punkt unter dem Punkt Impressum ein!

**Comment by McFly753** [comment]
Ich würde es nicht als Menüpunkt sehen, sondern in Grau direkt auf die graue Fläche schreiben

**Comment by Mojo1917** [comment]
Okay, ich habe es jetzt als Footer Text unter die letzte Sektion gesetzt. Wir können hier jedoch nicht viel am Design ändern, da dies von Apple einheitlich gehalten wird ;)

**Comment by McFly753** [comment]
Danke!

Aber/Und: weil ich das für die anderen Apps einen schönen Effekt fände und wir ihn hier ausprobieren könnten: kannst Du versuchen, diese Zeile hinter dem letzten Eintrag (Impressum) zu verstecken und man sieht sie dann erst, wenn man die Seite nach unten "überzieht"?

**Comment by Mojo1917** [comment]
Klar, umgesetzt.

**Comment by McFly753** [comment]
So ist es ok, aber ich hätte es gerne ausprobiert, ob es geht, einen Text fix das schon stehen zu haben, er aber durch das letzte Kästchen verdeckt wird, aber wenn ich dieses wegziehe, der Text darunter erscheint?

**Comment by Mojo1917** [comment]
Klaro auch möglich ;) Ist im nächsten Update umgesetzt.

**Comment by McFly753** [comment]
Danke! Nur kannst Du es so machen, dass man sie ohne Herunterziehen gar nicht sieht?

**Comment by Mojo1917** [comment]
Oh ist auf meinen Geräte der Fall. Habe es aber nicht auf dem X getestet. Kommt ;)

**Comment by McFly753** [comment]
Danke! ;)

**Comment by Mojo1917** [comment]
Jetzt auch auf diesen Geräten behoben ;)

**Comment by McFly753** [comment]
Cool! ;)
