### ISSUE TITLE
Absturz der Apps beim importieren (eines größeren Objektes (ca. 12 Bilder, 80MB)  - bei manchen Usern, nicht bei allen.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#402]

**Comment by Mojo1917** [comment]
Fehler gefunden ;) Nach den Crash-Reports sieht es so aus, dass das etwas mit der Parallelität in der App zu tun hat. Sollte nach dem nächsten Update nicht mehr auftreten.

**Comment by Mojo1917** [comment]
Fehler aus dem Crash-Report wird jetzt abgefangen.

**Comment by McFly753** [comment]
wird gerade getestet
