### ISSUE TITLE
Können wir in der App überall "exportieren" statt "teilen" verwenden? ...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#403]
... weil wir verwenden ja auch "importieren"?

**Comment by Mojo1917** [comment]
Klar setze ich um!

**Comment by Mojo1917** [comment]
Habe es überall geändert, nur nicht bei 'In meinem Locbase teilen', da ich fand hier würde es komisch klingen. Solltest du es dennoch einheitlich haben wollen, kann ich das mit dem nächsten Update machen!

**Comment by McFly753** [comment]
![IMG_1917](https://user-images.githubusercontent.com/493612/54770279-fe5e4480-4c56-11e9-90d4-e1236204b47d.PNG)

**Comment by McFly753** [comment]
Kannst du nur die Syntax gleich machen, also dann in diesem Fall auch "Restaurants importieren"

Und in diesem Schritt: kannst Du die Statistik vor die Hilfe&Tour ziehen? (überall)

![IMG_1918](https://user-images.githubusercontent.com/493612/54770376-31a0d380-4c57-11e9-9442-31eb5ba9efc1.PNG)

**Comment by Mojo1917** [comment]
umgesetzt.

**Comment by McFly753** [comment]
Danke. Nur oben rechts steht dann immer noch Teilen, schreib dann hier auch exportieren.

Und wegen dem anderen: "In Locbase importieren"

**Comment by Mojo1917** [comment]
Okay ist behoben.

**Comment by McFly753** [comment]
Danke!
