### ISSUE TITLE
Ein Lückenfüllerobjekt, das nicht verändert wird, sollte nach schliessen sich wieder löschen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#404]
... hatten wir das nicht schon mal eingebaut gehabt?

**Comment by Mojo1917** [comment]
Du hast recht, dass sollte so laufen... Ich schaue es mir nochmal an ;)

**Comment by Mojo1917** [comment]
Also in der aktuellen Version der App wird das Objekt gelöscht, wenn es nicht verändert wurde. Wir haben diese Funktion bisher jedoch nur für Objekte eingeführt, die durch ein langes Drücken auf der Karte erzeugt wurden. Nicht für welche, die über das '+'-Zeichen erstellt wurden. Ich denke, diese Objekte wurden bei dir nicht gelöscht... Ich erweitere die App entsprechend ;)

**Comment by McFly753** [comment]
Bei mir, wenn ich zu nah an anderen Objekten dran bin, wird es nicht gelöscht. (Und die Bilder werden (nach dem Flackern zu urteilen) mind 2-3 mal aktualisiert)

**Comment by Mojo1917** [comment]
Ist korrigiert.

**Comment by McFly753** [comment]
Ist prinzipiell eingebaut, nur wenn Du direkt nach Neuinstallation der Mail (ohne was anderes gemacht zu haben) es ausprobierst, kannst Du weiterhin leere Objekt setzen...

**Comment by McFly753** [comment]
![IMG_1917](https://user-images.githubusercontent.com/493612/54770497-76c50580-4c57-11e9-8318-189a87d878ae.PNG)

**Comment by Mojo1917** [comment]
Korrigiert.
