### ISSUE TITLE
Das Kamerrabild sollte sich nicht verschieben, nachdem ich ein Bild gemacht habe...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#405]
... es rutscht leicht runter, weil der Auslöseknopf weg ist. Kannst Du das gemachte Bild nicht dennoch an der selben Position belassen?

**Comment by Mojo1917** [comment]
Leider nicht, denn dieses Fenster wird komplett vom iOS-System übernommen. Die App startet nur den 'Take-Photo' Dialog des Systems und bekommt am Ende das fertige Foto zurück. 
Wir könnten uns nur überlegen, diesen gesamten Prozess nachzubilden. Ich würde dies jedoch nicht machen, da dies sehr viel Zeit beanspruchen könnte und wir dann nicht mehr einen einheitlichen Ablauf mit anderen Apps haben, sollte Apple diesen Dialog überarbeiten.

**Comment by McFly753** [comment]
Nein, dann lass es so!
