### ISSUE TITLE
Optimierung Usability Datenbank teilen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#406]
Kannst Du bitte folgendes machen:

1.) gibt es nur eine Datenbank, springst Du direkt zum Teilen dieser Datenbank und lässt die eine nicht auswählen

2.) gibt es mehrere, lass uns darunter einen Text schreiben, dass an die zu teilende(n) Datenbank(en) oben auswählen soll. (Das hat leider ohne Anweisung keiner im Team verstanden, wie es weitergeht... ;) )

**Comment by Mojo1917** [comment]
umgesetzt.

**Comment by McFly753** [comment]
Danke
