### ISSUE TITLE
Ich habe jetzt (ca. 2.38 Perth Zeit am 17.03.) zwei mal einen App Absturz bekommen, weil ich versucht hatte, ein Thumbnail auf der Karte (durch Längerdrücken) auszuwählen ...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#407]
... siehts Du den Absturzgrund in den Loggs?

**Comment by McFly753** [comment]
-> können wir (falls wir das "Treffen" der Bilder nicht noch optimieren? Normalerweise will ich ein Objekt öffnen, ein Neus Objekt will ich nur erstellen, wenn ich die Karte relative weit reinzoome und nicht einem anderen Bild zu nahe komme?

**Comment by Mojo1917** [comment]
Habe den Absturz-Bericht bekommen ;) 
Ja das lässt sich auf jeden Fall einführen. Wir können auf ein bestimmtes Zoom-Level prüfen und nur ab einem Bestimmten, das erstellen durch lange drücken zulassen!

**Comment by McFly753** [comment]
ok

**Comment by Mojo1917** [comment]
Ein Objekt kann jetzt nur noch durch lange drücken erstellt werden, wenn die Karte mindestens so weit reingezoomt ist, wie bei der nahen Positionierung auf dem Nutzer.

Es gibt jedoch leider keine Möglichkeit in iOS zu prüfen, ob sich zwei Objekte auf der Karte 'nahe' sind. Wir müssten dies abhängig von Entfernung zum nächsten Objekt abschätzen und dann, wenn ein 'nahe' ist dieses öffnen, auch wenn der Nutzer nicht genau den Pin gedrückt hat. Ich bin mir nicht sicher wie gut wir das hinbekommen...

**Comment by Mojo1917** [comment]
PS: Ich habe den Fehler aus dem Crash-Report abgefangen.

**Comment by McFly753** [comment]
Danke!
