### ISSUE TITLE
Können wir bei allen Feldern (mind. Eigenschaften, Kategorien, Tags, Benennungen) Leerzeichen am Ende des Wortes abfangen und verhindern.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#409]
... das war heute oft ein Grund, dass Objekte nicht sauber (hier z.B. mit den Einstellungen) Eingelsen wurden, weil einmal ein Feld z.B. "Innen-Location" und das andere "Innen-Location " geheissen hat.

**Comment by Mojo1917** [comment]
Es sollte jetzt bei allen Felder entfernt werden, die als Text in der Datenbank gespeichert werden.

**Comment by McFly753** [comment]
Danke!
