### ISSUE TITLE
Sortier-Titel leicht anpassen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#41]
Lass uns hier dem User sauerb zeigen, was er sieht.

> Bei Besuchen passt es.

> Bei Entfernung würde ich was hinschreiben wie "in meiner Nähe" "am weitesten entfernt" o.ä.

> Bei letzter Besuch: "letzter Besuch im Januar 2018"

> Erstellungsdatum (bei jedem Zischnetitel): "Erstellt im Januar 2018" (oder hier eben nur das Datum wie gehabt. Was denkst Du?)

**Comment by Mojo1917** [comment]
Kann ich gerne so umsetzen. Du meinst die 'Einzelüberschriften' in der Liste richtig?

**Comment by Mojo1917** [comment]
Was soll denn 'in meiner Nähe' sein? Also in welchem Umkreis? oder soll ich einfach nur in die obere Überschrift "in meiner Nähe" oder "am weitesten entfernt" setzen je nach Sortierung?

**Comment by McFly753** [comment]
Genua // ja, hier haben wir ja nur eine Überschrift. Oder: wir machen heir auch Blöcke (ich weiss nicht, was Dir das Tool zurückliefert. Z.B. "bis 10km entfernt" "bis 50 km entfernt" ... 

Was denkst Du?

**Comment by Mojo1917** [comment]
klar können wir machen. Sollen wir dann für die Entfernung folgende Blöcke nehmen: [bis 10km, bis 30km, bis 50km, bis 100km, bis 200km, bis 500km, über 500km]?

**Comment by McFly753** [comment]
Ok, ja, mach das so. Danke!

**Comment by Mojo1917** [comment]
Ist implementiert. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Passt, nur mein Fehler: lass uns alle Zwsichentitel mit Kleinbuchstaben beginnen, dann ist es einheitlich. danke!

**Comment by Mojo1917** [comment]
Beides geändert. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Und, wir sollten über 500km noch merh Schritte einführen: 
1.000
2.000
4.000
8.000
12.000

**Comment by Mojo1917** [comment]
Schritte sind eingeführt. Änderungen kommen mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten
