### ISSUE TITLE
Export lädt sich nicht mehr in Dropbox hochladen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#412]
(Icloud geht aber)

es kommt immer dieser Fehler, egal in welchen Ordner

![IMG_2569](https://user-images.githubusercontent.com/493612/55736265-4638e600-5a23-11e9-8b16-0246d8ddf4da.PNG)

**Comment by Mojo1917** [comment]
Ist in der Dropbox noch ausreichend freier Speicherplatz vorhanden?

**Comment by McFly753** [comment]
Ja, noch über 2 TB...

**Comment by McFly753** [comment]
(geht bei anderen auch nicht - ging aber mal)

**Comment by Mojo1917** [comment]
Okay, bekomme den Fehler leider nicht reproduziert... Ist die Dropbox App in der neusten Version installiert?

**Comment by McFly753** [comment]
Es liegt an der Dateigröße... bis 156MB habe ich es geschafft, bei meinem 360MB Export bricht er ab. Ich weiss nicht genau, wo der Schwellwert ist. Aber wenn Du eine so große Datei hast, wird es auch bei Dir abbrechen.

**Comment by Mojo1917** [comment]
Ahh da hätte ich wohl noch was länger gebraucht um drauf zu kommen! Danke! Ich schaue mal was sich da machen lässt.

**Comment by Mojo1917** [comment]
Okay also die bekomme nicht mehr als knapp 260MB geteilt. Über Google Drive jedoch geht weit mehr. Daher wird dies eine Sperre in der Dropbox App sein.
Ich habe auch geschaut, ob wir Dropbox einfach ab einer gewissen Dateigröße ausschließen können. Jedoch geht das nicht. Denke wir müssen es daher so lassen.

**Comment by McFly753** [comment]
Ok, dann sollten wir aber eine Message anzeigen, wenn wir eine Datei ab dieser Größe haben, dass sie nicht in die Dropbox exportiert wird? (Oder bei Auswahl der Dropbox anzeigen, dass hierfür die Datei zu groß ist?)

**Comment by Mojo1917** [comment]
Wir zeigen ja bereits bei einer gewissen Größe einen Hinweis an. Sollen wir diesen ab der für Dropbox unzulässigen Größe einfach erweitern? Dann zeigen wir nicht zwei an und lassen dem Nutzer dennoch die Wahl Dropbox zu probieren. Was denkst du?

**Comment by McFly753** [comment]
Ja, aber lass uns das nach dem ersten Fenster als zweites Fenster (wenn das erste bestätigt wurde) anziegen. Igrndwas in deise Richtung: 
Da die Datei größer als 250MB ist, kann sie nicht in eine Dropbox gespeichert  werden, da dies von deren Seite nicht unterstützt wird. Du kannst diese Datei aber in Deine iCloud exportieren.

**Comment by Mojo1917** [comment]
Alles klar!

**Comment by Mojo1917** [comment]
Okay ist umgesetzt.

**Comment by McFly753** [comment]
Daran kann es scheinbar nun doch nicht liegen. Max konnte vorgestern ein Backup (aber hier der ganzen App) von über 1GB in die DRopbox hochladen. Kann es sein, dass wir dieses Größenproblem nur bei einzlenen Datenbaken haben, nicht aber bei dem ganzen App-Container?

**Comment by Mojo1917** [comment]
Okay, komisch jetzt würde mich interessieren, wonach deren App entscheidet ob Daten geladen werden dürfen oder nicht. Denn das einzige, was für Dropbox an den verschiedenen Dateien anders ist sind der Name, das Erstellungsdatum und die Dateigröße... Sie werden auch über die exakt gleiche Schnittstelle im System geteilt.
Vielleicht trifft Dropbox diese Auswahl auch über die Internetgeschwindigkeit oder andere Faktoren.
Ich denke jedoch, dass wir hier keinen weiteren Einfluss drauf nehmen können.
Ich denke wir können den Dialog dann wieder entfernen?

**Comment by McFly753** [comment]
Ich teste es bei mir nochmals und melde mich.

**Comment by McFly753** [comment]
Tel

**Comment by Mojo1917** [comment]
Okay ich habe die Message wieder deaktiviert und schließe den Issue dann jetzt.
