### ISSUE TITLE
Bitte die Reihenfolge im Menü tauschen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#413]
kann sein, dass ich dieses Ticket schon mal angelegt hatte.

![1](https://user-images.githubusercontent.com/493612/55736344-6c5e8600-5a23-11e9-8cae-b44e9e28564f.png)

**Comment by Mojo1917** [comment]
Ist bereits im kommenden Update umgesetzt ;)

**Comment by McFly753** [comment]
Danke
