### ISSUE TITLE
Können wir "User-Freundliche" Dateinamen verwenden?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#414]
... und Umlaute erlauben?

z.B. bei einzelnen Objekten:
LocbaseExport-MultipleObjects-DD_MM_JJJJ.locbase

z.B. bei ganzer Datenbank:
LocbaseExport-Datenbankname-DD_MM_JJJJ.locbase

z.B. bei Backup:
LocbaseBackup-DD_MM_JJJJ.locbase

![IMG_1928](https://user-images.githubusercontent.com/493612/55737451-7ed9bf00-5a25-11e9-9d2a-1aebebf6719d.PNG)

**Comment by Mojo1917** [comment]
Klaro, ich passe die Namen so an.
Ob Umlaute möglich sind muss ich prüfen!

**Comment by Mojo1917** [comment]
Umlaute werden jetzt zugelassen. Zusätzlich alle anderen Zeichen, die das iOS FileSystem erlaubt.

Namen sind jetzt auch angepasst. Jedoch würde ich anstatt 'DD_MM_JJJJ' 'JJJJ_MM_DD' verwenden, da 'DD_MM_JJJJ' nicht überall so verwendet wird. Das andere natürlich auch nicht, aber ich finde es ist so leichter zu erkennen.

**Comment by McFly753** [comment]
Danke!
