### ISSUE TITLE
(Ticket bezieht sich nur noch auf die rote App) Bug des fehlerhaften Datenbankimports eingegrenzt

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#415]
Die Bernadette hat nun alle 23 Objekte einer ihrer Datenbanken in ihr eigenes Locbase importiert, das geht einwandfrei. Nur wenn sie die ganze Datenbank mit diesen 23 Objekten in ihr eigenes Locbase importiert, hat ise nach dem "erfolgreichen" Import keine Objekte in der Datenbank.

Evtl. kannst Du mit dieser Information den Fehler eingrenzen?

**Comment by Mojo1917** [comment]
Okay, ich habe den Fehler gefunden. Es ist ein Fehler in der Erstellung des Backups + des Datenbankexports der App in der Version 0.9.450 (65). Dachte diesen schon in dieser Version behoben zu haben, ist jedoch nur in der 'blauen' Version gefixt.
Wir haben dieses Update ja nur nicht für dein Team freigegeben, da der PhotoImport hier Fehler machen kann. Ich würde daher sagen, dass ich den Export und Backup Fehler ausbessere sowie den Photopicker wieder verbessere und wir stellen dann diese verbesserte Version deinem Team zur Verfügung, bis sie auf die blaue Version wechseln. Was denkst du?

**Comment by McFly753** [comment]
Ja, gute Idee.

**Comment by Mojo1917** [comment]
Okay Update liegt bei Apple zur Prüfung!

**Comment by McFly753** [comment]
Danke! / ich lasse es sie installieren und testen

**Comment by McFly753** [comment]
Geht leider dennoch nicht. Die Datenbank wird als vollständig importiert angezeigt, aber die importierte Datenbank enthält dann keine Daten.

**Comment by Mojo1917** [comment]
Stammt der Export aus der neuen Version? Oder aus der alten?

**Comment by McFly753** [comment]
beides probiert. Beides mal der selbe Fehler. (Diesmal werden aber keine "leeren" Objkete angezeigt, sondern gar keine.)

**Comment by Mojo1917** [comment]
Okay das ist komisch. Ich versuche den 'neuen' Fehler zu finden!

**Comment by Mojo1917** [comment]
Also ich kann hier leider keine weiteren Fehler finden. Der Import von Dateien, die mit dieser Version erstellt werden klappt auf meinen Geräten einwandfrei.
Jedoch können ältere Dateien noch Fehler enthalten. Soll ich noch ein Update veröffentlichen, dass diese Dateien akzeptiert, indem es die Fehler vor dem Import zu korrigieren versucht?

**Comment by McFly753** [comment]
Ja, das wäre gut. Wenn Du das drin hast, gib Bescheid und ich lasse Bernadette nochmals testen.

**Comment by Mojo1917** [comment]
Okay neue Version liegt bei Apple für die Prüfung. Sollte morgen online kommen.

Diese Version importiert jetzt auch die fehlerhaften Dateien aus vorherigen Versionen.

**Comment by McFly753** [comment]
Geht leider weiterhin nicht -> tel

**Comment by Mojo1917** [comment]
Zurückgestellt. Könnte Fehler durch die verschiedensten App-Updates sein. Sollte nach Umzug auf neue App nicht mehr auftreten.

**Comment by McFly753** [comment]
Wir testen alles ganz zum Schlkuss hier nochmals. (Wir sehen jetzt auch, was bei den anderen beim Import passiert).

**Comment by McFly753** [comment]
... können wir eigentlcih schliessen
