### ISSUE TITLE
Lückenfüllerbild für noch nicht gelandene Biler

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#418]

**Comment by Mojo1917** [comment]
Habe kein passendes Bild gefunden, das wir leicht verwenden können. Zeige daher jetzt eine Ladeanimation ;)

**Comment by McFly753** [comment]
OK, kann es gerade nicht teten, weil die Bilder immer zu schnell geladen sind, als dass ich lückenfüller sehe. Ich schliess das Ticket.
