### ISSUE TITLE
LoadingScreen, wenn die App dien ersten Daten lädt

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#419]

**Comment by Mojo1917** [comment]
Screen ist eingebunden.

**Comment by McFly753** [comment]
Danke! Ein paar Text-Anpassungen:
- ... aus der Cloud zu laden. (Nicht landen)
- Komma nach „bereit sind“
- Komma nach “warten wollen”
- ... eine zusätzliche Datenbank... (statt neue)
- ... und die anderen werden (anderen klein)

**Comment by Mojo1917** [comment]
Okay umgesetzt ;)

**Comment by McFly753** [comment]
Danke!
