### ISSUE TITLE
Tastatur bei Notiz

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#42]
Nicht immer fahren alle Objeket hoch und dann steht die Tastatur über dem Feld, wo ich reinscheiben will.

**Comment by Mojo1917** [comment]
Okay sollte jetzt besser funktionieren.

**Comment by McFly753** [comment]
Immer noch nicht...

**Comment by Mojo1917** [comment]
Okay habe das scrollen nochmals angepasst. Jetzt sollte es funktionieren.
Änderung kommt mit dem nächsten Update.
