### ISSUE TITLE
Kannst Du in den Einstallungen auch das Menü "Datenbank importieren" und "Datenbank exportieren" anzeigen, auch wenn man nicht in den Datenbanken ist?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#420]
(und wenn man in den Datenbanklen ist, zeig im Menü "Datenbank löschen" an, nicht nur "Löschen")

**Comment by Mojo1917** [comment]
Beides Umgesetzt. Die Möglichkeit zum Teilen und importieren habe ich jedoch nur im Hauptmenü eingefügt, da sie logisch in den anderen Untermenüs keinen Sinn machen.

**Comment by McFly753** [comment]
Danke!
