### ISSUE TITLE
Langklick auf ein Bildchen in der Karte geht nicht mehr (also dass ich direkt in die Detailansicht springe)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#421]

**Comment by Mojo1917** [comment]
Funktioniert bei mir in der Karte problemlos und sollte auch nicht von dem Bug beim Teilen betroffen sein. Hast du das neue iOS 12.2 installiert?

**Comment by Mojo1917** [comment]
Der Timer für die Aktion liegt bei 0.5s

**Comment by McFly753** [comment]
Hm, 12.2 ist drauf und auch die neuste Version der blauen Locbase App - da ghet es nicht. Aber in der  roten App geht es?

**Comment by Mojo1917** [comment]
Okay die App hat sehr sensibel reagiert, wenn der Finger während des TouchEvents bewegt wurde. Das habe ich jetzt angepasst. Der Finger kann jetzt leicht bewegt werden.

**Comment by McFly753** [comment]
Danke, geht wieder.
