### ISSUE TITLE
Lass uns das Datenbank-Auswahl-Popup anders machen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#422]
und zwar gehen wir einfach auf einen rechtshänder und machen das Menü linksbündig (und aber so lange, dass es noch über die Mitte geht.

**Comment by Mojo1917** [comment]
Okay angepasst. Die Weite des Dialogs ist jetzt dann auch wieder einheitlich in der Breite mit den von Tag und Kategorie.

**Comment by McFly753** [comment]
Danke, aber ich würde auch die ganzen Kästen linjsbündig setzen, willst Du das mal ausprobieren?

**Comment by Mojo1917** [comment]
Okay kann ich machen, aber ich bin mir nicht so sicher ob das sinnvoll ist. Denn dann ist der Auswahldialog bei großen Geräten unter Umständen recht weit weg von dem auslösenden Feld. Man müsste auf einem iPad z.B. recht weit wischen, wenn der Dialog von der rechten Displayseite aus ausgelöst wurde.

**Comment by McFly753** [comment]
Was ist wenn wir es nur bei Klick auf die Mitte (also Datenbanktitel) auslösen lassen, dann kann der Finger nicht weit weg sein? Und dann den Kasten eben Linksbündig, aber von der Breite mind. bis zum aktiven Berecih auf der rechten Seite?

**Comment by Mojo1917** [comment]
Okay das verstehe ich jetzt nicht ganz. Lass das doch bei Gelegenheit am Telefon besprechen und ich setzte es ein Update später um?

**Comment by McFly753** [comment]
ganz einfach: so wie unten bei den Kategoriefilter, den ganzen Kasten eifach noch ganz linksbündig mahcen (den Kasten meine ich, nicht den Text). - Können aber auch geren telefonieren.

**Comment by Mojo1917** [comment]
Okay jetzt hab ichs verstanden ;) Auf dem iPad lasse ich die Dialoge jedoch so wie sie sind. Sonst muss man mit dem Finger so weit und die Dialoge tauchen irgendwo auf, oder?

**Comment by McFly753** [comment]
Danke!

**Comment by McFly753** [comment]
Danke!
