### ISSUE TITLE
Falls ich auf 0 Objekte filtere und die Anzeige kommt, dass ich hier klicken soll, um alle Filter aufzuheben: dieser Text ist zu hoch, da wir oben hierfür keine sensitive Fläche mehr haben - setz diese Zeile etwas tiefer, dass ich sie auch sinnvoll klicken kann.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#424]

**Comment by Mojo1917** [comment]
Oh du hast recht hier sind sich die beiden in die Quere gekommen. Ich habe die Zeile jetzt nicht weiter runter gesetzt, sondern das Problem anders gelöst. Ein Klick setzt die Filter zurück und das ziehen geht auch noch.

**Comment by McFly753** [comment]
Danke!
