### ISSUE TITLE
Bei Datenbanken "Teilen" ->. hier auch von exportieren sprechen.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#426]
"Wähle alle Datenbanken, die Du exportieren..."

Udn der "Button oben rechts" sollte dann auch hier "Exportieren" heissen.

**Comment by McFly753** [comment]
und lass uns hier beim Exportieren links oben nicht das "+" und den Pfeil nach unten anzeigen, sondern schreib da ein abbrechen hin, sobald mind. eine Datenbank ausgewählt ist.

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Das Menü blendet nicht benötigte Buttons auch beim Löschen aus, damit wir in der App einheitlich bleiben.

**Comment by McFly753** [comment]
Danke!
