### ISSUE TITLE
Einzelexport von Objekte geht nicht mehr. Sie haben immer 0kb (in der ICloud) 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#428]

**Comment by Mojo1917** [comment]
Fehler gefunden! Leider führt dies auch aktuell zu Fehlern beim Export/Import von Backups. Daher diese Funktion bitte bis zum nächsten Update nicht nutzen ;) Leider ist diese Funktion echt fehleranfällig...

**Comment by Mojo1917** [comment]
Fehler behoben :)

**Comment by McFly753** [comment]
Danke!
