### ISSUE TITLE
Kann es sein, dass wenn ich diesen neuen Startscreen (nach Neuinstallation) überspringe, er mir keine „alten“ Datenbanken nachlädt bzw. diese evtl. sogar löscht? Ich warte nun schon sehr lange, aber außer der leeren angelegten Datenbank taucht nichts Neues auf? 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#429]

**Comment by McFly753** [comment]
PS: ich habe jetzt die App neu installiert, da sind dann wieder alle Daten da, aber vorher ist auch nach langem Warten nichts gekommen. Evtl. schaust du Dir nochmals dieses „Überspringen“ an.

**Comment by Mojo1917** [comment]
Okay, vielen Dank für den Hinweis. Ich schaue nochmal drüber. Wie viel Zeit ist bei beiden Malen zwischen dem Deinstallieren und Öffnen der neuen Version vergangen?

**Comment by McFly753** [comment]
Beim ersten mal habe ich dann nach 15min Wraten aufgegeben. Beim zweiten mal (ohne überspringen) waren nach ein paar wenigen Minuten die Daten alle da - ich probiere es nochmals.

**Comment by Mojo1917** [comment]
Du brauchst nicht weiter testen ;) Kann ich auch machen!

**Comment by Mojo1917** [comment]
Aber ich meinte gerade eher die Zeit, die zwischen der Deinstallation und dem Öffnen der Neuinstallation vergangen ist. Manchmal dauert es einige Sekunden, bis iOS alles der alten App gelöscht hat.

**Comment by McFly753** [comment]
Ok, da habe ich nicht lange gewartet... ;)

**Comment by Mojo1917** [comment]
Ich habe hier nochmal alles angeschaut und kann den Fehler leider nicht erklären oder reproduzieren. Lass uns das nach dem nächsten Update nochmal beobachten.

**Comment by McFly753** [comment]
Ok, jetzt gehts bei mir auch... kannst Du, wenn er im Hintergrund noch dinge lädt, evtl. irgendwo die Aktivität anzeigen, dass man weiss, das noch was kommt? Oder evtl. sogra einen Fortschritt?

**Comment by McFly753** [comment]
Und: kann die App bereits mit dem Runterladen anfangen, gleich wenn sie installiert wurde, oder muss sie einmal mind. geöffnet worden sein?

**Comment by Mojo1917** [comment]
Das geht leider nicht. Sie muss mindestens einmal geöffnet worden sein. Beim ersten Mal Öffnen legt die App dann eine Subscription für das Gerät und das Nutzerverzeichnis an, sodass die Daten dann immer geladen werden.

**Comment by Mojo1917** [comment]
> Ok, jetzt gehts bei mir auch... kannst Du, wenn er im Hintergrund noch dinge lädt, evtl. irgendwo die Aktivität anzeigen, dass man weiss, das noch was kommt? Oder evtl. sogra einen Fortschritt?
Ich schaue mal, wo man das gut anzeigen kann.

**Comment by McFly753** [comment]
Ich lege das in neues Ticket.
