### ISSUE TITLE
Der Tastatur bei Texteingaben ein "Ok/Fertig etc." geben?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#43]
(z.B. bei der Notiz, dass ich die Eingabe beenden kann?)

(Das Wischen oder ins Leere Klicken ist nicht ganz intuitiv

**Comment by Mojo1917** [comment]
Bei der Notiz handelt es sich um ein mehrzeiliges Feld. Wenn ich dies umsetze kann man keinen Zeilenumbruch mehr erzeugen.
Soll ich das dennoch umsetzen?

**Comment by McFly753** [comment]
Nein, das meine ich nicht. Das Retorun lassen. 
Mann kann doch über der Tastatur eigene Buttons anhängen, nicht?

**Comment by Mojo1917** [comment]
Achso verstehe. Habe einen solchen Button bei dem Textfeld eingefügt. Ich werde ihn noch an jeder Stelle die ich für sinnvoll erachte einbinden. Da ich ihn jedoch manuell aktivieren muss kann ich die ein oder andere Stelle vergessen. Dann mich bitte einfach nochmal darauf hinweisen.

**Comment by McFly753** [comment]
ok, danke!

**Comment by McFly753** [comment]
Bei der Frei-Suche fehlt er

**Comment by McFly753** [comment]
Und: wir könnten auch - um geleich im System zu bleiben - stat ein "Fertig" einen Pfeil nahc unten anzeiegn, wie ich sonst überall im App - was meinst Du?

**Comment by Mojo1917** [comment]
Ist überall hinzugefügt. In der Freisuche bietet die Tastatur jedoch den 'Searchbutton' soll ich diesen Button dennoch hinzufügen?

**Comment by Mojo1917** [comment]
Bei der Freisuche gibt es ja den 'Search'-button auf der Tastatur. Soll ich den 'Pfeil' dennoch einfügen oder ist das dann nicht 'zu viel'?
Zusätzlich nimmt die Leiste in dieser Ansicht einiges von der Liste/Karte an Platz.

**Comment by McFly753** [comment]
Probier mal. Weil es ist nichtganz verständlcih, wenn ich zuest suchen wollte, mir es dann aber anders überlegen udn auch der Suche raus will (ohne zu suchen) und ich dann hierfür "Suchen" drücken muss.

**Comment by Mojo1917** [comment]
Naja die Suche läuft ja automatisch mit jedem eigegebenen Buchstanden durch. Das heißt es macht keinen Unterschied, ob der Nutzer Suche tippt und suchen möchte oder Suchen tippt und nicht Suchen möchte.

**Comment by McFly753** [comment]
Wir könnten oben statt des Pfeiles "Abbrechen" schreiben? 
> Tel

**Comment by Mojo1917** [comment]
Siehe meinen Kommentar hier zur Änderung der Suchzeile #82

**Comment by Mojo1917** [comment]
Lass uns diese Konversation komplett nach #82 legen. Geht ja mittlerweile um das gleiche.
