### ISSUE TITLE
Absturz nach Umschaltung auf Pins von Bildchens auf der Kartenansicht

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#430]
>> gehe mal auf die Karte (wenn Du mindestens ein Objekt hast) und schaue die Karte von Bildern auf Pins um, dann stürzt sie ab (und macht das immer, auch nach Neustart) und ich muss sie zwangsneustarten

**Comment by Mojo1917** [comment]
Danke dir für die Info! Ein Update lädt gerade zu Apple hoch.

**Comment by McFly753** [comment]
Danke, passt!
