### ISSUE TITLE
Sortierungs-Bug bei Reihenfolge in "Erstellungszeit"

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#431]
Es wird zwar nach Datum sortiert aber innerhalb der Tage alphabetisch und nicht nach Uhrzeit. Das wäre aber sinnvoll.

**Comment by Mojo1917** [comment]
Meinst du in der Liste? Also das zwei Objekte, die beide vom 17.4.18 sind, nicht alphabetisch sondern nach der Uhrzeit in der Liste sortiert werden? (Auch wenn wir die Uhrzeit nicht anzeigen?)
Ich kann gerne mit dem nächsten Update die App zusätzlich die Uhrzeit speichern lassen, sodass das dann möglich wird.

**Comment by McFly753** [comment]
Ja, genau. Weil es irritiert, wenn sie dann nicht merh in der erstellten REihenfolge sind. Hat ein Zeit/Datumstempel nicht immer auch die Zeitangabe mit dabei? / Danke!

**Comment by Mojo1917** [comment]
Nein die App speichert aktuell nur das Datum ab. Ich habe es so umgesetzt, da wir den Nutzer beim manuellen Setzen eines (Erstellungs)-Datums nur das Datum angeben lassen. Hier bekommen wir auch immer nur das Datum ohne Zeit. Wir hätten dann verschiedene Daten und müssten für die manuell eingegebenen Daten eine Zeit 'ausdenken'.
Zudem zeigen wir dem Nutzer diese Zeit nicht an. Würden in der Liste aber nach diesen 'unsichtbaren' Kriterien sortieren.

**Comment by McFly753** [comment]
Ok, alles klar. Ich würde soclhe "besonderen" Daten auf 0:01 Uhr setzen oder so...

**Comment by Mojo1917** [comment]
Das Erstellungsdatum eines Objekts wird jetzt auf die Sekunde genau gespeichert. Ausgenommen sind die Fälle von oben. Damit werden sie auch besser nach dem Erstellungsdatum sortiert.

**Comment by McFly753** [comment]
Hmm... lass uns hier teelfonieren, weil die Objete werden weiterhin nach Alphabet sortiert. Auch wenn ich die Bilder verschiebe und somit ja das Erstellungsdatum ändere. (Oder sortierets Du nach Datum und Zeit dann nach Alphabet?) - aber den Zeitstemplet holt sich das Objet ja aus dem ersten Bild, oder?

**Comment by Mojo1917** [comment]
Die Sortierung sollte Datum - Zeit (auf Sekunden) - Name sein; also effektiv keine Sortierung nach Name, da es relativ umwahrscheinlich ist, dass zwei Objekte in der gleichen Sekunde angelegt werden. Ich schaue aber nochmal über das erneut setzen der Zeit aus den Bilder.

**Comment by Mojo1917** [comment]
PS: Hatte hier einen Denkfehler. Wir ziehen das Erstellungsdatum nicht aus dem ersten Bild. Da auch später Bilder hinzugefügt werden können, die älter sind wird das Erstellungsdatum beim ersten Bildimport gesetzt und danach immer nur, wenn ein älteres Bild importiert wird.
Soll ich mit dem nächsten Update die Daten einfach einmal neu mit der Zeit auslesen und setzen? Dann würden wir für jedes Objekt das Erstellungsdatum (und Zeit) auf die des ältesten Bildes setzen.

**Comment by Mojo1917** [comment]
Dann klappt auch die Sortierung wieder!

**Comment by McFly753** [comment]
Ja, lass uns das machen. (Aber nur in der blauen App). 
> Testen ist ganz einfach, wenn Du zwei Objkete am selben Tag nimmst und den Titel "A" und "B" verwendest und dann die Titel umbenennst. Die Reiehnfolegn dürfen sich nicht ändern.

**Comment by Mojo1917** [comment]
Klaro nur in der blauen!
Okay ja so klappt es bei mir. Wird dann daran liegen, dass das Datum nicht neu geladen wird.

**Comment by Mojo1917** [comment]
Okay die Daten werden mit dem nächsten Update neu geladen und dann passt die Sortierung auch.

**Comment by McFly753** [comment]
Leider noch nicht -> tel
