### ISSUE TITLE
Bilder Problem bei löschen von Datenbanken

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#433]
Über die Test-Zeit haben sich bei mir (neben meiner Hauptdatenbank) einige Datenbanken 1 angehäuft, die ich gerade alle gelöscht habe. Danach bin ich in meine Hauptdatenbank gegangen, doch dann wurden keine Bilder mehr angezeigt. Sonst waren alle Daten da?

**Comment by McFly753** [comment]
Mein IPad hat den Fehler dann wegen der selben Datenbank mitgezogen.

Aber: es wird mit angezeigt, dass ich 60 Bilder habe und die Datenbank ca. 300MB groß ist.

**Comment by McFly753** [comment]
Ich habe jetzt 2 Std. gewartet, aber die Bilder erscheinen nicht mehr (sind aber alle "als transparente Bilder" da.)

**Comment by Mojo1917** [comment]
Okay das muss ich mir nochmal anschauen. Es hört sich an, als würde die Cloud ein Datenupdate an die Geräte schicken, das dazu führt, dass die Daten lokal nicht mehr gefunden werden. Hast du auf einem Gerät geprüft, ob die Bilder nach einer Neuinstallation wieder sichtbar waren? (Nur, wenn du das schon getestet hast)

**Comment by McFly753** [comment]
teste ich schnell, geb Dir gleich bescheid.

**Comment by McFly753** [comment]
Ja, bei Neuinstallation sind ide Bilder dann wieder da.

**Comment by Mojo1917** [comment]
Okay danke!

**Comment by Mojo1917** [comment]
Der Fehler liegt nicht beim Löschen der Datenbank. Ich denke der Fehler ist nur 'zufällig' hierbei als Nebeneffekt der Synchronisation aufgetreten. Ich habe weitere Verbesserungen an der Synchronisation vorgenommen. Kann aber nicht ausschließen, dass er nochmal auftritt. Ich werde weiterhin versuchen ihn bei mir nochmal zu erzeugen. 

Sollte er bei dir auftreten gib mir bitte kurz bescheid und ich lade kurzfristig ein Update hoch, das prüft was mit den lokalen Bildern passiert ist. Dafür ist jedoch wichtig, das du die App nicht neuinstallierst. (Hoffe das ist nicht notwendig und das neue Update behebt den Fehler)

**Comment by McFly753** [comment]
ok, Danke! Ich konnte es nicht testen, weil ich ja davor die App schon neuinstalliert hatte (wodurch die Bilder dann da waren) - aber ich schliesse das Ticket hier und beobachte es.
