### ISSUE TITLE
Fortschrittsanzeige oder Aktivitätsanzeige, wenn im Hintergrund Daten aus der Cloud geladen werden.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#436]
... kannst Du, wenn er im Hintergrund noch dinge lädt, evtl. irgendwo die Aktivität anzeigen, dass man weiss, das noch was kommt? Oder evtl. sogra einen Fortschritt?

**Comment by Mojo1917** [comment]
Ich denke wir könnten eine solche Anzeige gut in den Einstellungen anzeigen lassen. Nur leider nicht mit Fortschritt, da die Cloud nicht mitteilt, wie viele Datensätze insgesamt vorliegen. Dies kann ich erst einsehen, wenn die Daten bereits geladen sind.

**Comment by Mojo1917** [comment]
In den Einstellungen wird jetzt weiter unten ein Indikator gezeigt für Info über den Status gibt.
Dieser wird auch live aktualisiert.

**Comment by McFly753** [comment]
Danke für das Drehrad, aber Du siehst ja, wieviel Datensätze schon angekommen sind. Kannst Du das hier anzeiegn, z.B. Objekte, Bilder, MB?

Und wenn das geht, dann zeig doch bitte das Drehrad auch ncoh oben rechts, links neben dem Menü-Icon an, wenn was geladen wird. Und wenn ich da drauf cliekcn würde, spirnge ich in die Einstellugen runter zu diesem Eintrag.

**Comment by McFly753** [comment]
Und: könnetst Du, wenn die Datenbank anzeigefähig ist, in diese einfach reinspringen (wenn keine Detailansicht offen ist)?

**Comment by Mojo1917** [comment]
Okay also wir können den Drehkreis auch oben im Menü einblenden. Jedoch kann dieser dann nicht geklickt werden. Scheint ein Fehler im iOS System zu sein. Sobald ich den Indicator dem Button hinzufüge kann er nicht mehr geklickt werden.
Ich lassen den Indikator trotzdem im nächsten Update eingeblendet und dann schauen wir weiter.

Wir zeigen jetzt die Anzahl der geladenen Objekte und Bilder. Die MB Anzahl zu zeigen wäre recht ineffizient, da die App dann die ganze Zeit den durch die Bilder belegten Speicher berechnen müsst.

Okay die Ansicht schließt sich jetzt sobald eine Datenbank zur Ansicht bereit ist. Die Objekte werden dann im Hintergrund weiter geladen.

**Comment by McFly753** [comment]
Kannst du in den Einstellungen den „Dreher“ rechts lassen, und die Anzahl der Geländern Daten darunter in einer neuen Zeile anzeigen? Schaut besser aus.

**Comment by Mojo1917** [comment]
Umgesetzt.

**Comment by McFly753** [comment]
Danke!
