### ISSUE TITLE
Irgendwas stimmt bei den Ländern nicht...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#437]
... schau Dir Australien an
![1060af94-db06-4fbe-8199-b39777586d1c](https://user-images.githubusercontent.com/493612/57090841-9ae71e00-6cbc-11e9-8204-d48cee17f84f.jpg)

**Comment by Mojo1917** [comment]
Wir beziehen die Adressen (und Landesnamen) von den Apple-Servern. Wenn eine andere Sprache auf dem Gerät eingestellt ist übermittelt Apple den Landesnamen in der entsprechenden anderen Gerätesprache. Wir können daran leider nicht viel ändern. Jedoch kann ich in der Statistik die Länder nach den ISO-Codes gruppieren. Dann werden sie hier wieder zusammengefasst.

**Comment by Mojo1917** [comment]
Okay durch die Verwendung der ISO Kennung der Länder funktioniert dies zuverlässig auch wenn die Länder mit unterschiedlichen Sprachen eingegeben wurde.

**Comment by McFly753** [comment]
Super, beobachte ich, wenn wir für alle umstellen, da ich dann diese anderen dazenbanken sehen.
