### ISSUE TITLE
Ist es möglich, in der Detailansicht noch einen horizontalen Swipe zuzulassen, und so durch die Objekte (nach der gerade eingestellten Reihnefolgelogik der Liste) zu scrollen? 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#438]
(wenn zu viel Arbeit, hinten angestellt)

**Comment by Mojo1917** [comment]
Ja das sollte möglich sein. Besonders schwer wird es nur, wenn wir eine Animation zeigen wollen, die es aussehen lässt, als würde der Nutzer in so einer Art Tabliste wischen. Ein einfaches neuladen der Ansicht beim wischen sollte sich leichter umsetzen lassen.
Würde das reichen? Weil für so eine Animation ist die Ansicht nicht so ganz vorbereitet.

**Comment by McFly753** [comment]
OK, klar, reicht. Wenn es nicht zu viel Aufwand ist.

**Comment by Mojo1917** [comment]
Okay alles klar. Nein das sollte eigentlich gut umsetzbar sein. Ich würde jedoch das 'scrolling' auch zulassen, wenn der Nutzer die Ansicht über die Karte geöffnet hat. In diesem Fall würde ich das scrolling von der Reihenfolge her so ablaufen lassen, als hätte der das Element aus der Liste gewählt.
Ich denke hierdurch halten wir die Ansicht konsistent.

**Comment by Mojo1917** [comment]
Ist umgesetzt.

**Comment by McFly753** [comment]
Danke!
