### ISSUE TITLE
Können wir in der Bilder-Detailansicht im Menü anbieten (unter Bild xy löschen): Bild speichern (bzw. teilen) und den normalen Bild-Teildialog des OS anbieten?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#439]
Weil wenn cih ein Objket geschcikt bekomme udn ich ein Bild hieraus bei mir in meinen Fotso abspeichern möchte, geht das nicht.)

**Comment by Mojo1917** [comment]
Okay der iOS Dialog zum teilen von Bildern ist eingebunden und bietet Optionen wie 'in Photos sichern'

**Comment by McFly753** [comment]
Bei Teilen in Dateien passiert nichts und bei Speicher in meine Fotos stürzt die App immer ab.

**Comment by Mojo1917** [comment]
Absturz ist behoben + Auch große Bilder können jetzt geteilt werden.

**Comment by McFly753** [comment]
Danke!
