### ISSUE TITLE
Tagauswahl sollte, wenn leer, ein + haben und dann zu den Einstellungen springen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#44]
... damit ich da Tags anlegen kann.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Schreibe dort besser einfach nur: "Tags anlegen." (ohen das Plus)

**Comment by Mojo1917** [comment]
Ist geändert. Änderung kommt mit dem nächsten Update.
