### ISSUE TITLE
Draft-Titel des Objektes: kannst Du, falls ich das Objekt mit einem Foto definiere, das alter als "heute" ist, in den Titel "Objekt DD.MM.JJJ" schreiben, aber hier das Datum des Bildes verwenden, also das ältere Datum?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#440]

**Comment by Mojo1917** [comment]
Okay der Titel wird nur überschreiben, wenn er noch den Startnamen mit dem 'Objekt' o.ä. enthält und das Objekt über ein Bild definiert wird.

**Comment by McFly753** [comment]
Fast... :) - du schreibst jetzt neben dem neuem richtigen Titel noch das alter des Objkets in den Titel dahinter? :) > "... Alter: 4 Tage"

**Comment by Mojo1917** [comment]
Oh ja hatte ich so verstanden ;) Streiche ich mit dem nächsten Update wieder raus!

**Comment by Mojo1917** [comment]
Okay ist ausgebessert

**Comment by McFly753** [comment]
Danke, achte hier bitte nur auf die Syntax. (Mein Handy steht auf English) > wenn ich ein Foto einfüge von heute und damit ein Objekt ertselle nennt er es Objekt 01/08/2019 und wenn ich ein Objekt basierend auf einem älteren Bild erstelle, nennt er es Objekt 28 Jun 2018 -> dass es einfach gleich ist.  // Am besten wäre, wenn es auch im Englsichen gleich wie im Deustxche ist, könnten wir evtl. immer: . oder / verwenden?

**Comment by Mojo1917** [comment]
Klar, die App verwendet jetzt im Objekt Titel immer die gleiche Darstellung mit '/'
