### ISSUE TITLE
Ist es möglich, in dem Attributfeld bei Eingabe sich in einem temporären Speicher alle vorhergehenden Einträge zu merken und bei dieser Eingabe in einem "Vorschlagsdropdown" (ähnlich Excel etc.) anzubieten? 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#441]

**Comment by McFly753** [comment]
Ja, so wenn es einfach ist: "Oder soll die App Attribute anbieten, die genauso beginnen und bei anderen Objekten definiert sind?"
> wäre auch ein guter Test für alles andere, was noch kommt... ;)

**Comment by McFly753** [comment]
Ja, so: "Oder soll die App Attribute anbieten, die genauso beginnen und bei anderen Objekten definiert sind?"

**Comment by McFly753** [comment]
ja, so: "Oder soll die App Attribute anbieten, die genauso beginnen und bei anderen Objekten definiert sind?"

**Comment by McFly753** [comment]
ja, so: "Oder soll die App Attribute anbieten, die genauso beginnen und bei anderen Objekten definiert sind?!

**Comment by McFly753** [comment]
ja, so: "Oder soll die App Attribute anbieten, die genauso beginnen und bei anderen Objekten definiert sind?"

**Comment by McFly753** [comment]
:) soviel zu der DB-Internetverbindung... sorry für den Spam. :)

**Comment by Mojo1917** [comment]
Okay wie an Telefon besprochen zeigen wir die drei an besten passenden Optionen. Wenn es mehr gibt visualisieren wir dies durch '...'

**Comment by Mojo1917** [comment]
Ist umgesetzt.

**Comment by Mojo1917** [comment]
Im Emulator hat die Positionierung des Dialogs immer gut gepasst. Wäre aber super, wenn du das nochmal auf einem echten Gerät mit iPhoneX Layout testen könntest ;)

**Comment by McFly753** [comment]
super, Danke!
