### ISSUE TITLE
Wurde irgendwie nicht übersetzt 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#445]
![IMG_8895](https://user-images.githubusercontent.com/493612/61999820-62b66800-b07e-11e9-8bc7-826762b4c9e2.PNG)

![IMG_8896](https://user-images.githubusercontent.com/493612/61999829-a4dfa980-b07e-11e9-807b-5dd360b12653.PNG)

![IMG_8898](https://user-images.githubusercontent.com/493612/61999830-a90bc700-b07e-11e9-82bf-823c1b07c60d.PNG)

![IMG_9170](https://user-images.githubusercontent.com/493612/61999850-0dc72180-b07f-11e9-9475-9282f59eaede.PNG)

![IMG_8929](https://user-images.githubusercontent.com/493612/61999841-e6705480-b07e-11e9-8ea2-a7c712d7f36c.PNG)

![IMG_9256](https://user-images.githubusercontent.com/493612/61999857-37804880-b07f-11e9-8067-9471043e9f4e.PNG)

**Comment by Mojo1917** [comment]
Oh alles klar, die hat Xcode wohl nicht richtig importiert und mir sind sie auch nicht aufgefallen. Kommt mit dem nächsten Update.

**Comment by Mojo1917** [comment]
Okay ist alles übernommen. Hier hatte XCode die Strings garnicht richtig exportiert. Nur 'Unbekannt' steht noch aus, da das aktuell als Ortsname in der Datenbank steht. Ich werde es aber filtern und im Englischen anders ausgeben!

**Comment by Mojo1917** [comment]
Jetzt alles korrigiert.

**Comment by McFly753** [comment]
Danke (ich habe nicht überprüft)
