### ISSUE TITLE
Bitte unsere neue Adresse verwenden / und im Englischen ggf. von der Syntax her richtig darstellen.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#446]
![IMG_8928](https://user-images.githubusercontent.com/493612/61999906-474c5c80-b080-11e9-856e-c2c43e4c4dd1.PNG)

**Comment by Mojo1917** [comment]
Jetzt auch korrigiert.

**Comment by Mojo1917** [comment]
Gerade gesehen, dass ich mir mit der Adresse nicht sicher bin. Ist es Tulpenweg 7 oder ist es Schmiedgasse 6?
Und was hat sich sonst geändert? Also bei den Nummern? Und ist es noch Handelsregister Augsburg?

**Comment by Mojo1917** [comment]
Warte noch auf die USt.ID. Alois hat sie beantragt. Bis dahin zurückgestellt.

**Comment by McFly753** [comment]
ok

**Comment by McFly753** [comment]
UsStNr: DE254954569

**Comment by Mojo1917** [comment]
Super danke, binde ich ein!

**Comment by Mojo1917** [comment]
Daten sind getauscht!

**Comment by McFly753** [comment]
Danke!
