### ISSUE TITLE
Ansichtsproblem im Englischen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#447]
![IMG_8927](https://user-images.githubusercontent.com/493612/61999953-33edc100-b081-11e9-84f6-dccc5033b177.PNG)

Ne Idee hier?

**Comment by Mojo1917** [comment]
Wir haben ein ähnliches Problem bereits im Deutschen auf dem iPhone SE. Hier lassen wir iOS die Größe automatisch regeln. Da sie dadurch jedoch recht klein wird hatte ich das für alle anderen Geräte deaktiviert. Sollen wir es damit mal versuchen? Andernfalls würde mir nur noch einfallen den Text zu kürzen.

**Comment by Mojo1917** [comment]
Wir könnten 'Image' mit 'Img.' kürzen

**Comment by McFly753** [comment]
Ok, probiere einfach mal, so wie Du es am besten siehts.

**Comment by Mojo1917** [comment]
Okay, ist umgesetzt.
