### ISSUE TITLE
Von Max: Darstellung Datenbankübergreifend ...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#448]
... Obwohl ich in der Flowers Datenbank nur 2 Einträge habe wird hier auch mein letzter Eintrag in die Food Datenbank angezeigt 

(Diese Darstellung verschwindet nach einmal hin und verschalten)

Bild folg...

**Comment by McFly753** [comment]
![IMG_9284](https://user-images.githubusercontent.com/493612/62000136-e2dfcc00-b084-11e9-8284-a1dc056d3c85.jpg)

**Comment by Mojo1917** [comment]
Okay, schaue ich mir an.

**Comment by Mojo1917** [comment]
Fehler sollte bereits behoben sein.
