### ISSUE TITLE
Tag-Bereich dynamisch machen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#45]
Also wenn es keine Tags gibt, reicht eine Zeile.

**Comment by Mojo1917** [comment]
Kann ich gerne machen. Da das Design jedoch sehr komplex muss hier mit festen Größen gearbeitet werden. 
Sprich: Verkleinere ich die Höhe dieses Elements vergrößert sich hierdurch nur der Abstand zum Element darunter.
Soll ich dies dennoch umsetzen?

**Comment by McFly753** [comment]
Hmm. Du kannst kein Textfeld variable in der GRöße verändern? 
Darunter würde dann das einzeilieg Textfeld kommen (Fix, immer eine Zeile) 
und darunter füllen wir mit Notizfled dynamsich auf. 
Geht das nicht?

**Comment by Mojo1917** [comment]
Doch können wir machen. Dann bewege ich alle Element einfach per Code dynamisch zueinander.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Unten das große Textfeld geht aber dann entweder um zwei Spaten oder um eine Spalte nicht ganz bis nach unten.

**Comment by Mojo1917** [comment]
Okay ist jetzt behoben. Änderungen kommen mit dem nächsten Update.
