### ISSUE TITLE
Vom Max: ...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#452]
... evtl. hatte ich das Ticket schonmal reingestellt:

"Fotos ohne Koordinate eingefügt, dann lange auf die Karte gedrückt - App stürzt ab"

![IMG_9289](https://user-images.githubusercontent.com/493612/62316414-ad2d4f80-b497-11e9-8393-c38dea2c6289.PNG)

**Comment by Mojo1917** [comment]
Stammt der Fehler aus der aktuellen Version? Ich bekomme ihn leider nicht reproduziert.

**Comment by McFly753** [comment]
Ich frage nach...

**Comment by McFly753** [comment]
Lass uns schliessen
