### ISSUE TITLE
Didaktische Hilfe...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#453]
Können wir, wenn der User aus der Detailansicht auf die Karte des Objkets klickt (und dann zur Karte springt und zu dem Objekt zoomt) das Objket "ausgewählt" anzeigen, so dass bereits das kleine Kästchen mit dem Objekttitel und dem (i) daneben angezeigt wird (und der User damit leicht sofort wieder zurück in diese Desatilansicht springen kann?

**Comment by Mojo1917** [comment]
Ist umgesetzt. Kommt mit dem nächsten Update.
