### ISSUE TITLE
Icloud-Sync-Anzeige stimmt nicht... / Optimierung...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#455]
... ich habe meine App gelöscht und ca. 2.5GB Daten in der Icloud unter Locbase. Er hat gerade mal 3 leere Datenbanken wiederhergestellt und sagt aber bereits, dass die Icloud Synchronistaion abgeschlossen ist.

Auch das Drehen des Kreises ist irritierend, wenn er sich nicht merh Dreht, obwohl noch was hoch/runter geladen wird.

> Allgemein, können wir hier die Anzeige etws ändern:

- darunter das mit den "Die Daten werden..." nicht anziegen, dafür die noch auzuführende Aktion. Z.B.: 54,5MB auf Gerät / 2.5GB in i-Cloud (und daneben entweder der Drehkreis oder ein Häckchen.)
- ggf. könnten wir unter diese Zeile doch die Erklärung anzeiegn, dann aber entsprechend der Synchronisationsrichtung: 
"Es wurden noch nicht alle Daten aus der i-Cloud geladen. Die Daten werden angezeigt, sobald die Synchronisation abgeschlosen ist."
oder
"Es wurden noch nicht alle Datein in die i-Cloud geschrieben."

- Zsätzlich nach Neuinstallation der App, nachdem ich von dem "Begrüßungs-Warte-Screen" (den ich manuell überspringen könnte) zur App sebst springe, würde ich noch ein Popup anzeigen und dort schrieben: "Es wurden noch nicht alle Daten aus der i-Cloud geladen. Die Daten werden angezeigt, sobald die Synchronisation abgeschlosen ist."

// EDIT Niklas:
Anzeige, wie viele Daten (Anzahl) noch hoch oder runter geladen werden müssen.

**Comment by Mojo1917** [comment]
Umgesetzt!
