### ISSUE TITLE
Wenn ich ein Blankobild bei einem Objekt hatte, dann aber Bilder Hochlade, würde ich das Blankobild löschen...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#456]
... ausser ich habe einen Kommentar in dem Bild gemacht.
<img width="204" alt="Bildschirmfoto 2019-08-03 um 19 10 46" src="https://user-images.githubusercontent.com/493612/62414950-9404da00-b622-11e9-9fa0-a5e6fe41da0e.png">

**Comment by Mojo1917** [comment]
Okay, ist angepasst.
