### ISSUE TITLE
Beim Rückspielen eines Backups, wenn es größer ist, können wir dann einen Fortschritt anzeigen?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#457]
(Es wird ein Fortschritt beim Einspielen des Backups angeziegt, aber nicht beim Laden des Backups)

![IMG_9872](https://user-images.githubusercontent.com/493612/62414972-de865680-b622-11e9-9c9a-d2b5bf506240.png)

**Comment by Mojo1917** [comment]
Klar, der Fortschritt wird jetzt angezeigt ;)
