### ISSUE TITLE
Beim Export von (ganzen!) Datenbanken werden Fehler bei Feldbezeichnungen angezeigt?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#458]
![IMG_9795](https://user-images.githubusercontent.com/493612/62415017-b519fa80-b623-11e9-9f87-66c8b4bd43f2.png)

![IMG_9796](https://user-images.githubusercontent.com/493612/62415018-b9deae80-b623-11e9-9336-15701d72abf0.png)

**Comment by McFly753** [comment]
Importiere mal diese Testdatenbanken vom Max (per Mail/Airdrop).

**Comment by Mojo1917** [comment]
Vielen Dank für die Datei!
Ich konnte den Fehler jedoch noch nicht ganz nachvollziehen. Beim exportieren und importieren eines Backups treten bei den Datenbanken aber keine Fehler auf, oder?

**Comment by McFly753** [comment]
Es geht nur um den Import dieser Datenbank. Wenn Du sie importierst, werden dann diese Fehler nicht angezeigt?

**Comment by Mojo1917** [comment]
Doch ich bekomme die Fehler auch angezeigt. Ich habe auch verstanden wie der Fehler auftritt und es ist kein Fehler beim Import, hier verhält die App sich wie sie es sollte. Jedoch ist die Datei beim Export nicht einwandfrei erstellt worden. Ich komme aber noch dahinter ;)

**Comment by Mojo1917** [comment]
Okay ich habe den Fehler beheben können. Dieser konnte beim Export von mehreren Datenbanken entstehen. Hierbei hat die App die Eigenschaften nicht richtig verknüpft. Der Fehler tritt nach dem nächsten Update nicht mehr auf.
Soll ich die Fehler in der Datei von dir korrigieren? Oder kann diese neu exportiert werden.
