### ISSUE TITLE
Wenn ich Datenbanken (mit unterschiedlichen "Tag"-Feld-Bezeichnungen switche, wird diese in den Einstellungen nicht gleich aktualisiert. Erst wenn ich die Tag-Benennung verändere, wird sie aktualisiert.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#459]
![IMG_F495221D8E25-1](https://user-images.githubusercontent.com/493612/62415059-34a7c980-b624-11e9-9500-94894476d283.jpeg)

**Comment by Mojo1917** [comment]
Danke, ist korrigiert. Kommt mit dem nächsten Update.
