### ISSUE TITLE
Bitte die Länder und Orte zuerst nach Anzahl der Objekte und dann erst (bei gleicher Anzahl) nach Alphabet sortieren.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#460]
<img width="322" alt="Bildschirmfoto 2019-08-03 um 19 26 57" src="https://user-images.githubusercontent.com/493612/62415097-bf88c400-b624-11e9-8af1-1f305d1d7c04.png">

**Comment by McFly753** [comment]
Und das Unbekannt bitte immer zum schluss setzen.

**Comment by Mojo1917** [comment]
Ist umgesetzt! Kommt mit dem nächsten Update :)
