### ISSUE TITLE
Übersetzung/Sprache

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#463]
![IMG_9681](https://user-images.githubusercontent.com/493612/70543706-c9f43500-1ba5-11ea-8f0f-69edad96adff.png)

**Comment by Mojo1917** [comment]
Dieser Wert kommt auch dem Nutzerfeld 'Attribute', dass in den DB-Einstellungen gesetzt werden kann. Daher keine Übersetzung dafür möglich ;)

**Comment by McFly753** [comment]
Klar... :) // Ich sollte die Tickets vom Team besser anschauen, bevor ich sie weitergebe... ;)
