### ISSUE TITLE
Beim Verschieben des Hauptbildes an eine andere Position ist die App abgestürzt. Mit diesem Hauptbild wurde im Offlinemodus das Objekt erstellt.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#467]

**Comment by Mojo1917** [comment]
Fehler tritt bei mir nicht mehr auf. Ggf. bereits in meiner Arbeitsversion korrigiert. Bitte nach dem nächsten Update nochmal testen. Sorry für die Umstände..
