### ISSUE TITLE
Scroll auch bereist zulassen, wenn noch kein Scoll notwenig wäre...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#47]
... das hattest Du in der letzten Version so.

Z.B. bei der Listenansicht. 

Hier spielt man einfach immer gerne... ;)

**Comment by Mojo1917** [comment]
Meinst du das 'bouncen' in der Liste? ;)

**Comment by McFly753** [comment]
Ja, bzw. dass ich die Liste überhaupt vertikal bewegen kann, auch wenn sie sich noch nicht im Scroll befindet.

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Die Liste bounct jetzt auch wenn noch nicht genug Daten zum scrollen vorhanden sind. Änderung kommt mit dem nächsten Update.
