### ISSUE TITLE
Wenn ich im Flugzeug z.B. ein Objekt mit zwei Bildern erstelle, bekomme ich das "Fehlerhafte Adressermittlungs"-Fenster zweimal. Kannst Du das auf einmal beschränken?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#471]

**Comment by Mojo1917** [comment]
Meinst du, wenn du zwei Fotos zusammen oder nach­ei­n­an­der importierst?

**Comment by McFly753** [comment]
Genau, Sorry!

**Comment by Mojo1917** [comment]
Okay, wird jetzt nur noch einmal angezeigt. Wenn du das Object jedoch schließt und anschließend wieder öffnest wird der Dialog wieder gezeigt. Andernfalls müssten wir diese Info auch auf dem Gerät abspeichern.

**Comment by McFly753** [comment]
Ok, Danke!
