### ISSUE TITLE
Kannst Du in der Statistik (und der Anzeige bei dem Ort) unterscheiden zwischen "unknown" und "unknown" - also einmal ist es, dass es keinen Ort gibt und das andere mal, dass das Objekt keine Koordinate besitzt (bzw. bei 0 0 liegt). Evtl. einmal "Ort ohne Namen" und das andere mal "kein Ort". (Etc.)

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#473]

**Comment by Mojo1917** [comment]
Fast fertig. Fällt nur in ein paar Fallen noch aus.

**Comment by Mojo1917** [comment]
Ist an allen Stellen, an denen die Orte der Objekte angezeigt werden angepasst. Nur in der Statistik kann ich es nicht so leicht abfangen, da die Daten hier anders aus der Datenbank kommen.
Da es eh wenig Sinn macht auf dieses Attribut zu filtern und würde ich es in der Statistik vielleicht machen, wie von dir hier vorgeschlagen? Würde das passen? #480

**Comment by McFly753** [comment]
Ok!
