### ISSUE TITLE
Kannst Du das "last on" nicht anzeigen, wenn es noch keinen Besuch gibt?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#475]
![IMG_8860](https://user-images.githubusercontent.com/493612/70548984-70dccf00-1bae-11ea-9014-c0641819aaa0.jpeg)

**Comment by Mojo1917** [comment]
Kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke!
