### ISSUE TITLE
Wenn ich eine zweite Datenbank erstelle... 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#48]
... würde ich bis auf "Datenbank2" und Objket/Objkete nichts weiter ausfüllen, auch keine Objketeigenschaften.

**Comment by Mojo1917** [comment]
Hat sich erübrigt mit diesem Punkt #54

**Comment by McFly753** [comment]
Lass uns beim erstellen der Datenbank aber sofort den Cursor in das Datenbanknamen-Feld setzen und die Tastaur ausklappen.

**Comment by Mojo1917** [comment]
Ist übernommen. Änderung kommt mit dem nächsten Update.
