### ISSUE TITLE
Mehrere Fotos auf einmal machen können... -> Vom Max: Ich fände es sehr brauchbar wenn man beim Fotografieren mehrere Fotos direkt hintereinander machen könnte (momentan nutze ich hierfür den workarounds dass ich zuerst Fotos mit meiner normalen Fotoapp mache und danach erst in Locbase anlege und importiere dann die gemachten Fotos

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#481]

**Comment by Mojo1917** [comment]
Wir können das Photo import und photo aufnehmen in einen Dialog legen. Dann kann man Photos machen und welche aus der Galerie auswählen. Ich denke das ist vielleicht sogar noch besser.

**Comment by Mojo1917** [comment]
Verhalten entsprechend angepasst. So geht jetzt alles viel schneller.

**Comment by Mojo1917** [comment]
Notiz an mich: Änderungen wie besprochen umsetzen.

**Comment by Mojo1917** [comment]
- Dialog für Sample image entfernt
- Back to top button im Auswahldialog wieder sichtbar
- Sample image wird erzeugt, wenn das Objekt ohne Bild gespeichert wird.

**Comment by McFly753** [comment]
Danke!
