### ISSUE TITLE
Bernadette: Die meisten Beschriftungen in Settings sind noch Deutsch, aber manche schon English

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#485]

**Comment by McFly753** [comment]
![image](https://user-images.githubusercontent.com/493612/71543597-b8859800-29af-11ea-8a14-83dace4b3e5f.png)

**Comment by Mojo1917** [comment]
Scheint ein Fehler in der Version zu sein. Bei mir sind alle übersetzt. Checke ich nochmal nach dem nächsten 'Release Build'. Vielleicht kommt es hier zu Fehlern.
