### ISSUE TITLE
Bernadette: English Übersetzung. Der Name des Objects wird dann automatisch als ganzes Wort zusammengefügt, e.g. "Objectname" welches aber im Englischen nicht geht. Da muss es "object name" heißen. 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#487]
Matthias: nur wenn es leicht zu fixen ist, ansonsten lassen.

**Comment by Mojo1917** [comment]
Sollte sich leicht fixen lassen. Aber an welcher Stelle passiert das? Kann es gerade nicht finden.

**Comment by Mojo1917** [comment]
Found it! Fixed with the next update.
