### ISSUE TITLE
Location basierte Benachrichtigung geht scheinbar nur, wenn App offen ist.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#488]

**Comment by Mojo1917** [comment]
Funktioniert bei mir. Ist 'Always' in den iPhone Einstellungen unter Locbase > Location ausgewählt?

**Comment by McFly753** [comment]
Ja, ist es. Aber ich kann es nochmals Aus und an schalten und erneut testen

**Comment by McFly753** [comment]
ich teste nochmals

**Comment by McFly753** [comment]
Ich musste diese Funktion ausschalten und nochmals anschalten, erst dann ging sie wieder - kannst Du da was optimieren?

**Comment by Mojo1917** [comment]
Klar, ich schaue was Apple da zu lässt ;)

**Comment by Mojo1917** [comment]
Muss hierfür über die nächsten Tagen auf meinen Geräten testen :)

**Comment by McFly753** [comment]
ok

**Comment by Mojo1917** [comment]
Okay, beim starten des Tracking wird iOS jetzt mittgeteilt, dass es wichtig ist, dass der Standort Zugriff nicht beendet wird.
Benachrichtigungen funktionieren jetzt auch, wenn nur 'While using App' ausgewählt ist. In diesem Fall blendet die App oben den blauen Balken ein, der angibt, dass die App auf den Standort zugreift.

**Comment by Mojo1917** [comment]
Beachte aber, dass Locbase dich nur einmal alle 24H darüber informiert, dass ein Objekt in der Nähe ist.

**Comment by McFly753** [comment]
Danke!
