### ISSUE TITLE
Wenn ich bei einem neuen Projekt mit der Kamera ein Foto machen will, stürzt mir die App IMMER ab.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#490]

**Comment by Mojo1917** [comment]
Okay, muss hierfür auf Crash report warten!

**Comment by Mojo1917** [comment]
Wird mit dem nächsten Update korrigiert.

**Comment by Mojo1917** [comment]
Ticket sollte mit dem neuen Photoimport obsolet sein

**Comment by McFly753** [comment]
Ja, nur ich habe ein anderes Problem: wenn ich auf diesem Weg ein Bild mach, besitzt das Bild keine Geokooridnaten!
