### ISSUE TITLE
Datenbank Struktur Import stürzt ab

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#493]

**Comment by Mojo1917** [comment]
iOS 13 abhängiger Fehler. ist jetzt behoben.

**Comment by McFly753** [comment]
wird getestet.

**Comment by McFly753** [comment]
Kann das mein komplettes Team schon testen oder nur die paar (direkten) Tester?

**Comment by Mojo1917** [comment]
Sehe gerade, dass die Version genehmigt wurde, aber nicht automatisch freigegeben. Soll ich sie für alle freigeben? Es gab ja keine kritischen Fehler bei dir, richtig?

**Comment by McFly753** [comment]
Ja, wäre gut! Danke!

**Comment by Mojo1917** [comment]
Okay, ist freigegeben.

**Comment by McFly753** [comment]
Passt! Danke!
