### ISSUE TITLE
Make sync button clickable

### ISSUE THREAD

**Issue by Mojo1917** [Mojo1917/LocBase#494]

**Comment by Mojo1917** [comment]
Leider nicht möglich. Sobald ich den 'Kreisel' zu dem Button hinzufüge lässt er sich nicht mehr klicken.  Geht nur solange ich Bild oder Text verwende. 
Tut mir leid.

**Comment by McFly753** [comment]
ok, alles klar. was ist, wenn wir daneben/drunten in so einem fall "syncing" schreiben - dann wäre er klickbar, oder? ;)

**Comment by Mojo1917** [comment]
Das ist richtig, aber ich kann nur den Kreisel zeigen, oder 'syncing' schreiben. Sollen wir es damit versuchen?

**Comment by McFly753** [comment]
Ja, in ganz kleiner Schrift, dass es wie ein Icon aussieht. Du kannst ihn aber nicht blinken etc. lassen? // aber warum kannst Du nicht einen Icon (Dreirad) und daneben einen Text anzeigen, das verstehe ich nicht ganz?

**Comment by McFly753** [comment]
Also der Kreise ist noch klickst, das das „sync“ daneben?

**Comment by Mojo1917** [comment]
Okay, jetzt verstehe ich was du meinst das geht natürlich! Dann mache ich Text und daneben der Kreisel, wobei der Text klickbar ist.

**Comment by Mojo1917** [comment]
Habe es jetzt doch geschafft, den Kreis mit einem ClickEvent zu versehen. Hatte beim letzten Mal wohl eine Flag vergessen.

**Comment by McFly753** [comment]
Danke!
