### ISSUE TITLE
erste Datenbank als Muss

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#5]
Ich würde den User "zwingen", wenn die App noch keein Datenbank hat, eine anzuzeiegn. Also in den Einstellungen starten.

> Hier würde ich die erste Datenbank auch zuerst als Eingabefeld wie darunter den Objektnamen anzeigen, das ist intuitiver. Erst wenn man dieses Feld verlassen hat, wird es mit pfeil nach rechts angezeigt wie derzeit 

> solange kein Namen für Datenbank und Objekt/Objekte gewählt wurde, würde ich den User nicht aus den Einstellungen gehen lassen.

**Comment by Mojo1917** [comment]
Ich denke dieses Verhalten der App könnte zu Verwirrung führen. Sollen wir nicht besser eine Art 'Setup'-Screen einbauen? Dieser wird dann beim Ersten Öffnen der App angezeigt und verlangt die nötigen Eingaben'

**Comment by McFly753** [comment]
Ja, das wäre auch eine Lösung. 
Oder wir füllen die erste Datenbank sogar teilweise voraus und dann kann der User, muss sie aber nicht verändern.
Datenbankname: Neue Datenbank
Objektnamen: Objekt / Objkete
Drei Eigenschaften: Eigenschaft1/Eigenschaft2 und Eigenschaft3
Zwei Tags: Tag1 und Tag2

Oder wir füllen die Datenbank so wie gesagt teilweise aus UND machen eine Setup-Einführung. Also merh ne Hilfe?

**Comment by Mojo1917** [comment]
Datenbanken werden jetzt vorausgefüllt. Sobald der Nutzer zum ersten Mal die Einstellungen öffnet werden ihm hier die einzelnen Funktionen in der Einstellungen erklärt.

Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Super, vielen Dank. -> Wird dem User auch was in der normalen Objketanzeige erklärt, wenn er das erste mal die App öffnet?

**Comment by Mojo1917** [comment]
Nein kann ich aber gerne einbauen, wenn dir der 'Tutorial'-Stil gefällt, wie er in den Einstellungen ist.

**Comment by McFly753** [comment]
Denek ich wäre sinnvoll, dann erklären wir somit die ganze App und nicht nur die Einstellungen, was denkst Du?

**Comment by Mojo1917** [comment]
Ja macht auf jeden Fall Sinn. Sonst könnte der Einstieg für externe Nutzer schwierig werden.

**Comment by McFly753** [comment]
Ja, passt, ist ne schöne Lösung. Machen wir dann für alles zum Schluss. 
NUR: ich muss aus dieser "Hilfe" rauskommen, also sie abbrechen können. (Wiel derzeit muss ich bis zum Ende drin bleiben.)

**Comment by Mojo1917** [comment]
Tutorial kann jetzt pausiert werden. 
Durch Tippen außerhalb des blauen Kreises wird das Tutorial an der Stelle bis zum nächsten Öffnen der Einstellungen pausiert. Oder soll ich es dann komplett beenden?

Änderungen kommen mit dem nächsten Update.

**Comment by McFly753** [comment]
Nein, pausiert ist gut.

**Comment by McFly753** [comment]
Wir müssen das Tutorial anders machen. Wril jetzt klicke ich ausserhalb, es geht zu und beim nächsten mal in den Einstellungen startet es von neuem.

Lass uns doch irgendwo einen text anhöängen mit "Toutorial beenden" // Und später haben wir dann eh noch irgendwo einen Holfebutton, wo man es wiedr einsteraten kann.

**Comment by Mojo1917** [comment]
Okay verstehe. Dann lass es uns doch so machen, dass das Klicken außerhalb das Tutorial beendet.

Und wir setzen oben rechts neben das Impressum-Icon einen Button mit dem das Tutorial wieder gestartet werden kann. Was denkst du?

**Comment by McFly753** [comment]
Ok, lass uns das probieren

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten
