### ISSUE TITLE
Wenn ich aus der Statistik mit einem Filter herauskomme, müssen natürlich die anderen Filter aufgehoben werden...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#50]
.... also ich übernheme dann nur diesen einen Filter aus der Statistik.

**Comment by Mojo1917** [comment]
Okay die Filter werden ab jetzt nur noch um den neuen Suchbegriff erweitert und nicht mehr zurückgesetzt.

**Comment by Mojo1917** [comment]
Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Geht noch nicht ganz, z.B. wird ein zuvor gesetzer Favroiten-Filter nicht aufgehoben.

**Comment by McFly753** [comment]
Und: freitextfilter werden hier addiert.

**Comment by McFly753** [comment]
Und: ich kann dann manuell diesen Freitextfilter nicht mehr löschen?

**Comment by Mojo1917** [comment]
Da wir die Suchleiste nach unten gelegt haben muss sie manuell nach oben verschoben werden, wenn das Keyboard sichtbar wird. Leider hat iOS hier den Fehler, dass dann den 'Löschen' Button nicht mehr funktioniert. Ich habe gerade versucht die zu umgehen oder den Button anders hinzuzufügen. Leider mehr all das nicht.

Wir haben also nur zwei Möglichkeiten:
1. Die Suchleiste wieder nach oben zu legen (Passt aber nicht ins Design, wenn der Rest der Filter unten ist)
2. Es so lassen und ggf. den Löschen Button ausblenden soweit möglich. Sobald die Tastatur wieder geschlossen ist kann der Button wieder verwendet werden.

**Comment by McFly753** [comment]
es hat nichts mit dem Keyboard zu tun. Ich konnte (sobald Du addiert hats) den Löschbutton nigt mehr nutzen (Keybord war geshlossen) - das wichtig ist, dass Du die bestehenden Filter löschst, wenn ich aus der Statoistik mit einer Übernhame komme. (Stern und Freitext)

**Comment by Mojo1917** [comment]
Lass uns das am einfachten auch am Telefon besprechen.

**Comment by McFly753** [comment]
OK.

**Comment by Mojo1917** [comment]
Zurücksetzen aller Filter und Suchbegriffe sobald in der Statistik etwas ausgewählt wurde. Zusätzlich setzen wir alle Filter und Suchbegriffe zurück, wenn die App gestartet wird.

**Comment by Mojo1917** [comment]
Filter werden jetzt bei jedem Mal, wenn der Nutzer aus der Statistik kommt zurückgesetzt. Zusätzlich werden sie zurück gesetzt, wenn die App startet.

Änderung kommt mit dem nächsten Update.
