### ISSUE TITLE
Den Auf-Eigenen-Standort-Button doppelt belegen.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#52]
Würde das gehen? Der erste klick auf die Standorttaste scrollt zu deinem Standort (ohne den Zoombereich zu ändern) und falls ich nichts manuell an der Ansicht ädere und nochmals auf diese Taste drücke, zoomt die Anzeieg auf meinen Standort rein?

**Comment by Mojo1917** [comment]
Klar wird gemacht.

**Comment by Mojo1917** [comment]
Ist eingefügt. Änderung kommt mit dem nächsten Update
