### ISSUE TITLE
Der Bilder/Daten Button ist vertauscht...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#55]
... also wenn man sich die Logik des Map/Sat Buttons anschaut.

**Comment by Mojo1917** [comment]
ads heißt soll die App beim Ersten Mal mit der Bilderansicht starten?

**Comment by McFly753** [comment]
Das ist egal, mir geht es daraum, dass die Logik des einen Buttos wie die Logik des andern ist. (alos entweder zeigt der Button an, in welchen Stadius ich hinschalten kann oder der Button zeigt an, in welchem Stadius ich mich gerade befinde. Derzeit hat der obere Button die eine und der untere die andere Logik - und diese sollte gleich sein.

**Comment by Mojo1917** [comment]
Okay jetzt verstehe ich das. Aber diese Logik ist doch derzeit schon eingebaut. Beide Button zeigen an auf was der Nutzer umschaltet sobald er auf den Knopf drückt.
Bilder um auf Bilder zu schalten; Daten um auf Datenansicht zu schalten.
Sat um auf Satelliten zu wechseln; Map um auf die Karte zu wechseln.

**Comment by McFly753** [comment]
Jetzt passt es, vorher war der obere falsch herum... :)
