### ISSUE TITLE
Beim Verändern von Bildkoordinaten den text etwas ändern...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#57]
.... und zwar zeig an "Schreibe Positionsdaten" (Statt "lade")

**Comment by Mojo1917** [comment]
Ist übernommen. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Sorry, bitte schreibe da hin. "Schreibe neue Positionsdaten." 
danke! ;)

**Comment by Mojo1917** [comment]
Ist übernommen. Änderung kommt mit dem nächsten Update.
