### ISSUE TITLE
Datenbank-Titel-Anzeige

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#6]
> Oben die Anzeige des Titels der Datenbank würde ich nicht unterstreichen, wenn dann nur die Klammer.

**Comment by Mojo1917** [comment]
Kannst du mir hierzu einen Screenshot anhängen? Auf meinem Testgerät sehe ich nicht unterstrichen. Nur damit ich nicht an der falschen Stelle in der App suche.

**Comment by McFly753** [comment]
#17

**Comment by McFly753** [comment]
Und die Klammer kannst Du auch weglassen, wenn es ohne klammer schöner aussieht. Eigtlcih reicht vom Content her dann auch 3/27 statt 3 von 27

**Comment by Mojo1917** [comment]
Okay die Darstellung habe ich geändert.

**Comment by Mojo1917** [comment]
Die Buttons sind unterstrichen, weil du in deinen Einstellungen > Allgemein > Bedienungshilfen 'Tastenformen' aktiviert hast. Um die Striche zu deaktivieren muss nur diese Option deaktiviert werden.

**Comment by McFly753** [comment]
Du hast Recht, habts ausgeschaltet... ;)

**Comment by Mojo1917** [comment]
Glaube das hier sollte dann so passen.

**Comment by McFly753** [comment]
Ja, denke ich auch.

**Comment by McFly753** [comment]
-> s. Kommentar in #7

**Comment by Mojo1917** [comment]
Ist übernommen. Kommt mit dem nächsten Update.
