### ISSUE TITLE
Sortierung beim Umschalten zwischen Karte und Liste gleich lassen.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#61]
Fände ich intuitiver (auch wenn die nicht "ganz" gleich sind, wegen der fehlenden Reihenfolge in der Kartenansicht).

**Comment by Mojo1917** [comment]
Okay wird gemacht.

**Comment by Mojo1917** [comment]
Sind jetzt synchron. Änderung kommt mit dem nächsten Update.
