### ISSUE TITLE
Impressum

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#62]
Du kannst Dich gerne ins Impressum mit reinschreiben.

Gib als Firma diese Adresse an:

Thinktronic GmbH
Lechfeldstr. 16
86438 Kissing

Geschäftsführer: Till Haunschild
Handelsregister Augsburg
HRB 27089
St.Nr: 143/186/30713
Ust-ID: DE 254954569

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
- Schreib oben über Thinktronic dazu: 
Idee & Konzept:

- Setz oben, wenn Du das Logo stehen läßt, auch den NAmen der App dazu.

- Und schau, ob Du bzgl. Leerzeichen udn Schriftgrößen der Überschriften es etwas ruhiger setzen kannst (die erste Seite).

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

Nur was soll ich genau an den Überschriften ändern? Habe sie jetzt mal an den linken Rand gezogen.

**Comment by McFly753** [comment]
Hm, lass sie mal zentriert.

**Comment by Mojo1917** [comment]
Sind jetzt wieder zentriert. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten
