### ISSUE TITLE
Der Overlay-Kasten unten bei der Beschriftung des Bildes liegt an einer ungünstigen Position...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#64]
.... zumindest bei Iphone-Hochkant Bildern... 

(Weil es nicht ganz sauber aussieht. / Wenn man reinzoomt ist alles wieder gut.)

**Comment by McFly753** [comment]
![img_4408](https://user-images.githubusercontent.com/493612/35178699-e2d6c68e-fd8c-11e7-8d34-e0b85c0d4823.PNG)
![img_4409](https://user-images.githubusercontent.com/493612/35178700-e3040496-fd8c-11e7-9c9e-393949d4bad0.PNG)

**Comment by Mojo1917** [comment]
Ist behoben. Der Kasten und das Bild überlappen sich jetzt nicht mehr. Das ist leider die einzige Möglichkeit dieses Verhalten zu ändern.

Änderung kommt mit dem nächsten Update.
