### ISSUE TITLE
Bitte abfragen, falls ich einen Besuch vor das Erstellungsdatum lege...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#65]
... dass man hiermit das Erstellungsdatum des Objketes nach vorne legt (dann wird dieses ausnahmsweise verändert)

... oder man bricht damit ab.

**Comment by Mojo1917** [comment]
Wie ist es, wenn ein Besuch durch ein Bild erzeugt wird und vor dem Erstellungsdatum liegt? Dann auch nachfragen oder direkt ändern oder ignorieren?

**Comment by McFly753** [comment]
Hmm, dann würde ich auch fragen, ob ich das Erstellungsdatum verändern soll. Wenn der User nein sagt, dann lege ich aber auch keien Besuchseintarg durch dieses Bild an.

**Comment by Mojo1917** [comment]
Ist implementiert. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Passt. Ändere nur den Text leicht ab:

- Du versuchst, (Komma danach)
- Soll das Erstellungsdatum auch auf den 3.12.2017 gesetzt werden? (dynamisch)

**Comment by Mojo1917** [comment]
Ist angepasst. Änderung kommt mit dem nächsten Update.
