### ISSUE TITLE
Wenn ich eine zweite Datenbank habe (und diese ausgewählt habe( und erneut in die Einstellungen dorthin gehe, kann ich nicht mehr zur ersten Datenbank umschalten?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#67]

**Comment by Mojo1917** [comment]
Sollte durch tippen in den Im Bild pink markierten Bereich funktionieren.
![simulator screen shot - iphone 7 - 2018-01-24 at 13 09 33](https://user-images.githubusercontent.com/20678932/35312576-d8ae4d8e-0107-11e8-95fb-f0cd63984661.png)

**Comment by McFly753** [comment]
Ok, teste ich!

**Comment by McFly753** [comment]
Ja, hast recht, aber ist nicht intuitiv... - können wir es verständlicher machen, dass ich wirkclih rechts klicken muss?

**Comment by Mojo1917** [comment]
Okay ich werde mir was überlegen. Vielleicht wir es logischer, wenn wir den 'haken' in grau anzeigen für die die nicht ausgewählt sind?

**Comment by Mojo1917** [comment]
Okay ich habe hier jetzt wie in deinem ursprünglichen Desigentwurf Radiobuttons eingebaut. Diese sollten intuitiver sein denke ich. Was hälst du davon?
![foto 27 01 18 16 37 36](https://user-images.githubusercontent.com/20678932/35469444-99c3c29a-0380-11e8-97e3-afa5cfb16712.png)

**Comment by McFly753** [comment]
OK!
-> auf nächste Version warten
