### ISSUE TITLE
Optisch: schaue dir mal den Filterblock (ausgeklappt) an:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#68]
- und versuch, die Überschriften "Filter" und "Farbsortierung" gleich zu setzen.

- und, als Redundnaz: setz doch in die Filter-Zeiel auf die rechte Seite auch so nen kleinen Pfeil nach unten (wie oebn linsk bei den Objketen), dass nan die Filterzeile einklappen kann.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderungen kommen mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke! Und ich denke, wir können über ujnd unzter der Suchleiste noch etwas vertikalen Platz sparen.

**Comment by Mojo1917** [comment]
Abstand ist reduziert. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten

**Comment by McFly753** [comment]
etwas mehr - hatte hier aber schon ein anderes Ticket eröffnet, schliesse dieses.
