### ISSUE TITLE
Titelanzeige Objekt 

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#7]
> Wenn ein neues Objekt noch keinen Namen hat, würde ich oben das Objekt bereits "Unbekannt" nenenn und oben auch hinschreiben. Evtl. könnten wir dem User auch entgegenkommen, und "Unbekannt 13/01/18" hinzuschreiben, also das aktuelle Datum dahinter in den Namen.

> Und den Titel würde ich nicht unterstreichen.

> Können wir das (Baum 1 von 7) viel kleiner setzen, evtl. sogar zweizeilig als kompackten Block?

**Comment by Mojo1917** [comment]
Benennung und Untertitel sind eingefügt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Super, aber:

> Bennen das Objekt auch in der Datenbank so. Also nicht nur in der Anzeige.

> Und, weil es schöner aussieht: nenne es "Objekt 20.01.18" (Objket natürlich dynamsich.)

**Comment by McFly753** [comment]
UND: kannst Du diese Untertitel-Logik auch beim Titel der Datenbank verwenden.
(dort aber dann statt "Objekt 1 von 2" > "2 Objekte von 2")

**Comment by Mojo1917** [comment]
Ist übernommen. Kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Danke, passt. Nur das bitte noch: (von Oben)

"Und, weil es schöner aussieht: nenne es "Objekt 20.01.18" (Objket natürlich dynamsich.)"

**Comment by Mojo1917** [comment]
Oh klar sorry hatte ich übersehen. Unbenannt ist jetzt durch den Objekt-Singular ersetzt.
