### ISSUE TITLE
Schönheitssache Objektansicht

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#70]
Kannst Du den ausgeschriebene Ort einafch nach unten zu den Koordinaten setzen. So hängt er unmotiviert im Leerraum rum.

**Comment by Mojo1917** [comment]
Ort ist nach unten gezogen. Liegt jetzt direkt über den Koordinaten. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Lass ihm etwas mehr Abstand. Mind. den Absatnd wie "Letzter Besuch" zu dem Datum darunter.

(Und pass auch das "Erstellt am" noch an (ist auch einen Tick zu nach am darunterliegenden Datum)

**Comment by Mojo1917** [comment]
Ist angepasst. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten

Evtl.: lass uns überlegen, ob in dem nun geschaffenen Zwischenraum der Favoritenstern gut passen würde...

**Comment by Mojo1917** [comment]
Ich schaue ob der Button sich da gut macht.

**Comment by Mojo1917** [comment]
Mir gefällt der Stern hier nicht. Er passt meiner Meinung nach nicht gut ins Design, da wir darüber und darunter Text haben. Finde er wirkt hier ein wenig verloren.
Ich kann ihn dennoch nach unten ziehen.

**Comment by McFly753** [comment]
ok, lass erstmal so. Danke!
