### ISSUE TITLE
Farb-Punkte Logik passt bei Entfernung noch nicht....

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#72]
... hier haben bei mir Objkete in Hamburg und München die selbe Farbe?

**Comment by Mojo1917** [comment]
Okay zur Farbsortierung: Da es zu viel Rechenzeit kostet jedes Mal Kreise auf die Karte zu malen habe ich der App vier Punkte in verschiedenen Farben hinzugefügt. Daher haben wir nur 4 verschieden farbige Kreise und keinen dynamischen Farbverlauf.
Die App geht dann für die Einteilung wie folgt vor: Sie berechnet die Distanz zwischen dem nächsten Objekt und dem das am weitesten weg ist. Diese Distanz wird dann durch vier geteilt und auf die Farben verteilt.

Hast du möglicherweise ein Objekt, dass noch sehr viel weiter weg ist? Wenn ja würde das erklären, warum München und Hamburg in die gleiche Farbe fallen.
Die andere Möglichkeit wäre, dass die App noch keinen genauen Standort von dir erfassen konnte. Dann kann die Distanz nicht berechnet werden und alle haben die gleiche Farbe. Sobald die App das Erste Mal den Standort erfasst hat wird die Karte und die Farben automatisch aktualisiert.

**Comment by McFly753** [comment]
Hm, da habe ich wohl den Kommentar das letzte mal veregssen. Vorschalg: merh Frabpunkte als nur 4 wählen? 6 oder 8?
Und ich teste dann auch nochmals.

**Comment by Mojo1917** [comment]
Wir verwenden dann jetzt 6 Farben und möglicherweise einen anderen Algorithmus um die Objekt einzuteilen.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
Hab eine Farbkommenteirung, aber ein anderes Ticket geöffent, schcliesse das hier.
