### ISSUE TITLE
Wenn ich ein Objekt zum ersten mal mit einem Bilde "fülle", welches keine Geo-Koordinate hat...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#73]
.... würde ich ne Abfrage bringen, ob man dem Bild eine Koordinate geben will.

**Comment by Mojo1917** [comment]
Okay wird umgesetzt.

**Comment by Mojo1917** [comment]
Entsprechender Dialog ist eingebaut. Dieser öffnet nach Bestätigung dann die Ansicht in der die Bild-Positionen verschoben werden können.

**Comment by McFly753** [comment]
-> auf nächste Version warten

**Comment by McFly753** [comment]
Alles in einem neuen Ticket. schliesse dieses.
