### ISSUE TITLE
Ein/Ausklapp Fehler bei dem Filterbereich...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#75]
![img_4461](https://user-images.githubusercontent.com/493612/35307940-80cffc32-00a5-11e8-9031-0e3b3bb51c3c.PNG)

ich schaffe es irgendwie, den ausgeklappten Filterbereich optisch zu zerstören... 
Richtig wird es erst nach abschiessen der App.

**Comment by McFly753** [comment]
In diesem Fall ist dann nach dem Neustarten der App auch der Wilkommens-Screen zerschossen... s. Bild:

![img_4465](https://user-images.githubusercontent.com/493612/35307992-ccb9d56e-00a5-11e8-9968-c2fd458376ff.PNG)

**Comment by Mojo1917** [comment]
Okay das ist sehr merkwürdig. Ich kann mir nicht erklären, wie es dazu kommt. 
Vor allem das Bild wird unter iOS nie so verschnitten. Normalerweise wird es nur unproportional gestaucht.

Kannst du dir vielleicht erklären, wie es dazu kam?
Tritt der Fehler häufiger auf?
Was für ein iOS-Gerät nutzt du?

Ich habe dennoch beide Teile der App nochmal im Design überprüft und angepasst. Der Fehler sollte jetzt nicht mehr auftreten.

**Comment by McFly753** [comment]
Ich weiss nicht, wie ich es geschafft hatte, versuche es dann nochmals zu wiederholen...

**Comment by McFly753** [comment]
-> auf nächste Version warten - dann sehen wir, ob der Fehelr nochmals auftritt - ich schliesse aber jetzt mal dieses Ticket
