### ISSUE TITLE
Plus kommt ja nach oben rechts, Einstellungen nach oben Links und...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#77]
... wo machen wir ein Icon für das starten des Tutorials hin?
Oben links, rechts neben Einstellungen? 
Oder gar nict auf die Hauptoberflöche, sondenr nur zum Starten in den Einstellunegn und es ist dann eine einzieg Tour, die eben in den Einstellunegn startet und dann auch die anderen Bereiche erklärt?

**Comment by Mojo1917** [comment]
Ich würde es in die Einstellungen neben das Impressum legen. Sobald der Button gedrückt wird wir der Nutzer per Dialog darauf hingewiesen, dass das Tutorial für die App gestartet ist und dann nun jeder Bereich den er öffnet erklärt wird. Außerdem würde ich ihn darauf hinweisen, wie das Tutorial unterbrochen werden kann.
Öffnet er dann einen Bereich wir ihm in diesem alles erklärt. Öffnet der den nächsten hier das selbe. Und so weiter.

**Comment by McFly753** [comment]
Ok, alles klar!

**Comment by Mojo1917** [comment]
Tutorial ist entsprechend eingebaut. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten
