### ISSUE TITLE
Leichte Änderungen in der Statistik:

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#78]
- kannst Du die Tags vor die Länder setzen?
- und ist es rechnerisch zu aufwändig, undte rdie Länder auch die Städte aufzuführen?

**Comment by Mojo1917** [comment]
Tags sind vor die Länder gezogen.

**Comment by Mojo1917** [comment]
Nein ich denke das sollte gehen. Also Länder und Städte in die gleiche Liste oder die Städte in eine neue Liste?

**Comment by McFly753** [comment]
Städt bitte in eine neue Liste unter die Länder, weil die werden dann die Längste Liste darstellen, Danke!

**Comment by Mojo1917** [comment]
Okay habe ich mir fast gedacht ;) Kommt mit einem späteren Update.

**Comment by Mojo1917** [comment]
Sind eingebaut. Änderungen kommen mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten
