### ISSUE TITLE
Abundzu passt was noch nicht mit der Entfernungsberechnug...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#79]
... siehe zwei Beispiele:

**Comment by McFly753** [comment]
![img_4457](https://user-images.githubusercontent.com/493612/35308386-c7a32d1c-00a7-11e8-8f52-2706a92c8c1f.PNG)

**Comment by McFly753** [comment]
![img_4461](https://user-images.githubusercontent.com/493612/35308396-d5a09a3a-00a7-11e8-83c4-280cb25e3b22.PNG)

**Comment by Mojo1917** [comment]
Dieser Fehler tritt auf, wenn die App noch keine Standort beziehen konnte. Sobald ein Standort erfasst wurde wird die anzeige angepasst. 

Sollte die App noch keinen Standort haben wird ab sofort '--' angezeigt.

**Comment by Mojo1917** [comment]
Zusätzlich verlangt die App nun eine Genauigkeit von 100m bevor die Distanz angezeigt wird. Somit können komplett falsche Angaben ausgeschlossen werden.
