### ISSUE TITLE
Objekte rechts-links scroll ermöglichen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#8]
Ist es möglich, so wie Du es bei den Bildern implementiert hast, mit einen horizontalen Scroll die Objekte zu wechseln? (also über die Liste, die gerade im Filter sind)

**Comment by Mojo1917** [comment]
Sollte funktionieren denke ich. Ich werde schauen, dass die App in der Ansicht auf 'Wisch'-Gesten wartet. Sollte eine solche erfolgen fragt die App das nächste Objekt nach und lädt die Ansicht neu. Die Ansicht kann dann jedoch nur neu geladen werden und ein 'wischen' nicht animiert.

Wie soll die App sich verhalten, wenn das Objekt über die Karte geöffnet wurde?

**Comment by McFly753** [comment]
> Wenn es nur ein Objket in der anzuzeigenden Liste gibt (wie wenn ich z.B. aus der Karte komme), kann ich nicht wischen.

> Ohne Animation wird es nicht intuitiv sein, oder? // bei den Bildern ist ja auch ne Animation da, das kann man nicht anders machen, oder?

(Hierzu: das Bilderwischen ist nicht ruckelfrei. Das Bild bleibt in der Mitte seiner "BEwegung" für ein paar Millisekunden stehen... ist komsich.)

**Comment by McFly753** [comment]
Ist noch nicht drin, oder?

**Comment by Mojo1917** [comment]
Nein ist nicht drin. Wird auch sehr wahrscheinlich nicht möglich sein.

**Comment by Mojo1917** [comment]
Ruckelt es beim wischen bei dir immernoch?

**Comment by McFly753** [comment]
Bei den Bilderm ab und zu, aber ist viel besser jetzt!

**Comment by McFly753** [comment]
Ok, kein Problem, dann aber amcht in der Objketansicht dei Unterüberschrift keinen Sinn.
(Lass uns die hier wegnehmen)

**Comment by Mojo1917** [comment]
Untertitel ist entfernt. Änderung kommt mit dem nächsten Update.
