### ISSUE TITLE
wenn man auf der Kartenansicht auf der Bildchen-Ansicht ist, macht die Farbsortierung keinen Sinn...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#80]
.... könnten wir sie hier dann irgendwei deaktiviert anziegen?

**Comment by Mojo1917** [comment]
Buttons werden jetzt mit einer Transparenz angezeigt und deaktiviert. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten
