### ISSUE TITLE
die Eigenschaften in der Statistik müssen irgendwie anders dargestellt werden, weil wenn ich draufklicke...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#81]
... auf was filter ich dann?

**Comment by Mojo1917** [comment]
Was hälst du davon, das bei einem Touch die erste Option gewählt wird. Erfolgt innerhalb einer halben Sekunde ein zweiter Touch wird die zweiter gewählt. 
Wir könnten das dann farblich kennzeichnen.

**Comment by McFly753** [comment]
Wenn es didaktisch funktioniert? Meinst Du, der Zuschauer versteht es? -> Tel

**Comment by McFly753** [comment]
(User) ;)

**Comment by Mojo1917** [comment]
Können wir durch Tutorial theoretisch erklären ;)

**Comment by Mojo1917** [comment]
Sollte eine Eigenschaft zwei Optionen haben 'splitten' wir die Zeile und binden zwei Buttons ein.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.
