### ISSUE TITLE
dei Suchzeile funktioniert nicht ganz richtig...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#82]
.... wenn die Tastatur dazugeklappt ist, kann ich das kreuzchen nicht verwenden.

.... wenn die Taststaur weggeklappt ist, und etwas noch in der SUche steht, und ich das kreuzchen zum löschen der zeiel verwendne will, wird die Tastatur eingeblendet, was ich ja gar nicht brauche...

**Comment by Mojo1917** [comment]
Lass uns das hier auch am Telefon besprechen zusammen mit #50

**Comment by McFly753** [comment]
ok

**Comment by Mojo1917** [comment]
Die Suchzeile werde ich nochmal überarbeiten und entsprechend implementieren.

**Comment by Mojo1917** [comment]
Suchzeile ist jetzt komplett überarbeitet. Sie sollte jetzt sinnvoll und zuverlässig funktionieren.

Änderungen kommen mit dem nächsten Update.

**Comment by McFly753** [comment]
Passt jetzt, nur Schönheitsfehler: wenn ich das x verwende, um den Suchfilter zu löschen, hüpft kurz die Leiste nach oben. Kannst Du das unterbinden, ist ruhiger.

**Comment by Mojo1917** [comment]
Das geht leider nicht. Da beim drücken auf das x die Tastatur immer ausklappen würde ist das die einzige Möglichkeit das abzufangen. 
Wir haben nur die Möglichkeit, dass die Zeile leicht hüpft oder das Keyboard ausklappt.

**Comment by Mojo1917** [comment]
Wir können das 'hüpfen' versuchen zu verkleinern. Aber dann ist nicht sichergestellt, dass es immer zuverlässig das Keyboard unterdrückt.

**Comment by McFly753** [comment]
lassen wir so.
