### ISSUE TITLE
In der Tags-Zeile in einem Objekt würde ich den text ändern auf

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#85]
Tags auswählen

und auch in grau

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten

**Comment by McFly753** [comment]
Sorry, nur "Tags" - dann sind wir gleich mit dem Feld darüber und darunter

**Comment by Mojo1917** [comment]
Ist geändert. Änderung kommt mit dem nächsten Update.
