### ISSUE TITLE
Bei Klick auf Datum oder Ort in einem Bild oder auf erstellt am oder Letzet Besuch am oder Ort...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#86]
... bitte wie in der Statistik mit Hinterlegunhg etc. dem User zeigen, dass er hiermit gerade klickt.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten
