### ISSUE TITLE
Die Eigenschaftsfilter in Objekten können nicht merh auf "neutral" bzw. aus gestellt werden

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#87]
(wenn die Eigenshcfat aus zwei Werten besteht)

Und: das Umschalten ist von der Zeit her sehr "träge"

**Comment by Mojo1917** [comment]
Okay kann ich gerne ändern. Ich hielt das 'sperren' für sinnvoll, weil ich dachte ein Objekt könnte entweder das Eine oder das Andere sein. Aber nicht 'Keins von beidem'.

Ich werde schauen, ob ich das Umschalten beschleunigen kann.

**Comment by Mojo1917** [comment]
Objekte schalten jetzt ohne Verzögerung um.
Zudem können Objekt jetzt bei 2 möglichen Eigenschaften auch wieder 'Kein von beidem' annehmen.

Änderungen kommen mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten
