### ISSUE TITLE
Optische Erweiterung...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#88]
... können wir in der Listenansicht die Zwichentitel beim Scrollen oben am Bildschirmrand immer stehen lassen? Also wenn ich dann weiter herunterscrolle, übernimmt dann der näcshte Zwichentitel, wenn er oben angelangt ist, den Platz vom letzten etc.

Weisst Du, was ich meine? Kennt man aus anderen Apps so.

Damit würde man bei veieln Eintrögen immer sehen, in welchem Bereich ich mich befinde...

**Comment by Mojo1917** [comment]
Ist umgesetzt. Änderung kommt mit dem nächsten Update.

**Comment by McFly753** [comment]
-> auf nächste Version warten
