### ISSUE TITLE
Kein Bild Icon auch als Icon anzeigen

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#9]
Kannst Du anstelle von "Kein Bild" auch das "neue Bild Icon" hinsetzen?

> Und, hast ein ein etwas filigraneres/dezenteres Icon hierfür (auch unten dann, wenn es für die weiteren BIlder runter rutscht.

**Comment by Mojo1917** [comment]
Ist umgesetzt. Ich habe beide Icons kleiner gemacht. Jetzt sehen sie dezenter aus.

**Comment by McFly753** [comment]
danke, schau ich dann an.

**Comment by McFly753** [comment]
Danke, passt. Nur: in der Listenansicht, kannst Du hier, wenn ein Objket kein Bild hat, einfach nur die graue Fläche anzeigen, ohen "kein Bild"?

**Comment by Mojo1917** [comment]
Ist übernommen. Änderung kommt mit dem nächsten Update.
