### ISSUE TITLE
Legal unter der Karte: können wir das "legal" schöner positionieren?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#90]
... oder unter den Button legen? ;)

So abgeschnitten sieht es etwas komisch aus

**Comment by McFly753** [comment]
Ja, warten wir auf später

**Comment by McFly753** [comment]
Was ist, wenn wir es so verschieben, dass es einfach etwas weiter rechts sitzt und somit nicht mehr ganz das "Map" überlappt (sondern eben rehcts daneben sitzt)?

**Comment by Mojo1917** [comment]
Apple hat dies leider in seiner aktuelle SDK Agreements verboten: 

>  Your Application must not remove, obscure or alter Apple’s or its licensors’ copyright notices,
trademarks, or any other proprietary rights or legal notices, documents or hyperlinks that may appear in
or be provided through the Apple Maps Service;

Ich denke wir sollten dies dann besser lassen ;) Ich ziehe unsere Buttons einfach ein paar Pixel hoch, damit wir die Überschneidung vermeiden.

**Comment by McFly753** [comment]
OK!
