### ISSUE TITLE
Problematik der obersten I-Phone-Zeile...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#91]
... wenn HotSpot an ist oder Telefonat aktiv ist etc.

**Comment by Mojo1917** [comment]
Überlagerung von Tastatur und Suchzeile ist behoben.

**Comment by Mojo1917** [comment]
Fehler sollte mit der nächsten Version behoben werden. Im Simulator trat das Problem nicht mehr auf (siehe Video)
Nur die Probleme mit dem Launchscreen lassen sich nicht beheben. Scheint ein Fehler in iOS 11 zu sein.

**Comment by Mojo1917** [comment]
![ohne titel3](https://user-images.githubusercontent.com/20678932/35478615-a8217690-042d-11e8-9b6b-19c682a00939.gif)
