### ISSUE TITLE
Karten-Ansicht-Start...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#92]
... wenn ich das erste mal die App öffne und keine Objkete zum anziegen sind (bzw. wenn Filter so gesetzt sind, dass keine Objkete zum Anziegen sind), dann spring in "Kontinent-Zoom" auf meinen Standort. (Z.Z. springe ich irgendwo an den 0-Punkt des Koordinatensystems.)

... wenn ich aus den Einstellungne etc. komme, musst Du galaube ich die Anziege erneut abfragen, weil ich werde dann oftmals zu einem Objekt geführt, obwol z.B. zwei zum Anziegen wären (und das oben im Untertitel auch angezeigt wird).

**Comment by McFly753** [comment]
Wenn ich z.B. aus der Liste komme (3 Objkeet werden angezeigt) und zur Karte wechsle, wird ein Objket angeflogen.

**Comment by Mojo1917** [comment]
Ist behoben. Änderung kommt mit dem nächsten Update.
