### ISSUE TITLE
Beim Umschalten von Filtern wird kurzzeitig (wenn es ein Doppelfilter ist) beide Filter in einer Zeile und mit dementsprechend kleinen Fonts angezeigt...

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#94]
... das irritiert etwas, kannst Du das beheben?

**Comment by Mojo1917** [comment]
Nein leider nicht. Da wir mit dynamischen Textgrößen arbeiten braucht iOS kurz um das anzupassen. Wir können auch eine feste setzen, aber dann ist nicht garantiert dass immer alles sichtbar ist.

**Comment by McFly753** [comment]
ok, kein Problem, danke.
