### ISSUE TITLE
Frabsortierungen: bitte nimm wirklich Farben, also weiss/grau ohne Blaufärbung nicht verwenden

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#96]
Weil schu Dir die Punkte mal auf der Karten (nicht Sat) ansicht an, kann man eigentlcih iohne Farbe nur serh schwer erkennen.

**Comment by Mojo1917** [comment]
Farbton bei hellster Farbe geändert. Lässt sich jetzt auf der Karte gut erkennen.
