### ISSUE TITLE
Können wir auf der Karte den "mein Standort" Button auch mit einem 3. Klick belegen?

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#98]
Die ersten beiden sind klar, der dritte Klick würde wieder zu der definierten Ansicht füprhen, also alle Objkete anzuzeigen.

**Comment by Mojo1917** [comment]
Geht schon, aber das würde nicht zuverlässig funktionieren. Sollen wir es dennoch einbauen?

**Comment by McFly753** [comment]
Es wäre schön, irgendwie wieder zu allen Objkeetn zurückuzukommen - also zu der Standartansicht, wo alle Objkete angezeigt werden. Kannst Du das versuchen?

**Comment by Mojo1917** [comment]
Okay ist umgesetzt. Um hier jedoch eine Stabilität der Funktion zu garantieren mussten die Karten Animationen nach dem Drücken dieses Knopfes entfernt werden.

**Comment by McFly753** [comment]
super!
