### ISSUE TITLE
Ausgeklappter Sortier/Filterbereich: kannst Du hier die Abstände vor und nach der Suchleiste noch reduzieren, dass es keine Platzverschwendung ist aber dennoch einheitlich aussieht.

### ISSUE THREAD

**Issue by McFly753** [Mojo1917/LocBase#99]
> Probier den doppelten Abstand der Sortierleiste zur darunterliegenden Menüleiste.

**Comment by Mojo1917** [comment]
Abstand ist jetzt minimal und gleich. Weiter lässt er sich aufgrund von Überschneidungen nicht reduzieren.
